// apps/vben5/packages/@abp/saas/src/components/editions/EditionModal.vue
<script setup lang="ts">
import type { EditionDto } from '../../types';

import { ref } from 'vue';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { message } from 'ant-design-vue';

import { useEditionsApi } from '../../api';

const emits = defineEmits<{
  (event: 'change', val: EditionDto): void;
}>();

const edition = ref<EditionDto>();

const { cancel, createApi, getApi, updateApi } = useEditionsApi();

const [Form, formApi] = useVbenForm({
  async handleSubmit(values) {
    await onSubmit(values);
  },
  schema: [
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
        autocomplete: 'off',
      },
      fieldName: 'displayName',
      label: $t('AbpSaas.DisplayName:EditionName'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});

const [Modal, modalApi] = useVbenModal({
  onClosed: cancel,
  async onConfirm() {
    await formApi.validateAndSubmitForm();
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      await onGet();
    }
  },
  title: $t('AbpSaas.Editions'),
});

async function onGet() {
  const { id } = modalApi.getData<EditionDto>();
  if (!id) {
    formApi.setValues({});
    edition.value = undefined;
    modalApi.setState({ title: $t('AbpSaas.NewEdition') });
    return;
  }
  try {
    modalApi.setState({ loading: true });
    const editionDto = await getApi(id);
    modalApi.setState({
      title: `${$t('AbpSaas.Editions')} - ${editionDto.displayName}`,
    });
    formApi.setValues(editionDto);
    edition.value = editionDto;
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onSubmit(values: Record<string, any>) {
  const api = edition.value?.id
    ? updateApi(edition.value!.id, {
        concurrencyStamp: values.concurrencyStamp,
        displayName: values.displayName,
      })
    : createApi({
        displayName: values.displayName,
      });
  try {
    modalApi.setState({ submitting: true });
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/saas/editions/edition-modal.tsx
import { useEffect, useState } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi, updateApi, getApi } from "@/api/saas/editions";
import type { EditionDto } from "#/saas/editions";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: EditionDto) => void;
	editionId?: string;
}

const EditionModal: React.FC<Props> = ({ visible, onClose, onChange, editionId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [loading, setLoading] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const [concurrencyStamp, setConcurrencyStamp] = useState<string | undefined>(undefined);

	useEffect(() => {
		if (visible) {
			form.resetFields();
			if (editionId) {
				fetchEdition(editionId);
			} else {
				setConcurrencyStamp(undefined);
			}
		}
	}, [visible, editionId, form]);

	const fetchEdition = async (id: string) => {
		try {
			setLoading(true);
			const dto = await getApi(id);
			form.setFieldsValue(dto);
			setConcurrencyStamp(dto.concurrencyStamp);
		} finally {
			setLoading(false);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const api = editionId ? updateApi(editionId, { ...values, concurrencyStamp }) : createApi(values);

			const res = await api;
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const modalTitle = editionId
		? `${$t("AbpSaas.Editions")} - ${form.getFieldValue("displayName") || ""}`
		: $t("AbpSaas.NewEdition");

	return (
		<Modal
			open={visible}
			title={modalTitle}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item label={$t("AbpSaas.DisplayName:EditionName")} name="displayName" rules={[{ required: true }]}>
					<Input autoComplete="off" allowClear />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default EditionModal;
