// apps/vben5/packages/@abp/saas/src/components/editions/EditionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { EditionDto } from '../../types/editions';

import { defineAsyncComponent, h } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { AuditLogPermissions, EntityChangeDrawer } from '@abp/auditing';
import { useFeatures } from '@abp/core';
import { FeatureModal } from '@abp/features';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useEditionsApi } from '../../api/useEditionsApi';
import { EditionsPermissions } from '../../constants/permissions';

defineOptions({
  name: 'EditionTable',
});

const MenuItem = Menu.Item;
const AuditLogIcon = createIconifyIcon('fluent-mdl2:compliance-audit');
const FeatureIcon = createIconifyIcon('pajamas:feature-flag');

const { isEnabled } = useFeatures();
const { hasAccessByCodes } = useAccess();
const { cancel, deleteApi, getPagedListApi } = useEditionsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  schema: [
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
        autocomplete: 'off',
      },
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<EditionDto> = {
  columns: [
    {
      align: 'left',
      field: 'displayName',
      sortable: true,
      title: $t('AbpSaas.DisplayName:EditionName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: hasAccessByCodes([
        EditionsPermissions.Update,
        EditionsPermissions.Delete,
      ]),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        return await getPagedListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<EditionDto> = {
  cellClick: () => {},
  sortChange: () => {
    gridApi.query();
  },
};
const [EditionModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./EditionModal.vue')),
});
const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});
const [EditionChangeDrawer, entityChangeDrawerApi] = useVbenDrawer({
  connectedComponent: EntityChangeDrawer,
});
const [EditionFeatureModal, featureModalApi] = useVbenModal({
  connectedComponent: FeatureModal,
});

const onCreate = () => {
  modalApi.setData({});
  modalApi.open();
};

const onUpdate = (row: EditionDto) => {
  modalApi.setData(row);
  modalApi.open();
};

const onDelete = (row: EditionDto) => {
  Modal.confirm({
    centered: true,
    content: $t('AbpSaas.EditionDeletionConfirmationMessage', [
      row.displayName,
    ]),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      await gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
};

const onMenuClick = (row: EditionDto, info: MenuInfo) => {
  switch (info.key) {
    case 'entity-changes': {
      entityChangeDrawerApi.setData({
        entityId: row.id,
        entityTypeFullName: 'LINGYUN.Abp.Saas.Edition',
        subject: row.displayName,
      });
      entityChangeDrawerApi.open();
      break;
    }
    case 'features': {
      featureModalApi.setData({
        displayName: row.displayName,
        providerKey: row.id,
        providerName: 'E',
      });
      featureModalApi.open();
    }
  }
};
</script>

<template>
  <Grid :table-title="$t('AbpSaas.Editions')">
    <template #toolbar-tools>
      <Button
        type="primary"
        v-access:code="[EditionsPermissions.Create]"
        @click="onCreate"
        :icon="h(PlusOutlined)"
      >
        {{ $t('AbpSaas.NewEdition') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[EditionsPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[EditionsPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="
                  isEnabled(['AbpAuditing.Logging.AuditLog']) &&
                  hasAccessByCodes([AuditLogPermissions.Default])
                "
                key="entity-changes"
                :icon="h(AuditLogIcon)"
              >
                {{ $t('AbpAuditLogging.EntitiesChanged') }}
              </MenuItem>
              <MenuItem
                v-if="hasAccessByCodes([EditionsPermissions.ManageFeatures])"
                key="features"
                :icon="h(FeatureIcon)"
              >
                {{ $t('AbpSaas.ManageFeatures') }}
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <EditionModal @change="() => gridApi.query()" />
  <EditionChangeDrawer />
  <EditionFeatureModal />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/saas/editions/edition-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, EllipsisOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getPagedListApi } from "@/api/saas/editions";
import type { EditionDto } from "#/saas/editions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { EditionsPermissions } from "@/constants/saas/permissions"; // Assuming constants location
import { AuditLogPermissions } from "@/constants/management/auditing/permissions";

import { Iconify } from "@/components/icon";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";

import EditionModal from "./edition-modal";
import FeatureModal from "@/components/abp/features/feature-modal";
import { useFeatures } from "@/hooks/abp/fake-hooks/use-abp-feature";
import { EntityChangeDrawer } from "@/components/abp/auditing/entity-change-drawer";

const EditionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();
	const featureChecker = useFeatures();

	// Modal States
	const [editionModalVisible, setEditionModalVisible] = useState(false);
	const [featureModalVisible, setFeatureModalVisible] = useState(false);
	const [entityChangeDrawerVisible, setEntityChangeDrawerVisible] = useState(false);

	const [selectedEditionId, setSelectedEditionId] = useState<string | undefined>();
	const [selectedEditionName, setSelectedEditionName] = useState<string | undefined>();

	const { mutateAsync: deleteEdition } = useMutation({
		mutationFn: deleteApi,
		onSuccess: async () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			await queryClient.invalidateQueries({ queryKey: ["editions"], exact: false });
			actionRef.current?.reload();
		},
	});

	const handleCreate = () => {
		setSelectedEditionId(undefined);
		setEditionModalVisible(true);
	};

	const handleUpdate = (row: EditionDto) => {
		setSelectedEditionId(row.id);
		setEditionModalVisible(true);
	};

	const handleDelete = (row: EditionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpSaas.EditionDeletionConfirmationMessage", { 0: row.displayName }),
			onOk: async () => {
				await deleteEdition(row.id);
			},
		});
	};

	const handleMenuClick = (key: string, row: EditionDto) => {
		if (key === "features") {
			setSelectedEditionId(row.id);
			setSelectedEditionName(row.displayName);
			setFeatureModalVisible(true);
		} else if (key === "entity-changes") {
			setSelectedEditionId(row.id);
			setSelectedEditionName(row.displayName);
			setEntityChangeDrawerVisible(true);
		}
	};

	const columns: ProColumns<EditionDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpSaas.DisplayName:EditionName"),
			dataIndex: "displayName",
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 220,
			hideInTable: !hasAccessByCodes([EditionsPermissions.Update, EditionsPermissions.Delete]),
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[EditionsPermissions.Update],
					)}
					{withAccessChecker(
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>,
						[EditionsPermissions.Delete],
					)}

					<Dropdown
						menu={{
							items: [
								featureChecker.isEnabled("AbpAuditing.Logging.AuditLog") &&
								hasAccessByCodes([AuditLogPermissions.Default])
									? {
											key: "entity-changes",
											label: $t("AbpAuditLogging.EntitiesChanged"),
											icon: <Iconify icon="fluent-mdl2:compliance-audit" />,
										}
									: null,
								hasAccessByCodes([EditionsPermissions.ManageFeatures])
									? {
											key: "features",
											label: $t("AbpSaas.ManageFeatures"),
											icon: <Iconify icon="pajamas:feature-flag" />,
										}
									: null,
							].filter(Boolean) as any,
							onClick: ({ key }) => handleMenuClick(key, record),
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<EditionDto>
					headerTitle={$t("AbpSaas.Editions")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					search={{
						labelWidth: "auto",
					}}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("AbpSaas.NewEdition")}
							</Button>,
							[EditionsPermissions.Create],
						),
					]}
					request={async (params, sorter) => {
						const { current, pageSize, ...filters } = params;
						const sorting =
							sorter && Object.keys(sorter).length > 0
								? Object.keys(sorter)
										.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
										.join(", ")
								: undefined;

						const query = await queryClient.fetchQuery({
							queryKey: ["editions", params, sorter],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									sorting: sorting,
									filter: filters.filter,
								}),
						});

						return {
							data: query.items,
							total: query.totalCount,
							success: true,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<EditionModal
				visible={editionModalVisible}
				editionId={selectedEditionId}
				onClose={() => setEditionModalVisible(false)}
				onChange={async () => {
					await queryClient.invalidateQueries({ queryKey: ["editions"], exact: false });
					actionRef.current?.reload();
				}}
			/>

			<FeatureModal
				visible={featureModalVisible}
				providerName="E"
				providerKey={selectedEditionId}
				displayName={selectedEditionName}
				onClose={() => setFeatureModalVisible(false)}
			/>

			<EntityChangeDrawer
				open={entityChangeDrawerVisible}
				input={{ entityId: selectedEditionId, entityTypeFullName: "LINGYUN.Abp.Saas.Edition" }}
				subject={selectedEditionName}
				onClose={() => setEntityChangeDrawerVisible(false)}
			/>
		</>
	);
};

export default EditionTable;
