// apps/react-admin/src/pages/management/notifications/definitions/notifications/notification-send-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, Select, Tabs } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { sendNotiferApi } from "@/api/management/notifications/notifications";
import type { NotificationDefinitionDto } from "#/notifications/definitions";
import { NotificationContentType } from "#/notifications";
import PropertyTable from "@/components/abp/properties/property-table";
import { useEnumMaps } from "./use-enum-maps";

// import MarkdownEditor from "@/components/markdown-editor"; //TODO

interface Props {
	visible: boolean;
	onClose: () => void;
	notification?: NotificationDefinitionDto;
}

const NotificationSendModal: React.FC<Props> = ({ visible, onClose, notification }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const { notificationSeverityOptions } = useEnumMaps();

	const [activeTab, setActiveTab] = useState("basic");
	const [submitting, setSubmitting] = useState(false);
	const [properties, setProperties] = useState<Record<string, any>>({});

	useEffect(() => {
		if (visible && notification) {
			form.resetFields();
			setProperties({});
			setActiveTab("basic");
		}
	}, [visible, notification]);

	const handleSubmit = async () => {
		if (!notification) return;
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			await sendNotiferApi({
				culture: values.culture, // Add culture input if needed
				data: {
					description: values.description,
					message: values.message,
					title: values.title,
					...properties, // Merge extra properties
				},
				name: notification.name,
				severity: values.severity,
			});

			toast.success($t("Notifications.SendSuccessfully"));
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const isMarkdown = notification?.contentType === NotificationContentType.Markdown;
	const isWeChat = notification?.providers?.some((p) => p.toLowerCase().includes("wechat"));

	return (
		<Modal
			title={$t("Notifications.Notifications:Send")}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			width={800}
			destroyOnClose
		>
			<Form form={form} layout="vertical" labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
				<Tabs activeKey={activeTab} onChange={setActiveTab}>
					<Tabs.TabPane key="basic" tab={$t("Notifications.BasicInfo")}>
						<Form.Item label={$t("Notifications.DisplayName:Name")}>
							<Input disabled value={notification?.displayName || notification?.name} />
						</Form.Item>

						{!notification?.template && (
							<>
								<Form.Item name="title" label={$t("Notifications.Notifications:Title")} rules={[{ required: true }]}>
									<Input.TextArea autoSize={{ minRows: 1 }} />
								</Form.Item>

								<Form.Item
									name="message"
									label={$t("Notifications.Notifications:Message")}
									rules={[{ required: true }]}
								>
									{isMarkdown ? (
										<Input.TextArea rows={10} placeholder="Markdown content..." />
										// Replace with <MarkdownEditor /> if available.
									) : (
										<Input.TextArea autoSize={{ minRows: 4 }} />
									)}
								</Form.Item>

								<Form.Item name="description" label={$t("Notifications.Notifications:Description")}>
									<Input.TextArea autoSize={{ minRows: 2 }} />
								</Form.Item>
							</>
						)}

						<Form.Item name="severity" label={$t("Notifications.Notifications:Severity")}>
							<Select allowClear options={notificationSeverityOptions} />
						</Form.Item>
					</Tabs.TabPane>

					<Tabs.TabPane key="props" tab={$t("Notifications.Properties")}>
						{/* Reusing PropertyTable to edit the 'data' payload for the notification */}
						<PropertyTable
							data={properties}
							onChange={(prop) => setProperties((prev) => ({ ...prev, [prop.key]: prop.value }))}
							onDelete={(prop) => {
								const next = { ...properties };
								delete next[prop.key];
								setProperties(next);
							}}
						/>
					</Tabs.TabPane>
				</Tabs>
			</Form>
		</Modal>
	);
};

export default NotificationSendModal;

// apps/vben5/packages/@abp/notifications/src/components/definitions/notifications/NotificationSendModal.vue
<script setup lang="ts">
import type { FormInstance } from 'ant-design-vue';

import type { NotificationDefinitionDto } from '../../../types';

import {
  computed,
  defineAsyncComponent,
  ref,
  toValue,
  useTemplateRef,
} from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { PropertyTable } from '@abp/ui';
import { Form, Input, message, Select, Tabs, Textarea } from 'ant-design-vue';

import { useNotificationDefinitionsApi } from '../../../api';
import { useNotificationsApi } from '../../../api/useNotificationsApi';
import { NotificationContentType, NotificationSeverity } from '../../../types';
import { useEnumMaps } from './useEnumMaps';

const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

const MarkdownEditor = defineAsyncComponent(() =>
  import('@abp/components/vditor').then((module) => module.MarkdownEditor),
);

const defaultModel: {
  culture?: string;
  data: Record<string, any>;
  description?: string;
  message: string;
  name: string;
  severity?: NotificationSeverity;
  title: string;
} = {
  data: {},
  message: '',
  name: '',
  title: '',
};

const activeTabKey = ref('basic');
const formModel = ref({ ...defaultModel });
const form = useTemplateRef<FormInstance>('form');
const notification = ref<NotificationDefinitionDto>();

const { notificationSeverityOptions } = useEnumMaps();
const { sendNotiferApi } = useNotificationsApi();
const { getApi } = useNotificationDefinitionsApi();

const getMarkdownToolbar = computed(() => {
  if (
    notification.value?.providers &&
    notification.value.providers.some((x) =>
      x.toLocaleLowerCase().includes('wechat'),
    )
  ) {
    // 微信仅支持部分markdown语法
    // see: https://developer.work.weixin.qq.com/document/path/96458#%E6%94%AF%E6%8C%81%E7%9A%84markdown%E8%AF%AD%E6%B3%95
    return ['headings', 'bold', 'italic', 'strike', 'link', 'code', 'quote'];
  }
  return undefined;
});

const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onConfirm: onSubmit,
  async onOpenChange(isOpen) {
    if (isOpen) {
      formModel.value = { ...defaultModel };
      await onInit();
    }
  },
});

async function onInit() {
  const dto = modalApi.getData<NotificationDefinitionDto>();
  const notificationDto = await getApi(dto.name);
  notification.value = {
    ...notificationDto,
    displayName: dto.displayName,
  };
  formModel.value.name = dto.name;
}

async function onSubmit() {
  await form.value?.validate();
  try {
    modalApi.setState({ submitting: true });
    const input = toValue(formModel);
    await sendNotiferApi({
      culture: input.culture,
      data: {
        description: input.description,
        message: input.message,
        title: input.title,
      },
      name: input.name,
      severity: input.severity,
    });
    message.success($t('Notifications.SendSuccessfully'));
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="$t('Notifications.Notifications:Send')">
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }">
      <Tabs v-model:active-key="activeTabKey">
        <TabPane key="basic" :tab="$t('Notifications.BasicInfo')">
          <FormItem name="name" :label="$t('Notifications.DisplayName:Name')">
            <Input disabled :value="notification?.displayName" />
          </FormItem>
          <FormItem
            v-if="!notification?.template"
            name="title"
            :label="$t('Notifications.Notifications:Title')"
            required>
            <Textarea v-model:value="formModel.title" />
          </FormItem>
          <FormItem
            v-if="!notification?.template"
            name="message"
            :label="$t('Notifications.Notifications:Message')"
            required>
            <MarkdownEditor
              v-if="
                notification?.contentType === NotificationContentType.Markdown
              "
              v-model="formModel.message"
              :height="300"
              :toolbar="getMarkdownToolbar" />
            <Textarea v-else v-model:value="formModel.message" />
          </FormItem>
          <FormItem
            v-if="!notification?.template"
            name="description"
            :label="$t('Notifications.Notifications:Description')">
            <Textarea v-model:value="formModel.description" />
          </FormItem>
          <FormItem
            name="severity"
            :label="$t('Notifications.Notifications:Severity')">
            <Select
              allow-clear
              v-model:value="formModel.severity"
              :options="notificationSeverityOptions" />
          </FormItem>
        </TabPane>
        <TabPane key="props" :tab="$t('Notifications.Properties')">
          <PropertyTable :data="formModel.data" />
        </TabPane>
      </Tabs>
    </Form>
  </Modal>
</template>

<style scoped></style>
