// apps/vben5/packages/@abp/openiddict/src/components/uris/UriTable.vue
<script setup lang="ts">
import type { VxeGridPropTypes } from 'vxe-table';

import { computed, defineAsyncComponent, h, reactive } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, Popconfirm } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

defineOptions({
  name: 'UriTable',
});

const props = defineProps<{
  title: string;
  uris?: string[];
}>();

const emits = defineEmits<{
  (event: 'change', uri: string): void;
  (event: 'delete', uri: string): void;
}>();

interface Uri {
  uri: string;
}

const getDataResource = computed((): Uri[] => {
  if (!props.uris) return [];
  return props.uris.map((uri) => {
    return { uri };
  });
});

const columnsConfig = reactive<VxeGridPropTypes.Columns<Uri>>([
  {
    align: 'left',
    field: 'uri',
    title: 'Uri',
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 180,
  },
]);
const toolbarConfig = reactive<VxeGridPropTypes.ToolbarConfig>({
  slots: {
    buttons: 'toolbar_buttons',
    tools: 'toolbar_tools',
  },
});

const [UriModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./UriModal.vue')),
});

function onCreate() {
  modalApi.open();
}

function onDelete(uri: Uri) {
  emits('delete', uri.uri);
}

function onChange(uri: string) {
  emits('change', uri);
}
</script>

<template>
  <VxeGrid
    :columns="columnsConfig"
    :data="getDataResource"
    :toolbar-config="toolbarConfig"
  >
    <template #toolbar_buttons>
      <h3>{{ title }}</h3>
    </template>
    <template #toolbar_tools>
      <Button :icon="h(PlusOutlined)" type="primary" @click="onCreate">
        {{ $t('AbpOpenIddict.Uri:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Popconfirm
          :title="`${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.uri])}`"
          @confirm="onDelete(row)"
        >
          <Button :icon="h(DeleteOutlined)" block danger type="link">
            {{ $t('AbpUi.Delete') }}
          </Button>
        </Popconfirm>
      </div>
    </template>
  </VxeGrid>
  <UriModal @change="onChange" />
</template>

<style scoped></style>

// apps/react-admin/src/pages/openiddict/applications/uri-table.tsx
import { useState } from "react";
import { Button, Popconfirm } from "antd";
import { DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ProColumns } from "@ant-design/pro-table";
import UriModal from "./uri-modal";

interface UriTableProps {
	title: string;
	uris?: string[];
	onChange?: (uri: string) => void;
	onDelete?: (uri: string) => void;
}

interface UriItem {
	uri: string;
	key: string;
}

const UriTable: React.FC<UriTableProps> = ({ title, uris = [], onChange, onDelete }) => {
	const { t: $t } = useTranslation();
	const [modalVisible, setModalVisible] = useState(false);

	const dataSource = uris.map((uri) => ({
		uri,
		key: uri,
	}));

	const columns: ProColumns<UriItem>[] = [
		{
			title: "Uri",
			dataIndex: "uri",
			align: "left",
		},
		{
			title: $t("AbpUi.Actions"),
			width: 180,
			fixed: "right",
			render: (_, record) => (
				<Popconfirm
					title={$t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: record.uri })}
					onConfirm={() => onDelete?.(record.uri)}
				>
					<Button type="link" danger icon={<DeleteOutlined />} block>
						{$t("AbpUi.Delete")}
					</Button>
				</Popconfirm>
			),
		},
	];

	return (
		<>
			<ProTable<UriItem>
				headerTitle={title}
				columns={columns}
				dataSource={dataSource}
				search={false}
				pagination={false}
				toolBarRender={() => [
					<Button key="add" type="primary" icon={<PlusOutlined />} onClick={() => setModalVisible(true)}>
						{$t("AbpOpenIddict.Uri:AddNew")}
					</Button>,
				]}
			/>

			<UriModal
				visible={modalVisible}
				onClose={() => setModalVisible(false)}
				onChange={(uri) => {
					onChange?.(uri);
					setModalVisible(false);
				}}
			/>
		</>
	);
};

export default UriTable;
