// apps/react-admin/src/pages/management/localization/languages/localization-language-modal.tsx
import { useEffect, useState } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi, updateApi, getApi } from "@/api/management/localization/languages";
import type { LanguageDto } from "#/management/localization/languages";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: LanguageDto) => void;
	cultureName?: string;
}

const LocalizationLanguageModal: React.FC<Props> = ({ visible, onClose, onChange, cultureName }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [loading, setLoading] = useState(false);
	const [submitting, setSubmitting] = useState(false);

	useEffect(() => {
		if (visible) {
			form.resetFields();
			if (cultureName) {
				fetchLanguage(cultureName);
			}
		}
	}, [visible, cultureName, form]);

	const fetchLanguage = async (name: string) => {
		try {
			setLoading(true);
			const dto = await getApi(name);
			form.setFieldsValue(dto);
		} finally {
			setLoading(false);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const api = cultureName ? updateApi(cultureName, values) : createApi(values);

			const res = await api;
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const modalTitle = cultureName
		? `${$t("AbpLocalization.Languages")} - ${cultureName}`
		: $t("LocalizationManagement.Language:AddNew");

	return (
		<Modal
			open={visible}
			title={modalTitle}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			destroyOnClose
			width="50%"
		>
			<Form form={form} layout="vertical">
				<Form.Item
					label={$t("AbpLocalization.DisplayName:CultureName")}
					name="cultureName"
					rules={[{ required: true }]}
				>
					<Input disabled={!!cultureName} autoComplete="off" />
				</Form.Item>
				<Form.Item label={$t("AbpLocalization.DisplayName:UiCultureName")} name="uiCultureName">
					<Input autoComplete="off" />
				</Form.Item>
				<Form.Item
					label={$t("AbpLocalization.DisplayName:DisplayName")}
					name="displayName"
					rules={[{ required: true }]}
				>
					<Input autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default LocalizationLanguageModal;

// apps/vben5/packages/@abp/localization/src/components/languages/LocalizationLanguageModal.vue
<script setup lang="ts">
import type { FormInstance } from 'ant-design-vue';

import type { LanguageDto } from '../../types/languages';

import { defineEmits, defineOptions, ref, toValue, useTemplateRef } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Form, Input, message } from 'ant-design-vue';

import { useLanguagesApi } from '../../api/useLanguagesApi';

defineOptions({
  name: 'LocalizationLanguageModal',
});
const emits = defineEmits<{
  (event: 'change', data: LanguageDto): void;
}>();

const FormItem = Form.Item;

const defaultModel = {} as LanguageDto;

const form = useTemplateRef<FormInstance>('form');
const formModel = ref<LanguageDto>({ ...defaultModel });

const { cancel, createApi, getApi, updateApi } = useLanguagesApi();
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('LocalizationLanguageModal has closed!');
  },
  onConfirm: onSubmit,
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      formModel.value = { ...defaultModel };
      modalApi.setState({
        title: $t('LocalizationManagement.Language:AddNew'),
      });
      const { cultureName } = modalApi.getData<LanguageDto>();
      cultureName && (await onGet(cultureName));
    }
  },
  title: $t('LocalizationManagement.Language:AddNew'),
});
async function onGet(name: string) {
  try {
    modalApi.setState({ loading: true });
    const dto = await getApi(name);
    formModel.value = dto;
    modalApi.setState({
      title: `${$t('AbpLocalization.Languages')} - ${dto.cultureName}`,
    });
  } finally {
    modalApi.setState({ loading: false });
  }
}
async function onSubmit() {
  await form.value?.validate();
  try {
    modalApi.setState({ submitting: true });
    const input = toValue(formModel);
    const api = input.id
      ? updateApi(input.cultureName, input)
      : createApi(input);
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <FormItem
        :label="$t('AbpLocalization.DisplayName:CultureName')"
        name="cultureName"
        required
      >
        <Input v-model:value="formModel.cultureName" autocomplete="off" />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:UiCultureName')"
        name="uiCultureName"
      >
        <Input v-model:value="formModel.uiCultureName" autocomplete="off" />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:DisplayName')"
        name="displayName"
        required
      >
        <Input v-model:value="formModel.displayName" autocomplete="off" />
      </FormItem>
    </Form>
  </Modal>
</template>

<style scoped></style>
