// apps/react-admin/src/pages/management/localization/languages/localization-language-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Modal, Space } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { getListApi, deleteApi } from "@/api/management/localization/languages";
import type { LanguageDto } from "#/management/localization/languages";
import LocalizationLanguageModal from "./localization-language-modal";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { LanguagesPermissions } from "@/constants/management/localization/permissions";
import useAbpStore from "@/store/abpCoreStore";
import orderBy from "lodash.orderby";
import { useSetLocale } from "@/store/localeI18nStore";
import { LocalEnum, StorageEnum } from "#/enum";
import { getStringItem } from "@/utils/storage";

const LocalizationLanguageTable: React.FC = () => {
	const { t: $t, i18n } = useTranslation();
	const setLocale = useSetLocale();
	const currentLng = getStringItem(StorageEnum.I18N) || LocalEnum.en_US;

	const actionRef = useRef<ActionType>();
	const [modalVisible, setModalVisible] = useState(false);
	const [currentCulture, setCurrentCulture] = useState<string | undefined>();
	const [modal, contextHolder] = Modal.useModal();

	// Use store to access and update application configuration
	const application = useAbpStore((state) => state.application);

	const handleOpenModal = (cultureName?: string) => {
		setCurrentCulture(cultureName);
		setModalVisible(true);
	};

	const handleDelete = (row: LanguageDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.cultureName }),
			onOk: async () => {
				await deleteApi(row.cultureName);
				toast.success($t("AbpUi.DeletedSuccessfully"));
				handleDataChange(row);
			},
		});
	};

	const handleDataChange = async (data: LanguageDto) => {
		actionRef.current?.reload();

		// If the changed language is the currently active language, refresh the localization config
		const currentCultureName = application?.localization.currentCulture.cultureName;
		if (data.cultureName === currentCultureName) {
			try {
				await setLocale(currentLng as LocalEnum, i18n);
			} catch (error) {
				console.error("Failed to refresh localization", error);
			}
		}
	};

	const columns: ProColumns<LanguageDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpLocalization.DisplayName:CultureName"),
			dataIndex: "cultureName",
			sorter: true,
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpLocalization.DisplayName:DisplayName"),
			dataIndex: "displayName",
			sorter: true,
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpLocalization.DisplayName:UiCultureName"),
			dataIndex: "uiCultureName",
			sorter: true,
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 220,
			render: (_, record) => (
				<Space>
					{hasAccessByCodes([LanguagesPermissions.Update]) && (
						<Button type="link" icon={<EditOutlined />} onClick={() => handleOpenModal(record.cultureName)}>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{/* !record.isStatic && no isStatic */}
					{hasAccessByCodes([LanguagesPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<LanguageDto>
					headerTitle={$t("AbpLocalization.Languages")}
					actionRef={actionRef}
					rowKey="cultureName"
					columns={columns}
					search={{
						labelWidth: "auto",
					}}
					toolBarRender={() => [
						hasAccessByCodes([LanguagesPermissions.Create]) && (
							<Button key="add" type="primary" icon={<PlusOutlined />} onClick={() => handleOpenModal()}>
								{$t("LocalizationManagement.Language:AddNew")}
							</Button>
						),
					]}
					request={async (params, sorter) => {
						// Client-side pagination and sorting logic mirroring the Vue component
						// 1. Fetch all data
						const { items } = await getListApi({ filter: params.filter });

						let dataSource = [...items];

						// 2. Sort
						if (sorter && Object.keys(sorter).length > 0) {
							const sortField = Object.keys(sorter)[0];
							const sortOrder = sorter[sortField] === "ascend" ? "asc" : "desc";
							dataSource = orderBy(dataSource, [sortField], [sortOrder]);
						}

						// 3. Paginate
						const current = params.current || 1;
						const pageSize = params.pageSize || 10;
						const startIndex = (current - 1) * pageSize;
						const endIndex = startIndex + pageSize;
						const pageData = dataSource.slice(startIndex, endIndex);

						return {
							data: pageData,
							success: true,
							total: dataSource.length,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<LocalizationLanguageModal
				visible={modalVisible}
				cultureName={currentCulture}
				onClose={() => setModalVisible(false)}
				onChange={handleDataChange}
			/>
		</>
	);
};

export default LocalizationLanguageTable;

// apps/vben5/packages/@abp/localization/src/components/languages/LocalizationLanguageTable.vue
<script setup lang="ts">
import type { VbenFormProps, VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { LanguageDto } from '../../types/languages';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useAbpStore } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useLanguagesApi } from '../../api/useLanguagesApi';
import { useLocalizationsApi } from '../../api/useLocalizationsApi';
import { LanguagesPermissions } from '../../constants/permissions';

defineOptions({
  name: 'LocalizationLanguageTable',
});

const dataSource = ref<LanguageDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const abpStore = useAbpStore();
const { deleteApi, getListApi } = useLanguagesApi();
const { getLocalizationApi } = useLocalizationsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<LanguageDto> = {
  columns: [
    {
      align: 'left',
      field: 'cultureName',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:CultureName'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:DisplayName'),
    },
    {
      align: 'left',
      field: 'uiCultureName',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:UiCultureName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<LanguageDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [LocalizationLanguageModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./LocalizationLanguageModal.vue'),
  ),
});

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input);
    pageState.total = items.length;
    dataSource.value = items;
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = dataSource.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: LanguageDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: LanguageDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.cultureName])}`,
    onOk: async () => {
      await deleteApi(row.cultureName);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onChange(row);
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

async function onChange(data: LanguageDto) {
  const input = await gridApi.formApi.getValues();
  onGet(input);
  // 资源变化刷新本地多语言缓存
  const cultureName =
    abpStore.application!.localization.currentCulture.cultureName;
  if (data.cultureName === cultureName) {
    const localization = await getLocalizationApi({
      cultureName,
    });
    abpStore.setLocalization(localization);
  }
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('AbpLocalization.Languages')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[LanguagesPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('LocalizationManagement.Language:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[LanguagesPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="!row.isStatic"
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[LanguagesPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
  </Grid>
  <LocalizationLanguageModal @change="onChange" />
</template>

<style scoped></style>
