// apps/react-admin/src/pages/platform/data-dictionaries/data-dictionary-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, TreeSelect } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi, updateApi, getApi, getAllApi } from "@/api/platform/data-dictionaries";
import type { DataDto, DataCreateDto, DataUpdateDto } from "#/platform/data-dictionaries";
import { listToTree } from "@/utils/tree";
interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: DataDto) => void;
	dataId?: string;
	parentId?: string;
}

const DataDictionaryModal: React.FC<Props> = ({ visible, onClose, onChange, dataId, parentId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);
	const [treeData, setTreeData] = useState<any[]>([]);
	const [formData, setFormData] = useState<DataDto | null>(null);

	useEffect(() => {
		if (visible) {
			form.resetFields();
			initData();
		}
	}, [visible, dataId, parentId]);

	const initData = async () => {
		// Fetch tree data for Parent selection
		const { items } = await getAllApi();
		const tree = listToTree(items, { id: "id", pid: "parentId" });
		setTreeData(tree);

		if (dataId) {
			const dto = await getApi(dataId);
			setFormData(dto);
			form.setFieldsValue(dto);
		} else if (parentId) {
			setFormData(null);
			form.setFieldValue("parentId", parentId);
		} else {
			setFormData(null);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			let res: DataDto;
			if (dataId) {
				res = await updateApi(dataId, values as DataUpdateDto);
			} else {
				res = await createApi(values as DataCreateDto);
			}

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const modalTitle = dataId
		? `${$t("AppPlatform.Data:Edit")} - ${formData?.name || ""}`
		: parentId
			? $t("AppPlatform.Data:AddChildren")
			: $t("AppPlatform.Data:AddNew");

	return (
		<Modal
			title={modalTitle}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item name="parentId" label={$t("AppPlatform.DisplayName:ParentData")}>
					<TreeSelect
						treeData={treeData}
						fieldNames={{ label: "displayName", value: "id", children: "children" }}
						allowClear
						treeDefaultExpandAll
						disabled={!!dataId} // Often prevent moving parent during edit for simplicity
					/>
				</Form.Item>

				<Form.Item name="name" label={$t("AppPlatform.DisplayName:Name")} rules={[{ required: true }]}>
					<Input disabled={!!dataId} autoComplete="off" />
				</Form.Item>

				<Form.Item name="displayName" label={$t("AppPlatform.DisplayName:DisplayName")} rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="description" label={$t("AppPlatform.DisplayName:Description")}>
					<Input.TextArea autoSize={{ minRows: 3 }} />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default DataDictionaryModal;

// apps/vben5/packages/@abp/platform/src/components/data-dictionaries/DataDictionaryModal.vue
<script setup lang="ts">
import type {
  DataCreateDto,
  DataDto,
  DataUpdateDto,
} from '../../types/dataDictionaries';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { listToTree } from '@abp/core';
import { message } from 'ant-design-vue';

import { useDataDictionariesApi } from '../../api';

const emits = defineEmits<{
  (event: 'change', data: DataDto): void;
}>();

const { createApi, getAllApi, getApi, updateApi } = useDataDictionariesApi();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      dependencies: {
        show: false,
        triggerFields: ['name'],
      },
      fieldName: 'id',
    },
    {
      component: 'ApiTreeSelect',
      componentProps: {
        allowClear: true,
        api: async () => {
          const { items } = await getAllApi();
          return listToTree(items, {
            id: 'id',
            pid: 'parentId',
          });
        },
        labelField: 'displayName',
        valueField: 'id',
        childrenField: 'children',
      },
      dependencies: {
        disabled: (values) => {
          return !!values?.id;
        },
        triggerFields: ['id'],
      },
      fieldName: 'parentId',
      label: $t('AppPlatform.DisplayName:ParentData'),
    },
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('AppPlatform.DisplayName:Name'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'displayName',
      label: $t('AppPlatform.DisplayName:DisplayName'),
      rules: 'required',
    },
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 3,
        },
      },
      fieldName: 'description',
      label: $t('AppPlatform.DisplayName:Description'),
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  onOpenChange: async (isOpen) => {
    if (isOpen) {
      await onGet();
    }
  },
});

async function onGet() {
  try {
    modalApi.setState({ loading: true });
    formApi.resetForm();
    const { displayName, id, parentId } = modalApi.getData<DataDto>();
    let title = $t('AppPlatform.Data:AddNew');
    if (id) {
      const dto = await getApi(id);
      formApi.setValues(dto);
      title = `${$t('AppPlatform.Data:Edit')} - ${dto.name}`;
    } else if (parentId) {
      title = `${$t('AppPlatform.Data:AddChildren')} - ${displayName}`;
      formApi.setFieldValue('parentId', parentId);
    }
    modalApi.setState({ title });
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onSubmit(values: Record<string, any>) {
  try {
    modalApi.setState({ submitting: true });
    const api = values.id
      ? updateApi(values.id, values as DataUpdateDto)
      : createApi(values as DataCreateDto);
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>
