// apps/react-admin/src/pages/platform/data-dictionaries/data-dictionary-item-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, Select, Checkbox, InputNumber, DatePicker } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import dayjs from "dayjs";
import { createItemApi, updateItemApi } from "@/api/platform/data-dictionaries";
import type { DataDto, DataItemDto, DataItemCreateDto, DataItemUpdateDto } from "#/platform/data-dictionaries";
import { ValueType } from "#/platform/data-dictionaries";
import { formatToDate, formatToDateTime } from "@/utils/abp";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: () => void;
	data?: DataDto;
	item?: DataItemDto;
}

const DataDictionaryItemModal: React.FC<Props> = ({ visible, onClose, onChange, data, item }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);

	// Watch valueType to dynamically render the default value input
	const valueType = Form.useWatch("valueType", form);
	const allowBeNull = Form.useWatch("allowBeNull", form);

	useEffect(() => {
		if (visible && data) {
			form.resetFields();
			if (item) {
				// Edit Mode: Map string values back to typed values
				form.setFieldsValue({
					...item,
					defaultValue: mapFromDefaultValue(item.valueType, item.defaultValue),
				});
			} else {
				// Create Mode defaults
				form.setFieldsValue({
					allowBeNull: true,
					valueType: ValueType.String,
				});
			}
		}
	}, [visible, data, item, form]);

	const mapFromDefaultValue = (type: ValueType, val?: string) => {
		if (!val) return undefined;
		switch (type) {
			case ValueType.Boolean:
				return val.toLowerCase() === "true";
			case ValueType.Numeic:
				return Number(val);
			case ValueType.Array:
				return val.split(",");
			case ValueType.Date:
			case ValueType.DateTime:
				return dayjs(val);
			default:
				return val;
		}
	};

	const mapToDefaultValue = (type: ValueType, val?: any) => {
		if (val === undefined || val === null) return undefined;
		switch (type) {
			case ValueType.Boolean:
				return String(val);
			case ValueType.Array:
				return (val as string[]).join(",");
			case ValueType.Date:
				return formatToDate(val);
			case ValueType.DateTime:
				return formatToDateTime(val);
			case ValueType.Numeic:
				return String(val);
			default:
				return String(val);
		}
	};

	const handleSubmit = async () => {
		if (!data) return;
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const submitData = {
				...values,
				defaultValue: mapToDefaultValue(values.valueType, values.defaultValue),
			};

			if (item) {
				await updateItemApi(data.id, item.name, submitData as DataItemUpdateDto);
			} else {
				await createItemApi(data.id, submitData as DataItemCreateDto);
			}

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange();
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const renderDefaultValueInput = () => {
		switch (valueType) {
			case ValueType.Boolean:
				return <Checkbox>{$t("AppPlatform.DisplayName:DefaultValue")}</Checkbox>;
			case ValueType.Numeic:
				return <InputNumber className="w-full" />;
			case ValueType.Date:
				return <DatePicker className="w-full" />;
			case ValueType.DateTime:
				return <DatePicker showTime className="w-full" />;
			case ValueType.Array:
				return <Select mode="tags" />;
			case ValueType.String:
				return <Input autoComplete="off" />;
			default:
				return <Input autoComplete="off" />;
		}
	};

	const modalTitle = item ? `${$t("AppPlatform.Data:EditItem")} - ${item.name}` : $t("AppPlatform.Data:AppendItem");

	return (
		<Modal
			title={modalTitle}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			width={600}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				{/* Helper hidden field for ID if needed, though we use 'item' prop logic */}

				<Form.Item name="name" label={$t("AppPlatform.DisplayName:Name")} rules={[{ required: true }]}>
					<Input disabled={!!item} autoComplete="off" />
				</Form.Item>

				<Form.Item name="displayName" label={$t("AppPlatform.DisplayName:DisplayName")} rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="valueType" label={$t("AppPlatform.DisplayName:ValueType")} rules={[{ required: true }]}>
					<Select
						disabled={!!item} // Usually changing type after creation causes data issues
						onChange={() => form.setFieldValue("defaultValue", undefined)}
						options={[
							{ label: "String", value: ValueType.String },
							{ label: "Number", value: ValueType.Numeic },
							{ label: "Date", value: ValueType.Date },
							{ label: "DateTime", value: ValueType.DateTime },
							{ label: "Boolean", value: ValueType.Boolean },
							{ label: "Array", value: ValueType.Array },
						]}
					/>
				</Form.Item>

				<Form.Item name="allowBeNull" valuePropName="checked">
					<Checkbox>{$t("AppPlatform.DisplayName:AllowBeNull")}</Checkbox>
				</Form.Item>

				<Form.Item
					name="defaultValue"
					label={$t("AppPlatform.DisplayName:DefaultValue")}
					valuePropName={valueType === ValueType.Boolean ? "checked" : "value"}
					rules={[{ required: !allowBeNull, message: $t("AbpUi.ThisFieldIsRequired") }]}
				>
					{renderDefaultValueInput()}
				</Form.Item>

				<Form.Item name="description" label={$t("AppPlatform.DisplayName:Description")}>
					<Input.TextArea autoSize={{ minRows: 3 }} />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default DataDictionaryItemModal;

// apps/vben5/packages/@abp/platform/src/components/data-dictionaries/DataDictionaryItemModal.vue
<script setup lang="ts">
import type {
  DataDto,
  DataItemCreateDto,
  DataItemDto,
  DataItemUpdateDto,
} from '../../types';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDate, formatToDateTime } from '@abp/core';
import { message } from 'ant-design-vue';
import cloneDeep from 'lodash.clonedeep';

import { useDataDictionariesApi } from '../../api';
import { ValueType } from '../../types';

interface ModalState {
  data: DataDto;
  item: DataItemDto;
}

const emits = defineEmits<{
  (event: 'change'): void;
}>();

const { createItemApi, updateItemApi } = useDataDictionariesApi();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      dependencies: {
        show: false,
        triggerFields: ['name'],
      },
      fieldName: 'id',
    },
    {
      component: 'Input',
      dependencies: {
        disabled: (values) => {
          return !!values?.id;
        },
        triggerFields: ['id'],
      },
      fieldName: 'name',
      label: $t('AppPlatform.DisplayName:Name'),
      rules: 'required',
    },
    {
      component: 'Input',
      componentProps: {
        autocomplete: 'off',
      },
      fieldName: 'displayName',
      label: $t('AppPlatform.DisplayName:DisplayName'),
      rules: 'required',
    },
    {
      component: 'Select',
      componentProps: {
        onChange(valueType: ValueType) {
          onValueTypeChange(valueType);
        },
        options: [
          { label: 'String', value: ValueType.String },
          { label: 'Number', value: ValueType.Numeic },
          { label: 'Date', value: ValueType.Date },
          { label: 'DateTime', value: ValueType.DateTime },
          { label: 'Boolean', value: ValueType.Boolean },
          { label: 'Array', value: ValueType.Array },
          // TODO: Object 暂不支持
          // { label: 'Object', value: ValueType.Object },
        ],
      },
      fieldName: 'valueType',
      label: $t('AppPlatform.DisplayName:ValueType'),
      rules: 'selectRequired',
    },
    {
      component: 'Input',
      fieldName: 'defaultValue',
      label: $t('AppPlatform.DisplayName:DefaultValue'),
    },
    {
      component: 'Checkbox',
      fieldName: 'allowBeNull',
      label: $t('AppPlatform.DisplayName:AllowBeNull'),
    },
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 3,
        },
      },
      fieldName: 'description',
      label: $t('AppPlatform.DisplayName:Description'),
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  async onConfirm() {
    await formApi.validateAndSubmitForm();
  },
  onOpenChange(isOpen) {
    if (isOpen) {
      onInit();
    }
  },
});

function onInit() {
  formApi.resetForm();
  const state = modalApi.getData<ModalState>();
  let title = $t('AppPlatform.Data:AppendItem');
  if (state.item?.id) {
    onValueTypeChange(state.item.valueType);
    formApi.setValues({
      ...state.item,
      defaultValue: mapFromDefaultValue(state.item),
    });
    title = `${$t('AppPlatform.Data:EditItem')} - ${state.item.name}`;
  } else {
    formApi.updateSchema([
      {
        component: 'Input',
        componentProps: {
          autocomplete: 'off',
        },
        dependencies: {
          rules(values) {
            return values.allowBeNull ? null : 'required';
          },
          triggerFields: ['valueType', 'allowBeNull'],
        },
        fieldName: 'defaultValue',
      },
    ]);
    formApi.setValues({
      allowBeNull: true,
    });
  }
  modalApi.setState({ title });
}

async function onSubmit(values: Record<string, any>) {
  try {
    modalApi.setState({ submitting: true });
    const state = modalApi.getData<ModalState>();
    const input = cloneDeep(values);
    input.defaultValue = mapToDefaultValue(input.valueType, input.defaultValue);
    const api = input.id
      ? updateItemApi(state.data.id, input.name, input as DataItemUpdateDto)
      : createItemApi(state.data.id, input as DataItemCreateDto);
    await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change');
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}

function onValueTypeChange(valueType: ValueType) {
  let component = 'Input';
  let componentProps: Record<string, any> | undefined;
  switch (valueType) {
    case ValueType.Array: {
      component = 'Select';
      componentProps = {
        mode: 'tags',
      };
      break;
    }
    case ValueType.Boolean: {
      component = 'Checkbox';
      break;
    }
    case ValueType.Date:
    case ValueType.DateTime: {
      component = 'DatePicker';
      componentProps = {
        showTime: valueType === ValueType.DateTime,
        valueFormat:
          valueType === ValueType.DateTime
            ? 'YYYY-MM-DD HH:mm:ss'
            : 'YYYY-MM-DD',
      };
      break;
    }
    case ValueType.Numeic: {
      component = 'InputNumber';
      break;
    }
    case ValueType.String: {
      componentProps = {
        autocomplete: 'off',
      };
      break;
    }
  }
  formApi.updateSchema([
    {
      component,
      componentProps,
      dependencies: {
        rules(values) {
          return values.allowBeNull ? null : 'required';
        },
        triggerFields: ['valueType', 'allowBeNull'],
      },
      fieldName: 'defaultValue',
    },
  ]);
  formApi.setFieldValue('defaultValue', undefined);
}

function mapToDefaultValue(valueType: ValueType, defaultValue?: any) {
  if (!defaultValue) {
    return undefined;
  }
  switch (valueType) {
    case ValueType.Array: {
      return (defaultValue as string[]).join(',');
    }
    case ValueType.Boolean: {
      return (defaultValue as boolean).toString();
    }
    case ValueType.Date: {
      return formatToDate(defaultValue);
    }
    case ValueType.DateTime: {
      return formatToDateTime(defaultValue);
    }
    case ValueType.Numeic: {
      return (defaultValue as number).toString();
    }
  }
  return defaultValue;
}

function mapFromDefaultValue(dataItem: DataItemDto) {
  if (!dataItem.defaultValue) {
    return undefined;
  }
  let defaultValue: any | undefined;
  switch (dataItem.valueType) {
    case ValueType.Array: {
      defaultValue = dataItem.defaultValue.split(',');
      break;
    }
    case ValueType.Boolean: {
      defaultValue = Boolean(dataItem.defaultValue);
      break;
    }
    case ValueType.Date: {
      defaultValue = formatToDate(dataItem.defaultValue);
      break;
    }
    case ValueType.DateTime: {
      defaultValue = formatToDateTime(dataItem.defaultValue);
      break;
    }
    case ValueType.Numeic: {
      defaultValue = Number(dataItem.defaultValue);
      break;
    }
    case ValueType.String: {
      defaultValue = dataItem.defaultValue;
      break;
    }
  }
  return defaultValue;
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>
