// apps/vben5/packages/@abp/platform/src/components/data-dictionaries/DataDictionaryTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { DataDto } from '../../types/dataDictionaries';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { listToTree, useAuthorization } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useDataDictionariesApi } from '../../api/useDataDictionariesApi';
import { DataDictionaryPermissions } from '../../constants/permissions';

defineOptions({
  name: 'DataDictionaryTable',
});

const MenuItem = Menu.Item;
const ItemsIcon = createIconifyIcon('material-symbols:align-items-stretch');

const { isGranted } = useAuthorization();
const { deleteApi, getAllApi } = useDataDictionariesApi();

const expandRowKeys = ref<string[]>([]);
const dataDictionaries = ref<DataDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const gridOptions: VxeGridProps<DataDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      slots: { default: 'name' },
      title: $t('AppPlatform.DisplayName:Name'),
      treeNode: true,
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:DisplayName'),
    },
    {
      align: 'left',
      field: 'description',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:Description'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: isGranted(
        [
          DataDictionaryPermissions.Default,
          DataDictionaryPermissions.Update,
          DataDictionaryPermissions.Delete,
        ],
        false,
      ),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  rowConfig: {
    keyField: 'id',
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      queryMethod: onGet,
    },
    zoom: true,
  },
  treeConfig: {
    accordion: true,
    parentField: 'parentId',
    rowField: 'id',
    transform: false,
  },
};
const gridEvents: VxeGridListeners<DataDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
  toggleTreeExpand(params) {
    if (params.expanded) {
      expandRowKeys.value.push(params.row.id);
    } else {
      expandRowKeys.value = expandRowKeys.value.filter(
        (key) => key !== params.row.id,
      );
    }
    onExpandChange();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  gridEvents,
  gridOptions,
});

const [DataDictionaryModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./DataDictionaryModal.vue'),
  ),
});
const [DataDictionaryItemDrawer, itemDrawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(
    () => import('./DataDictionaryItemDrawer.vue'),
  ),
});

async function onGet() {
  try {
    gridApi.setLoading(true);
    const { items } = await getAllApi();
    const treeItems = listToTree(items, {
      id: 'id',
      pid: 'parentId',
    });
    pageState.total = treeItems.length;
    dataDictionaries.value = treeItems;
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

function onExpandChange() {
  gridApi.setGridOptions({
    treeConfig: {
      expandRowKeys: expandRowKeys.value,
    },
  });
}

function onPageChange() {
  const items = dataDictionaries.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: DataDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: DataDto) {
  Modal.confirm({
    afterClose: () => {
      gridApi.setLoading(false);
    },
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessage')}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await deleteApi(row.id);
        message.success($t('AbpUi.DeletedSuccessfully'));
        onGet();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onMenuClick(row: DataDto, info: MenuInfo) {
  switch (info.key) {
    case 'children': {
      modalApi.setData({
        displayName: row.displayName,
        parentId: row.id,
      });
      modalApi.open();
      break;
    }
    case 'items': {
      onManageItems(row);
      break;
    }
  }
}

function onManageItems(row: DataDto) {
  itemDrawerApi.setData(row);
  itemDrawerApi.open();
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('AppPlatform.DisplayName:DataDictionary')">
    <template #toolbar-tools>
      <Button
        v-if="isGranted([DataDictionaryPermissions.Create])"
        :icon="h(PlusOutlined)"
        type="primary"
        @click="onCreate"
      >
        {{ $t('AppPlatform.Data:AddNew') }}
      </Button>
    </template>
    <template #name="{ row }">
      <Button type="link" @click="onManageItems(row)">{{ row.name }}</Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          v-if="
            isGranted(
              [
                DataDictionaryPermissions.Default,
                DataDictionaryPermissions.Update,
              ],
              false,
            )
          "
          :icon="h(EditOutlined)"
          block
          type="link"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="isGranted([DataDictionaryPermissions.Delete])"
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown
          v-if="
            isGranted(
              [
                DataDictionaryPermissions.Create,
                DataDictionaryPermissions.ManageItems,
              ],
              false,
            )
          "
        >
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="isGranted([DataDictionaryPermissions.Create])"
                key="children"
              >
                <div class="flex flex-row items-center gap-[4px]">
                  <PlusOutlined />
                  {{ $t('AppPlatform.Data:AddChildren') }}
                </div>
              </MenuItem>
              <MenuItem
                v-if="isGranted([DataDictionaryPermissions.ManageItems])"
                key="items"
              >
                <div class="flex flex-row items-center gap-[4px]">
                  <ItemsIcon />
                  {{ $t('AppPlatform.Data:Items') }}
                </div>
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <DataDictionaryModal @change="onGet" />
  <DataDictionaryItemDrawer />
</template>

<style scoped></style>

// apps/react-admin/src/pages/platform/data-dictionaries/data-dictionary-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Dropdown, Space, Modal, Card } from "antd";
import { PlusOutlined, EditOutlined, DeleteOutlined, EllipsisOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { deleteApi, getAllApi } from "@/api/platform/data-dictionaries";
import type { DataDto } from "#/platform/data-dictionaries";
import { DataDictionaryPermissions } from "@/constants/platform/permissions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { Iconify } from "@/components/icon";

import DataDictionaryModal from "./data-dictionary-modal";
import DataDictionaryItemDrawer from "./data-dictionary-item-drawer";
import { listToTree } from "@/utils/tree";

const DataDictionaryTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();

	// State
	const [modalVisible, setModalVisible] = useState(false);
	const [drawerVisible, setDrawerVisible] = useState(false);
	const [selectedData, setSelectedData] = useState<DataDto | undefined>();
	const [selectedParentId, setSelectedParentId] = useState<string | undefined>();

	// Handlers
	const handleCreate = () => {
		setSelectedData(undefined);
		setSelectedParentId(undefined);
		setModalVisible(true);
	};

	const handleUpdate = (record: DataDto) => {
		setSelectedData(record);
		setSelectedParentId(undefined);
		setModalVisible(true);
	};

	const handleAddChild = (record: DataDto) => {
		setSelectedData(undefined);
		setSelectedParentId(record.id);
		setModalVisible(true);
	};

	const handleManageItems = (record: DataDto) => {
		setSelectedData(record);
		setDrawerVisible(true);
	};

	const handleDelete = (record: DataDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: async () => {
				await deleteApi(record.id);
				toast.success($t("AbpUi.DeletedSuccessfully"));
				actionRef.current?.reload();
			},
		});
	};

	const columns: ProColumns<DataDto>[] = [
		{
			title: $t("AppPlatform.DisplayName:Name"),
			dataIndex: "name",
			width: 200,
			render: (_, record) => (
				<Button type="link" onClick={() => handleManageItems(record)} style={{ padding: 0 }}>
					{record.name}
				</Button>
			),
		},
		{
			title: $t("AppPlatform.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 200,
		},
		{
			title: $t("AppPlatform.DisplayName:Description"),
			dataIndex: "description",
			ellipsis: true,
		},
		{
			title: $t("AbpUi.Actions"),
			key: "actions",
			fixed: "right",
			width: 250,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[DataDictionaryPermissions.Update],
					)}
					{withAccessChecker(
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>,
						[DataDictionaryPermissions.Delete],
					)}
					<Dropdown
						menu={{
							items: [
								{
									key: "add-child",
									label: $t("AppPlatform.Data:AddChildren"),
									icon: <PlusOutlined />,
									onClick: () => handleAddChild(record),
									disabled: !hasAccessByCodes([DataDictionaryPermissions.Create]),
								},
								{
									key: "items",
									label: $t("AppPlatform.Data:Items"),
									icon: <Iconify icon="material-symbols:align-items-stretch" />,
									onClick: () => handleManageItems(record),
									disabled: !hasAccessByCodes([DataDictionaryPermissions.ManageItems]),
								},
							],
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<DataDto>
					headerTitle={$t("AppPlatform.DisplayName:DataDictionary")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					search={false}
					pagination={false}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("AppPlatform.Data:AddNew")}
							</Button>,
							[DataDictionaryPermissions.Create],
						),
					]}
					request={async () => {
						const { items } = await getAllApi();
						const tree = listToTree(items, { id: "id", pid: "parentId" });
						return {
							data: tree,
							success: true,
						};
					}}
					expandable={{
						defaultExpandAllRows: true,
					}}
				/>
			</Card>
			<DataDictionaryModal
				visible={modalVisible}
				onClose={() => setModalVisible(false)}
				onChange={() => actionRef.current?.reload()}
				dataId={selectedData?.id}
				parentId={selectedParentId}
			/>

			<DataDictionaryItemDrawer
				visible={drawerVisible}
				onClose={() => setDrawerVisible(false)}
				dataDto={selectedData}
			/>
		</>
	);
};

export default DataDictionaryTable;
