// apps/vben5/packages/@abp/platform/src/components/data-dictionaries/DataDictionaryItemDrawer.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { DataDto, DataItemDto } from '../../types/dataDictionaries';

import { defineAsyncComponent, h, reactive, ref } from 'vue';

import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { isNullOrWhiteSpace } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  CheckOutlined,
  CloseOutlined,
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useDataDictionariesApi } from '../../api';
import { ValueType } from '../../types/dataDictionaries';

const { deleteItemApi, getApi } = useDataDictionariesApi();

const dataItems = ref<DataItemDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});
const valueTypeMaps: { [key: number]: string } = {
  [ValueType.Array]: 'Array',
  [ValueType.Boolean]: 'Boolean',
  [ValueType.Date]: 'Date',
  [ValueType.DateTime]: 'DateTime',
  [ValueType.Numeic]: 'Number',
  [ValueType.Object]: 'Object',
  [ValueType.String]: 'String',
};

const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-2/3',
  async onOpenChange(isOpen) {
    if (isOpen) {
      const { name } = drawerApi.getData<DataDto>();
      drawerApi.setState({
        title: `${$t('AppPlatform.DisplayName:DataDictionary')} - ${name}`,
      });
      await onGet();
    }
  },
  showConfirmButton: false,
  title: $t('AppPlatform.Data:Items'),
});

const gridOptions: VxeGridProps<DataItemDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:Name'),
      treeNode: true,
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:DisplayName'),
    },
    {
      align: 'left',
      field: 'description',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:Description'),
    },
    {
      align: 'left',
      field: 'valueType',
      formatter: ({ row }) => {
        return valueTypeMaps[row.valueType] ?? row.valueType;
      },
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:ValueType'),
    },
    {
      align: 'left',
      field: 'defaultValue',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:DefaultValue'),
    },
    {
      align: 'left',
      field: 'allowBeNull',
      minWidth: 150,
      slots: { default: 'allowBeNull' },
      title: $t('AppPlatform.DisplayName:AllowBeNull'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
  treeConfig: {
    accordion: true,
    parentField: 'parentId',
    rowField: 'id',
    transform: true,
  },
};

const gridEvents: VxeGridListeners<DataItemDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  gridEvents,
  gridOptions,
});

const [DataDictionaryItemModal, itemModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./DataDictionaryItemModal.vue'),
  ),
});

async function onGet() {
  const { id } = drawerApi.getData<DataDto>();
  if (isNullOrWhiteSpace(id)) {
    return;
  }
  try {
    drawerApi.setState({ loading: true });
    const dto = await getApi(id);
    dataItems.value = dto.items;
    pageState.total = dto.items.length;
    onPageChange();
  } finally {
    drawerApi.setState({
      loading: false,
    });
  }
}

function onPageChange() {
  const items = dataItems.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  const data = drawerApi.getData<DataDto>();
  itemModalApi.setData({ data });
  itemModalApi.open();
}

function onUpdate(row: DataItemDto) {
  const data = drawerApi.getData<DataDto>();
  itemModalApi.setData({ data, item: row });
  itemModalApi.open();
}

function onDelete(row: DataItemDto) {
  Modal.confirm({
    afterClose: () => {
      gridApi.setLoading(false);
    },
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessage')}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        const { id } = drawerApi.getData<DataDto>();
        await deleteItemApi(id, row.name);
        message.success($t('AbpUi.DeletedSuccessfully'));
        onGet();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
</script>

<template>
  <Drawer>
    <Grid :table-title="$t('AppPlatform.Data:Items')">
      <template #toolbar-tools>
        <Button :icon="h(PlusOutlined)" type="primary" @click="onCreate">
          {{ $t('AppPlatform.Data:AppendItem') }}
        </Button>
      </template>
      <template #allowBeNull="{ row }">
        <div class="flex flex-row justify-center">
          <CheckOutlined v-if="row.allowBeNull" class="text-green-500" />
          <CloseOutlined v-else class="text-red-500" />
        </div>
      </template>
      <template #action="{ row }">
        <div class="flex flex-row">
          <Button
            :icon="h(EditOutlined)"
            block
            type="link"
            @click="onUpdate(row)"
          >
            {{ $t('AbpUi.Edit') }}
          </Button>
          <Button
            :icon="h(DeleteOutlined)"
            block
            danger
            type="link"
            @click="onDelete(row)"
          >
            {{ $t('AbpUi.Delete') }}
          </Button>
        </div>
      </template>
    </Grid>
    <DataDictionaryItemModal @change="onGet" />
  </Drawer>
</template>

<style scoped></style>

// apps/react-admin/src/pages/platform/data-dictionaries/data-dictionary-item-drawer.tsx
import type React from "react";
import { useEffect, useRef, useState } from "react";
import { Drawer, Button, Space, Modal, Tag } from "antd";
import { PlusOutlined, EditOutlined, DeleteOutlined, CheckOutlined, CloseOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { getApi, deleteItemApi } from "@/api/platform/data-dictionaries";
import type { DataDto, DataItemDto } from "#/platform/data-dictionaries";
import { ValueType } from "#/platform/data-dictionaries";
import DataDictionaryItemModal from "./data-dictionary-item-modal";

interface Props {
	visible: boolean;
	onClose: () => void;
	dataDto?: DataDto;
}

const DataDictionaryItemDrawer: React.FC<Props> = ({ visible, onClose, dataDto }) => {
	const { t: $t } = useTranslation();
	const [modal, contextHolder] = Modal.useModal();
	const actionRef = useRef<ActionType>();
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedItem, setSelectedItem] = useState<DataItemDto | undefined>();
	const [dataItems, setDataItems] = useState<DataItemDto[]>([]);
	const [loading, setLoading] = useState(false);

	useEffect(() => {
		if (visible && dataDto) {
			fetchItems();
		}
	}, [visible, dataDto]);

	const fetchItems = async () => {
		if (!dataDto) return;
		try {
			setLoading(true);
			// The API structure implies getting the parent DataDto returns the items list
			const res = await getApi(dataDto.id);
			setDataItems(res.items || []);
		} finally {
			setLoading(false);
		}
	};

	const handleCreate = () => {
		setSelectedItem(undefined);
		setModalVisible(true);
	};

	const handleUpdate = (record: DataItemDto) => {
		setSelectedItem(record);
		setModalVisible(true);
	};

	const handleDelete = (record: DataItemDto) => {
		if (!dataDto) return;
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: async () => {
				await deleteItemApi(dataDto.id, record.name);
				toast.success($t("AbpUi.DeletedSuccessfully"));
				fetchItems();
			},
		});
	};

	const valueTypeMaps: Record<number, string> = {
		[ValueType.Array]: "Array",
		[ValueType.Boolean]: "Boolean",
		[ValueType.Date]: "Date",
		[ValueType.DateTime]: "DateTime",
		[ValueType.Numeic]: "Number",
		[ValueType.Object]: "Object",
		[ValueType.String]: "String",
	};

	const columns: ProColumns<DataItemDto>[] = [
		{
			title: $t("AppPlatform.DisplayName:Name"),
			dataIndex: "name",
			width: 150,
			sorter: (a, b) => a.name.localeCompare(b.name),
		},
		{
			title: $t("AppPlatform.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 150,
		},
		{
			title: $t("AppPlatform.DisplayName:ValueType"),
			dataIndex: "valueType",
			width: 120,
			render: (val) => <Tag>{valueTypeMaps[val as number] || val}</Tag>,
		},
		{
			title: $t("AppPlatform.DisplayName:DefaultValue"),
			dataIndex: "defaultValue",
			width: 150,
			ellipsis: true,
		},
		{
			title: $t("AppPlatform.DisplayName:AllowBeNull"),
			dataIndex: "allowBeNull",
			width: 100,
			align: "center",
			render: (val) =>
				val ? <CheckOutlined className="text-green-500" /> : <CloseOutlined className="text-red-500" />,
		},
		{
			title: $t("AbpUi.Actions"),
			key: "actions",
			fixed: "right",
			width: 150,
			render: (_, record) => (
				<Space>
					<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
						{$t("AbpUi.Edit")}
					</Button>
					<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
						{$t("AbpUi.Delete")}
					</Button>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Drawer
				title={dataDto ? `${$t("AppPlatform.DisplayName:DataDictionary")} - ${dataDto.displayName}` : ""}
				width="60%"
				open={visible}
				onClose={onClose}
				destroyOnClose
			>
				<ProTable<DataItemDto>
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					dataSource={dataItems}
					loading={loading}
					search={false}
					toolBarRender={() => [
						<Button key="add" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
							{$t("AppPlatform.Data:AppendItem")}
						</Button>,
					]}
					pagination={{ pageSize: 15 }}
				/>
			</Drawer>

			<DataDictionaryItemModal
				visible={modalVisible}
				onClose={() => setModalVisible(false)}
				onChange={fetchItems}
				data={dataDto}
				item={selectedItem}
			/>
		</>
	);
};

export default DataDictionaryItemDrawer;
