// apps/vben5/packages/@abp/oss/src/components/containers/ContainerModal.vue
<script setup lang="ts">
import type { OssContainerDto } from '../../types';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { message } from 'ant-design-vue';

import { useContainesApi } from '../../api';

const emits = defineEmits<{
  (event: 'change', data: OssContainerDto): void;
}>();

const { cancel, createApi } = useContainesApi();

const [Form, formApi] = useVbenForm({
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('AbpOssManagement.DisplayName:Name'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  onCancel: cancel,
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
});

async function onSubmit(values: Record<string, any>) {
  try {
    modalApi.setState({ submitting: true });
    const dto = await createApi(values.name);
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="$t('AbpOssManagement.Containers:Create')">
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/oss/containers/container-modal.tsx
import { useEffect, useState } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi } from "@/api/oss/containes";
import type { OssContainerDto } from "#/oss/containes";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: OssContainerDto) => void;
}

const ContainerModal: React.FC<Props> = ({ visible, onClose, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);

	useEffect(() => {
		if (visible) {
			form.resetFields();
		}
	}, [visible, form]);

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const dto = await createApi(values.name);

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(dto);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	return (
		<Modal
			open={visible}
			title={$t("AbpOssManagement.Containers:Create")}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item label={$t("AbpOssManagement.DisplayName:Name")} name="name" rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default ContainerModal;
