// apps/vben5/packages/@abp/platform/src/components/layouts/LayoutModal.vue
<script setup lang="ts">
import type {
  LayoutCreateDto,
  LayoutDto,
  LayoutUpdateDto,
} from '../../types/layouts';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { isNullOrWhiteSpace, listToTree } from '@abp/core';
import { message } from 'ant-design-vue';

import { useDataDictionariesApi, useLayoutsApi } from '../../api';

const emits = defineEmits<{
  (event: 'change', data: LayoutDto): void;
}>();

const { createApi, getApi, updateApi } = useLayoutsApi();
const {
  getAllApi: getDataDictionariesApi,
  getByNameApi: getDataDictionaryByNameApi,
} = useDataDictionariesApi();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      dependencies: {
        show: false,
        triggerFields: ['name'],
      },
      fieldName: 'id',
    },
    {
      component: 'ApiSelect',
      componentProps: {
        allowClear: true,
        api: () => getDataDictionaryByNameApi('UI Framework'),
        labelField: 'displayName',
        resultField: 'items',
        valueField: 'name',
      },
      dependencies: {
        if: (values) => {
          return !values?.id;
        },
        triggerFields: ['id'],
      },
      fieldName: 'framework',
      label: $t('AppPlatform.DisplayName:UIFramework'),
      rules: 'selectRequired',
    },
    {
      component: 'ApiTreeSelect',
      componentProps: {
        allowClear: true,
        api: async () => {
          const { items } = await getDataDictionariesApi();
          return listToTree(items, {
            id: 'id',
            pid: 'parentId',
          });
        },
        labelField: 'displayName',
        valueField: 'id',
        childrenField: 'children',
      },
      dependencies: {
        if: (values) => {
          return !values?.id;
        },
        triggerFields: ['id'],
      },
      fieldName: 'dataId',
      label: $t('AppPlatform.DisplayName:LayoutConstraint'),
      rules: 'selectRequired',
    },
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('AppPlatform.DisplayName:Name'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'displayName',
      label: $t('AppPlatform.DisplayName:DisplayName'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'path',
      label: $t('AppPlatform.DisplayName:Path'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'redirect',
      label: $t('AppPlatform.DisplayName:Redirect'),
    },
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 3,
        },
      },
      fieldName: 'description',
      label: $t('AppPlatform.DisplayName:Description'),
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  closeOnClickModal: false,
  closeOnPressEscape: false,
  draggable: true,
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  onOpenChange: async (isOpen) => {
    if (isOpen) {
      await onGet();
    }
  },
});

async function onGet() {
  formApi.resetForm();
  const { id } = modalApi.getData<LayoutDto>();
  if (isNullOrWhiteSpace(id)) {
    modalApi.setState({ title: $t('AppPlatform.Layout:AddNew') });
    return;
  }
  try {
    modalApi.setState({ loading: true });
    const dto = await getApi(id);
    formApi.setValues(dto, false);
    modalApi.setState({
      title: `${$t('AppPlatform.Layout:Edit')} - ${dto.displayName}`,
    });
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onSubmit(values: Record<string, any>) {
  try {
    modalApi.setState({ submitting: true });
    const api = values.id
      ? updateApi(values.id, values as LayoutUpdateDto)
      : createApi(values as LayoutCreateDto);
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/platform/layouts/layout-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi, updateApi, getApi } from "@/api/platform/layouts";
import {
	getByNameApi as getDataDictionaryByNameApi,
	getAllApi as getDataDictionariesApi,
} from "@/api/platform/data-dictionaries";
import type { LayoutDto, LayoutCreateDto, LayoutUpdateDto } from "#/platform/layouts";
import { listToTree } from "@/utils/tree";
import ApiSelect from "@/components/abp/adapter/api-select";
import ApiTreeSelect from "@/components/abp/adapter/api-tree-select";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: LayoutDto) => void;
	layoutId?: string;
}

const LayoutModal: React.FC<Props> = ({ visible, onClose, onChange, layoutId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);
	const [loading, setLoading] = useState(false);

	useEffect(() => {
		if (visible) {
			form.resetFields();
			if (layoutId) {
				fetchLayout(layoutId);
			}
		}
	}, [visible, layoutId]);

	const fetchLayout = async (id: string) => {
		try {
			setLoading(true);
			const dto = await getApi(id);
			form.setFieldsValue(dto);
		} finally {
			setLoading(false);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			let res: LayoutDto;
			if (layoutId) {
				res = await updateApi(layoutId, values as LayoutUpdateDto);
			} else {
				res = await createApi(values as LayoutCreateDto);
			}

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const uiFrameworkApi = () => getDataDictionaryByNameApi("UI Framework");

	const constraintsApi = async () => {
		const { items } = await getDataDictionariesApi();
		return listToTree(items, {
			id: "id",
			pid: "parentId",
		});
	};

	const modalTitle = layoutId
		? `${$t("AppPlatform.Layout:Edit")} - ${form.getFieldValue("displayName") || ""}`
		: $t("AppPlatform.Layout:AddNew");

	return (
		<Modal
			title={modalTitle}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				{!layoutId && (
					<>
						<Form.Item
							name="framework"
							label={$t("AppPlatform.DisplayName:UIFramework")}
							rules={[{ required: true, message: $t("AbpUi.ThisFieldIsRequired") }]}
						>
							<ApiSelect
								api={uiFrameworkApi}
								resultField="items"
								labelField="displayName"
								valueField="name"
								allowClear
							/>
						</Form.Item>

						<Form.Item
							name="dataId"
							label={$t("AppPlatform.DisplayName:LayoutConstraint")}
							rules={[{ required: true, message: $t("AbpUi.ThisFieldIsRequired") }]}
						>
							<ApiTreeSelect
								api={constraintsApi}
								fieldNames={{ label: "displayName", value: "id", children: "children" }}
								allowClear
								treeDefaultExpandAll
							/>
						</Form.Item>
					</>
				)}

				<Form.Item name="name" label={$t("AppPlatform.DisplayName:Name")} rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="displayName" label={$t("AppPlatform.DisplayName:DisplayName")} rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="path" label={$t("AppPlatform.DisplayName:Path")} rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="redirect" label={$t("AppPlatform.DisplayName:Redirect")}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="description" label={$t("AppPlatform.DisplayName:Description")}>
					<Input.TextArea autoSize={{ minRows: 3 }} />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default LayoutModal;
