// apps/react-admin/src/pages/openiddict/authorizations/authorization-modal.tsx
import { Form, Input, Modal, Select } from "antd";
import { useTranslation } from "react-i18next";
import { useQuery } from "@tanstack/react-query";
import type { IdentityUserDto } from "#/management/identity/user";
import { getApi as getApplication } from "@/api/openiddict/applications";
import { getApi as getAuthorization } from "@/api/openiddict/authorizations";
import { findByIdApi } from "@/api/management/identity/user-lookup";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { UserLookupPermissions } from "@/constants/management/identity/permissions";
import JsonEdit from "@/components/abp/common/json-edit";
import { useEffect } from "react";
import { CircleLoading } from "@/components/loading";

interface Props {
	visible: boolean;
	authorizationId?: string;
	onClose: () => void;
}

const AuthorizationModal: React.FC<Props> = ({ visible, authorizationId, onClose }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	// 获取授权详情和关联数据
	const { data: authorizationData, isLoading } = useQuery({
		queryKey: ["authorization", authorizationId],
		queryFn: async () => {
			if (!authorizationId) {
				return Promise.reject(new Error("authorizationId is undefined"));
			}

			const authorization = await getAuthorization(authorizationId);
			if (!authorization.applicationId) {
				return Promise.reject(new Error("authorization.applicationId is undefined"));
			}
			const application = await getApplication(authorization.applicationId);

			let subjectInfo: IdentityUserDto | undefined;
			if (hasAccessByCodes([UserLookupPermissions.Default])) {
				if (authorization.subject) {
					subjectInfo = await findByIdApi(authorization.subject);
				}
			}

			return {
				...authorization,
				applicationId: `${application.clientId}(${authorization.applicationId})`,
				subject: subjectInfo?.userName ? `${subjectInfo.userName}(${authorization.subject})` : authorization.subject,
			};
		},
		enabled: visible && !!authorizationId,
	});

	// 更新表单数据
	useEffect(() => {
		if (authorizationData && authorizationData.id === authorizationId) {
			form.setFieldsValue(authorizationData);
		}
	}, [authorizationData]);

	const formItems = [
		{
			name: "applicationId",
			label: $t("AbpOpenIddict.DisplayName:ApplicationId"),
			component: Input,
		},
		{
			name: "subject",
			label: $t("AbpOpenIddict.DisplayName:Subject"),
			component: Input,
		},
		{
			name: "type",
			label: $t("AbpOpenIddict.DisplayName:Type"),
			component: Input,
		},
		{
			name: "creationDate",
			label: $t("AbpOpenIddict.DisplayName:CreationDate"),
			component: Input,
		},
		{
			name: "status",
			label: $t("AbpOpenIddict.DisplayName:Status"),
			component: Input,
		},
		{
			name: "scopes",
			label: $t("AbpOpenIddict.DisplayName:Scopes"),
			component: Select,
			props: {
				mode: "tags" as const,
				open: false,
			},
		},
		{
			name: "properties",
			label: $t("AbpOpenIddict.DisplayName:Properties"),
			render: (value: string) => <JsonEdit data={value || ""} />,
		},
	];

	return (
		<Modal open={visible} title={$t("AbpOpenIddict.Authorizations")} onCancel={onClose} footer={null} width="50%">
			{!!authorizationId && visible && isLoading ? (
				<CircleLoading />
			) : (
				<Form
					form={form}
					layout="vertical"
					disabled // 表单只读
				>
					{formItems.map((item) => (
						<Form.Item key={item.name} name={item.name} label={item.label}>
							{item.render ? (
								item.render(form.getFieldValue(item.name))
							) : (
								<item.component className="w-full" readOnly {...item.props} />
							)}
						</Form.Item>
					))}
				</Form>
			)}
		</Modal>
	);
};

export default AuthorizationModal;

// apps/vben5/packages/@abp/openiddict/src/components/authorizations/AuthorizationModal.vue
<script setup lang="ts">
import type { OpenIddictAuthorizationDto } from '../../types';

import { useAccess } from '@vben/access';
import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  type IdentityUserDto,
  userLookupApi,
  UserLookupPermissions,
} from '@abp/identity';
import { CodeEditor } from '@abp/ui';
import { Select } from 'ant-design-vue';

import { getApi as getApplication } from '../../api/applications';
import { getApi as getAuthorization } from '../../api/authorizations';

defineOptions({
  name: 'AuthorizationModal',
});

const Option = Select.Option;

const { hasAccessByCodes } = useAccess();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  schema: [
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'applicationId',
      label: $t('AbpOpenIddict.DisplayName:ApplicationId'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'subject',
      label: $t('AbpOpenIddict.DisplayName:Subject'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'type',
      label: $t('AbpOpenIddict.DisplayName:Type'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'creationDate',
      label: $t('AbpOpenIddict.DisplayName:CreationDate'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'status',
      label: $t('AbpOpenIddict.DisplayName:Status'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'scopes',
      label: $t('AbpOpenIddict.DisplayName:Scopes'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'properties',
      label: $t('AbpOpenIddict.DisplayName:Properties'),
    },
  ],

  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      try {
        modalApi.setState({ loading: true });
        const { id } = modalApi.getData<OpenIddictAuthorizationDto>();
        await onGet(id);
      } finally {
        modalApi.setState({ loading: false });
      }
    }
  },
  showConfirmButton: false,
  title: $t('AbpOpenIddict.Authorizations'),
});

async function onGet(id: string) {
  const authorization = await getAuthorization(id);
  const application = await getApplication(authorization.applicationId!);
  let subjectInfo: IdentityUserDto | undefined;
  if (hasAccessByCodes([UserLookupPermissions.Default])) {
    subjectInfo = await userLookupApi.findByIdApi(authorization.subject!);
  }
  formApi.setValues({
    ...authorization,
    applicationId: `${application.clientId}(${authorization.applicationId})`,
    subject: subjectInfo?.userName
      ? `${subjectInfo.userName}(${authorization.subject})`
      : authorization.subject,
  });
}
</script>

<template>
  <Modal>
    <Form>
      <template #scopes="{ modelValue }">
        <Select :disabled="true" :value="modelValue" mode="tags">
          <Option
            v-for="scope in modelValue"
            :key="scope"
            :title="scope"
            :value="scope"
          />
        </Select>
      </template>
      <template #properties="{ modelValue }">
        <CodeEditor :value="modelValue" readonly />
      </template>
    </Form>
  </Modal>
</template>

<style scoped></style>
