// apps/vben5/packages/@abp/identity/src/components/security-logs/SecurityLogDrawer.vue
<script setup lang="ts">
import type { SecurityLogDto } from '../../types/security-logs';

import { ref } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { Descriptions } from 'ant-design-vue';

import { getApi } from '../../api/security-logs';

defineOptions({
  name: 'SecurityLogDrawer',
});

const DescriptionsItem = Descriptions.Item;

const formModel = ref<SecurityLogDto>({} as SecurityLogDto);

const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-auto',
  onCancel() {
    drawerApi.close();
  },
  onConfirm: async () => {},
  onOpenChange: async (isOpen: boolean) => {
    formModel.value = {} as SecurityLogDto;
    if (isOpen) {
      try {
        drawerApi.setState({ loading: true });
        const dto = drawerApi.getData<SecurityLogDto>();
        await onGet(dto.id);
      } finally {
        drawerApi.setState({ loading: false });
      }
    }
  },
  title: $t('AbpAuditLogging.SecurityLog'),
});
/** 查询审计日志 */
async function onGet(id: string) {
  const dto = await getApi(id);
  formModel.value = dto;
}
</script>

<template>
  <Drawer>
    <div style="width: 800px">
      <Descriptions :colon="false" :column="2" bordered size="small">
        <DescriptionsItem :label="$t('AbpAuditLogging.ApplicationName')">
          {{ formModel.applicationName }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.CreationTime')">
          {{ formatToDateTime(formModel.creationTime) }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.Identity')">
          {{ formModel.identity }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.TenantName')">
          {{ formModel.tenantName }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.Actions')">
          {{ formModel.action }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.CorrelationId')">
          {{ formModel.correlationId }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.UserId')">
          {{ formModel.userId }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.UserName')">
          {{ formModel.userName }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.ClientId')">
          {{ formModel.clientId }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.ClientIpAddress')">
          {{ formModel.clientIpAddress }}
        </DescriptionsItem>
        <DescriptionsItem
          :label="$t('AbpAuditLogging.BrowserInfo')"
          :label-style="{ width: '110px' }"
          :span="2"
        >
          {{ formModel.browserInfo }}
        </DescriptionsItem>
        <DescriptionsItem :label="$t('AbpAuditLogging.Additional')" :span="2">
          {{ formModel.extraProperties }}
        </DescriptionsItem>
      </Descriptions>
    </div>
  </Drawer>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/security-logs/security-log-drawer.tsx
import type React from "react";
import { Drawer, Descriptions } from "antd";
import { formatToDateTime } from "@/utils/abp";
import { useTranslation } from "react-i18next";
import { useQuery } from "@tanstack/react-query";
import { getApi } from "@/api/management/identity/security-logs";

interface Props {
	visible: boolean;
	onClose: () => void;
	securityLogId?: string;
}

const SecurityLogDrawer: React.FC<Props> = ({ visible, onClose, securityLogId }) => {
	const { t: $t } = useTranslation();

	const { data: formModel, isLoading } = useQuery({
		queryKey: ["securityLog", securityLogId],
		queryFn: () => {
			if (!securityLogId) {
				return Promise.reject(new Error("securityLogId is undefined"));
			}
			return getApi(securityLogId);
		},
		enabled: visible && !!securityLogId,
	});

	return (
		<Drawer
			title={$t("AbpAuditLogging.SecurityLog")}
			open={visible}
			onClose={onClose}
			width={800}
			loading={isLoading}
			destroyOnClose
		>
			<Descriptions bordered size="small" column={2} labelStyle={{ width: "110px" }} colon={false}>
				<Descriptions.Item label={$t("AbpAuditLogging.ApplicationName")}>
					{formModel?.applicationName}
				</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.CreationTime")}>
					{formModel?.creationTime ? formatToDateTime(formModel.creationTime) : ""}
				</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.Identity")}>{formModel?.identity}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.TenantName")}>{formModel?.tenantName}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.Actions")}>{formModel?.action}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.CorrelationId")}>{formModel?.correlationId}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.UserId")}>{formModel?.userId}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.UserName")}>{formModel?.userName}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.ClientId")}>{formModel?.clientId}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.ClientIpAddress")}>
					{formModel?.clientIpAddress}
				</Descriptions.Item>
				<Descriptions.Item label={$t("AbpAuditLogging.BrowserInfo")} span={2}>
					{formModel?.browserInfo}
				</Descriptions.Item>

				<Descriptions.Item label={$t("AbpAuditLogging.Additional")} span={2}>
					{formModel?.extraProperties ? JSON.stringify(formModel.extraProperties, null, 2) : ""}
				</Descriptions.Item>
			</Descriptions>
		</Drawer>
	);
};

export default SecurityLogDrawer;
