// apps/react-admin/src/components/abp/auditing/entity-change-drawer.tsx
import { getListWithUsernameApi } from "@/api/management/auditing/entity-changes";
import { EntityChangeTable } from "./entity-change-table";
import type { EntityChangeGetWithUsernameInput } from "#/management/auditing/entity-changes";
import { Drawer } from "antd";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";

interface EntityChangeDrawerProps {
	open: boolean;
	onClose: () => void;
	input?: EntityChangeGetWithUsernameInput;
	subject?: string;
}

export const EntityChangeDrawer: React.FC<EntityChangeDrawerProps> = ({ open, onClose, input, subject }) => {
	const { t } = useTranslation();

	const { data: entityChanges = [] } = useQuery({
		queryKey: ["entityChanges", input],
		queryFn: async () => {
			if (!input) return [];
			const { items } = await getListWithUsernameApi(input);
			return items.map((item) => ({
				...item.entityChange,
				userName: item.userName,
			}));
		},
		enabled: open && !!input,
	});

	return (
		<Drawer title={`${t("AbpAuditLogging.EntitiesChanged")}: ${subject}`} open={open} onClose={onClose} width={800}>
			<EntityChangeTable data={entityChanges} showUserName />
		</Drawer>
	);
};

// apps/vben5/packages/@abp/auditing/src/components/entity-changes/EntityChangeDrawer.vue
<script setup lang="ts">
import type {
  EntityChangeDto,
  EntityChangeGetWithUsernameInput,
} from '../../types/entity-changes';

import { ref } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { getListWithUsernameApi } from '../../api/entity-changes';
import EntityChangeTable from '../entity-changes/EntityChangeTable.vue';

const entityChanges = ref<EntityChangeDto[]>([]);

const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-auto',
  onCancel() {
    drawerApi.close();
  },
  onConfirm: async () => {},
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      const input = drawerApi.getData<EntityChangeGetWithUsernameInput>();
      const { items } = await getListWithUsernameApi(input);
      entityChanges.value = items.map((item) => {
        return {
          ...item.entityChange,
          userName: item.userName,
        };
      });
    }
  },
  title: $t('AbpAuditLogging.EntitiesChanged'),
});
</script>

<template>
  <Drawer>
    <div style="max-width: 800px">
      <EntityChangeTable :data="entityChanges" show-user-name />
    </div>
  </Drawer>
</template>

<style scoped></style>
