// apps/vben5/packages/@abp/oss/src/components/objects/FileList.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { OssContainerDto } from '../../types/containes';
import type { OssObjectDto } from '../../types/objects';

import { defineAsyncComponent, h, nextTick, ref, watch } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDateTime, isNullOrWhiteSpace } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  DownloadOutlined,
  UploadOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useObjectsApi } from '../../api';
import { useContainesApi } from '../../api/useContainesApi';
import { OssObjectPermissions } from '../../constants/permissions';

defineOptions({
  name: 'FileList',
});

const props = defineProps<{
  bucket: string;
  path: string;
}>();

const kbUnit = 1 * 1024;
const mbUnit = kbUnit * 1024;
const gbUnit = mbUnit * 1024;

const { hasAccessByCodes } = useAccess();
const { cancel, getObjectsApi } = useContainesApi();
const { deleteApi, generateUrlApi } = useObjectsApi();

const selectedKeys = ref<string[]>([]);

const gridOptions: VxeGridProps<OssContainerDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'isFolder',
      formatter: ({ cellValue }) => {
        return cellValue
          ? $t('AbpOssManagement.DisplayName:Folder')
          : $t('AbpOssManagement.DisplayName:Standard');
      },
      minWidth: 150,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:FileType'),
    },
    {
      align: 'left',
      field: 'size',
      formatter: ({ cellValue }) => {
        const size = Number(cellValue);
        if (size > gbUnit) {
          let gb = Math.round(size / gbUnit);
          if (gb < 1) {
            gb = 1;
          }
          return `${gb} GB`;
        }
        if (size > mbUnit) {
          let mb = Math.round(size / mbUnit);
          if (mb < 1) {
            mb = 1;
          }
          return `${mb} MB`;
        }
        let kb = Math.round(size / kbUnit);
        if (kb < 1) {
          kb = 1;
        }
        return `${kb} KB`;
      },
      minWidth: 150,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:Size'),
    },
    {
      align: 'left',
      field: 'creationDate',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      minWidth: 120,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:CreationDate'),
    },
    {
      align: 'left',
      field: 'lastModifiedDate',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      minWidth: 120,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:LastModifiedDate'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 200,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        const res = await getObjectsApi({
          bucket: props.bucket,
          maxResultCount: page.pageSize,
          prefix: props.path,
          sorting,
          skipCount: (page.currentPage - 1) * page.pageSize,
        });
        return {
          totalCount: res.maxKeys,
          items: res.objects,
        };
      },
    },
    autoLoad: false,
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  sortConfig: {
    remote: true,
  },
  toolbarConfig: {
    custom: true,
    export: false,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<OssContainerDto> = {
  checkboxAll: (params) => {
    selectedKeys.value = params.records.map((record) => record.name);
  },
  checkboxChange: (params) => {
    selectedKeys.value = params.records.map((record) => record.name);
  },
  sortChange: () => {
    gridApi.query();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  gridEvents,
  gridOptions,
});

const [FileUploadModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./FileUploadModal.vue'),
  ),
});

function onUpload() {
  modalApi.setData({
    bucket: props.bucket,
    path: props.path,
  });
  modalApi.open();
}

function onDelete(row: OssObjectDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name]),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await deleteApi({
        bucket: props.bucket,
        mD5: false,
        object: row.name,
        path: row.path,
      });
      message.success($t('AbpUi.DeletedSuccessfully'));
      await gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

async function onDownload(row: OssObjectDto) {
  const downloadUrl = await generateUrlApi({
    bucket: props.bucket,
    mD5: false,
    object: row.name,
    path: row.path,
  });
  const link = document.createElement('a');
  link.style.display = 'none';
  link.href = downloadUrl;
  link.setAttribute('download', row.name);
  document.body.append(link);
  link.click();
}

watch(
  () => props.bucket,
  (bucket) => {
    nextTick(() => {
      gridApi.setGridOptions({
        toolbarConfig: {
          refresh: !isNullOrWhiteSpace(bucket),
        },
      });
      if (!isNullOrWhiteSpace(bucket)) {
        gridApi.query();
      }
    });
  },
);

watch(
  () => props.path,
  (newVal, oldVal) => {
    if (newVal !== oldVal) {
      nextTick(() => {
        gridApi.query();
      });
    }
  },
);
</script>

<template>
  <Grid :table-title="$t('AbpOssManagement.FileList')">
    <template #toolbar-tools>
      <Button
        v-if="props.path"
        :icon="h(UploadOutlined)"
        type="primary"
        @click="onUpload"
      >
        {{ $t('AbpOssManagement.Objects:UploadFile') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          v-if="
            !row.isFolder && hasAccessByCodes([OssObjectPermissions.Download])
          "
          :icon="h(DownloadOutlined)"
          block
          type="link"
          @click="onDownload(row)"
        >
          {{ $t('AbpOssManagement.Objects:Download') }}
        </Button>
        <Button
          v-if="hasAccessByCodes([OssObjectPermissions.Delete])"
          :icon="h(DeleteOutlined)"
          danger
          block
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
  </Grid>
  <FileUploadModal @file-uploaded="() => gridApi.query()" />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/oss/objects/file-list.tsx
import type React from "react";
import { useRef, useState, useEffect } from "react";
import { Button, Card, Modal, Space } from "antd";
import { DeleteOutlined, DownloadOutlined, UploadOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { getObjectsApi } from "@/api/oss/containes";
import { deleteApi, generateUrlApi } from "@/api/oss/objects";
import type { OssObjectDto } from "#/oss/objects";
import { formatToDateTime } from "@/utils/abp";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { OssObjectPermissions } from "@/constants/oss/permissions";
import FileUploadModal from "./file-upload-modal";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";

interface Props {
	bucket: string;
	path: string;
}

const FileList: React.FC<Props> = ({ bucket, path }) => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();
	const [uploadModalVisible, setUploadModalVisible] = useState(false);

	// Reload table when bucket or path changes
	useEffect(() => {
		if (bucket) {
			actionRef.current?.reload();
		}
	}, [bucket, path]);

	const handleUpload = () => {
		setUploadModalVisible(true);
	};

	const handleDelete = (row: OssObjectDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: async () => {
				await deleteApi({
					bucket,
					object: row.name,
					path: row.path,
				});
				toast.success($t("AbpUi.DeletedSuccessfully"));
				actionRef.current?.reload();
			},
		});
	};

	const handleDownload = async (row: OssObjectDto) => {
		const url = await generateUrlApi({
			bucket,
			mD5: false,
			object: row.name,
			path: row.path,
		});
		const link = document.createElement("a");
		link.style.display = "none";
		link.href = url;
		link.setAttribute("download", row.name);
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
	};

	const formatSize = (size?: number) => {
		if (!size) return "";
		const kb = 1024;
		const mb = kb * 1024;
		const gb = mb * 1024;

		if (size > gb) return `${(size / gb).toFixed(2)} GB`;
		if (size > mb) return `${(size / mb).toFixed(2)} MB`;
		return `${(size / kb).toFixed(2)} KB`;
	};

	const columns: ProColumns<OssObjectDto>[] = [
		{
			title: $t("AbpOssManagement.DisplayName:Name"),
			dataIndex: "name",
			minWidth: 150,
			sorter: true,
		},
		{
			title: $t("AbpOssManagement.DisplayName:FileType"),
			dataIndex: "isFolder",
			minWidth: 150,
			sorter: true,
			render: (val) => (val ? $t("AbpOssManagement.DisplayName:Folder") : $t("AbpOssManagement.DisplayName:Standard")),
		},
		{
			title: $t("AbpOssManagement.DisplayName:Size"),
			dataIndex: "size",
			minWidth: 150,
			sorter: true,
			render: (_, row) => formatSize(row.size),
		},
		{
			title: $t("AbpOssManagement.DisplayName:CreationDate"),
			dataIndex: "creationDate",
			minWidth: 150,
			sorter: true,
			render: (_, row) => formatToDateTime(row.creationDate),
		},
		{
			title: $t("AbpOssManagement.DisplayName:LastModifiedDate"),
			dataIndex: "lastModifiedDate",
			minWidth: 150,
			sorter: true,
			render: (_, row) => formatToDateTime(row.lastModifiedDate),
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 200,
			render: (_, record) => (
				<Space>
					{!record.isFolder && hasAccessByCodes([OssObjectPermissions.Download]) && (
						<Button type="link" icon={<DownloadOutlined />} onClick={() => handleDownload(record)}>
							{$t("AbpOssManagement.Objects:Download")}
						</Button>
					)}
					{hasAccessByCodes([OssObjectPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<OssObjectDto>
					headerTitle={$t("AbpOssManagement.FileList")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={false}
					toolBarRender={() => [
						path && (
							<Button key="upload" type="primary" icon={<UploadOutlined />} onClick={handleUpload}>
								{$t("AbpOssManagement.Objects:UploadFile")}
							</Button>
						),
					]}
					request={async (params, sorter) => {
						if (!bucket) return { data: [], success: true };

						const sorting =
							sorter && Object.keys(sorter).length > 0
								? Object.keys(sorter)
										.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
										.join(", ")
								: undefined;

						// Note: Prefix logic handles path filtering
						// Logic for path: if path is ./ or empty, prefix might be empty or root logic
						const prefix = path === "./" ? "" : path;

						const res = await getObjectsApi({
							bucket,
							maxResultCount: params.pageSize,
							skipCount: ((params.current || 1) - 1) * (params.pageSize || 10),
							prefix: prefix,
							sorting,
							// You might need delimiter here if listing "current folder only"
							// delimiter: '/'
						});

						return {
							data: res.objects,
							total: res.maxKeys,
							success: true,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<FileUploadModal
				visible={uploadModalVisible}
				bucket={bucket}
				path={path === "./" ? "" : path}
				onClose={() => setUploadModalVisible(false)}
				onFileUploaded={() => actionRef.current?.reload()}
			/>
		</>
	);
};

export default FileList;
