// apps/vben5/packages/@abp/oss/src/components/objects/FolderTree.vue
<script setup lang="ts">
import type { EventDataNode, Key } from 'ant-design-vue/es/vc-tree/interface';
import type { TreeProps } from 'ant-design-vue/es/vc-tree/props';

import type { OssContainerDto } from '../../types';
import type { OssObjectDto } from '../../types/objects';

import { defineAsyncComponent, onMounted, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Button, Card, DirectoryTree, Empty, Select } from 'ant-design-vue';

import { useContainesApi } from '../../api';

const emits = defineEmits<{
  (event: 'bucketChange', data: string): void;
  (event: 'folderChange', data: string): void;
}>();

interface Folder {
  children?: Folder[];
  isLeaf?: boolean;
  key: string;
  name: string;
  path?: string;
  title: string;
}

const { getListApi: getContainersApi, getObjectsApi } = useContainesApi();

const [FolderModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./FolderModal.vue')),
});

const rootFolder: Folder = {
  isLeaf: false,
  key: './',
  name: './',
  path: '',
  title: $t('AbpOssManagement.Objects:Root'),
  children: [],
};

const bucket = ref<string>('');
const loadedFolders = ref<string[]>([]);
const expandedFolders = ref<string[]>([]);
const selectedFolders = ref<string[]>([]);
const containers = ref<OssContainerDto[]>([]);
const folders = ref<Folder[]>([
  {
    ...rootFolder,
  },
]);

const onLoadChildFolders: TreeProps['loadData'] = async (treeNode) => {
  let path = '';
  if (treeNode.dataRef?.path) {
    path = path + treeNode.dataRef?.path;
  }
  if (treeNode.dataRef?.name) {
    path = path + treeNode.dataRef?.name;
  }
  try {
    treeNode.dataRef!.children = await getFolders(bucket.value!, path);
  } catch {
    treeNode.dataRef!.children = [];
  }
  folders.value = [...folders.value];
  loadedFolders.value = [...loadedFolders.value, treeNode.key.toString()];
};

async function onInit() {
  const getContainersRes = await getContainersApi({
    maxResultCount: 1000,
  });
  containers.value = getContainersRes.containers;
}

async function getFolders(bucket: string, path?: string) {
  const { objects } = await getObjectsApi({
    bucket,
    delimiter: '/',
    maxResultCount: 1000,
    prefix: path ?? '',
  });
  return objects
    .filter((f) => f.isFolder)
    .map((folder) => {
      return {
        isLeaf: false,
        key: `${folder.path ?? ''}${folder.name}`,
        name: folder.name,
        path: folder.path,
        title: folder.name,
        children: [],
      };
    });
}

function onFolderExpand(
  _: Key[],
  info: {
    expanded: boolean;
    node: EventDataNode;
  },
) {
  if (!info.expanded) {
    const keys = loadedFolders.value;
    const findIndex = keys.lastIndexOf(info.node.key.toString());
    findIndex !== -1 && keys.splice(findIndex);
    loadedFolders.value = keys;
  }
}

function onFolderChange(selectedKeys: Key[]) {
  if (selectedKeys.length === 1) {
    emits('folderChange', selectedKeys[0]!.toString());
  }
}

async function onBucketChange(bucket: string) {
  emits('bucketChange', bucket);
  expandedFolders.value = [];
  loadedFolders.value = [];
  folders.value = [
    {
      ...rootFolder,
    },
  ];
}

function onCreate() {
  modalApi.setData({
    bucket: bucket.value,
    path: selectedFolders.value[0],
  });
  modalApi.open();
}

function onFolderCreated(ossObject: OssObjectDto) {
  const keys = expandedFolders.value;
  const findIndex = keys.lastIndexOf(ossObject.path);
  if (findIndex !== -1) {
    keys.splice(findIndex);
    expandedFolders.value = keys;
    loadedFolders.value = [];
  }
}

onMounted(onInit);
</script>

<template>
  <Card :title="$t('AbpOssManagement.Containers')" class="h-full">
    <div class="flex h-full flex-col gap-2">
      <Select
        :placeholder="$t('AbpOssManagement.Containers:Select')"
        :options="containers"
        :field-names="{ label: 'name', value: 'name' }"
        v-model:value="bucket"
        @change="(e) => onBucketChange(e!.toString())"
      />
      <Button v-if="bucket" block type="primary" ghost @click="onCreate">
        {{ $t('AbpOssManagement.Objects:CreateFolder') }}
      </Button>
      <div class="h-[calc(100%-100px)] overflow-auto">
        <DirectoryTree
          v-if="bucket"
          block-node
          v-model:expanded-keys="expandedFolders"
          v-model:selected-keys="selectedFolders"
          :loaded-keys="loadedFolders"
          :tree-data="folders"
          :load-data="onLoadChildFolders"
          @select="onFolderChange"
          @expand="onFolderExpand"
        />
        <Empty v-else />
      </div>
    </div>
  </Card>
  <FolderModal @change="onFolderCreated" />
</template>

<style scoped lang="scss">
:deep(.ant-tree) {
  .ant-tree-title {
    // word-break: break-word;
    white-space: normal;
  }
}

:deep(.ant-card-body) {
  height: calc(100% - 56px);
}
</style>

// apps/react-admin/src/pages/oss/objects/folder-tree.tsx
import type React from "react";
import { useState } from "react";
import { Card, Select, Button, Tree, Empty, Spin } from "antd";
import { useTranslation } from "react-i18next";
import { useQuery } from "@tanstack/react-query";
import { getListApi as getContainersApi, getObjectsApi } from "@/api/oss/containes";
import FolderModal from "./folder-modal";

const { DirectoryTree } = Tree;

interface FolderNode {
	key: string;
	title: string;
	isLeaf?: boolean;
	children?: FolderNode[];
	dataRef?: { path?: string; name: string };
}

interface Props {
	onBucketChange: (bucket: string) => void;
	onFolderChange: (path: string) => void;
}

const FolderTree: React.FC<Props> = ({ onBucketChange, onFolderChange }) => {
	const { t: $t } = useTranslation();

	// -- State --
	const [bucket, setBucket] = useState<string>("");
	const [treeData, setTreeData] = useState<FolderNode[]>([]);

	// Controlled Tree State
	const [expandedKeys, setExpandedKeys] = useState<React.Key[]>([]);
	const [selectedKeys, setSelectedKeys] = useState<React.Key[]>([]);
	const [loadedKeys, setLoadedKeys] = useState<React.Key[]>([]);

	// Modal State
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedPathForCreate, setSelectedPathForCreate] = useState<string>("");

	// -- 1. React Query for Containers --
	const { data: containerData, isLoading: isContainersLoading } = useQuery({
		queryKey: ["oss-containers-list"],
		queryFn: () => getContainersApi({ maxResultCount: 1000 }),
	});

	const containers = containerData?.containers || [];

	// -- Helpers --
	const rootNode: FolderNode = {
		key: "./",
		title: $t("AbpOssManagement.Objects:Root"),
		isLeaf: false,
		dataRef: { path: "", name: "./" },
		children: [],
	};

	// 3. FIX: Completely reset tree when bucket changes
	const handleBucketChange = (val: string) => {
		setBucket(val);
		onBucketChange(val);

		// Reset ALL list states to prevent stale paths
		setTreeData([rootNode]);
		setExpandedKeys([]);
		setLoadedKeys([]);
		setSelectedKeys([]);
		setSelectedPathForCreate(""); // Reset create path
		onFolderChange(""); // Reset file list path
	};

	const getFolders = async (bucketName: string, prefix: string) => {
		const { objects } = await getObjectsApi({
			bucket: bucketName,
			delimiter: "/",
			maxResultCount: 1000,
			prefix: prefix,
		});
		return objects
			.filter((f) => f.isFolder)
			.map((folder) => ({
				key: `${folder.path || ""}${folder.name}`,
				title: folder.name,
				isLeaf: false,
				dataRef: folder,
				children: [],
			}));
	};

	const updateTreeData = (list: FolderNode[], key: React.Key, children: FolderNode[]): FolderNode[] => {
		return list.map((node) => {
			if (node.key === key) {
				return { ...node, children };
			}
			if (node.children) {
				return { ...node, children: updateTreeData(node.children, key, children) };
			}
			return node;
		});
	};

	// -- Tree Event Handlers --

	const onLoadData = async ({ key, dataRef }: any) => {
		if (!bucket) return;

		let path = "";
		if (dataRef?.path) path += dataRef.path;
		if (dataRef?.name && dataRef.name !== "./") path += dataRef.name;

		try {
			const childFolders = await getFolders(bucket, path);
			setTreeData((origin) => updateTreeData(origin, key, childFolders));
			setLoadedKeys((prev) => [...prev, key]);
		} catch (error) {
			console.error(error);
			setTreeData((origin) => updateTreeData(origin, key, []));
		}
	};

	const onExpand = (keys: React.Key[], info: any) => {
		setExpandedKeys(keys);
		if (!info.expanded) {
			const nodeKey = info.node.key;
			setLoadedKeys((prev) => prev.filter((k) => k !== nodeKey));
		}
	};

	const onSelect = (keys: React.Key[], info: any) => {
		setSelectedKeys(keys);
		if (keys.length === 1) {
			const keyStr = keys[0].toString();
			// 1. Determine Path
			const nodePath = keyStr === "./" ? "" : keyStr;

			// 2. Pass path to parent (File List)
			onFolderChange(nodePath);

			// 3. FIX: Store specific path for "Create Folder" modal
			setSelectedPathForCreate(nodePath);
		}
	};

	const handleCreateFolder = () => {
		// If nothing selected, it stays empty (root), which is handled by default state
		setModalVisible(true);
	};

	const handleFolderCreated = () => {
		handleBucketChange(bucket); // TODO just re-fetch entire tree for simplicity  parent's other children (file-list.tsx) should also refresh (1), and the reverse is also true (2) and the same applies in reverse.
	};

	return (
		<>
			<Card title={$t("AbpOssManagement.Containers")} className="h-full flex flex-col">
				<div className="flex flex-col gap-2 flex-1">
					{isContainersLoading ? (
						<div className="flex justify-center p-4">
							<Spin />
						</div>
					) : (
						<Select
							placeholder={$t("AbpOssManagement.Containers:Select")}
							options={containers.map((c) => ({ label: c.name, value: c.name }))}
							value={bucket || undefined}
							onChange={handleBucketChange}
							className="w-full"
						/>
					)}

					{bucket ? (
						<>
							<Button block type="primary" ghost onClick={handleCreateFolder}>
								{$t("AbpOssManagement.Objects:CreateFolder")}
							</Button>
							<div className="overflow-auto flex-1 mt-2">
								<DirectoryTree
									key={bucket}
									blockNode
									treeData={treeData}
									// Controlled State
									expandedKeys={expandedKeys}
									selectedKeys={selectedKeys}
									loadedKeys={loadedKeys}
									// Handlers
									loadData={onLoadData}
									onSelect={onSelect}
									onExpand={onExpand}
									// Default
									defaultExpandedKeys={["./"]}
								/>
							</div>
						</>
					) : (
						<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} />
					)}
				</div>
			</Card>

			<FolderModal
				visible={modalVisible}
				bucket={bucket}
				path={selectedPathForCreate}
				onClose={() => setModalVisible(false)}
				onChange={handleFolderCreated}
			/>
		</>
	);
};

export default FolderTree;
