// apps/vben5/packages/@abp/oss/src/components/objects/FolderModal.vue
<script setup lang="ts">
import type { OssObjectDto } from '../../types/objects';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { message } from 'ant-design-vue';

import { useObjectsApi } from '../../api';

interface ModalState {
  bucket: string;
  path?: string;
}

const emits = defineEmits<{
  (event: 'change', data: OssObjectDto): void;
}>();

const { createApi } = useObjectsApi();

const [Form, formApi] = useVbenForm({
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('AbpOssManagement.DisplayName:Name'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});

const [Modal, modalApi] = useVbenModal({
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
});

async function onSubmit(values: Record<string, any>) {
  try {
    const state = modalApi.getData<ModalState>();
    modalApi.setState({ submitting: true });
    const dto = await createApi({
      bucket: state.bucket,
      fileName: values.name,
      overwrite: false,
      path: state.path,
    });
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="$t('AbpOssManagement.Objects:CreateFolder')">
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/oss/objects/folder-modal.tsx
import { useEffect, useState } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi } from "@/api/oss/objects";
import type { OssObjectDto } from "#/oss/objects";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: OssObjectDto) => void;
	bucket: string;
	path?: string;
}

const FolderModal: React.FC<Props> = ({ visible, onClose, onChange, bucket, path }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);

	useEffect(() => {
		if (visible) {
			form.resetFields();
		}
	}, [visible, form]);

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const dto = await createApi({
				bucket: bucket,
				fileName: values.name,
				overwrite: false,
				path: path,
			});

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(dto);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	return (
		<Modal
			open={visible}
			title={$t("AbpOssManagement.Objects:CreateFolder")}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item label={$t("AbpOssManagement.DisplayName:Name")} name="name" rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default FolderModal;
