// apps/vben5/packages/@abp/permissions/src/components/definitions/permissions/PermissionDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { PermissionDefinitionDto } from '../../../types/definitions';
import type { PermissionGroupDefinitionDto } from '../../../types/groups';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  listToTree,
  useLocalization,
  useLocalizationSerializer,
} from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal, Tag } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

import { usePermissionDefinitionsApi } from '../../../api/usePermissionDefinitionsApi';
import { usePermissionGroupDefinitionsApi } from '../../../api/usePermissionGroupDefinitionsApi';
import { GroupDefinitionsPermissions } from '../../../constants/permissions';
import { useTypesMap } from './types';

defineOptions({
  name: 'PermissionDefinitionTable',
});

interface PermissionVo {
  children: PermissionVo[];
  displayName: string;
  groupName: string;
  isEnabled: boolean;
  isStatic: boolean;
  name: string;
  parentName?: string;
  providers: string[];
  stateCheckers: string[];
}
interface PermissionGroupVo {
  displayName: string;
  name: string;
  permissions: PermissionVo[];
}

const permissionGroups = ref<PermissionGroupVo[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const { Lr } = useLocalization();
const { deserialize } = useLocalizationSerializer();
const { multiTenancySidesMap, providersMap } = useTypesMap();
const { getListApi: getGroupsApi } = usePermissionGroupDefinitionsApi();
const { deleteApi, getListApi: getPermissionsApi } =
  usePermissionDefinitionsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<PermissionGroupDefinitionDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'group',
      slots: { content: 'group' },
      type: 'expand',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('AbpPermissionManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AbpPermissionManagement.DisplayName:DisplayName'),
    },
  ],
  expandConfig: {
    padding: true,
    trigger: 'row',
  },
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};
const subGridColumns: VxeGridProps<PermissionDefinitionDto>['columns'] = [
  {
    align: 'center',
    type: 'seq',
    width: 50,
  },
  {
    align: 'left',
    field: 'name',
    minWidth: 150,
    title: $t('AbpPermissionManagement.DisplayName:Name'),
    treeNode: true,
  },
  {
    align: 'left',
    field: 'displayName',
    minWidth: 120,
    title: $t('AbpPermissionManagement.DisplayName:DisplayName'),
  },
  {
    align: 'center',
    field: 'multiTenancySide',
    minWidth: 100,
    slots: { default: 'tenant' },
    title: $t('AbpPermissionManagement.DisplayName:MultiTenancySide'),
  },
  {
    align: 'center',
    field: 'providers',
    minWidth: 100,
    slots: { default: 'providers' },
    title: $t('AbpPermissionManagement.DisplayName:Providers'),
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 180,
  },
];

const gridEvents: VxeGridListeners<PermissionGroupDefinitionDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [GroupGrid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [PermissionDefinitionModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./PermissionDefinitionModal.vue'),
  ),
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const groupRes = await getGroupsApi(input);
    const permissionRes = await getPermissionsApi(input);
    pageState.total = groupRes.items.length;
    permissionGroups.value = groupRes.items.map((group) => {
      const localizableGroup = deserialize(group.displayName);
      const permissions = permissionRes.items
        .filter((permission) => permission.groupName === group.name)
        .map((permission) => {
          const localizablePermission = deserialize(permission.displayName);
          return {
            ...permission,
            displayName: Lr(
              localizablePermission.resourceName,
              localizablePermission.name,
            ),
          };
        });
      return {
        ...group,
        displayName: Lr(localizableGroup.resourceName, localizableGroup.name),
        permissions: listToTree(permissions, {
          id: 'name',
          pid: 'parentName',
        }),
      };
    });
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = permissionGroups.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: PermissionDefinitionDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: PermissionDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <GroupGrid :table-title="$t('AbpPermissionManagement.PermissionDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[GroupDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('AbpPermissionManagement.PermissionDefinitions:AddNew') }}
      </Button>
    </template>
    <template #group="{ row: group }">
      <VxeGrid
        :columns="subGridColumns"
        :data="group.permissions"
        :tree-config="{
          trigger: 'row',
          rowField: 'name',
          childrenField: 'children',
        }"
      >
        <template #tenant="{ row: permission }">
          <Tag color="blue">
            {{ multiTenancySidesMap[permission.multiTenancySide] }}
          </Tag>
        </template>
        <template #providers="{ row: permission }">
          <template v-for="provider in permission.providers" :key="provider">
            <Tag color="blue" style="margin: 5px">
              {{ providersMap[provider] }}
            </Tag>
          </template>
        </template>
        <template #action="{ row: permission }">
          <div class="flex flex-row">
            <Button
              :icon="h(EditOutlined)"
              block
              type="link"
              v-access:code="[GroupDefinitionsPermissions.Update]"
              @click="onUpdate(permission)"
            >
              {{ $t('AbpUi.Edit') }}
            </Button>
            <Button
              v-if="!permission.isStatic"
              :icon="h(DeleteOutlined)"
              block
              danger
              type="link"
              v-access:code="[GroupDefinitionsPermissions.Delete]"
              @click="onDelete(permission)"
            >
              {{ $t('AbpUi.Delete') }}
            </Button>
          </div>
        </template>
      </VxeGrid>
    </template>
  </GroupGrid>
  <PermissionDefinitionModal @change="() => onGet()" />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/permissions/permissions/permission-definition-table.tsx
import { useCallback, useRef, useState } from "react";
import { Button, Card, Modal, Space, Table, Tag } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import type { MultiTenancySides, PermissionDefinitionDto } from "#/management/permissions/definitions";
import { type ActionType, ProTable, type ProColumns } from "@ant-design/pro-table";

import { localizationSerializer } from "@/utils/abp/localization-serializer";

import { deleteApi, getListApi as getPermissionsApi } from "@/api/management/permissions/definitions";
import { getListApi as getGroupsApi } from "@/api/management/permissions/groups";
import { GroupDefinitionsPermissions } from "@/constants/management/permissions";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import PermissionDefinitionModal from "./permission-definition-modal";
import { useLocalizer } from "@/hooks/abp/use-localization";
import { useTypesMap } from "./types";
import { listToTree } from "@/utils/tree";
import type { ExtraPropertyDictionary } from "#/abp-core";
import type { ColumnsType } from "antd/es/table";
import { toast } from "sonner";

interface PermissionVo {
	children: PermissionVo[];
	displayName: string;
	groupName: string;
	isEnabled: boolean;
	isStatic: boolean;
	multiTenancySide: MultiTenancySides;
	name: string;
	parentName?: string;
	providers: string[];
	stateCheckers: string;
	extraProperties: ExtraPropertyDictionary;
}

interface PermissionGroupVo {
	displayName: string;
	name: string;
	permissions: PermissionVo[];
}

const PermissionDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const [modal, contextHolder] = Modal.useModal();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedPermission, setSelectedPermission] = useState<PermissionDefinitionDto>();

	const [searchParams, setSearchParams] = useState<{ filter?: string }>({});

	const { Lr } = useLocalizer(
		undefined,
		useCallback(() => {
			actionRef.current?.reload();
			setModalVisible(false);
		}, []),
	);

	const { deserialize } = localizationSerializer();
	const { multiTenancySidesMap, providersMap } = useTypesMap($t);

	// 删除权限操作
	const { mutateAsync: deletePermission } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["permissions", "permissionGroups"] });
		},
	});

	// 获取权限数据
	const { data, isLoading } = useQuery({
		queryKey: ["permissions", "permissionGroups", searchParams],
		queryFn: async () => {
			const [groupRes, permissionRes] = await Promise.all([
				getGroupsApi(searchParams),
				getPermissionsApi(searchParams),
			]);

			const groups: PermissionGroupVo[] = groupRes.items.map((group) => {
				const localizableGroup = deserialize(group.displayName);
				const permissions = permissionRes.items
					.filter((permission) => permission.groupName === group.name)
					.map((permission) => {
						const localizablePermission = deserialize(permission.displayName);
						return {
							...permission,
							displayName: Lr(localizablePermission.resourceName, localizablePermission.name),
						};
					});
				return {
					...group,
					displayName: Lr(localizableGroup.resourceName, localizableGroup.name),
					permissions: listToTree<PermissionVo>(permissions, {
						id: "name",
						pid: "parentName",
					}),
				};
			});

			return groups;
		},
	});

	const handleDelete = async (permission: PermissionDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: permission.name }),
			onOk: () => deletePermission(permission.name),
		});
	};

	const mainColumns: ProColumns<PermissionGroupVo>[] = [
		{
			title: "",
			dataIndex: "index",
			valueType: "index",
			width: 50,
			render: (_, __, index) => index + 1,
		},
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true, // hide in table
		},
		{
			title: $t("AbpPermissionManagement.DisplayName:Name"),
			dataIndex: "name",
			width: 150,
			hideInSearch: true,
		},
		{
			title: $t("AbpPermissionManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 150,
			hideInSearch: true,
		},
	];

	const subColumns: ColumnsType<PermissionVo> = [
		{
			title: $t("AbpPermissionManagement.DisplayName:Name"),
			dataIndex: "name",
			width: 200,
			ellipsis: true,
		},
		{
			title: $t("AbpPermissionManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 200,
		},
		{
			align: "center",
			minWidth: 100,
			// slots: { default: 'tenant' },
			title: $t("AbpPermissionManagement.DisplayName:MultiTenancySide"),
			render: (_, record) => (
				<Space>
					<Tag color="blue">{multiTenancySidesMap[record.multiTenancySide]}</Tag>
				</Space>
			),
		},
		{
			title: $t("AbpPermissionManagement.DisplayName:Providers"),
			width: 200,
			render: (_, record) => (
				<Space>
					{record.providers.map((provider) => (
						<Tag key={provider} color="blue">
							{providersMap[provider]}
						</Tag>
					))}
				</Space>
			),
		},
		{
			title: $t("AbpUi.Actions"),
			width: 180,
			fixed: "right",
			render: (_, record) => (
				<Space>
					{hasAccessByCodes([GroupDefinitionsPermissions.Update]) && (
						<Button
							type="link"
							icon={<EditOutlined />}
							onClick={() => {
								setSelectedPermission(record);
								setModalVisible(true);
							}}
						>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{!record.isStatic && hasAccessByCodes([GroupDefinitionsPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
				</Space>
			),
		},
	];

	const expandedRowRender = (group: PermissionGroupVo) => {
		return (
			<Table<PermissionVo>
				columns={subColumns}
				dataSource={group.permissions}
				pagination={false}
				rowKey={(record) => record.name}
				indentSize={30}
				expandable={{
					defaultExpandAllRows: false,
					childrenColumnName: "children", // 指定子项字段
				}}
			/>
		);
	};

	// 工具栏
	const toolBarRender = () => [
		hasAccessByCodes([GroupDefinitionsPermissions.Create]) && (
			<Button
				type="primary"
				icon={<PlusOutlined />}
				onClick={() => {
					setSelectedPermission(undefined);
					setModalVisible(true);
				}}
			>
				{$t("AbpPermissionManagement.PermissionDefinitions:AddNew")}
			</Button>
		),
	];

	return (
		<>
			{contextHolder}

			<Card>
				<ProTable<PermissionGroupVo>
					headerTitle={$t("AbpPermissionManagement.PermissionDefinitions")}
					actionRef={actionRef}
					columns={mainColumns}
					dataSource={data}
					loading={isLoading}
					rowKey={(record) => record.name}
					expandable={{ expandedRowRender }}
					toolBarRender={toolBarRender}
					pagination={{
						showSizeChanger: true,
						total: data?.length,
					}}
					search={{
						labelWidth: "auto",
						span: 12, //search part width
						defaultCollapsed: true,
					}}
					request={async (params) => {
						const { filter } = params;
						setSearchParams({ filter: filter });
						//强制重新请求数据（用于table的刷新按钮）
						await queryClient.invalidateQueries({ queryKey: ["permissions", "permissionGroups"] });
						return { data, success: true, total: data?.length };
					}}
				/>
			</Card>
			<PermissionDefinitionModal
				visible={modalVisible}
				permission={selectedPermission}
				onClose={() => {
					setModalVisible(false);
					setSelectedPermission(undefined);
				}}
				onChange={() => {
					setModalVisible(false);
					actionRef.current?.reload();
				}}
			/>
		</>
	);
};

export default PermissionDefinitionTable;
