// apps/react-admin/src/pages/platform/menus/menu-drawer.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Drawer, Form, Input, Checkbox, Button, Steps, Card, TreeSelect, Select, InputNumber, DatePicker } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import dayjs from "dayjs";
import { createApi, updateApi, getApi } from "@/api/platform/menus";
import { getPagedListApi as getLayoutsApi, getApi as getLayoutApi } from "@/api/platform/layouts";
import { getApi as getDataDictionaryApi } from "@/api/platform/data-dictionaries";
import type { MenuDto, MenuCreateDto, MenuUpdateDto } from "#/platform/menus";
import { ValueType } from "#/platform/data-dictionaries";
import ApiSelect from "@/components/abp/adapter/api-select";
import IconPicker from "@/components/abp/adapter/icon-picker";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: MenuDto) => void;
	// Passing initial state via props instead of drawerApi.getData
	editMenu?: { id?: string; parentId?: string; layoutId?: string };
	rootMenus: MenuDto[]; // Tree data for Parent selection
}

const MenuDrawer: React.FC<Props> = ({ visible, onClose, onChange, editMenu, rootMenus }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm(); // Basic Info
	const [metaForm] = Form.useForm(); // Meta Info

	const [currentStep, setCurrentStep] = useState(0);
	const [submitting, setSubmitting] = useState(false);
	const [loading, setLoading] = useState(false);
	const [menuMetas, setMenuMetas] = useState<any[]>([]); // Dynamic fields definition

	// Watch Layout ID to load meta definitions
	const layoutId = Form.useWatch("layoutId", form);

	useEffect(() => {
		if (visible) {
			init();
		}
	}, [visible, editMenu]);

	// Load Meta definitions when Layout changes
	useEffect(() => {
		if (layoutId && visible) {
			loadMetaDefinitions(layoutId);
		} else {
			setMenuMetas([]);
		}
	}, [layoutId, visible]);

	const init = async () => {
		setCurrentStep(0);
		form.resetFields();
		metaForm.resetFields();
		setMenuMetas([]);

		// If ID exists, load data (Edit Mode)
		if (editMenu?.id) {
			setLoading(true);
			try {
				const dto = await getApi(editMenu.id);
				form.setFieldsValue(dto);
				// Meta values will be set after meta definitions are loaded via layoutId effect
				// We might need a ref or state to hold meta values temporarily
				setTimeout(() => setMetaValues(dto.meta, dto.layoutId), 500);
			} finally {
				setLoading(false);
			}
		} else {
			// Create Mode
			form.setFieldsValue({
				parentId: editMenu?.parentId,
				layoutId: editMenu?.layoutId,
			});
			// Handle path prefix based on parent
			if (editMenu?.parentId) {
				const parent = await getApi(editMenu.parentId);
				// Antd Input addonBefore logic handled in render
			}
		}
	};

	const loadMetaDefinitions = async (lId: string) => {
		try {
			setLoading(true);
			const layoutDto = await getLayoutApi(lId);
			// Auto-fill component path if creating new
			if (!editMenu?.id) {
				form.setFieldValue("component", layoutDto.path);
			}

			const dataDto = await getDataDictionaryApi(layoutDto.dataId);
			setMenuMetas(dataDto.items?.sort() || []);
		} finally {
			setLoading(false);
		}
	};

	const setMetaValues = (meta: Record<string, any>, lId: string) => {
		// This runs after definitions are loaded
		// We need to map raw values to component values (e.g. string 'true' to boolean true)
		// Since setMenuMetas is async/state based, robust implementation would map inside the render or a useEffect depending on menuMetas
		// Simplified logic here assuming definitions loaded:

		// We need a way to parse values based on type which is in menuMetas state.
		// This is tricky with async state updates.
		// For now, let's rely on the form submission to format outgoing data,
		// and try to set fields directly if possible.
		if (!meta) return;

		// Quick parse attempt based on known logic
		const parsedValues: any = { ...meta };
		// Refinement would require iterating over menuMetas to cast types (e.g. "true" -> true)
		metaForm.setFieldsValue(parsedValues);
	};

	const handleParentChange = async (val: string) => {
		if (val) {
			const parent = await getApi(val);
			// Store parent path for display/logic
		}
	};

	const onSubmit = async () => {
		try {
			setSubmitting(true);
			const basicValues = await form.validateFields();
			const metaValues = await metaForm.validateFields();

			// Format meta values to strings/etc as expected by backend DTO
			const formattedMeta: Record<string, string> = {};
			Object.keys(metaValues).forEach((key) => {
				const val = metaValues[key];
				if (val === undefined || val === null) return;

				// Simple casting logic based on value type check or metadata if available
				if (dayjs.isDayjs(val)) formattedMeta[key] = val.format("YYYY-MM-DD HH:mm:ss");
				else if (Array.isArray(val)) formattedMeta[key] = val.join(",");
				else formattedMeta[key] = String(val);
			});

			let path = basicValues.path;
			if (!path.startsWith("/")) path = `/${path}`;
			// Add parent path logic if needed

			const payload = {
				...basicValues,
				path,
				meta: formattedMeta,
			};

			let res: MenuDto;
			if (basicValues.id) {
				res = await updateApi(basicValues.id, payload as MenuUpdateDto);
			} else {
				res = await createApi(payload as MenuCreateDto);
			}

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (e) {
			console.error(e);
		} finally {
			setSubmitting(false);
		}
	};

	const renderMetaInput = (item: any) => {
		switch (item.valueType) {
			case ValueType.Boolean:
				return <Checkbox>{item.displayName}</Checkbox>;
			case ValueType.Numeic:
				return <InputNumber className="w-full" />;
			case ValueType.Date:
				return <DatePicker className="w-full" />;
			case ValueType.DateTime:
				return <DatePicker showTime className="w-full" />;
			case ValueType.Array:
				return <Select mode="tags" />;
			case ValueType.String:
				if (item.name.toLowerCase().includes("icon")) {
					return <IconPicker />;
				}
				return <Input autoComplete="off" />;
			default:
				return <Input autoComplete="off" />;
		}
	};

	const drawerTitle = editMenu?.id
		? `${$t("AppPlatform.Menu:Edit")} - ${form.getFieldValue("name") || ""}`
		: $t("AppPlatform.Menu:AddNew");

	return (
		<Drawer
			title={drawerTitle}
			width={720}
			open={visible}
			onClose={onClose}
			destroyOnClose
			maskClosable={false}
			footer={
				<div className="flex justify-end gap-2">
					{currentStep === 1 && <Button onClick={() => setCurrentStep(0)}>{$t("AppPlatform.PreStep")}</Button>}
					{currentStep === 0 && (
						<Button type="primary" onClick={() => form.validateFields().then(() => setCurrentStep(1))}>
							{$t("AppPlatform.NextStep")}
						</Button>
					)}
					{currentStep === 1 && (
						<Button type="primary" loading={submitting} onClick={onSubmit}>
							{$t("AbpUi.Submit")}
						</Button>
					)}
				</div>
			}
		>
			<Steps current={currentStep} className="mb-8 max-w-lg mx-auto">
				<Steps.Step title={$t("AppPlatform.DisplayName:Basic")} />
				<Steps.Step title={$t("AppPlatform.DisplayName:Meta")} />
			</Steps>

			{/* Basic Form */}
			<div style={{ display: currentStep === 0 ? "block" : "none" }}>
				<Form form={form} layout="vertical">
					<Form.Item name="id" hidden>
						<Input />
					</Form.Item>

					<Form.Item name="layoutId" label={$t("AppPlatform.DisplayName:Layout")} rules={[{ required: true }]}>
						<ApiSelect
							api={() => getLayoutsApi({ maxResultCount: 100 })}
							labelField="displayName"
							valueField="id"
							resultField="items"
							allowClear
						/>
					</Form.Item>

					<Form.Item name="isPublic" valuePropName="checked">
						<Checkbox>{$t("AppPlatform.DisplayName:IsPublic")}</Checkbox>
					</Form.Item>

					<Form.Item name="parentId" label={$t("AppPlatform.DisplayName:ParentMenu")}>
						<TreeSelect
							treeData={rootMenus}
							fieldNames={{ label: "displayName", value: "id", children: "children" }}
							allowClear
							treeDefaultExpandAll
							onChange={handleParentChange}
						/>
					</Form.Item>

					<Form.Item name="name" label={$t("AppPlatform.DisplayName:Name")} rules={[{ required: true }]}>
						<Input autoComplete="off" />
					</Form.Item>

					<Form.Item name="displayName" label={$t("AppPlatform.DisplayName:DisplayName")} rules={[{ required: true }]}>
						<Input autoComplete="off" />
					</Form.Item>

					<Form.Item name="path" label={$t("AppPlatform.DisplayName:Path")} rules={[{ required: true }]}>
						<Input autoComplete="off" />
					</Form.Item>

					<Form.Item name="component" label={$t("AppPlatform.DisplayName:Component")} rules={[{ required: true }]}>
						<Input autoComplete="off" />
					</Form.Item>

					<Form.Item name="redirect" label={$t("AppPlatform.DisplayName:Redirect")}>
						<Input autoComplete="off" />
					</Form.Item>

					<Form.Item name="description" label={$t("AppPlatform.DisplayName:Description")}>
						<Input.TextArea autoSize={{ minRows: 3 }} />
					</Form.Item>
				</Form>
			</div>

			{/* Meta Form */}
			<div style={{ display: currentStep === 1 ? "block" : "none" }}>
				<Form form={metaForm} layout="vertical">
					{menuMetas.map((item) => (
						<Form.Item
							key={item.name}
							name={item.name}
							label={item.displayName}
							tooltip={item.description}
							rules={item.allowBeNull ? [] : [{ required: true }]}
							valuePropName={item.valueType === ValueType.Boolean ? "checked" : "value"}
						>
							{renderMetaInput(item)}
						</Form.Item>
					))}
					{menuMetas.length === 0 && <div className="text-center text-gray-500 py-10">No Meta Fields Defined</div>}
				</Form>
			</div>
		</Drawer>
	);
};

export default MenuDrawer;

// apps/vben5/packages/@abp/platform/src/components/menus/MenuDrawer.vue
<script setup lang="ts">
import type { MenuDto } from '../../types';
import type { DataItemDto } from '../../types/dataDictionaries';
import type { MenuDrawerState } from './types';

import { ref } from 'vue';

import { useVbenDrawer, useVbenForm } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDate, formatToDateTime, isNullOrWhiteSpace } from '@abp/core';
import { Button, Card, message, Steps } from 'ant-design-vue';

import { useMenusApi } from '../../api';
import { useDataDictionariesApi } from '../../api/useDataDictionariesApi';
import { useLayoutsApi } from '../../api/useLayoutsApi';
import { ValueType } from '../../types/dataDictionaries';

const emits = defineEmits<{
  (event: 'change', data: MenuDto): void;
}>();

const Step = Steps.Step;

type TabKey = 'basic' | 'meta';
type RenderComponentContentType = (
  value: Partial<Record<string, any>>,
) => Record<string, any>;

const currentStep = ref(0);
const submiting = ref(false);
const showMetaForm = ref(false);
const parentMenu = ref<MenuDto>();
const menuMetas = ref<DataItemDto[]>([]);
const activeTabKey = ref<TabKey>('basic');

const { createApi, getApi, updateApi } = useMenusApi();
const { getApi: getLayoutApi, getPagedListApi: getLayoutsApi } =
  useLayoutsApi();
const { getApi: getDataDictionaryApi } = useDataDictionariesApi();

const [BasicForm, basicFormApi] = useVbenForm({
  commonConfig: {
    colon: true,
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onNextStep,
  schema: [
    {
      component: 'Input',
      dependencies: {
        show: false,
        triggerFields: ['name'],
      },
      fieldName: 'id',
    },
    {
      component: 'ApiSelect',
      componentProps: {
        allowClear: true,
        api: getLayoutsApi,
        labelField: 'displayName',
        onChange: onLayoutChange,
        resultField: 'items',
        valueField: 'id',
      },
      fieldName: 'layoutId',
      label: $t('AppPlatform.DisplayName:Layout'),
      rules: 'selectRequired',
    },
    {
      component: 'Checkbox',
      fieldName: 'isPublic',
      label: $t('AppPlatform.DisplayName:IsPublic'),
      renderComponentContent: () => {
        return {
          default: () => [$t('AppPlatform.DisplayName:IsPublic')],
        };
      },
    },
    {
      component: 'TreeSelect',
      componentProps: {
        allowClear: true,
        fieldNames: {
          label: 'displayName',
          value: 'id',
        },
        onChange: onParentIdChange,
      },
      fieldName: 'parentId',
      label: $t('AppPlatform.DisplayName:ParentMenu'),
    },
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('AppPlatform.DisplayName:Name'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'displayName',
      label: $t('AppPlatform.DisplayName:DisplayName'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'path',
      label: $t('AppPlatform.DisplayName:Path'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'component',
      label: $t('AppPlatform.DisplayName:Component'),
      rules: 'required',
    },
    {
      component: 'Input',
      fieldName: 'redirect',
      label: $t('AppPlatform.DisplayName:Redirect'),
    },
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 3,
        },
      },
      fieldName: 'description',
      label: $t('AppPlatform.DisplayName:Description'),
    },
  ],
  showDefaultActions: false,
  submitButtonOptions: {
    content: $t('AppPlatform.NextStep'),
  },
});
const [MetaForm, metaFormApi] = useVbenForm({
  commonConfig: {
    colon: true,
    componentProps: {
      class: 'w-full',
    },
    labelWidth: 150,
  },
  handleSubmit: onSubmit,
  resetButtonOptions: {
    content: $t('AppPlatform.PreStep'),
  },
  schema: [],
  showDefaultActions: false,
});
const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-2/3',
  onConfirm: onSubmit,
  onOpenChange: async (isOpen) => {
    if (isOpen) {
      await onInit();
    }
  },
});

function onPreStep() {
  currentStep.value = 0;
}

async function onNextStep() {
  currentStep.value = 1;
}

async function onInit() {
  metaFormApi.removeSchemaByFields(menuMetas.value.map((x) => x.name));
  const { editMenu, rootMenus } = drawerApi.getData<MenuDrawerState>();
  basicFormApi.resetForm();
  metaFormApi.resetForm();
  activeTabKey.value = 'basic';
  parentMenu.value = undefined;
  showMetaForm.value = false;
  submiting.value = false;
  menuMetas.value = [];
  currentStep.value = 0;
  onInitRootMenus(rootMenus);
  if (!isNullOrWhiteSpace(editMenu?.layoutId)) {
    await onLayoutChange(editMenu!.layoutId);
    await basicFormApi.setFieldValue('layoutId', editMenu!.layoutId);
  }
  if (isNullOrWhiteSpace(editMenu?.id)) {
    await basicFormApi.setFieldValue('parentId', editMenu!.parentId);
    await onParentIdChange(editMenu!.parentId);
    drawerApi.setState({ title: $t('AppPlatform.Menu:AddNew') });
    return;
  }
  const dto = await getApi(editMenu!.id);
  await basicFormApi.setValues(dto);
  // 编辑模式无需使用前缀
  await onParentIdChange(undefined);
  onInitMetaFormValues(dto.meta);
  drawerApi.setState({ title: `${$t('AppPlatform.Menu:Edit')} - ${dto.name}` });
}

async function onParentIdChange(menuId?: string) {
  basicFormApi.updateSchema([
    {
      componentProps: {
        addonBefore: '',
      },
      fieldName: 'path',
    },
  ]);
  if (menuId) {
    const parentMenuDto = await getApi(menuId);
    parentMenu.value = parentMenuDto;
    basicFormApi.updateSchema([
      {
        componentProps: {
          addonBefore: parentMenuDto.path,
        },
        fieldName: 'path',
      },
    ]);
  }
}

async function onLayoutChange(layoutId?: string) {
  metaFormApi.removeSchemaByFields(menuMetas.value.map((x) => x.name));
  if (!layoutId) {
    showMetaForm.value = false;
    menuMetas.value = [];
    return;
  }
  try {
    drawerApi.setState({ loading: true });
    const layoutDto = await getLayoutApi(layoutId);
    const dataDto = await getDataDictionaryApi(layoutDto.dataId);
    basicFormApi.setFieldValue('component', layoutDto.path);
    menuMetas.value = dataDto.items.sort();
    onInitMetaFormSchemas();
  } finally {
    drawerApi.setState({ loading: false });
  }
}

function onInitRootMenus(rootMenus: MenuDto[]) {
  basicFormApi.updateSchema([
    {
      fieldName: 'parentId',
      componentProps: {
        treeData: rootMenus,
      },
    },
  ]);
}

function onInitMetaFormSchemas() {
  metaFormApi.removeSchemaByFields(menuMetas.value.map((x) => x.name));
  const metaValues: Record<string, any> = {};
  menuMetas.value.forEach((dataItem) => {
    metaFormApi.setState((pre) => {
      let component = 'Input';
      let defaultValue: any | undefined;
      let componentProps: Record<string, any> | undefined;
      let renderComponentContent: RenderComponentContentType | undefined;
      switch (dataItem.valueType) {
        case ValueType.Array: {
          component = 'Select';
          componentProps = {
            mode: 'tags',
          };
          if (!isNullOrWhiteSpace(dataItem.defaultValue)) {
            defaultValue = dataItem.defaultValue.split(',');
          }
          break;
        }
        case ValueType.Boolean: {
          component = 'Checkbox';
          defaultValue = dataItem.defaultValue === 'true';
          renderComponentContent = () => {
            return {
              default: () => [dataItem.displayName],
            };
          };
          break;
        }
        case ValueType.Date:
        case ValueType.DateTime: {
          component = 'DatePicker';
          defaultValue = dataItem.defaultValue;
          componentProps = {
            showTime: dataItem.valueType === ValueType.DateTime,
            valueFormat:
              dataItem.valueType === ValueType.DateTime
                ? 'YYYY-MM-DD HH:mm:ss'
                : 'YYYY-MM-DD',
          };
          break;
        }
        case ValueType.Numeic: {
          component = 'InputNumber';
          defaultValue = dataItem.defaultValue
            ? Number(dataItem.defaultValue)
            : undefined;
          break;
        }
        case ValueType.String: {
          // 约定名称包含icon时使用IconPicker组件
          const itemNameLowerCase = dataItem.name.toLocaleLowerCase();
          if (itemNameLowerCase.includes('icon')) {
            component = 'IconPicker';
            componentProps = {
              style: {
                width: '100%',
              },
            };
          } else {
            componentProps = {
              autocomplete: 'off',
            };
          }
          defaultValue = dataItem.defaultValue;
          break;
        }
      }
      metaValues[dataItem.name] = defaultValue;
      return {
        schema: [
          ...(pre?.schema ?? []),
          {
            component,
            componentProps,
            fieldName: dataItem.name,
            help: dataItem.description,
            label: dataItem.displayName,
            renderComponentContent,
            rules: dataItem.allowBeNull ? undefined : 'required',
          },
        ],
      };
    });
  });
  metaFormApi.setValues(metaValues);
  showMetaForm.value = true;
}

function onInitMetaFormValues(meta?: Record<string, any>) {
  metaFormApi.resetForm();
  if (!meta) {
    return;
  }
  const values: Record<string, any> = {};
  menuMetas.value.forEach((dataItem) => {
    const metaValue = meta[dataItem.name];
    if (isNullOrWhiteSpace(metaValue)) {
      return;
    }
    switch (dataItem.valueType) {
      case ValueType.Array: {
        const metaValueArr = String(metaValue);
        values[dataItem.name] = metaValueArr.split(',');
        break;
      }
      case ValueType.Boolean: {
        values[dataItem.name] = String(metaValue) === 'true';
        break;
      }
      case ValueType.Date: {
        values[dataItem.name] = formatToDate(metaValue);
        break;
      }
      case ValueType.DateTime: {
        values[dataItem.name] = formatToDateTime(metaValue);
        break;
      }
      case ValueType.Numeic: {
        values[dataItem.name] = Number(metaValue);
        break;
      }
      case ValueType.String: {
        values[dataItem.name] = String(metaValue);
        break;
      }
    }
  });
  metaFormApi.setValues(values);
}

async function onSubmit() {
  try {
    submiting.value = true;
    drawerApi.setState({ loading: true });
    const basicInput = await basicFormApi.getValues();
    const metaInput = await metaFormApi.getValues();
    let combPath = String(basicInput.path);
    if (!combPath.startsWith('/')) {
      combPath = `/${combPath}`;
    }
    if (parentMenu.value && !combPath.startsWith(parentMenu.value.path)) {
      combPath = `${parentMenu.value?.path ?? ''}${combPath}`;
    }
    const api = basicInput.id
      ? updateApi(basicInput.id, {
          component: basicInput.component,
          description: basicInput.description,
          displayName: basicInput.displayName,
          isPublic: basicInput.isPublic,
          meta: metaInput,
          name: basicInput.name,
          parentId: basicInput.parentId,
          path: combPath,
          redirect: basicInput.redirect,
        })
      : createApi({
          component: basicInput.component,
          description: basicInput.description,
          displayName: basicInput.displayName,
          isPublic: basicInput.isPublic,
          layoutId: basicInput.layoutId,
          meta: metaInput,
          name: basicInput.name,
          parentId: basicInput.parentId,
          path: combPath,
          redirect: basicInput.redirect,
        });
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    drawerApi.close();
  } finally {
    submiting.value = false;
    drawerApi.setState({ loading: false });
  }
}
</script>

<template>
  <Drawer>
    <Card>
      <div class="mx-auto max-w-lg">
        <Steps :current="currentStep">
          <Step :title="$t('AppPlatform.DisplayName:Basic')" />
          <Step :title="$t('AppPlatform.DisplayName:Meta')" />
        </Steps>
      </div>
      <div class="p-20">
        <BasicForm v-show="currentStep === 0" />
        <MetaForm v-show="currentStep === 1" />
      </div>
    </Card>

    <template #footer>
      <Button v-if="currentStep === 1" @click="onPreStep">
        {{ $t('AppPlatform.PreStep') }}
      </Button>
      <Button
        v-if="currentStep === 0"
        type="primary"
        @click="basicFormApi.validateAndSubmitForm"
        :loading="submiting"
      >
        {{ $t('AppPlatform.NextStep') }}
      </Button>
      <Button
        v-if="currentStep === 1"
        type="primary"
        @click="metaFormApi.validateAndSubmitForm"
        :loading="submiting"
      >
        {{ $t('AbpUi.Submit') }}
      </Button>
    </template>
  </Drawer>
</template>

<style scoped lang="scss">
:deep(.grid-cols-1) {
  .flex-shrink-0 {
    .relative {
      button {
        width: 100%;
      }
    }
  }
}
</style>
