// apps/react-admin/src/pages/platform/menus/menu-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Space, Modal, Card } from "antd";
import { PlusOutlined, EditOutlined, DeleteOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation } from "@tanstack/react-query";
import { deleteApi, getAllApi } from "@/api/platform/menus";
import { getPagedListApi as getLayoutsApi } from "@/api/platform/layouts";
import type { MenuDto } from "#/platform/menus";
import { MenuPermissions } from "@/constants/platform/permissions";
import { withAccessChecker } from "@/utils/abp/access-checker";
import { Iconify } from "@/components/icon";

import MenuDrawer from "./menu-drawer";
import { listToTree } from "@/utils/tree";

const MenuTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();

	const [drawerVisible, setDrawerVisible] = useState(false);
	const [editMenuState, setEditMenuState] = useState<
		{ id?: string; parentId?: string; layoutId?: string } | undefined
	>();
	const [menuTree, setMenuTree] = useState<MenuDto[]>([]);

	const { mutateAsync: deleteMenu } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			actionRef.current?.reload();
		},
	});

	const handleCreate = (row?: MenuDto) => {
		setEditMenuState({
			layoutId: row?.layoutId,
			parentId: row?.id,
		});
		setDrawerVisible(true);
	};

	const handleUpdate = (row: MenuDto) => {
		setEditMenuState({ id: row.id });
		setDrawerVisible(true);
	};

	const handleDelete = (row: MenuDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: () => deleteMenu(row.id),
		});
	};

	const columns: ProColumns<MenuDto>[] = [
		{
			title: $t("AppPlatform.DisplayName:Layout"),
			dataIndex: "layoutId",
			valueType: "select",
			hideInTable: true,
			request: async ({ keyWords }) => {
				const res = await getLayoutsApi({ filter: keyWords, maxResultCount: 20 });
				return res.items.map((l) => ({ label: l.displayName, value: l.id }));
			},
			fieldProps: { showSearch: true, allowClear: true },
		},
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AppPlatform.DisplayName:Name"),
			dataIndex: "name",
			width: 250,
			render: (_, row) => (
				<Space>
					{row.meta?.icon && <Iconify icon={row.meta.icon} />}
					{row.name}
				</Space>
			),
		},
		{
			title: $t("AppPlatform.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 150,
		},
		{
			title: $t("AppPlatform.DisplayName:Description"),
			dataIndex: "description",
			ellipsis: true,
		},
		{
			title: $t("AbpUi.Actions"),
			key: "actions",
			fixed: "right",
			width: 220,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<PlusOutlined />} onClick={() => handleCreate(record)}>
							{$t("AppPlatform.Menu:AddChildren")}
						</Button>,
						[MenuPermissions.Create],
					)}
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[MenuPermissions.Update],
					)}
					{withAccessChecker(
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>,
						[MenuPermissions.Delete],
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<MenuDto>
					headerTitle={$t("AppPlatform.DisplayName:Menus")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					search={{ labelWidth: "auto" }}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={() => handleCreate()}>
								{$t("AppPlatform.Menu:AddNew")}
							</Button>,
							[MenuPermissions.Create],
						),
					]}
					request={async (params) => {
						const { layoutId, filter } = params;
						const { items } = await getAllApi({ layoutId, filter });
						const tree = listToTree(items, { id: "id", pid: "parentId" });

						setMenuTree(tree); // Save for drawer

						return {
							data: tree,
							success: true,
							total: items.length,
						};
					}}
					expandable={{ defaultExpandAllRows: true }}
					pagination={false}
				/>
			</Card>
			<MenuDrawer
				visible={drawerVisible}
				onClose={() => setDrawerVisible(false)}
				onChange={() => actionRef.current?.reload()}
				editMenu={editMenuState}
				rootMenus={menuTree}
			/>
		</>
	);
};

export default MenuTable;

// apps/vben5/packages/@abp/platform/src/components/menus/MenuTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { MenuDto } from '../../types/menus';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { IconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { listToTree, useAuthorization } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useLayoutsApi } from '../../api';
import { useMenusApi } from '../../api/useMenusApi';
import { MenuPermissions } from '../../constants/permissions';

defineOptions({
  name: 'MenuTable',
});

const { isGranted } = useAuthorization();
const { deleteApi, getAllApi } = useMenusApi();
const { getPagedListApi: getLayoutsApi } = useLayoutsApi();

const expandRowKeys = ref<string[]>([]);
const dataDictionaries = ref<MenuDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: true,
  collapsedRows: 2,
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 在label后显示一个冒号
    colon: true,
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onGet,
  schema: [
    {
      component: 'ApiSelect',
      componentProps: {
        allowClear: true,
        api: getLayoutsApi,
        labelField: 'displayName',
        resultField: 'items',
        valueField: 'id',
      },
      fieldName: 'layoutId',
      label: $t('AppPlatform.DisplayName:Layout'),
    },
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 过滤条件变更时是否提交表单
  submitOnChange: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<MenuDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 250,
      slots: { default: 'name' },
      title: $t('AppPlatform.DisplayName:Name'),
      treeNode: true,
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:DisplayName'),
    },
    {
      align: 'left',
      field: 'description',
      minWidth: 150,
      title: $t('AppPlatform.DisplayName:Description'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: isGranted(
        [
          MenuPermissions.Default,
          MenuPermissions.Create,
          MenuPermissions.Update,
          MenuPermissions.Delete,
        ],
        false,
      ),
      width: 300,
    },
  ],
  exportConfig: {},
  keepSource: true,
  rowConfig: {
    keyField: 'id',
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      queryMethod: onGet,
    },
    zoom: true,
  },
  treeConfig: {
    accordion: true,
    parentField: 'parentId',
    rowField: 'id',
    transform: false,
  },
};

const gridEvents: VxeGridListeners<MenuDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
  toggleTreeExpand(params) {
    if (params.expanded) {
      expandRowKeys.value.push(params.row.id);
    } else {
      expandRowKeys.value = expandRowKeys.value.filter(
        (key) => key !== params.row.id,
      );
    }
    onExpandChange();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [MenuDrawer, drawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(() => import('./MenuDrawer.vue')),
});

async function onGet() {
  try {
    gridApi.setLoading(true);
    const input = await gridApi.formApi.getValues();
    const { items } = await getAllApi(input);
    const treeItems = listToTree(items, {
      id: 'id',
      pid: 'parentId',
    });
    pageState.total = treeItems.length;
    dataDictionaries.value = treeItems;
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

function onExpandChange() {
  gridApi.setGridOptions({
    treeConfig: {
      expandRowKeys: expandRowKeys.value,
    },
  });
}

function onPageChange() {
  const items = dataDictionaries.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate(row?: MenuDto) {
  drawerApi.setData({
    layoutId: row?.layoutId,
    parentId: row?.id,
  });
  drawerApi.open();
}

function onUpdate(row: MenuDto) {
  drawerApi.setData(row);
  drawerApi.open();
}

function onDelete(row: MenuDto) {
  Modal.confirm({
    afterClose: () => {
      gridApi.setLoading(false);
    },
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessage')}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await deleteApi(row.id);
        message.success($t('AbpUi.DeletedSuccessfully'));
        onGet();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('AppPlatform.DisplayName:Menus')">
    <template #toolbar-tools>
      <Button
        v-if="isGranted([MenuPermissions.Create])"
        :icon="h(PlusOutlined)"
        type="primary"
        @click="onCreate()"
      >
        {{ $t('AppPlatform.Menu:AddNew') }}
      </Button>
    </template>
    <template #name="{ row }">
      <div class="flex flex-row items-center gap-2">
        <IconifyIcon v-if="row.meta.icon" :icon="row.meta.icon" />
        <span>{{ row.name }}</span>
      </div>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          v-if="isGranted([MenuPermissions.Create])"
          :icon="h(PlusOutlined)"
          block
          type="link"
          @click="onCreate(row)"
        >
          {{ $t('AppPlatform.Menu:AddChildren') }}
        </Button>
        <Button
          v-if="
            isGranted([MenuPermissions.Default, MenuPermissions.Update], false)
          "
          :icon="h(EditOutlined)"
          block
          type="link"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="isGranted([MenuPermissions.Delete])"
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
  </Grid>
  <MenuDrawer @change="onGet" />
</template>

<style scoped></style>
