// apps/vben5/packages/@abp/webhooks/src/components/subscriptions/WebhookSubscriptionModal.vue
<script setup lang="ts">
import type { TenantDto } from '@abp/saas';
import type { PropertyInfo } from '@abp/ui';
import type { FormInstance } from 'ant-design-vue';

import type {
  WebhookAvailableGroupDto,
  WebhookSubscriptionDto,
} from '../../types';

import { defineEmits, defineOptions, ref, toValue, useTemplateRef } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { isNullOrWhiteSpace } from '@abp/core';
import { useTenantsApi } from '@abp/saas';
import { PropertyTable } from '@abp/ui';
import {
  Checkbox,
  Form,
  Input,
  InputNumber,
  InputPassword,
  message,
  Select,
  Tabs,
  Textarea,
  Tooltip,
} from 'ant-design-vue';
import debounce from 'lodash.debounce';

import { useSubscriptionsApi } from '../../api/useSubscriptionsApi';

defineOptions({
  name: 'WebhookSubscriptionModal',
});
const emits = defineEmits<{
  (event: 'change', data: WebhookSubscriptionDto): void;
}>();

const FormItem = Form.Item;
const FormItemRest = Form.ItemRest;
const SelectGroup = Select.OptGroup;
const SelectOption = Select.Option;
const TabPane = Tabs.TabPane;

const defaultModel: WebhookSubscriptionDto = {
  creationTime: new Date(),
  displayName: '',
  extraProperties: {},
  id: '',
  isActive: true,
  isStatic: false,
  webhooks: [],
  webhookUri: '',
};
type TabActiveKey = 'basic' | 'headers';

const isEditModel = ref(false);
const activeTabKey = ref<TabActiveKey>('basic');
const form = useTemplateRef<FormInstance>('form');
const formModel = ref<WebhookSubscriptionDto>({ ...defaultModel });
const webhookGroups = ref<WebhookAvailableGroupDto[]>([]);
const tenants = ref<TenantDto[]>([]);

const { hasAccessByCodes } = useAccess();
const { getPagedListApi: getTenantsApi } = useTenantsApi();
const { cancel, createApi, getAllAvailableWebhooksApi, getApi, updateApi } =
  useSubscriptionsApi();

const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('WebhookSubscriptionModal has closed!');
  },
  onConfirm: async () => {
    await form.value?.validate();
    const input = toValue(formModel);
    const api = isEditModel.value
      ? updateApi(formModel.value.id, input)
      : createApi(input);
    try {
      modalApi.setState({ submitting: true });
      const res = await api;
      emits('change', res);
      message.success($t('AbpUi.SavedSuccessfully'));
      modalApi.close();
    } finally {
      modalApi.setState({ submitting: false });
    }
  },
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      isEditModel.value = false;
      activeTabKey.value = 'basic';
      formModel.value = { ...defaultModel };
      modalApi.setState({
        loading: true,
        showConfirmButton: true,
        title: $t('WebhooksManagement.Subscriptions:AddNew'),
      });
      try {
        const { id } = modalApi.getData<WebhookSubscriptionDto>();
        await onInit();
        !isNullOrWhiteSpace(id) && (await onGet(id));
      } finally {
        modalApi.setState({ loading: false });
      }
    }
  },
  title: $t('WebhooksManagement.Subscriptions:AddNew'),
});
async function onGet(id: string) {
  isEditModel.value = true;
  const dto = await getApi(id);
  formModel.value = dto;
  modalApi.setState({
    showConfirmButton: !dto.isStatic,
    title: $t('WebhooksManagement.Subscriptions:Edit'),
  });
}
async function onInit() {
  const [webhookGroupRes, tenantRes] = await Promise.all([
    getAllAvailableWebhooksApi(),
    onInitTenants(),
  ]);
  webhookGroups.value = webhookGroupRes.items;
  tenants.value = tenantRes;
}
async function onInitTenants(filter?: string) {
  if (!hasAccessByCodes(['AbpSaas.Tenants'])) {
    return [];
  }
  const { items } = await getTenantsApi({ filter });
  return items;
}
function onWebhooksFilter(onputValue: string, option: any) {
  if (option.displayname) {
    return option.displayname.includes(onputValue);
  }
  if (option.label) {
    return option.label.includes(onputValue);
  }
  return true;
}
const onTenantsSearch = debounce(async (input?: string) => {
  const tenantRes = await onInitTenants(input);
  tenants.value = tenantRes;
}, 500);
function onPropChange(prop: PropertyInfo) {
  formModel.value.headers ??= {};
  formModel.value.headers[prop.key] = prop.value;
}
function onPropDelete(prop: PropertyInfo) {
  formModel.value.headers ??= {};
  delete formModel.value.headers[prop.key];
}
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <Tabs v-model:active-key="activeTabKey">
        <TabPane key="basic" :tab="$t('WebhooksManagement.BasicInfo')">
          <FormItem
            name="isActive"
            :label="$t('WebhooksManagement.DisplayName:IsActive')"
            :extra="$t('WebhooksManagement.Description:IsActive')"
          >
            <Checkbox
              :disabled="formModel.isStatic"
              v-model:checked="formModel.isActive"
            >
              {{ $t('WebhooksManagement.DisplayName:IsActive') }}
            </Checkbox>
          </FormItem>
          <FormItem
            :label="$t('WebhooksManagement.DisplayName:WebhookUri')"
            :extra="$t('WebhooksManagement.Description:WebhookUri')"
            name="webhookUri"
            required
          >
            <Input
              v-model:value="formModel.webhookUri"
              :disabled="formModel.isStatic"
              autocomplete="off"
              allow-clear
            />
          </FormItem>
          <FormItem
            name="webhooks"
            :label="$t('WebhooksManagement.DisplayName:Webhooks')"
            :extra="$t('WebhooksManagement.Description:Webhooks')"
          >
            <Select
              :disabled="formModel.isStatic"
              allow-clear
              mode="multiple"
              v-model:value="formModel.webhooks"
              :filter-option="onWebhooksFilter"
            >
              <SelectGroup
                v-for="group in webhookGroups"
                :key="group.name"
                :label="group.displayName"
              >
                <SelectOption
                  v-for="option in group.webhooks"
                  :key="option.name"
                  :value="option.name"
                  :displayname="option.displayName"
                >
                  <Tooltip placement="right">
                    <template #title>
                      {{ option.description }}
                    </template>
                    {{ option.displayName }}
                  </Tooltip>
                </SelectOption>
              </SelectGroup>
            </Select>
          </FormItem>
          <FormItem
            v-if="hasAccessByCodes(['AbpSaas.Tenants'])"
            :label="$t('WebhooksManagement.DisplayName:TenantId')"
            :extra="$t('WebhooksManagement.Description:TenantId')"
            name="tenantId"
          >
            <Select
              v-model:value="formModel.tenantId"
              :disabled="formModel.isStatic"
              :options="tenants"
              :field-names="{ label: 'normalizedName', value: 'id' }"
              :filter-option="false"
              @search="onTenantsSearch"
              show-search
              allow-clear
            />
          </FormItem>
          <FormItem
            :label="$t('WebhooksManagement.DisplayName:TimeoutDuration')"
            :extra="$t('WebhooksManagement.Description:TimeoutDuration')"
            name="timeoutDuration"
          >
            <InputNumber
              class="w-full"
              v-model:value="formModel.timeoutDuration"
              :disabled="formModel.isStatic"
              :min="10"
              :max="300"
              autocomplete="off"
            />
          </FormItem>
          <FormItem
            :label="$t('WebhooksManagement.DisplayName:Secret')"
            :extra="$t('WebhooksManagement.Description:Secret')"
            name="secret"
          >
            <InputPassword
              v-model:value="formModel.secret"
              :disabled="formModel.isStatic"
              autocomplete="off"
              allow-clear
            />
          </FormItem>
          <FormItem
            :label="$t('WebhooksManagement.DisplayName:Description')"
            name="description"
          >
            <Textarea
              v-model:value="formModel.description"
              :disabled="formModel.isStatic"
              :auto-size="{ minRows: 3 }"
              autocomplete="off"
              allow-clear
            />
          </FormItem>
        </TabPane>
        <TabPane
          key="headers"
          :tab="$t('WebhooksManagement.DisplayName:Headers')"
        >
          <FormItemRest>
            <PropertyTable
              :data="formModel.headers"
              :disabled="formModel.isStatic"
              @change="onPropChange"
              @delete="onPropDelete"
            />
          </FormItemRest>
        </TabPane>
      </Tabs>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/webhooks/subscriptions/webhook-subscription-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, Checkbox, Select, Tabs, Tooltip } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { useMutation } from "@tanstack/react-query";
import { createApi, updateApi, getApi, getAllAvailableWebhooksApi } from "@/api/webhooks/subscriptions";
import { getPagedListApi as getTenantsApi } from "@/api/saas/tenants";
import type { WebhookSubscriptionDto, WebhookAvailableGroupDto } from "#/webhooks/subscriptions";
import type { TenantDto } from "#/saas/tenants";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import type { PropertyInfo } from "@/components/abp/properties/types";
import PropertyTable from "@/components/abp/properties/property-table";
import debounce from "lodash.debounce";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: WebhookSubscriptionDto) => void;
	subscriptionId?: string;
}

// 1. Define a local type that includes the missing property
interface LocalWebhookSubscriptionDto extends WebhookSubscriptionDto {
	isStatic?: boolean;
}

// 2. Use the local type for the default model
const defaultModel: LocalWebhookSubscriptionDto = {
	creationTime: new Date(),
	displayName: "",
	extraProperties: {},
	headers: {},
	id: "",
	isActive: true,
	isStatic: false,
	webhooks: [],
	webhookUri: "",
} as LocalWebhookSubscriptionDto;

const WebhookSubscriptionModal: React.FC<Props> = ({ visible, onClose, onChange, subscriptionId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	const [activeTab, setActiveTab] = useState("basic");
	// 3. State uses the local type
	const [formModel, setFormModel] = useState<LocalWebhookSubscriptionDto>({ ...defaultModel });
	const [loading, setLoading] = useState(false);
	const [isEditModel, setIsEditModel] = useState(false);

	const [webhookGroups, setWebhookGroups] = useState<WebhookAvailableGroupDto[]>([]);
	const [tenants, setTenants] = useState<TenantDto[]>([]);

	useEffect(() => {
		if (visible) {
			setActiveTab("basic");
			form.resetFields();
			initData();

			if (subscriptionId) {
				fetchSubscription(subscriptionId);
				setIsEditModel(true);
			} else {
				setFormModel({ ...defaultModel });
				setIsEditModel(false);
			}
		}
	}, [visible, subscriptionId]);

	const initData = async () => {
		try {
			const [groupRes, tenantRes] = await Promise.all([getAllAvailableWebhooksApi(), fetchTenants()]);
			setWebhookGroups(groupRes.items);
			setTenants(tenantRes);
		} catch (error) {
			console.error(error);
		}
	};

	const fetchTenants = async (filter?: string) => {
		if (!hasAccessByCodes(["AbpSaas.Tenants"])) {
			return [];
		}
		const { items } = await getTenantsApi({ filter, maxResultCount: 50 });
		return items;
	};

	const fetchSubscription = async (id: string) => {
		try {
			setLoading(true);
			const dto = await getApi(id);
			// 4. Cast the API response to the local type
			setFormModel(dto as LocalWebhookSubscriptionDto);
			form.setFieldsValue(dto);
		} finally {
			setLoading(false);
		}
	};

	const { mutateAsync: createSub, isPending: isCreating } = useMutation({
		mutationFn: createApi,
		onSuccess: (res) => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		},
	});

	const { mutateAsync: updateSub, isPending: isUpdating } = useMutation({
		mutationFn: (data: WebhookSubscriptionDto) => updateApi(data.id, data),
		onSuccess: (res) => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		},
	});

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			const submitData = {
				...formModel,
				...values,
			};

			if (isEditModel) {
				await updateSub(submitData);
			} else {
				await createSub(submitData);
			}
		} catch (error) {
			console.error(error);
		}
	};

	const handleTenantsSearch = debounce(async (input: string) => {
		const res = await fetchTenants(input);
		setTenants(res);
	}, 500);

	const handlePropChange = (prop: PropertyInfo) => {
		setFormModel((prev) => ({
			...prev,
			headers: {
				...prev.headers,
				[prop.key]: prop.value,
			},
		}));
	};

	const handlePropDelete = (prop: PropertyInfo) => {
		setFormModel((prev) => {
			const next = { ...prev.headers };
			delete next[prop.key];
			return { ...prev, headers: next };
		});
	};

	const modalTitle = isEditModel
		? $t("WebhooksManagement.Subscriptions:Edit")
		: $t("WebhooksManagement.Subscriptions:AddNew");

	return (
		<Modal
			title={modalTitle}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={isCreating || isUpdating || loading}
			// 5. Use the property safely
			okButtonProps={{ disabled: formModel.isStatic }}
			width={800}
			destroyOnClose
		>
			<Form form={form} layout="vertical" labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
				<Tabs activeKey={activeTab} onChange={setActiveTab}>
					<Tabs.TabPane key="basic" tab={$t("WebhooksManagement.BasicInfo")}>
						<Form.Item
							name="isActive"
							valuePropName="checked"
							label={$t("WebhooksManagement.DisplayName:IsActive")}
							extra={$t("WebhooksManagement.Description:IsActive")}
						>
							<Checkbox disabled={formModel.isStatic}>{$t("WebhooksManagement.DisplayName:IsActive")}</Checkbox>
						</Form.Item>

						<Form.Item
							name="webhookUri"
							label={$t("WebhooksManagement.DisplayName:WebhookUri")}
							extra={$t("WebhooksManagement.Description:WebhookUri")}
							rules={[{ required: true }]}
						>
							<Input disabled={formModel.isStatic} autoComplete="off" allowClear />
						</Form.Item>

						<Form.Item
							name="webhooks"
							label={$t("WebhooksManagement.DisplayName:Webhooks")}
							extra={$t("WebhooksManagement.Description:Webhooks")}
						>
							<Select
								disabled={formModel.isStatic}
								allowClear
								mode="multiple"
								options={webhookGroups.map((group) => ({
									label: group.displayName,
									options: group.webhooks.map((wh) => ({
										label: (
											<Tooltip title={wh.description} placement="right">
												{wh.displayName}
											</Tooltip>
										),
										value: wh.name,
									})),
								}))}
							/>
						</Form.Item>

						{hasAccessByCodes(["AbpSaas.Tenants"]) && (
							<Form.Item
								name="tenantId"
								label={$t("WebhooksManagement.DisplayName:TenantId")}
								extra={$t("WebhooksManagement.Description:TenantId")}
							>
								<Select
									disabled={formModel.isStatic}
									allowClear
									showSearch
									onSearch={handleTenantsSearch}
									filterOption={false}
									options={tenants.map((t) => ({ label: t.name, value: t.id }))}
								/>
							</Form.Item>
						)}

						<Form.Item
							name="secret"
							label={$t("WebhooksManagement.DisplayName:Secret")}
							extra={$t("WebhooksManagement.Description:Secret")}
						>
							<Input.Password disabled={formModel.isStatic} autoComplete="off" allowClear />
						</Form.Item>

						<Form.Item name="description" label={$t("WebhooksManagement.DisplayName:Description")}>
							<Input.TextArea disabled={formModel.isStatic} autoSize={{ minRows: 3 }} allowClear />
						</Form.Item>
					</Tabs.TabPane>

					<Tabs.TabPane key="headers" tab={$t("WebhooksManagement.DisplayName:Headers")}>
						<PropertyTable
							data={formModel.headers}
							disabled={formModel.isStatic}
							onChange={handlePropChange}
							onDelete={handlePropDelete}
						/>
					</Tabs.TabPane>
				</Tabs>
			</Form>
		</Modal>
	);
};

export default WebhookSubscriptionModal;
