// apps/vben5/packages/@abp/saas/src/components/tenants/TenantTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { TenantDto } from '../../types/tenants';

import { defineAsyncComponent, h, reactive } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { AuditLogPermissions, EntityChangeDrawer } from '@abp/auditing';
import { useFeatures } from '@abp/core';
import { FeatureModal } from '@abp/features';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useTenantsApi } from '../../api/useTenantsApi';
import { TenantsPermissions } from '../../constants/permissions';

defineOptions({
  name: 'EditionTable',
});

const MenuItem = Menu.Item;
const CheckIcon = createIconifyIcon('ant-design:check-outlined');
const CloseIcon = createIconifyIcon('ant-design:close-outlined');
const AuditLogIcon = createIconifyIcon('fluent-mdl2:compliance-audit');
const ConnectionIcon = createIconifyIcon('mdi:connection');
const FeatureIcon = createIconifyIcon('pajamas:feature-flag');

const { isEnabled } = useFeatures();
const { hasAccessByCodes } = useAccess();
const { cancel, deleteApi, getPagedListApi } = useTenantsApi();

const dataBaseOptions = reactive([
  { label: 'MySql', value: 'MySql' },
  { label: 'Oracle', value: 'Oracle' },
  { label: 'Postgres', value: 'Postgres' },
  { label: 'Sqlite', value: 'Sqlite' },
  { label: 'SqlServer', value: 'SqlServer' },
]);

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  schema: [
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
        autocomplete: 'off',
      },
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<TenantDto> = {
  columns: [
    {
      align: 'center',
      field: 'isActive',
      slots: { default: 'isActive' },
      sortable: true,
      title: $t('AbpSaas.DisplayName:IsActive'),
      width: 120,
    },
    {
      align: 'left',
      field: 'name',
      sortable: true,
      title: $t('AbpSaas.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'editionName',
      title: $t('AbpSaas.DisplayName:EditionName'),
      width: 160,
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: hasAccessByCodes([
        TenantsPermissions.Update,
        TenantsPermissions.Delete,
      ]),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        return await getPagedListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<TenantDto> = {
  cellClick: () => {},
  sortChange: () => {
    gridApi.query();
  },
};
const [TenantModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./TenantModal.vue')),
});
const [TenantConnectionStringsModal, connectionStringsModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./ConnectionStringsModal.vue'),
  ),
});
const [TenantChangeDrawer, entityChangeDrawerApi] = useVbenDrawer({
  connectedComponent: EntityChangeDrawer,
});
const [TenantFeatureModal, tenantFeatureModalApi] = useVbenModal({
  connectedComponent: FeatureModal,
});
const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const onCreate = () => {
  modalApi.setData({});
  modalApi.open();
};

const onUpdate = (row: TenantDto) => {
  modalApi.setData(row);
  modalApi.open();
};

const onDelete = (row: TenantDto) => {
  Modal.confirm({
    centered: true,
    content: $t('AbpSaas.TenantDeletionConfirmationMessage', [row.name]),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      await gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
};

const onMenuClick = (row: TenantDto, info: MenuInfo) => {
  switch (info.key) {
    case 'connection-strings': {
      connectionStringsModalApi.setData(row);
      connectionStringsModalApi.open();
      break;
    }
    case 'entity-changes': {
      entityChangeDrawerApi.setData({
        entityId: row.id,
        entityTypeFullName: 'LINGYUN.Abp.Saas.Tenant',
        subject: row.name,
      });
      entityChangeDrawerApi.open();
      break;
    }
    case 'features': {
      tenantFeatureModalApi.setData({
        displayName: row.name,
        providerKey: row.id,
        providerName: 'T',
      });
      tenantFeatureModalApi.open();
    }
  }
};
</script>

<template>
  <Grid :table-title="$t('AbpSaas.Tenants')">
    <template #toolbar-tools>
      <Button
        type="primary"
        v-access:code="[TenantsPermissions.Create]"
        @click="onCreate"
        :icon="h(PlusOutlined)"
      >
        {{ $t('AbpSaas.NewTenant') }}
      </Button>
    </template>
    <template #isActive="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.isActive" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[TenantsPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[TenantsPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="
                  hasAccessByCodes([TenantsPermissions.ManageConnectionStrings])
                "
                key="connection-strings"
                :icon="h(ConnectionIcon)"
              >
                {{ $t('AbpSaas.ConnectionStrings') }}
              </MenuItem>
              <MenuItem
                v-if="hasAccessByCodes([TenantsPermissions.ManageFeatures])"
                key="features"
                :icon="h(FeatureIcon)"
              >
                {{ $t('AbpSaas.ManageFeatures') }}
              </MenuItem>
              <MenuItem
                v-if="
                  isEnabled('AbpAuditing.Logging.AuditLog') &&
                  hasAccessByCodes([AuditLogPermissions.Default])
                "
                key="entity-changes"
                :icon="h(AuditLogIcon)"
              >
                {{ $t('AbpAuditLogging.EntitiesChanged') }}
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <TenantModal
    :data-base-options="dataBaseOptions"
    @change="() => gridApi.query()"
  />
  <TenantConnectionStringsModal :data-base-options="dataBaseOptions" />
  <TenantFeatureModal />
  <TenantChangeDrawer />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/saas/tenants/tenant-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space } from "antd";
import {
	EditOutlined,
	DeleteOutlined,
	PlusOutlined,
	EllipsisOutlined,
	CheckOutlined,
	CloseOutlined,
} from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getPagedListApi } from "@/api/saas/tenants";
import type { TenantDto } from "#/saas/tenants";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { TenantsPermissions } from "@/constants/saas/permissions"; // Adjust paths
import { Iconify } from "@/components/icon";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";

import TenantModal from "./tenant-modal";
import TenantConnectionStringsModal from "./tenant-connection-strings-modal";
import FeatureModal from "@/components/abp/features/feature-modal";
import { useFeatures } from "@/hooks/abp/fake-hooks/use-abp-feature";
import { AuditLogPermissions } from "@/constants/management/auditing";
import { EntityChangeDrawer } from "@/components/abp/auditing/entity-change-drawer";

const TenantTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const featureChecker = useFeatures();

	const [modal, contextHolder] = Modal.useModal();
	// Modal/Drawer States
	const [tenantModalVisible, setTenantModalVisible] = useState(false);
	const [connStrModalVisible, setConnStrModalVisible] = useState(false);
	const [featureModalVisible, setFeatureModalVisible] = useState(false);
	const [entityChangeVisible, setEntityChangeVisible] = useState(false);

	const [selectedTenantId, setSelectedTenantId] = useState<string | undefined>();
	const [selectedTenant, setSelectedTenant] = useState<TenantDto | undefined>();

	// Data Base Options (Reactive constant from Vue example)
	const dataBaseOptions = [
		{ label: "MySql", value: "MySql" },
		{ label: "Oracle", value: "Oracle" },
		{ label: "Postgres", value: "Postgres" },
		{ label: "Sqlite", value: "Sqlite" },
		{ label: "SqlServer", value: "SqlServer" },
	];

	const { mutateAsync: deleteTenant } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			actionRef.current?.reload();
		},
	});

	const handleCreate = () => {
		setSelectedTenantId(undefined);
		setTenantModalVisible(true);
	};

	const handleUpdate = (row: TenantDto) => {
		setSelectedTenantId(row.id);
		setTenantModalVisible(true);
	};

	const handleDelete = (row: TenantDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpSaas.TenantDeletionConfirmationMessage", { 0: row.name }),
			onOk: async () => {
				await deleteTenant(row.id);
			},
		});
	};

	const handleMenuClick = (key: string, row: TenantDto) => {
		setSelectedTenant(row);
		if (key === "connection-strings") {
			setConnStrModalVisible(true);
		} else if (key === "features") {
			setFeatureModalVisible(true);
		} else if (key === "entity-changes") {
			setEntityChangeVisible(true);
		}
	};

	const columns: ProColumns<TenantDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpSaas.DisplayName:IsActive"),
			dataIndex: "isActive",
			align: "center",
			width: 120,
			render: (val) =>
				val ? <CheckOutlined className="text-green-500" /> : <CloseOutlined className="text-red-500" />,
			hideInSearch: true,
		},
		{
			title: $t("AbpSaas.DisplayName:Name"),
			dataIndex: "name",
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("AbpSaas.DisplayName:EditionName"),
			dataIndex: "editionName",
			width: 160,
			hideInSearch: true,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 220,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[TenantsPermissions.Update],
					)}
					{withAccessChecker(
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>,
						[TenantsPermissions.Delete],
					)}
					<Dropdown
						menu={{
							items: [
								hasAccessByCodes([TenantsPermissions.ManageConnectionStrings])
									? {
											key: "connection-strings",
											label: $t("AbpSaas.ConnectionStrings"),
											icon: <Iconify icon="mdi:connection" />,
										}
									: null,
								hasAccessByCodes([TenantsPermissions.ManageFeatures])
									? {
											key: "features",
											label: $t("AbpSaas.ManageFeatures"),
											icon: <Iconify icon="pajamas:feature-flag" />,
										}
									: null,
								featureChecker.isEnabled("AbpAuditing.Logging.AuditLog") &&
								hasAccessByCodes([AuditLogPermissions.Default])
									? {
											key: "entity-changes",
											label: $t("AbpAuditLogging.EntitiesChanged"),
											icon: <Iconify icon="fluent-mdl2:compliance-audit" />,
										}
									: null,
							].filter(Boolean) as any,
							onClick: ({ key }) => handleMenuClick(key, record),
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<TenantDto>
					headerTitle={$t("AbpSaas.Tenants")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					search={{ labelWidth: "auto" }}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("AbpSaas.NewTenant")}
							</Button>,
							[TenantsPermissions.Create],
						),
					]}
					request={async (params, sorter) => {
						const { current, pageSize, ...filters } = params;
						const sorting =
							sorter && Object.keys(sorter).length > 0
								? Object.keys(sorter)
										.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
										.join(", ")
								: undefined;

						const query = await queryClient.fetchQuery({
							queryKey: ["tenants", params, sorter],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									sorting: sorting,
									filter: filters.filter,
								}),
						});

						return {
							data: query.items,
							total: query.totalCount,
							success: true,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<TenantModal
				visible={tenantModalVisible}
				tenantId={selectedTenantId}
				dataBaseOptions={dataBaseOptions}
				onClose={() => setTenantModalVisible(false)}
				onChange={() => actionRef.current?.reload()}
			/>

			<TenantConnectionStringsModal
				visible={connStrModalVisible}
				tenant={selectedTenant}
				dataBaseOptions={dataBaseOptions}
				onClose={() => setConnStrModalVisible(false)}
			/>

			{selectedTenant && (
				<>
					<FeatureModal
						visible={featureModalVisible}
						providerName="T"
						providerKey={selectedTenant.id}
						displayName={selectedTenant.name}
						onClose={() => setFeatureModalVisible(false)}
					/>
					<EntityChangeDrawer
						open={entityChangeVisible}
						input={{ entityId: selectedTenant.id, entityTypeFullName: "LINGYUN.Abp.Saas.Tenant" }}
						subject={selectedTenant.name}
						onClose={() => setEntityChangeVisible(false)}
					/>
				</>
			)}
		</>
	);
};

export default TenantTable;
