// apps/vben5/packages/@abp/platform/src/components/menus/MenuAllotModal.vue
<script setup lang="ts">
import type { MenuSubject } from './types';

import { ref } from 'vue';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { listToTree } from '@abp/core';
import { message } from 'ant-design-vue';

import {
  useDataDictionariesApi,
  useMenusApi,
  useRoleMenusApi,
  useUserMenusApi,
} from '../../api';

interface ModalState {
  identity: string;
}

defineOptions({
  name: 'MenuAllotModal',
});

const props = defineProps<{
  subject: MenuSubject;
}>();

const checkedMenuIds = ref<string[]>([]);

const { getAllApi: getAllMenusApi } = useMenusApi();
const { getAllApi: getUserMenusApi, setMenusApi: setUserMenusApi } =
  useUserMenusApi();
const { getAllApi: getRoleMenusApi, setMenusApi: setRoleMenusApi } =
  useRoleMenusApi();
const { getByNameApi: getDataDictionaryByNameApi } = useDataDictionariesApi();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'ApiSelect',
      componentProps: {
        allowClear: true,
        api: () => getDataDictionaryByNameApi('UI Framework'),
        labelField: 'displayName',
        onChange: onInitMenus,
        resultField: 'items',
        valueField: 'name',
      },
      dependencies: {
        if: (values) => {
          return !values?.id;
        },
        triggerFields: ['id'],
      },
      fieldName: 'framework',
      label: $t('AppPlatform.DisplayName:UIFramework'),
      rules: 'selectRequired',
    },
    {
      component: 'TreeSelect',
      componentProps: {
        allowClear: true,
        blockNode: true,
        fieldNames: {
          label: 'displayName',
          value: 'id',
        },
      },
      dependencies: {
        if(values) {
          return !!values.framework;
        },
        triggerFields: ['framework'],
      },
      fieldName: 'startupMenuId',
      label: $t('AppPlatform.Menu:SetStartup'),
    },
    {
      component: 'Tree',
      componentProps: {
        allowClear: true,
        blockNode: true,
        checkable: true,
        checkStrictly: true,
        fieldNames: {
          key: 'id',
          title: 'displayName',
        },
        onCheck: onMenuChecked,
      },
      dependencies: {
        if(values) {
          return !!values.framework;
        },
        triggerFields: ['framework'],
      },
      fieldName: 'menuIds',
      label: $t('AppPlatform.DisplayName:Menus'),
      modelPropName: 'checkedKeys',
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
});

function onMenuChecked(checkedKeys: { checked: string[] }) {
  checkedMenuIds.value = checkedKeys.checked;
}

async function onInitMenus(framework?: string) {
  if (!framework) {
    formApi.updateSchema([
      {
        componentProps: {
          treeData: [],
        },
        fieldName: 'menuIds',
      },
      {
        componentProps: {
          treeData: [],
        },
        fieldName: 'startupMenuId',
      },
    ]);
    formApi.setFieldValue('menuIds', []);
    return;
  }
  const state = modalApi.getData<ModalState>();
  const api =
    props.subject === 'user'
      ? getUserMenusApi({
          framework,
          userId: state.identity,
        })
      : getRoleMenusApi({
          framework,
          role: state.identity,
        });
  const [allMenus, identityMenus] = await Promise.all([
    getAllMenusApi({
      framework,
    }),
    api,
  ]);
  const treeData = listToTree(allMenus.items, {
    id: 'id',
    pid: 'parentId',
  });
  formApi.updateSchema([
    {
      componentProps: {
        treeData,
      },
      fieldName: 'menuIds',
    },
    {
      componentProps: {
        treeData,
      },
      fieldName: 'startupMenuId',
    },
  ]);
  checkedMenuIds.value = identityMenus.items.map((item) => item.id);
  formApi.setFieldValue('menuIds', checkedMenuIds.value);
  const startupMenu = identityMenus.items.find((item) => item.startup);
  formApi.setFieldValue('startupMenuId', startupMenu?.id);
}

async function onSubmit(values: Record<string, any>) {
  try {
    modalApi.setState({ submitting: true });
    const state = modalApi.getData<ModalState>();
    const api =
      props.subject === 'user'
        ? setUserMenusApi({
            framework: values.framework,
            menuIds: checkedMenuIds.value,
            startupMenuId: values.startupMenuId,
            userId: state.identity,
          })
        : setRoleMenusApi({
            framework: values.framework,
            menuIds: checkedMenuIds.value,
            roleName: state.identity,
            startupMenuId: values.startupMenuId,
          });
    await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="$t('AppPlatform.Menu:Manage')">
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/platform/menus/menu-allot-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Tree, TreeSelect } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { getAllApi as getAllMenusApi } from "@/api/platform/menus";
import { getAllApi as getUserMenusApi, setMenusApi as setUserMenusApi } from "@/api/platform/user-menus";
import { getAllApi as getRoleMenusApi, setMenusApi as setRoleMenusApi } from "@/api/platform/role-menus";
import { getByNameApi as getDataDictionaryByNameApi } from "@/api/platform/data-dictionaries";
import type { MenuSubject } from "./types";
import { listToTree } from "@/utils/tree";
import ApiSelect from "@/components/abp/adapter/api-select";

interface Props {
	visible: boolean;
	onClose: () => void;
	subject: MenuSubject;
	identity: string; // userId or roleName
}

const MenuAllotModal: React.FC<Props> = ({ visible, onClose, subject, identity }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);
	const [treeData, setTreeData] = useState<any[]>([]);
	const [checkedKeys, setCheckedKeys] = useState<React.Key[]>([]);

	// Watch framework to trigger tree data reload
	const framework = Form.useWatch("framework", form);

	useEffect(() => {
		if (visible) {
			form.resetFields();
			setTreeData([]);
			setCheckedKeys([]);
		}
	}, [visible, identity]);

	useEffect(() => {
		if (visible && framework && identity) {
			loadMenus(framework);
		}
	}, [framework, identity, visible]);

	const loadMenus = async (fw: string) => {
		try {
			// Fetch all menus for the framework to build the tree structure
			const allMenusRes = await getAllMenusApi({ framework: fw });
			const tree = listToTree(allMenusRes.items, { id: "id", pid: "parentId" });
			setTreeData(tree);

			// Fetch currently assigned menus for the user/role
			const assignedRes =
				subject === "user"
					? await getUserMenusApi({ framework: fw, userId: identity })
					: await getRoleMenusApi({ framework: fw, role: identity });

			const assignedIds = assignedRes.items.map((item) => item.id);
			setCheckedKeys(assignedIds);

			// Set startup menu
			const startupMenu = assignedRes.items.find((item) => item.startup);
			if (startupMenu) {
				form.setFieldValue("startupMenuId", startupMenu.id);
			}
		} catch (error) {
			console.error(error);
		}
	};

	const handleCheck = (checked: React.Key[] | { checked: React.Key[]; halfChecked: React.Key[] }) => {
		// AntD Tree checkStrictly returns object, normally array
		if (Array.isArray(checked)) {
			setCheckedKeys(checked);
		} else {
			setCheckedKeys(checked.checked);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const payload = {
				framework: values.framework,
				menuIds: checkedKeys as string[],
				startupMenuId: values.startupMenuId,
			};

			if (subject === "user") {
				await setUserMenusApi({ ...payload, userId: identity });
			} else {
				await setRoleMenusApi({ ...payload, roleName: identity });
			}

			toast.success($t("AbpUi.SavedSuccessfully"));
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	// Helper for ApiSelect
	const uiFrameworkApi = () => getDataDictionaryByNameApi("UI Framework");

	return (
		<Modal
			title={$t("AppPlatform.Menu:Manage")}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			destroyOnClose
			width={600}
		>
			<Form form={form} layout="vertical">
				<Form.Item
					name="framework"
					label={$t("AppPlatform.DisplayName:UIFramework")}
					rules={[{ required: true, message: $t("AbpUi.ThisFieldIsRequired") }]}
				>
					<ApiSelect api={uiFrameworkApi} resultField="items" labelField="displayName" valueField="name" allowClear />
				</Form.Item>

				{framework && (
					<>
						<Form.Item name="startupMenuId" label={$t("AppPlatform.Menu:SetStartup")}>
							<TreeSelect
								treeData={treeData}
								fieldNames={{ label: "displayName", value: "id", children: "children" }}
								allowClear
								treeDefaultExpandAll
								placeholder={$t("ui.placeholder.select")}
							/>
						</Form.Item>

						<Form.Item label={$t("AppPlatform.DisplayName:Menus")} required>
							<div className="border rounded p-2 max-h-[400px] overflow-auto">
								<Tree
									checkable
									checkStrictly
									treeData={treeData}
									fieldNames={{ title: "displayName", key: "id", children: "children" }}
									checkedKeys={checkedKeys}
									onCheck={handleCheck}
									defaultExpandAll
								/>
							</div>
						</Form.Item>
					</>
				)}
			</Form>
		</Modal>
	);
};

export default MenuAllotModal;
