// apps/vben5/packages/@abp/identity/src/components/organization-units/OrganizationUnitRoleTable.vue
<script setup lang="ts">
import type { IdentityRoleDto } from '../../types/roles';

import { computed, defineAsyncComponent, h, nextTick, watch } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  useVbenVxeGrid,
  type VxeGridListeners,
  type VxeGridProps,
} from '@abp/ui';
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, Modal } from 'ant-design-vue';

import { addRoles, getRoleListApi } from '../../api/organization-units';
import { removeOrganizationUnitApi } from '../../api/roles';
import { OrganizationUnitPermissions } from '../../constants/permissions';

defineOptions({
  name: 'OrganizationUnitRoleTable',
});

const props = defineProps<{
  selectedKey?: string;
}>();

const SelectRoleModal = defineAsyncComponent(
  () => import('./SelectRoleModal.vue'),
);

const { hasAccessByCodes } = useAccess();

const getAddRoleEnabled = computed(() => {
  return (
    props.selectedKey &&
    hasAccessByCodes([OrganizationUnitPermissions.ManageRoles])
  );
});

const gridOptions: VxeGridProps<IdentityRoleDto> = {
  columns: [
    {
      field: 'name',
      minWidth: '100px',
      title: $t('AbpIdentity.DisplayName:RoleName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'actions' },
      title: $t('AbpUi.Actions'),
      width: 180,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        if (!props.selectedKey) {
          return {
            totalCount: 0,
            items: [],
          };
        }
        return await getRoleListApi(props.selectedKey!, {
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<IdentityRoleDto> = {
  cellClick: () => {},
};
const [Grid, { query, setLoading }] = useVbenVxeGrid({
  gridEvents,
  gridOptions,
});

const [RoleModal, roleModalApi] = useVbenModal({
  connectedComponent: SelectRoleModal,
});

const onRefresh = () => {
  nextTick(query);
};

const onDelete = (row: IdentityRoleDto) => {
  Modal.confirm({
    centered: true,
    content: $t('AbpIdentity.OrganizationUnit:AreYouSureRemoveRole', [
      row.name,
    ]),
    onOk: () => {
      setLoading(true);
      return removeOrganizationUnitApi(row.id, props.selectedKey!)
        .then(onRefresh)
        .finally(() => setLoading(false));
    },
    title: $t('AbpUi.AreYouSure'),
  });
};

const onShowRole = () => {
  roleModalApi.setData({
    id: props.selectedKey,
  });
  roleModalApi.open();
};

const onCreateRole = (roles: IdentityRoleDto[]) => {
  roleModalApi.setState({
    closable: false,
    confirmLoading: true,
  });
  addRoles(props.selectedKey!, {
    roleIds: roles.map((item) => item.id),
  })
    .then(() => {
      roleModalApi.close();
      query();
    })
    .finally(() => {
      roleModalApi.setState({
        closable: true,
        confirmLoading: false,
      });
    });
};
watch(() => props.selectedKey, onRefresh);
</script>

<template>
  <Grid :table-title="$t('AbpIdentity.Roles')">
    <template #toolbar-tools>
      <Button
        v-if="getAddRoleEnabled"
        :icon="h(PlusOutlined)"
        type="primary"
        @click="onShowRole"
      >
        {{ $t('AbpIdentity.OrganizationUnit:AddRole') }}
      </Button>
    </template>
    <template #actions="{ row }">
      <Button
        :icon="h(DeleteOutlined)"
        danger
        type="link"
        v-access:code="[OrganizationUnitPermissions.ManageRoles]"
        @click="onDelete(row)"
      >
        {{ $t('AbpUi.Delete') }}
      </Button>
    </template>
  </Grid>
  <RoleModal @confirm="onCreateRole" />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/organization-units/organization-unit-role-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Modal } from "antd";
import { DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { IdentityRoleDto } from "#/management/identity/role";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { OrganizationUnitPermissions } from "@/constants/management/identity/permissions";
import SelectRoleModal from "./select-role-modal";
import { useMutation, useQuery } from "@tanstack/react-query";
import { removeOrganizationUnitApi } from "@/api/management/identity/role";
import { addRoles, getRoleListApi } from "@/api/management/identity/organization-units";
import { toast } from "sonner";

interface Props {
	selectedKey?: string;
}

const OrganizationUnitRoleTable: React.FC<Props> = ({ selectedKey }) => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();
	const [roleModalVisible, setRoleModalVisible] = useState(false);

	// 获取角色列表
	const { data, isLoading, refetch } = useQuery({
		queryKey: ["organizationUnitRoles", selectedKey],
		queryFn: () => {
			if (!selectedKey) {
				return Promise.reject(new Error("selectedKey is undefined"));
			}
			return getRoleListApi(selectedKey, { filter: "" });
		},
		enabled: !!selectedKey,
	});

	// 添加角色
	const { mutateAsync: addRolesToUnit } = useMutation({
		mutationFn: (roles: IdentityRoleDto[]) => {
			if (!selectedKey) {
				return Promise.reject(new Error("selectedKey is undefined"));
			}
			return addRoles(selectedKey, {
				roleIds: roles.map((role) => role.id),
			});
		},
		onSuccess: () => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			setRoleModalVisible(false);
			refetch();

			actionRef.current?.reload();
		},
	});

	// 移除角色
	const { mutateAsync: removeRole } = useMutation({
		mutationFn: (roleId: string) => {
			if (!selectedKey) {
				return Promise.reject(new Error("selectedKey is undefined"));
			}
			return removeOrganizationUnitApi(roleId, selectedKey);
		},
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			refetch();
			actionRef.current?.reload();
		},
	});

	const handleDelete = (role: IdentityRoleDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpIdentity.OrganizationUnit:AreYouSureRemoveRole", { 0: role.name }),
			onOk: () => removeRole(role.id),
		});
	};

	const columns: ProColumns<IdentityRoleDto>[] = [
		{
			title: $t("AbpIdentity.DisplayName:RoleName"),
			dataIndex: "name",
			width: 200,
		},
		{
			title: $t("AbpUi.Actions"),
			width: 180,
			fixed: "right",
			render: (_, record) => (
				<Button
					type="link"
					danger
					icon={<DeleteOutlined />}
					disabled={!hasAccessByCodes([OrganizationUnitPermissions.ManageRoles])}
					onClick={() => handleDelete(record)}
				>
					{$t("AbpUi.Delete")}
				</Button>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<IdentityRoleDto>
					headerTitle={$t("AbpIdentity.Roles")}
					actionRef={actionRef}
					columns={columns}
					dataSource={data?.items}
					loading={isLoading}
					rowKey="id"
					search={false}
					pagination={{
						showSizeChanger: true,
						total: data?.totalCount,
					}}
					toolBarRender={() => [
						selectedKey && hasAccessByCodes([OrganizationUnitPermissions.ManageRoles]) && (
							<Button type="primary" icon={<PlusOutlined />} onClick={() => setRoleModalVisible(true)}>
								{$t("AbpIdentity.OrganizationUnit:AddRole")}
							</Button>
						),
					]}
				/>
			</Card>
			{selectedKey && (
				<SelectRoleModal
					visible={roleModalVisible}
					onClose={() => setRoleModalVisible(false)}
					onConfirm={addRolesToUnit}
					organizationUnitId={selectedKey}
				/>
			)}
		</>
	);
};

export default OrganizationUnitRoleTable;
