// apps/vben5/packages/@abp/identity/src/components/organization-units/OrganizationUnitModal.vue
<script setup lang="ts">
import type {
  OrganizationUnitCreateDto,
  OrganizationUnitDto,
  OrganizationUnitUpdateDto,
} from '../../types/organization-units';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useVbenForm } from '@abp/ui';

import { createApi, getApi, updateApi } from '../../api/organization-units';

defineOptions({
  name: 'OrganizationUnitModal',
});
const emits = defineEmits<{
  (event: 'change', data: OrganizationUnitDto): void;
}>();

const defaultModel = {
  displayName: '',
} as OrganizationUnitDto;

const [Form, formApi] = useVbenForm({
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      componentProps: {
        style: {
          display: 'none',
        },
      },
      fieldName: 'id',
    },
    {
      component: 'Input',
      componentProps: {
        style: {
          display: 'none',
        },
      },
      fieldName: 'parentId',
    },
    {
      component: 'Input',
      componentProps: {
        autocomplete: 'off',
      },
      fieldName: 'displayName',
      label: $t('AbpIdentity.OrganizationUnit:DisplayName'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});

const [Modal, modalApi] = useVbenModal({
  closeOnClickModal: false,
  closeOnPressEscape: false,
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  async onOpenChange(isOpen: boolean) {
    if (isOpen) {
      const { id, parentId } = modalApi.getData<Record<string, any>>();
      if (id) {
        modalApi.setState({ loading: true });
        try {
          const dto = await getApi(id);
          modalApi.setState({
            title: $t('AbpIdentity.OrganizationUnit', [dto.displayName]),
          });
          formApi.setValues(dto);
        } finally {
          modalApi.setState({ loading: false });
        }
        return;
      }
      formApi.setValues({
        ...defaultModel,
        parentId,
      });
      modalApi.setState({
        title: $t('AbpIdentity.OrganizationUnit:New'),
      });
    }
  },
  title: $t('AbpIdentity.OrganizationUnit:New'),
});

async function onSubmit(input: Record<string, any>) {
  const api = input.id
    ? updateApi(input.id, input as OrganizationUnitUpdateDto)
    : createApi(input as OrganizationUnitCreateDto);
  try {
    modalApi.setState({
      confirmLoading: true,
    });
    const dto = await api;
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({
      confirmLoading: false,
    });
  }
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/organization-units/organization-unit-modal.tsx
import { useEffect } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import type {
	OrganizationUnitDto,
	OrganizationUnitCreateDto,
	OrganizationUnitUpdateDto,
} from "#/management/identity/organization-units";
import { useMutation, useQuery } from "@tanstack/react-query";
import { createApi, getApi, updateApi } from "@/api/management/identity/organization-units";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: OrganizationUnitDto) => void;
	id?: string;
	parentId?: string;
}

const defaultModel: Partial<OrganizationUnitDto> = {
	displayName: "",
};

const OrganizationUnitModal: React.FC<Props> = ({ visible, onClose, onChange, id, parentId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	// 查询组织单位详情
	const { data: unitData, isLoading } = useQuery({
		queryKey: ["organizationUnit", id],
		queryFn: () => {
			if (!id) {
				return Promise.reject(new Error("id is undefined"));
			}
			return getApi(id);
		},
		enabled: visible && !!id,
	});

	// 创建组织单位
	const { mutateAsync: createUnit, isPending: isCreating } = useMutation({
		mutationFn: (input: OrganizationUnitCreateDto) => createApi(input),
		onSuccess: (data) => {
			onChange(data);
			onClose();
		},
	});

	// 更新组织单位
	const { mutateAsync: updateUnit, isPending: isUpdating } = useMutation({
		mutationFn: (data: OrganizationUnitUpdateDto) => {
			if (!id) {
				return Promise.reject(new Error("id is undefined"));
			}
			return updateApi(id, data);
		},
		onSuccess: (data) => {
			onChange(data);
			onClose();
		},
	});

	useEffect(() => {
		if (visible) {
			if (id) {
				form.setFieldsValue(unitData);
			} else {
				form.setFieldsValue({
					...defaultModel,
					parentId,
				});
			}
		} else {
			form.resetFields();
		}
	}, [visible, unitData, id, parentId]);

	const handleOk = async () => {
		try {
			const values = await form.validateFields();
			if (id) {
				await updateUnit(values);
			} else {
				await createUnit(values);
			}
		} catch (error) {
			// Form validation error
		}
	};

	return (
		<Modal
			open={visible}
			title={
				id ? `${$t("AbpIdentity.OrganizationUnits")}: ${unitData?.displayName}` : $t("AbpIdentity.OrganizationUnit:New")
			}
			onCancel={onClose}
			onOk={handleOk}
			confirmLoading={isCreating || isUpdating || isLoading}
		>
			<Form form={form} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
				<Form.Item name="id" hidden>
					<Input />
				</Form.Item>
				<Form.Item name="parentId" hidden>
					<Input />
				</Form.Item>
				<Form.Item
					label={$t("AbpIdentity.OrganizationUnit:DisplayName")}
					name="displayName"
					rules={[{ required: true }]}
				>
					<Input autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default OrganizationUnitModal;
