// apps/vben5/packages/@abp/platform/src/components/workbench/components/WorkbenchQuickNavModal.vue
<script setup lang="ts">
import type { MenuDto, UserFavoriteMenuDto } from '../../../types';

import { defineAsyncComponent, ref } from 'vue';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { useAppConfig } from '@vben/hooks';
import { IconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { listToTree } from '@abp/core';
import { message, TreeSelect } from 'ant-design-vue';

import { useMyFavoriteMenusApi } from '../../../api/useMyFavoriteMenusApi';
import { useMyMenusApi } from '../../../api/useMyMenusApi';

const emits = defineEmits<{
  (event: 'change', data: UserFavoriteMenuDto): void;
}>();

const ColorPicker = defineAsyncComponent(() =>
  import('vue3-colorpicker').then((res) => {
    import('vue3-colorpicker/style.css');
    return res.ColorPicker;
  }),
);

const availableMenus = ref<MenuDto[]>([]);

const { getAllApi } = useMyMenusApi();
const { createApi } = useMyFavoriteMenusApi();
const { uiFramework } = useAppConfig(import.meta.env, import.meta.env.PROD);

const [Form, formApi] = useVbenForm({
  schema: [
    {
      label: $t('workbench.content.favoriteMenu.select'),
      fieldName: 'menuId',
      component: 'TreeSelect',
      rules: 'selectRequired',
    },
    {
      label: $t('workbench.content.favoriteMenu.color'),
      fieldName: 'color',
      component: 'ColorPicker',
      defaultValue: '#000000',
      modelPropName: 'pureColor',
    },
    {
      label: $t('workbench.content.favoriteMenu.alias'),
      fieldName: 'aliasName',
      component: 'Input',
    },
    {
      label: $t('workbench.content.favoriteMenu.icon'),
      fieldName: 'icon',
      component: 'IconPicker',
    },
  ],
  showDefaultActions: false,
  handleSubmit: onSubmit,
  commonConfig: {
    colon: true,
    componentProps: {
      class: 'w-full',
    },
  },
});
const [Modal, modalApi] = useVbenModal({
  async onConfirm() {
    await formApi.validateAndSubmitForm();
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      await onInitMenus();
    }
  },
});

async function onInitMenus() {
  const { items } = await getAllApi({
    framework: uiFramework,
  });
  const menus = listToTree<MenuDto>(items, { id: 'id', pid: 'parentId' });
  availableMenus.value = menus;
}

async function onSubmit(values: Record<string, any>) {
  try {
    modalApi.setState({ submitting: true });
    const menuDto = await createApi({
      framework: uiFramework,
      menuId: values.menuId,
      color: values.color,
      icon: values.icon,
      aliasName: values.aliasName,
    });
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', menuDto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="$t('workbench.content.favoriteMenu.manage')">
    <Form>
      <template #color="slotProps">
        <div class="flex flex-row items-center">
          <ColorPicker v-bind="slotProps" format="hex" />
          <span>({{ slotProps.value }})</span>
        </div>
      </template>
      <template #menuId="slotProps">
        <TreeSelect
          allow-clear
          class="w-full"
          tree-icon
          v-bind="slotProps"
          :field-names="{ label: 'displayName', value: 'id' }"
          :tree-data="availableMenus">
          <template #title="item">
            <div class="flex flex-row items-center gap-1">
              <IconifyIcon v-if="item.meta?.icon" :icon="item.meta.icon" />
              <span>{{ item.displayName }}</span>
            </div>
          </template>
        </TreeSelect>
      </template>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/platform/workbench/components/workbench-quick-nav-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, TreeSelect } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { getAllApi } from "@/api/platform/menus";
import { createApi } from "@/api/platform/my-favorite-menus";
import type { MenuDto } from "#/platform/menus";
import type { UserFavoriteMenuDto } from "#/platform/favorites";
import { ColorPicker } from "antd";
import IconPicker from "@/components/abp/adapter/icon-picker";
import { listToTree } from "@/utils/tree";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: UserFavoriteMenuDto) => void;
}

const WorkbenchQuickNavModal: React.FC<Props> = ({ visible, onClose, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [availableMenus, setAvailableMenus] = useState<MenuDto[]>([]);
	const [submitting, setSubmitting] = useState(false);
	// const { uiFramework } = useAppConfig(); // Retrieve global config
	const uiFramework = "react"; // Placeholder for global config

	useEffect(() => {
		if (visible) {
			initMenus();
			form.resetFields();
			// Default color
			form.setFieldValue("color", "#000000");
		}
	}, [visible]);

	const initMenus = async () => {
		try {
			const { items } = await getAllApi({ framework: uiFramework });
			const tree = listToTree(items, { id: "id", pid: "parentId" });
			setAvailableMenus(tree);
		} catch (e) {
			console.error(e);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const colorHex = typeof values.color === "string" ? values.color : values.color?.toHexString();

			const menuDto = await createApi({
				framework: uiFramework,
				menuId: values.menuId,
				color: colorHex,
				icon: values.icon,
				aliasName: values.aliasName,
			});

			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(menuDto);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	return (
		<Modal
			title={$t("workbench.content.favoriteMenu.manage")}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item
					name="menuId"
					label={$t("workbench.content.favoriteMenu.select")}
					rules={[{ required: true, message: $t("AbpUi.ThisFieldIsRequired") }]}
				>
					<TreeSelect
						treeData={availableMenus}
						fieldNames={{ label: "displayName", value: "id", children: "children" }}
						allowClear
						showSearch
						treeDefaultExpandAll
						placeholder={$t("ui.placeholder.select")}
					/>
				</Form.Item>

				<Form.Item name="color" label={$t("workbench.content.favoriteMenu.color")}>
					<ColorPicker showText />
				</Form.Item>

				<Form.Item name="aliasName" label={$t("workbench.content.favoriteMenu.alias")}>
					<Input autoComplete="off" />
				</Form.Item>

				<Form.Item name="icon" label={$t("workbench.content.favoriteMenu.icon")}>
					<IconPicker />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default WorkbenchQuickNavModal;
