// apps/vben5/packages/@abp/platform/src/components/workbench/components/WorkbenchQuickNav.vue
<script setup lang="ts">
import type { FavoriteMenu } from '../types';

import { computed, h } from 'vue';

import { $t } from '@vben/locales';

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  VbenIcon,
} from '@vben-core/shadcn-ui';

import { DeleteOutlined } from '@ant-design/icons-vue';
import { Dropdown, Menu, Modal } from 'ant-design-vue';

interface Props {
  items?: FavoriteMenu[];
  title: string;
}

defineOptions({
  name: 'WorkbenchQuickNav',
});

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
});

const emits = defineEmits<{
  (event: 'click', menu: FavoriteMenu): void;
  (event: 'delete', menu: FavoriteMenu): void;
  (event: 'add'): void;
}>();

const MenuItem = Menu.Item;

const getFavoriteMenus = computed(() => {
  const addMenu: FavoriteMenu = {
    id: 'addMenu',
    displayName: $t('workbench.content.favoriteMenu.create'),
    icon: 'ion:add-outline',
    color: '#00bfff',
    isDefault: true,
  };
  return [...props.items, addMenu];
});

function onClick(menu: FavoriteMenu) {
  if (menu.id === 'addMenu') {
    emits('add');
    return;
  }
  emits('click', menu);
}

function onMenuClick(key: string, menu: FavoriteMenu) {
  switch (key) {
    case 'delete': {
      Modal.confirm({
        centered: true,
        iconType: 'warning',
        title: $t('AbpUi.AreYouSure'),
        content: $t('AbpUi.ItemWillBeDeletedMessage'),
        okCancel: true,
        onOk: () => {
          emits('delete', menu);
        },
      });
    }
  }
}
</script>

<template>
  <Card>
    <CardHeader class="py-4">
      <CardTitle class="text-lg">{{ title }}</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap p-0">
      <template
        v-for="(item, index) in getFavoriteMenus"
        :key="item.displayName"
      >
        <Dropdown :trigger="['contextmenu']">
          <div
            :class="{
              'border-r-0': index % 3 === 2,
              'border-b-0': index < 3,
              'pb-4': index > 2,
              'rounded-bl-xl': index === items.length - 3,
              'rounded-br-xl': index === items.length - 1,
            }"
            class="flex-col-center border-border group w-1/3 cursor-pointer border-r border-t py-8 hover:shadow-xl"
            @click="onClick(item)"
          >
            <VbenIcon
              :color="item.color"
              :icon="item.icon"
              class="size-7 transition-all duration-300 group-hover:scale-125"
            />
            <span class="text-md mt-2 truncate">{{ item.displayName }}</span>
          </div>
          <template #overlay>
            <Menu
              v-if="!item.isDefault"
              @click="
                ({ key: menuKey }) => onMenuClick(menuKey.toString(), item)
              "
            >
              <MenuItem key="delete" :icon="h(DeleteOutlined)">
                {{ $t('workbench.content.favoriteMenu.delete') }}
              </MenuItem>
            </Menu>
          </template>
        </Dropdown>
      </template>
    </CardContent>
  </Card>
</template>

<style scoped></style>

// apps/react-admin/src/pages/platform/workbench/components/workbench-quick-nav.tsx
import React, { useMemo } from "react";
import { Card, Dropdown, Modal } from "antd";
import { DeleteOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { Iconify } from "@/components/icon";
import type { FavoriteMenu } from "../types";

interface Props {
	items?: FavoriteMenu[];
	title: string;
	onClick?: (menu: FavoriteMenu) => void;
	onDelete?: (menu: FavoriteMenu) => void;
	onAdd?: () => void;
}

const WorkbenchQuickNav: React.FC<Props> = ({ items = [], title, onClick, onDelete, onAdd }) => {
	const { t: $t } = useTranslation();

	const [modal, contextHolder] = Modal.useModal();
	const getFavoriteMenus = useMemo(() => {
		const addMenu: FavoriteMenu = {
			id: "addMenu",
			displayName: $t("workbench.content.favoriteMenu.create"),
			icon: "ion:add-outline",
			color: "#00bfff",
			isDefault: true,
		};
		return [...items, addMenu];
	}, [items, $t]);

	const handleClick = (menu: FavoriteMenu) => {
		if (menu.id === "addMenu") {
			onAdd?.();
			return;
		}
		onClick?.(menu);
	};

	const handleDelete = (menu: FavoriteMenu) => {
		modal.confirm({
			centered: true,
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: () => onDelete?.(menu),
		});
	};

	return (
		<>
			{contextHolder}
			<Card title={title} className="min-h-[300px] shadow-sm">
				<div className="flex flex-wrap">
					{getFavoriteMenus.map((item, index) => {
						const isAddBtn = item.id === "addMenu";
						// Calculate borders for grid layout (3 columns)
						const borderClasses = `
            flex flex-col items-center justify-center w-1/3 py-8 cursor-pointer
            border-t border-r border-gray-100 hover:shadow-lg transition-shadow duration-300 group
            ${index % 3 === 2 ? "border-r-0" : ""}
            ${index < 3 ? "border-t-0" : ""} 
          `;

						const content = (
							<div className={borderClasses} onClick={() => handleClick(item)}>
								<Iconify
									icon={item.icon || "mdi:circle"}
									style={{ color: item.color, fontSize: "28px" }}
									className="transition-transform duration-300 group-hover:scale-125"
								/>
								<span className="mt-2 text-sm text-gray-600 truncate px-2 w-full text-center">{item.displayName}</span>
							</div>
						);

						if (!item.isDefault && !isAddBtn) {
							return (
								<Dropdown
									key={item.id}
									trigger={["contextMenu"]}
									menu={{
										items: [
											{
												key: "delete",
												label: $t("workbench.content.favoriteMenu.delete"),
												icon: <DeleteOutlined />,
												onClick: () => handleDelete(item),
											},
										],
									}}
								>
									{content}
								</Dropdown>
							);
						}

						return <React.Fragment key={item.id}>{content}</React.Fragment>;
					})}
				</div>
			</Card>
		</>
	);
};

export default WorkbenchQuickNav;
