// apps/vben5/packages/@abp/localization/src/components/resources/LocalizationResourceTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { ResourceDto } from '../../types/resources';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useAbpStore } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useLocalizationsApi } from '../../api/useLocalizationsApi';
import { useResourcesApi } from '../../api/useResourcesApi';
import { ResourcesPermissions } from '../../constants/permissions';

defineOptions({
  name: 'LocalizationResourceTable',
});

const dataSource = ref<ResourceDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const abpStore = useAbpStore();
const { deleteApi, getListApi } = useResourcesApi();
const { getLocalizationApi } = useLocalizationsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<ResourceDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('AbpFeatureManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AbpFeatureManagement.DisplayName:DisplayName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<ResourceDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [LocalizationResourceModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./LocalizationResourceModal.vue'),
  ),
});

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input);
    pageState.total = items.length;
    dataSource.value = items;
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = dataSource.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: ResourceDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: ResourceDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onChange();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

async function onChange() {
  const input = await gridApi.formApi.getValues();
  onGet(input);
  // 资源变化刷新本地多语言缓存
  const cultureName = abpStore.localization!.currentCulture.cultureName;
  const localization = await getLocalizationApi({
    cultureName,
  });
  abpStore.setLocalization(localization);
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('AbpLocalization.Resources')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[ResourcesPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('LocalizationManagement.Resource:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[ResourcesPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="!row.isStatic"
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[ResourcesPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
  </Grid>
  <LocalizationResourceModal @change="onChange" />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/localization/resources/localization-resource-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Modal, Space } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { getListApi, deleteApi } from "@/api/management/localization/resources";
import type { ResourceDto } from "#/management/localization/resources";
import LocalizationResourceModal from "./localization-resource-modal";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { ResourcesPermissions } from "@/constants/management/localization/permissions";
import useAbpStore from "@/store/abpCoreStore";
import orderBy from "lodash.orderby";
import { useSetLocale } from "@/store/localeI18nStore";
import { getStringItem } from "@/utils/storage";
import { LocalEnum, StorageEnum } from "#/enum";

const LocalizationResourceTable: React.FC = () => {
	const { t: $t, i18n } = useTranslation();
	const setLocale = useSetLocale();
	const currentLng = getStringItem(StorageEnum.I18N) || LocalEnum.en_US;
	const actionRef = useRef<ActionType>();
	const [modalVisible, setModalVisible] = useState(false);
	const [currentResource, setCurrentResource] = useState<string | undefined>();
	const [modal, contextHolder] = Modal.useModal();

	const application = useAbpStore((state) => state.application);

	const handleOpenModal = (name?: string) => {
		setCurrentResource(name);
		setModalVisible(true);
	};

	const handleDelete = (row: ResourceDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: async () => {
				await deleteApi(row.name);
				toast.success($t("AbpUi.DeletedSuccessfully"));
				handleDataChange();
			},
		});
	};

	const handleDataChange = async () => {
		actionRef.current?.reload();

		// Refresh localization cache
		const currentCultureName = application?.localization.currentCulture.cultureName;
		if (currentCultureName) {
			try {
				await setLocale(currentLng as LocalEnum, i18n);
			} catch (error) {
				console.error("Failed to refresh localization", error);
			}
		}
	};

	const columns: ProColumns<ResourceDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpFeatureManagement.DisplayName:Name"),
			dataIndex: "name",
			sorter: true,
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpFeatureManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			sorter: true,
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 220,
			render: (_, record) => (
				<Space>
					{hasAccessByCodes([ResourcesPermissions.Update]) && (
						<Button type="link" icon={<EditOutlined />} onClick={() => handleOpenModal(record.name)}>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{/* !record.isStatic && no isStatic */}
					{hasAccessByCodes([ResourcesPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<ResourceDto>
					headerTitle={$t("AbpLocalization.Resources")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={{
						labelWidth: "auto",
					}}
					toolBarRender={() => [
						hasAccessByCodes([ResourcesPermissions.Create]) && (
							<Button key="add" type="primary" icon={<PlusOutlined />} onClick={() => handleOpenModal()}>
								{$t("LocalizationManagement.Resource:AddNew")}
							</Button>
						),
					]}
					request={async (params, sorter) => {
						const { items } = await getListApi({ filter: params.filter });

						let dataSource = [...items];

						if (sorter && Object.keys(sorter).length > 0) {
							const sortField = Object.keys(sorter)[0];
							const sortOrder = sorter[sortField] === "ascend" ? "asc" : "desc";
							dataSource = orderBy(dataSource, [sortField], [sortOrder]);
						}

						const current = params.current || 1;
						const pageSize = params.pageSize || 10;
						const startIndex = (current - 1) * pageSize;
						const endIndex = startIndex + pageSize;
						const pageData = dataSource.slice(startIndex, endIndex);

						return {
							data: pageData,
							success: true,
							total: dataSource.length,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<LocalizationResourceModal
				visible={modalVisible}
				resourceName={currentResource}
				onClose={() => setModalVisible(false)}
				onChange={handleDataChange}
			/>
		</>
	);
};

export default LocalizationResourceTable;
