// apps/vben5/packages/@abp/identity/src/components/sessions/UserSessionTable.vue
<script setup lang="ts">
import type { VxeGridProps } from '@abp/ui';

import type { IdentitySessionDto } from '../../types/sessions';

import { computed, nextTick, reactive, watch } from 'vue';

import { useAccess } from '@vben/access';
import { $t } from '@vben/locales';

import { formatToDateTime, useAbpStore } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import { Button, Descriptions, Tag } from 'ant-design-vue';

import { IdentitySessionPermissions } from '../../constants/permissions';

const props = defineProps<{
  sessions: IdentitySessionDto[];
}>();
const emits = defineEmits<{
  (event: 'revoke', session: IdentitySessionDto): void;
}>();
const DescriptionItem = Descriptions.Item;

const { hasAccessByCodes } = useAccess();
const abpStore = useAbpStore();
/** 获取登录用户会话Id */
const getMySessionId = computed(() => {
  return abpStore.application?.currentUser.sessionId;
});
/** 获取是否允许撤销会话 */
const getAllowRevokeSession = computed(() => {
  return (session: IdentitySessionDto) => {
    if (getMySessionId.value === session.sessionId) {
      return false;
    }
    return hasAccessByCodes([IdentitySessionPermissions.Revoke]);
  };
});

const gridOptions = reactive<VxeGridProps<IdentitySessionDto>>({
  columns: [
    {
      align: 'left',
      slots: { content: 'deviceInfo' },
      type: 'expand',
      width: 50,
    },
    {
      align: 'left',
      field: 'device',
      slots: { default: 'device' },
      title: $t('AbpIdentity.DisplayName:Device'),
      width: 150,
    },
    {
      align: 'left',
      field: 'signedIn',
      minWidth: 200,
      title: $t('AbpIdentity.DisplayName:SignedIn'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 120,
    },
  ],
  expandConfig: {
    padding: true,
    trigger: 'default',
  },
  exportConfig: {},
  keepSource: true,
  pagerConfig: {
    autoHidden: true,
  },
  toolbarConfig: {},
});

const [Grid, gridApi] = useVbenVxeGrid({ gridOptions });

watch(
  () => props.sessions,
  (sessions) => {
    nextTick(() => {
      gridApi.setGridOptions({
        data: sessions,
      });
    });
  },
  {
    immediate: true,
  },
);

function onDelete(session: IdentitySessionDto) {
  emits('revoke', session);
}
</script>

<template>
  <Grid>
    <template #device="{ row }">
      <div class="flex flex-row">
        <span>{{ row.device }}</span>
        <div class="pl-[5px]">
          <Tag v-if="row.sessionId === getMySessionId" color="#87d068">
            {{ $t('AbpIdentity.CurrentSession') }}
          </Tag>
        </div>
      </div>
    </template>
    <template #deviceInfo="{ row }">
      <Descriptions :colon="false" :column="2" bordered size="small">
        <DescriptionItem
          :label="$t('AbpIdentity.DisplayName:SessionId')"
          :span="2"
        >
          {{ row.sessionId }}
        </DescriptionItem>
        <DescriptionItem :label="$t('AbpIdentity.DisplayName:Device')">
          {{ row.device }}
        </DescriptionItem>
        <DescriptionItem :label="$t('AbpIdentity.DisplayName:DeviceInfo')">
          {{ row.deviceInfo }}
        </DescriptionItem>
        <DescriptionItem :label="$t('AbpIdentity.DisplayName:ClientId')">
          {{ row.clientId }}
        </DescriptionItem>
        <DescriptionItem :label="$t('AbpIdentity.DisplayName:IpAddresses')">
          {{ row.ipAddresses }}
        </DescriptionItem>
        <DescriptionItem :label="$t('AbpIdentity.DisplayName:SignedIn')">
          {{ formatToDateTime(row.signedIn) }}
        </DescriptionItem>
        <DescriptionItem :label="$t('AbpIdentity.DisplayName:LastAccessed')">
          {{ formatToDateTime(row.lastAccessed) }}
        </DescriptionItem>
      </Descriptions>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          v-if="getAllowRevokeSession(row)"
          danger
          size="small"
          @click="onDelete(row)"
        >
          {{ $t('AbpIdentity.RevokeSession') }}
        </Button>
      </div>
    </template>
  </Grid>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/sessions/user-session-table.tsx
import { Button, Descriptions, Table, Tag, type TableColumnType } from "antd";
import { useTranslation } from "react-i18next";
import type { IdentitySessionDto } from "#/management/identity/sessions";
import { formatToDateTime } from "@/utils/abp";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { IdentitySessionPermissions } from "@/constants/management/identity/permissions";
import { useApplication } from "@/store/abpCoreStore";
import { Space } from "antd";

interface Props {
	sessions: IdentitySessionDto[];
	onRevoke: (session: IdentitySessionDto) => void;
}

const UserSessionTable: React.FC<Props> = ({ sessions, onRevoke }) => {
	const { t: $t } = useTranslation();
	const application = useApplication();

	const isCurrentSession = (sessionId: string) => {
		return application?.currentUser.sessionId === sessionId;
	};

	const allowRevokeSession = (session: IdentitySessionDto) => {
		if (isCurrentSession(session.sessionId)) {
			return false;
		}
		return hasAccessByCodes([IdentitySessionPermissions.Revoke]);
	};

	const expandedRowRender = (record: IdentitySessionDto) => {
		return (
			<Descriptions bordered size="small" column={2}>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:SessionId")} span={2}>
					{record.sessionId}
				</Descriptions.Item>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:Device")}>{record.device}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:DeviceInfo")}>{record.deviceInfo}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:ClientId")}>{record.clientId}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:IpAddresses")}>{record.ipAddresses}</Descriptions.Item>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:SignedIn")}>
					{formatToDateTime(record.signedIn)}
				</Descriptions.Item>
				<Descriptions.Item label={$t("AbpIdentity.DisplayName:LastAccessed")}>
					{formatToDateTime(record.lastAccessed)}
				</Descriptions.Item>
			</Descriptions>
		);
	};

	const columns: TableColumnType<IdentitySessionDto>[] = [
		{
			title: $t("AbpIdentity.DisplayName:Device"),
			dataIndex: "device",
			width: 150,
			render: (_, record) => (
				<Space>
					<span>{record.device}</span>
					{isCurrentSession(record.sessionId) && <Tag color="#87d068">{$t("AbpIdentity.CurrentSession")}</Tag>}
				</Space>
			),
		},
		{
			title: $t("AbpIdentity.DisplayName:SignedIn"),
			dataIndex: "signedIn",
			render: (value) => formatToDateTime(value),
		},
		{
			title: $t("AbpUi.Actions"),
			width: 120,
			fixed: "right",
			render: (_, record) => (
				<div>
					{allowRevokeSession(record) && (
						<Button danger size="small" onClick={() => onRevoke(record)}>
							{$t("AbpIdentity.RevokeSession")}
						</Button>
					)}
				</div>
			),
		},
	];

	return (
		<Table<IdentitySessionDto>
			columns={columns}
			dataSource={sessions}
			rowKey="sessionId"
			expandable={{
				expandedRowRender,
				expandRowByClick: true,
			}}
			pagination={false}
		/>
	);
};

export default UserSessionTable;
