// apps/vben5/packages/@abp/openiddict/src/components/properties/PropertyTable.vue
<script setup lang="ts">
import type { VxeGridPropTypes } from 'vxe-table';

import type { PropertyInfo, PropertyProps } from './types';

import { computed, defineAsyncComponent, h, reactive } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, Popconfirm } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

defineOptions({
  name: 'PropertyTable',
});

const props = defineProps<PropertyProps>();
const emits = defineEmits<{
  (event: 'change' | 'delete', data: PropertyInfo): void;
}>();

const getDataResource = computed((): PropertyInfo[] => {
  if (!props.data) return [];
  return Object.keys(props.data).map((item) => {
    return {
      key: item,
      value: props.data![item]!,
    };
  });
});

const columnsConfig = reactive<VxeGridPropTypes.Columns<PropertyInfo>>([
  {
    align: 'left',
    field: 'key',
    minWidth: 200,
    title: $t('AbpOpenIddict.Propertites:Key'),
  },
  {
    align: 'left',
    field: 'value',
    minWidth: 200,
    title: $t('AbpOpenIddict.Propertites:Value'),
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 180,
  },
]);

const [PropertyModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./PropertyModal.vue')),
});

function onCreate() {
  modalApi.open();
}

function onDelete(prop: PropertyInfo) {
  emits('delete', prop);
}

function onChange(prop: PropertyInfo) {
  emits('change', prop);
}
</script>

<template>
  <VxeGrid
    :columns="columnsConfig"
    :data="getDataResource"
    :toolbar-config="{ slots: { tools: 'toolbar_tools' } }">
    <template #toolbar_tools>
      <Button :icon="h(PlusOutlined)" type="primary" @click="onCreate">
        {{ $t('AbpOpenIddict.Propertites:New') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Popconfirm
          :title="`${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.key])}`"
          @confirm="onDelete(row)">
          <Button :icon="h(DeleteOutlined)" block danger type="link">
            {{ $t('AbpUi.Delete') }}
          </Button>
        </Popconfirm>
      </div>
    </template>
  </VxeGrid>
  <PropertyModal @change="onChange" />
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/properties/property-table.tsx
import { Button, Popconfirm, Table } from "antd";
import type { ColumnsType } from "antd/es/table";
import { PlusOutlined, DeleteOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { useMemo, useState } from "react";
import PropertyModal from "./property-modal";
import type { PropertyInfo, PropertyProps } from "./types";

const PropertyTable: React.FC<PropertyProps> = ({
	data = {},
	allowDelete = true,
	allowEdit = true,
	disabled = false,
	onChange,
	onDelete,
}) => {
	const { t: $t } = useTranslation();
	const [modalVisible, setModalVisible] = useState(false);

	const dataSource = useMemo((): PropertyInfo[] => {
		return Object.keys(data).map((key) => ({
			key,
			value: data[key],
		}));
	}, [data]);

	const columns: ColumnsType<PropertyInfo> = useMemo(() => {
		const baseColumns: ColumnsType<PropertyInfo> = [
			{
				align: "left",
				dataIndex: "key",
				fixed: "left",
				width: 100,
				title: $t("component.extra_property_dictionary.key"),
			},
			{
				align: "left",
				dataIndex: "value",
				fixed: "left",
				title: $t("component.extra_property_dictionary.value"),
			},
		];

		if (disabled) {
			return baseColumns;
		}

		return [
			...baseColumns,
			{
				align: "center",
				dataIndex: "action",
				fixed: "right",
				key: "action",
				title: $t("component.extra_property_dictionary.actions.title"),
				width: 150,
				render: (_, record: PropertyInfo) =>
					allowDelete && (
						<Popconfirm
							title={$t("component.extra_property_dictionary.itemWillBeDeleted", { key: record.key })}
							onConfirm={() => handleDelete(record)}
						>
							<Button block danger type="link" icon={<DeleteOutlined />}>
								{$t("component.extra_property_dictionary.actions.delete")}
							</Button>
						</Popconfirm>
					),
			},
		];
	}, [disabled, allowDelete, $t]);

	const handleCreate = () => {
		setModalVisible(true);
	};

	const handleDelete = (prop: PropertyInfo) => {
		onDelete?.(prop);
	};

	const handleChange = (prop: PropertyInfo) => {
		onChange?.(prop);
		setModalVisible(false);
	};

	return (
		<div className="flex flex-col gap-4">
			<div className="flex flex-row justify-end">
				{!disabled && allowEdit && (
					<Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
						{$t("component.extra_property_dictionary.actions.create")}
					</Button>
				)}
			</div>
			<div className="justify-center">
				<Table columns={columns} dataSource={dataSource} rowKey="key" />
			</div>
			<PropertyModal visible={modalVisible} onClose={() => setModalVisible(false)} onChange={handleChange} />
		</div>
	);
};

export default PropertyTable;
