// apps/react-admin/src/pages/text-templating/template-content-curtule-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Select, Input, Button, Card, Row, Col } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import useAbpStore from "@/store/abpCoreStore";
import { getApi, restoreToDefaultApi, updateApi } from "@/api/text-templating/template-contents";
import type { TextTemplateContentDto } from "#/text-templating/contents";
import type { TextTemplateDefinitionDto } from "#/text-templating/definitions";

interface Props {
	visible: boolean;
	onClose: () => void;
	templateDefinition?: TextTemplateDefinitionDto;
	onChange?: (data: TextTemplateContentDto) => void;
}

const TemplateContentCurtuleModal: React.FC<Props> = ({ visible, onClose, templateDefinition, onChange }) => {
	const { t: $t } = useTranslation();
	const application = useAbpStore((state) => state.application);

	const [modal, contextHolder] = Modal.useModal();
	const [sourceForm] = Form.useForm();
	const [targetForm] = Form.useForm();
	const [submitting, setSubmitting] = useState(false);
	const [loading, setLoading] = useState(false);

	// Get available languages
	const languages = application?.localization.languages || [];
	const currentCulture = application?.localization.currentCulture.cultureName;

	const fetchContent = async (culture: string | undefined, isSource: boolean) => {
		if (!templateDefinition?.name) return;
		try {
			setLoading(true);
			const data = await getApi({
				name: templateDefinition.name,
				culture: culture,
			});
			if (isSource) {
				sourceForm.setFieldValue("content", data.content);
			} else {
				targetForm.setFieldValue("content", data.content);
			}
		} finally {
			setLoading(false);
		}
	};

	useEffect(() => {
		if (visible && templateDefinition) {
			// Initial Load
			sourceForm.setFieldValue("culture", currentCulture);
			targetForm.setFieldValue("culture", currentCulture);

			// Fetch initial data for both sides
			fetchContent(currentCulture, true);
			fetchContent(currentCulture, false);
		}
	}, [visible, templateDefinition]);

	const handleCultureChange = (val: string, isSource: boolean) => {
		fetchContent(val, isSource);
	};

	const handleSave = async () => {
		if (!templateDefinition) return;
		try {
			const values = await targetForm.validateFields();
			setSubmitting(true);

			const dto = await updateApi(templateDefinition.name, {
				content: values.content,
				culture: values.culture,
			});

			toast.success($t("AbpTextTemplating.TemplateContentUpdated"));
			onChange?.(dto);
			onClose();
		} catch (e) {
			console.error(e);
		} finally {
			setSubmitting(false);
		}
	};

	const handleRestore = () => {
		if (!templateDefinition) return;
		modal.confirm({
			title: $t("AbpTextTemplating.RestoreToDefault"),
			content: $t("AbpTextTemplating.RestoreToDefaultMessage"),
			onOk: async () => {
				const culture = targetForm.getFieldValue("culture");
				await restoreToDefaultApi(templateDefinition.name, { culture });
				toast.success($t("AbpTextTemplating.TemplateContentRestoredToDefault"));
				// Refresh target content
				fetchContent(culture, false);
			},
		});
	};

	return (
		<>
			{contextHolder}
			<Modal
				title={$t("AbpTextTemplating.EditContents")}
				open={visible}
				onCancel={onClose}
				onOk={handleSave}
				confirmLoading={submitting}
				width="90%"
				style={{ top: 20 }}
				okText={$t("AbpTextTemplating.SaveContent")}
				destroyOnClose
			>
				<Card
					title={templateDefinition ? `${$t("AbpTextTemplating.DisplayName:Name")} - ${templateDefinition.name}` : ""}
					extra={
						<Button danger type="primary" onClick={handleRestore}>
							{$t("AbpTextTemplating.RestoreToDefault")}
						</Button>
					}
					loading={loading}
				>
					<Row gutter={16}>
						{/* Source Side (Read Only) */}
						<Col span={12}>
							<Form form={sourceForm} layout="vertical">
								<Form.Item name="culture" label={$t("AbpTextTemplating.BaseCultureName")} rules={[{ required: true }]}>
									<Select
										options={languages}
										fieldNames={{ label: "displayName", value: "cultureName" }}
										onChange={(val) => handleCultureChange(val, true)}
									/>
								</Form.Item>
								<Form.Item name="content" label={$t("AbpTextTemplating.BaseContent")}>
									<Input.TextArea autoSize={{ minRows: 20 }} readOnly />
								</Form.Item>
							</Form>
						</Col>

						{/* Target Side (Editable) */}
						<Col span={12}>
							<Form form={targetForm} layout="vertical">
								<Form.Item
									name="culture"
									label={$t("AbpTextTemplating.TargetCultureName")}
									rules={[{ required: true }]}
								>
									<Select
										options={languages}
										fieldNames={{ label: "displayName", value: "cultureName" }}
										onChange={(val) => handleCultureChange(val, false)}
									/>
								</Form.Item>
								<Form.Item name="content" label={$t("AbpTextTemplating.TargetContent")} rules={[{ required: true }]}>
									<Input.TextArea autoSize={{ minRows: 20 }} showCount />
								</Form.Item>
							</Form>
						</Col>
					</Row>
				</Card>
			</Modal>
		</>
	);
};

export default TemplateContentCurtuleModal;

// apps/vben5/packages/@abp/text-templating/src/components/definitions/TemplateContentCurtuleModal.vue
<script setup lang="ts">
import type { ExtendedFormApi } from '@vben/common-ui';

import type { TextTemplateContentDto } from '../../types';
import type { TextTemplateDefinitionDto } from '../../types/definitions';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useAbpStore } from '@abp/core';
import { Modal as AntdvModal, Button, Card, message } from 'ant-design-vue';

import { useTemplateContentsApi } from '../../api';

defineProps<{
  title: string;
}>();
const emits = defineEmits<{
  (event: 'change', data: TextTemplateContentDto): void;
}>();
const abpStore = useAbpStore();
const { getApi, restoreToDefaultApi, updateApi } = useTemplateContentsApi();

const [SourceForm, sourceFormApi] = useVbenForm({
  commonConfig: {
    colon: true,
    componentProps: {
      class: 'w-full',
    },
    disabled: true,
  },
  layout: 'vertical',
  schema: [
    {
      component: 'Select',
      componentProps: {
        fieldNames: {
          label: 'displayName',
          value: 'cultureName',
        },
        onChange: (val?: string) => onCultureChange(sourceFormApi, val),
      },
      fieldName: 'culture',
      label: $t('AbpTextTemplating.BaseCultureName'),
      rules: 'required',
    },
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 20,
        },
        showCount: true,
      },
      fieldName: 'content',
      label: $t('AbpTextTemplating.BaseContent'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});
const [TargetForm, targetFormApi] = useVbenForm({
  commonConfig: {
    colon: true,
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  layout: 'vertical',
  schema: [
    {
      component: 'Select',
      componentProps: {
        fieldNames: {
          label: 'displayName',
          value: 'cultureName',
        },
        onChange: (val?: string) => onCultureChange(targetFormApi, val),
      },
      fieldName: 'culture',
      label: $t('AbpTextTemplating.TargetCultureName'),
      rules: 'required',
    },
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 20,
        },
        showCount: true,
      },
      fieldName: 'content',
      label: $t('AbpTextTemplating.TargetContent'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  confirmText: $t('AbpTextTemplating.SaveContent'),
  fullscreen: true,
  fullscreenButton: false,
  async onConfirm() {
    await targetFormApi.validateAndSubmitForm();
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      await onInit();
    }
  },
});

async function onInit() {
  try {
    modalApi.setState({ loading: true });
    const culture =
      abpStore.application?.localization.currentCulture.cultureName;
    const languages = abpStore.application?.localization.languages ?? [];
    sourceFormApi.updateSchema([
      {
        componentProps: {
          options: languages,
        },
        fieldName: 'culture',
      },
    ]);
    targetFormApi.updateSchema([
      {
        componentProps: {
          options: languages,
        },
        fieldName: 'culture',
      },
    ]);
    const { name } = modalApi.getData<TextTemplateDefinitionDto>();
    const { content } = await getApi({
      culture,
      name,
    });
    sourceFormApi.setValues({
      content,
      culture,
    });
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onCultureChange(formApi: ExtendedFormApi, culture?: string) {
  const { name } = modalApi.getData<TextTemplateDefinitionDto>();
  const { content } = await getApi({
    culture,
    name,
  });
  formApi.setValues({
    content,
    culture,
  });
}

async function onSubmit(values: Record<string, string>) {
  try {
    modalApi.setState({ submitting: true });
    const { name } = modalApi.getData<TextTemplateDefinitionDto>();
    const dto = await updateApi(name, {
      content: values.content ?? '',
      culture: values.culture,
    });
    emits('change', dto);
    message.success($t('AbpTextTemplating.TemplateContentUpdated'));
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}

function onRestoreToDefault() {
  AntdvModal.confirm({
    centered: true,
    content: $t('AbpTextTemplating.RestoreToDefaultMessage'),
    onOk: async () => {
      const { name } = modalApi.getData<TextTemplateDefinitionDto>();
      const formValues = await sourceFormApi.getValues();
      await restoreToDefaultApi(name, {
        culture: formValues.culture,
      });
      message.success($t('AbpTextTemplating.TemplateContentRestoredToDefault'));
      await onInit();
    },
    title: $t('AbpTextTemplating.RestoreToDefault'),
  });
}
</script>

<template>
  <Modal :title="$t('AbpTextTemplating.EditContents')">
    <Card :title="title">
      <template #extra>
        <Button danger type="primary" @click="onRestoreToDefault">
          {{ $t('AbpTextTemplating.RestoreToDefault') }}
        </Button>
      </template>
      <div class="flex flex-row gap-3">
        <div class="w-1/2">
          <SourceForm />
        </div>
        <div class="w-1/2">
          <TargetForm />
        </div>
      </div>
    </Card>
  </Modal>
</template>

<style scoped></style>
