// apps/vben5/packages/@abp/notifications/src/components/definitions/groups/NotificationGroupDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { NotificationGroupDefinitionDto } from '../../../types/groups';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { useLocalization, useLocalizationSerializer } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useNotificationGroupDefinitionsApi } from '../../../api/useNotificationGroupDefinitionsApi';
import {
  GroupDefinitionsPermissions,
  NotificationDefinitionsPermissions,
} from '../../../constants/permissions';

defineOptions({
  name: 'NotificationGroupDefinitionTable',
});

const MenuItem = Menu.Item;
const DefinitionIcon = createIconifyIcon('nimbus:notification');

const dataSource = ref<NotificationGroupDefinitionDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const { Lr } = useLocalization();
const { hasAccessByCodes } = useAccess();
const { deserialize } = useLocalizationSerializer();
const { deleteApi, getListApi } = useNotificationGroupDefinitionsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<NotificationGroupDefinitionDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('Notifications.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('Notifications.DisplayName:DisplayName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<NotificationGroupDefinitionDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [NotificationGroupDefinitionModal, groupModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./NotificationGroupDefinitionModal.vue'),
  ),
});
const [NotificationDefinitionModal, defineModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('../notifications/NotificationDefinitionModal.vue'),
  ),
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input);
    pageState.total = items.length;
    dataSource.value = items.map((item) => {
      const localizableString = deserialize(item.displayName);
      return {
        ...item,
        displayName: Lr(localizableString.resourceName, localizableString.name),
      };
    });
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = dataSource.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  groupModalApi.setData({});
  groupModalApi.open();
}

function onUpdate(row: NotificationGroupDefinitionDto) {
  groupModalApi.setData(row);
  groupModalApi.open();
}

function onDelete(row: NotificationGroupDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onMenuClick(row: NotificationGroupDefinitionDto, info: MenuInfo) {
  switch (info.key) {
    case 'definitions': {
      defineModalApi.setData({
        groupName: row.name,
      });
      defineModalApi.open();
      break;
    }
  }
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('Notifications.GroupDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[GroupDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('Notifications.GroupDefinitions:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[GroupDefinitionsPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="!row.isStatic"
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[GroupDefinitionsPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown v-if="!row.isStatic">
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="
                  hasAccessByCodes([NotificationDefinitionsPermissions.Create])
                "
                key="definitions"
                :icon="h(DefinitionIcon)"
              >
                {{ $t('Notifications.NotificationDefinitions:AddNew') }}
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <NotificationGroupDefinitionModal @change="() => onGet()" />
  <NotificationDefinitionModal />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/notifications/definitions/groups/notification-group-definition-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, EllipsisOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getListApi } from "@/api/management/notifications/notification-group-definitions";
import type { NotificationGroupDefinitionDto } from "#/notifications/groups";
import { GroupDefinitionsPermissions, NotificationDefinitionsPermissions } from "@/constants/notifications/permissions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { useLocalizer } from "@/hooks/abp/use-localization";
import { Iconify } from "@/components/icon";

import NotificationGroupDefinitionModal from "./notification-group-definition-modal";
import NotificationDefinitionModal from "../notifications/notification-definition-modal";

const NotificationGroupDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const { deserialize } = localizationSerializer();
	const { Lr } = useLocalizer();
	const [modal, contextHolder] = Modal.useModal();

	// State
	const [groupModalVisible, setGroupModalVisible] = useState(false);
	const [definitionModalVisible, setDefinitionModalVisible] = useState(false);
	const [selectedGroupName, setSelectedGroupName] = useState<string | undefined>();

	const { mutateAsync: deleteGroup } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["notificationGroups"] });
			actionRef.current?.reload();
		},
	});

	const handleCreate = () => {
		setSelectedGroupName(undefined);
		setGroupModalVisible(true);
	};

	const handleUpdate = (row: NotificationGroupDefinitionDto) => {
		setSelectedGroupName(row.name);
		setGroupModalVisible(true);
	};

	const handleDelete = (row: NotificationGroupDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: () => deleteGroup(row.name),
		});
	};

	const handleMenuClick = (key: string, row: NotificationGroupDefinitionDto) => {
		if (key === "definitions") {
			setSelectedGroupName(row.name);
			setDefinitionModalVisible(true);
		}
	};

	const columns: ProColumns<NotificationGroupDefinitionDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("Notifications.DisplayName:Name"),
			dataIndex: "name",
			width: "auto",
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("Notifications.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: "auto",
			sorter: true,
			hideInSearch: true,
			render: (_, record) => {
				const localizableString = deserialize(record.displayName);
				return Lr(localizableString.resourceName, localizableString.name);
			},
		},
		{
			title: $t("AbpUi.Actions"),
			width: 220,
			fixed: "right",
			hideInSearch: true,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[GroupDefinitionsPermissions.Update],
					)}

					{!record.isStatic && (
						<>
							{withAccessChecker(
								<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
									{$t("AbpUi.Delete")}
								</Button>,
								[GroupDefinitionsPermissions.Delete],
							)}
							<Dropdown
								menu={{
									items: [
										hasAccessByCodes([NotificationDefinitionsPermissions.Create])
											? {
													key: "definitions",
													label: $t("Notifications.NotificationDefinitions:AddNew"),
													icon: <Iconify icon="nimbus:notification" />,
													onClick: () => handleMenuClick("definitions", record),
												}
											: null,
									].filter(Boolean) as any,
								}}
							>
								<Button type="link" icon={<EllipsisOutlined />} />
							</Dropdown>
						</>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<NotificationGroupDefinitionDto>
					headerTitle={$t("Notifications.GroupDefinitions")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={{ labelWidth: "auto" }}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("Notifications.GroupDefinitions:AddNew")}
							</Button>,
							[GroupDefinitionsPermissions.Create],
						),
					]}
					request={async (params) => {
						const { current, pageSize, ...filters } = params;
						const { items } = await getListApi({
							filter: filters.filter,
						});

						return {
							data: items,
							total: items.length,
							success: true,
						};
					}}
					pagination={{ defaultPageSize: 10, showSizeChanger: true }}
				/>
			</Card>
			<NotificationGroupDefinitionModal
				visible={groupModalVisible}
				groupName={selectedGroupName}
				onClose={() => setGroupModalVisible(false)}
				onChange={() => actionRef.current?.reload()}
			/>

			<NotificationDefinitionModal
				visible={definitionModalVisible}
				groupName={selectedGroupName}
				onClose={() => setDefinitionModalVisible(false)}
				onChange={() => actionRef.current?.reload()} // Optional refresh
			/>
		</>
	);
};

export default NotificationGroupDefinitionTable;
