// apps/vben5/packages/@abp/localization/src/components/texts/LocalizationTextModal.vue
<script setup lang="ts">
import type { FormInstance } from 'ant-design-vue';

import type { LanguageDto } from '../../types/languages';
import type { ResourceDto } from '../../types/resources';
import type {
  GetTextByKeyInput,
  TextDifferenceDto,
  TextDto,
} from '../../types/texts';

import {
  defineEmits,
  defineOptions,
  onMounted,
  ref,
  toValue,
  useTemplateRef,
} from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Form, Input, message, Select, Textarea } from 'ant-design-vue';

import { useLanguagesApi } from '../../api/useLanguagesApi';
import { useResourcesApi } from '../../api/useResourcesApi';
import { useTextsApi } from '../../api/useTextsApi';

defineOptions({
  name: 'LocalizationTextModal',
});
const emits = defineEmits<{
  (event: 'change', data: TextDto): void;
}>();

const FormItem = Form.Item;

const defaultModel = {} as TextDto;

const isEditModal = ref(false);
const form = useTemplateRef<FormInstance>('form');
const formModel = ref<TextDto>({ ...defaultModel });
const resources = ref<ResourceDto[]>([]);
const languages = ref<LanguageDto[]>([]);

const { getListApi: getLanguagesApi } = useLanguagesApi();
const { getListApi: getResourcesApi } = useResourcesApi();
const { cancel, getApi, setApi } = useTextsApi();

const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('LocalizationTextModal has closed!');
  },
  onConfirm: onSubmit,
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      isEditModal.value = false;
      modalApi.setState({
        title: $t('LocalizationManagement.Text:AddNew'),
      });
      const modalData = modalApi.getData<TextDifferenceDto>();
      formModel.value = { ...modalData };
      await onGet();
    }
  },
  title: $t('LocalizationManagement.Text:AddNew'),
});

async function onInit() {
  const [languageRes, resourceRes] = await Promise.all([
    getLanguagesApi(),
    getResourcesApi(),
  ]);
  languages.value = languageRes.items;
  resources.value = resourceRes.items;
}

async function onGet() {
  const dto = modalApi.getData<TextDifferenceDto>();
  if (dto.targetCultureName) {
    isEditModal.value = true;
    await onLoad({
      cultureName: dto.targetCultureName,
      key: dto.key,
      resourceName: dto.resourceName,
    });
  }
}

async function onLanguageChange(value: string) {
  const dto = modalApi.getData<TextDifferenceDto>();
  if (dto.targetCultureName) {
    await onLoad({
      cultureName: value,
      key: dto.key,
      resourceName: dto.resourceName,
    });
  }
}

async function onLoad(input: GetTextByKeyInput) {
  try {
    modalApi.setState({ loading: true });
    const textDto = await getApi(input);
    formModel.value = textDto;
    modalApi.setState({
      title: `${$t('AbpLocalization.Texts')} - ${textDto.key}`,
    });
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onSubmit() {
  await form.value?.validate();
  try {
    modalApi.setState({ submitting: true });
    const input = toValue(formModel);
    await setApi(input);
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', input);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}

onMounted(onInit);
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <FormItem
        :label="$t('AbpLocalization.DisplayName:CultureName')"
        name="cultureName"
        required
      >
        <Select
          v-model:value="formModel.cultureName"
          :options="languages"
          :field-names="{ label: 'displayName', value: 'cultureName' }"
          @change="(value) => onLanguageChange(value!.toString())"
        />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:ResourceName')"
        name="resourceName"
        required
      >
        <Select
          v-model:value="formModel.resourceName"
          :options="resources"
          :disabled="isEditModal"
          :field-names="{ label: 'displayName', value: 'name' }"
        />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:Key')"
        name="key"
        required
      >
        <Input
          :disabled="isEditModal"
          v-model:value="formModel.key"
          autocomplete="off"
        />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:Value')"
        name="value"
        required
      >
        <Textarea
          :auto-size="{ minRows: 3 }"
          v-model:value="formModel.value"
          autocomplete="off"
        />
      </FormItem>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/localization/texts/localization-text-modal.tsx
import { useEffect, useState } from "react";
import { Modal, Form, Input, Select } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { getApi, setApi } from "@/api/management/localization/texts";
import { getListApi as getLanguagesApi } from "@/api/management/localization/languages";
import { getListApi as getResourcesApi } from "@/api/management/localization/resources";
import type { TextDto, TextDifferenceDto } from "#/management/localization/texts";
import type { LanguageDto } from "#/management/localization/languages";
import type { ResourceDto } from "#/management/localization/resources";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: TextDto) => void;
	data?: TextDifferenceDto; // Data passed from the table row
	defaultTargetCulture?: string; // For creation
	defaultResourceName?: string; // For creation
}

const LocalizationTextModal: React.FC<Props> = ({
	visible,
	onClose,
	onChange,
	data,
	defaultTargetCulture,
	defaultResourceName,
}) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [loading, setLoading] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const [isEdit, setIsEdit] = useState(false);

	// Dropdown Data
	const [languages, setLanguages] = useState<LanguageDto[]>([]);
	const [resources, setResources] = useState<ResourceDto[]>([]);

	// Fetch Options on Mount
	useEffect(() => {
		const initOptions = async () => {
			const [langRes, resRes] = await Promise.all([getLanguagesApi(), getResourcesApi()]);
			setLanguages(langRes.items);
			setResources(resRes.items);
		};
		initOptions();
	}, []);

	// Handle Modal Open State
	useEffect(() => {
		if (visible) {
			form.resetFields();
			if (data?.targetCultureName) {
				// Edit Mode
				setIsEdit(true);
				fetchTextDetails({
					cultureName: data.targetCultureName,
					key: data.key,
					resourceName: data.resourceName,
				});
			} else {
				// Create Mode
				setIsEdit(false);
				form.setFieldsValue({
					cultureName: defaultTargetCulture,
					resourceName: defaultResourceName,
				});
			}
		}
	}, [visible, data, defaultTargetCulture, defaultResourceName, form]);

	const fetchTextDetails = async (input: { cultureName: string; key: string; resourceName: string }) => {
		try {
			setLoading(true);
			const textDto = await getApi(input);
			form.setFieldsValue(textDto);
		} finally {
			setLoading(false);
		}
	};

	// Handle changing culture dropdown inside the modal to switch context
	const handleLanguageChange = async (newCulture: string) => {
		// Only fetch if we have enough info to look up the key
		const currentValues = form.getFieldsValue();
		if (currentValues.key && currentValues.resourceName) {
			await fetchTextDetails({
				cultureName: newCulture,
				key: currentValues.key,
				resourceName: currentValues.resourceName,
			});
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);
			await setApi(values);
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(values);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	return (
		<Modal
			open={visible}
			title={isEdit ? `${$t("AbpLocalization.Texts")} - ${data?.key}` : $t("LocalizationManagement.Text:AddNew")}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			destroyOnClose
			width="50%"
		>
			<Form form={form} layout="vertical">
				<Form.Item
					label={$t("AbpLocalization.DisplayName:CultureName")}
					name="cultureName"
					rules={[{ required: true }]}
				>
					<Select
						showSearch
						optionFilterProp="displayName"
						fieldNames={{ label: "displayName", value: "cultureName" }}
						options={languages}
						onChange={handleLanguageChange}
					/>
				</Form.Item>

				<Form.Item
					label={$t("AbpLocalization.DisplayName:ResourceName")}
					name="resourceName"
					rules={[{ required: true }]}
				>
					<Select
						showSearch
						optionFilterProp="displayName"
						fieldNames={{ label: "displayName", value: "name" }}
						options={resources}
						disabled={isEdit} // Resource is locked when editing a specific key
					/>
				</Form.Item>

				<Form.Item label={$t("AbpLocalization.DisplayName:Key")} name="key" rules={[{ required: true }]}>
					<Input disabled={isEdit} autoComplete="off" />
				</Form.Item>

				<Form.Item label={$t("AbpLocalization.DisplayName:Value")} name="value" rules={[{ required: true }]}>
					<Input.TextArea autoSize={{ minRows: 3 }} autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default LocalizationTextModal;
