// apps/vben5/packages/@abp/text-templating/src/components/definitions/TemplateDefinitionModal.vue
<script setup lang="ts">
import type { ResourceDto } from '@abp/localization';
import type { PropertyInfo } from '@abp/ui';
import type { FormInstance } from 'ant-design-vue';

import type { TextTemplateDefinitionDto } from '../../types';

import { computed, ref, useTemplateRef } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  isNullOrWhiteSpace,
  useAbpStore,
  useLocalization,
  useLocalizationSerializer,
} from '@abp/core';
import { useResourcesApi } from '@abp/localization';
import { LocalizableInput, PropertyTable } from '@abp/ui';
import { Checkbox, Form, Input, message, Select, Tabs } from 'ant-design-vue';

import { useTemplateDefinitionsApi } from '../../api';

defineOptions({
  name: 'TemplateDefinitionModal',
});
const emits = defineEmits<{
  (event: 'change', data: TextTemplateDefinitionDto): void;
}>();

const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

type TabKey = 'basic' | 'properties';

const activeTabKey = ref<TabKey>('basic');
const isEditModel = ref(false);
const form = useTemplateRef<FormInstance>('form');
const formModel = ref<TextTemplateDefinitionDto>();
const textTemplateLayouts = ref<TextTemplateDefinitionDto[]>([]);
const textTemplateResources = ref<ResourceDto[]>([]);

const abpStore = useAbpStore();

const { Lr } = useLocalization();
const { hasAccessByCodes } = useAccess();
const { deserialize } = useLocalizationSerializer();
const { getListApi: getResourcesApi } = useResourcesApi();
const { cancel, createApi, getApi, getListApi, updateApi } =
  useTemplateDefinitionsApi();

const getLanguageOptions = computed(() => {
  const languages = abpStore.application?.localization.languages;
  if (!languages) {
    return [];
  }
  return languages.map((language) => {
    return {
      label: language.displayName,
      value: language.cultureName,
    };
  });
});

const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('TemplateDefinitionModal has closed!');
  },
  onConfirm: async () => {
    await form.value?.validate();
    const api = isEditModel.value
      ? updateApi(formModel.value!.name, formModel.value!)
      : createApi(formModel.value!);
    modalApi.setState({ submitting: true });
    api
      .then((res) => {
        message.success($t('AbpUi.SavedSuccessfully'));
        emits('change', res);
        modalApi.close();
      })
      .finally(() => {
        modalApi.setState({ submitting: false });
      });
  },
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      isEditModel.value = false;
      activeTabKey.value = 'basic';
      formModel.value = undefined;
      await Promise.all([onGet(), onInitLayouts(), onInitResources()]);
    }
  },
  title: $t('AbpTextTemplating.TextTemplates:AddNew'),
});

async function onGet() {
  const { name } = modalApi.getData<TextTemplateDefinitionDto>();
  if (isNullOrWhiteSpace(name)) {
    modalApi.setState({ title: $t('AbpTextTemplating.TextTemplates:AddNew') });
    formModel.value = {
      displayName: '',
      extraProperties: {},
      isInlineLocalized: false,
      isLayout: false,
      isStatic: false,
      name: '',
    };
    return;
  }
  try {
    modalApi.setState({ loading: true });
    formModel.value = await getApi(name);
    modalApi.setState({
      title: `${$t('AbpTextTemplating.TextTemplates')} - ${name}`,
    });
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onInitLayouts() {
  const { items } = await getListApi({
    isLayout: true,
  });
  textTemplateLayouts.value = items.map((item) => {
    const localizableString = deserialize(item.displayName);
    return {
      ...item,
      displayName: Lr(localizableString.resourceName, localizableString.name),
    };
  });
}

async function onInitResources() {
  // TODO: 是否暴露localization、模块常量
  if (!hasAccessByCodes(['LocalizationManagement.Resource'])) {
    return;
  }
  const { items } = await getResourcesApi();
  textTemplateResources.value = items;
}

function onIsInlineLocalizedChange(isInlineLocalized: boolean) {
  if (isInlineLocalized) {
    formModel.value!.localizationResourceName = undefined;
  }
}

function onIsLayoutChange(isLayout: boolean) {
  if (isLayout) {
    formModel.value!.layout = undefined;
  }
}

function onPropChange(prop: PropertyInfo) {
  formModel.value!.extraProperties ??= {};
  formModel.value!.extraProperties[prop.key] = prop.value;
}

function onPropDelete(prop: PropertyInfo) {
  formModel.value!.extraProperties ??= {};
  delete formModel.value!.extraProperties[prop.key];
}
</script>

<template>
  <Modal>
    <Form
      v-if="formModel"
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <Tabs v-model:active-key="activeTabKey">
        <TabPane key="basic" :tab="$t('AbpTextTemplating.BasicInfo')">
          <FormItem
            name="name"
            required
            :label="$t('AbpTextTemplating.DisplayName:Name')"
          >
            <Input
              allow-clear
              autocomplete="off"
              :disabled="!isEditModel || formModel.isStatic"
              v-model:value="formModel.name"
            />
          </FormItem>
          <FormItem
            :label="$t('WebhooksManagement.DisplayName:DisplayName')"
            name="displayName"
            required
          >
            <LocalizableInput
              v-model:value="formModel.displayName"
              :disabled="formModel.isStatic"
            />
          </FormItem>
          <FormItem
            name="isInlineLocalized"
            :label="$t('AbpTextTemplating.DisplayName:IsInlineLocalized')"
          >
            <Checkbox
              :disabled="formModel.isStatic"
              v-model:checked="formModel.isInlineLocalized"
              @change="(e) => onIsInlineLocalizedChange(e.target.checked)"
            >
              {{ $t('AbpTextTemplating.DisplayName:IsInlineLocalized') }}
            </Checkbox>
          </FormItem>
          <FormItem
            v-if="!formModel.isInlineLocalized"
            name="defaultCultureName"
            :label="$t('AbpTextTemplating.DisplayName:DefaultCultureName')"
          >
            <Select
              allow-clear
              :disabled="formModel.isStatic"
              v-model:value="formModel.defaultCultureName"
              :options="getLanguageOptions"
            />
          </FormItem>
          <FormItem
            v-if="formModel.isInlineLocalized"
            name="localizationResourceName"
            :label="$t('AbpTextTemplating.LocalizationResource')"
          >
            <Select
              allow-clear
              :disabled="formModel.isStatic"
              v-model:value="formModel.localizationResourceName"
              :options="textTemplateResources"
              :field-names="{
                label: 'displayName',
                value: 'name',
              }"
            />
          </FormItem>
          <FormItem
            name="isLayout"
            :label="$t('AbpTextTemplating.DisplayName:IsLayout')"
          >
            <Checkbox
              :disabled="formModel.isStatic"
              v-model:checked="formModel.isLayout"
              @change="(e) => onIsLayoutChange(e.target.checked)"
            >
              {{ $t('AbpTextTemplating.DisplayName:IsLayout') }}
            </Checkbox>
          </FormItem>
          <FormItem
            v-if="!formModel.isLayout"
            name="layout"
            :label="$t('AbpTextTemplating.DisplayName:Layout')"
          >
            <Select
              allow-clear
              :disabled="formModel.isStatic"
              v-model:value="formModel.layout"
              :options="textTemplateLayouts"
              :field-names="{
                label: 'displayName',
                value: 'name',
              }"
            />
          </FormItem>
        </TabPane>
        <TabPane key="properties" :tab="$t('AbpTextTemplating.Properties')">
          <PropertyTable
            :data="formModel.extraProperties"
            :disabled="formModel.isStatic"
            @change="onPropChange"
            @delete="onPropDelete"
          />
        </TabPane>
      </Tabs>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/text-templating/template-definition-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, Checkbox, Select, Tabs } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import useAbpStore from "@/store/abpCoreStore";
import { createApi, updateApi, getApi, getListApi } from "@/api/text-templating/template-definitions";
import { getListApi as getResourcesApi } from "@/api/management/localization/resources";
import type { TextTemplateDefinitionDto } from "#/text-templating/definitions";
import type { ResourceDto } from "#/management/localization/resources";
import LocalizableInput from "@/components/abp/localizable-input/localizable-input";
import PropertyTable from "@/components/abp/properties/property-table";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { useLocalizer } from "@/hooks/abp/use-localization";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: TextTemplateDefinitionDto) => void;
	templateName?: string;
}

const TemplateDefinitionModal: React.FC<Props> = ({ visible, onClose, onChange, templateName }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const application = useAbpStore((state) => state.application);
	const { deserialize } = localizationSerializer();
	const { Lr } = useLocalizer();

	const [activeTab, setActiveTab] = useState("basic");
	const [isEdit, setIsEdit] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const [loading, setLoading] = useState(false);
	const [formModel, setFormModel] = useState<Partial<TextTemplateDefinitionDto>>({});

	// Dropdown Options
	const [layouts, setLayouts] = useState<any[]>([]);
	const [resources, setResources] = useState<ResourceDto[]>([]);

	// Derived Options
	const languageOptions = (application?.localization.languages || []).map((l) => ({
		label: l.displayName,
		value: l.cultureName,
	}));

	// Initial Data Fetch
	useEffect(() => {
		if (visible) {
			loadInitialData();
		}
	}, [visible]);

	const loadInitialData = async () => {
		// Load Layouts
		const layoutRes = await getListApi({ isLayout: true });
		const formattedLayouts = layoutRes.items.map((item) => {
			const localizable = deserialize(item.displayName);
			return {
				...item,
				displayName: Lr(localizable.resourceName, localizable.name),
			};
		});
		setLayouts(formattedLayouts);

		// Load Resources if allowed
		if (hasAccessByCodes(["LocalizationManagement.Resource"])) {
			const res = await getResourcesApi();
			setResources(res.items);
		}
	};

	// Load Definition Data
	useEffect(() => {
		if (visible) {
			if (templateName) {
				setIsEdit(true);
				fetchDefinition(templateName);
			} else {
				setIsEdit(false);
				const initial = {
					displayName: "",
					extraProperties: {},
					isInlineLocalized: false,
					isLayout: false,
					isStatic: false,
					name: "",
				};
				setFormModel(initial);
				form.setFieldsValue(initial);
			}
		}
	}, [visible, templateName]);

	const fetchDefinition = async (name: string) => {
		try {
			setLoading(true);
			const dto = await getApi(name);
			setFormModel(dto);
			form.setFieldsValue(dto);
		} finally {
			setLoading(false);
		}
	};

	const handlePropChange = (prop: any) => {
		setFormModel((prev) => ({
			...prev,
			extraProperties: { ...prev.extraProperties, [prop.key]: prop.value },
		}));
	};

	const handlePropDelete = (prop: any) => {
		setFormModel((prev) => {
			const nextProps = { ...prev.extraProperties };
			delete nextProps[prop.key];
			return { ...prev, extraProperties: nextProps };
		});
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);
			const submitData = {
				...formModel,
				...values,
			} as TextTemplateDefinitionDto;

			const api = isEdit ? updateApi(submitData.name, submitData) : createApi(submitData as any);

			const res = await api;
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (e) {
			console.error(e);
		} finally {
			setSubmitting(false);
		}
	};

	return (
		<Modal
			title={
				isEdit
					? `${$t("AbpTextTemplating.TextTemplates")} - ${templateName}`
					: $t("AbpTextTemplating.TextTemplates:AddNew")
			}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			width="50%"
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Tabs activeKey={activeTab} onChange={setActiveTab}>
					<Tabs.TabPane key="basic" tab={$t("AbpTextTemplating.BasicInfo")}>
						<Form.Item name="name" label={$t("AbpTextTemplating.DisplayName:Name")} rules={[{ required: true }]}>
							<Input disabled={!isEdit && formModel.isStatic} autoComplete="off" />
						</Form.Item>

						<Form.Item
							name="displayName"
							label={$t("WebhooksManagement.DisplayName:DisplayName")}
							rules={[{ required: true }]}
						>
							<LocalizableInput disabled={formModel.isStatic} />
						</Form.Item>

						<Form.Item name="isInlineLocalized" valuePropName="checked">
							<Checkbox
								disabled={formModel.isStatic}
								onChange={(e) => {
									// Logic from Vue: if inline localized, clear resource name
									if (e.target.checked) {
										form.setFieldValue("localizationResourceName", undefined);
									}
								}}
							>
								{$t("AbpTextTemplating.DisplayName:IsInlineLocalized")}
							</Checkbox>
						</Form.Item>

						<Form.Item noStyle shouldUpdate={(prev, curr) => prev.isInlineLocalized !== curr.isInlineLocalized}>
							{({ getFieldValue }) =>
								!getFieldValue("isInlineLocalized") ? (
									<Form.Item name="defaultCultureName" label={$t("AbpTextTemplating.DisplayName:DefaultCultureName")}>
										<Select allowClear options={languageOptions} disabled={formModel.isStatic} />
									</Form.Item>
								) : (
									<Form.Item name="localizationResourceName" label={$t("AbpTextTemplating.LocalizationResource")}>
										<Select
											allowClear
											options={resources}
											fieldNames={{ label: "displayName", value: "name" }}
											disabled={formModel.isStatic}
										/>
									</Form.Item>
								)
							}
						</Form.Item>

						<Form.Item name="isLayout" valuePropName="checked">
							<Checkbox
								disabled={formModel.isStatic}
								onChange={(e) => {
									if (e.target.checked) {
										form.setFieldValue("layout", undefined);
									}
								}}
							>
								{$t("AbpTextTemplating.DisplayName:IsLayout")}
							</Checkbox>
						</Form.Item>

						<Form.Item noStyle shouldUpdate={(prev, curr) => prev.isLayout !== curr.isLayout}>
							{({ getFieldValue }) =>
								!getFieldValue("isLayout") && (
									<Form.Item name="layout" label={$t("AbpTextTemplating.DisplayName:Layout")}>
										<Select
											allowClear
											options={layouts}
											fieldNames={{ label: "displayName", value: "name" }}
											disabled={formModel.isStatic}
										/>
									</Form.Item>
								)
							}
						</Form.Item>
					</Tabs.TabPane>

					<Tabs.TabPane key="properties" tab={$t("AbpTextTemplating.Properties")}>
						<PropertyTable
							data={formModel.extraProperties}
							disabled={formModel.isStatic}
							onChange={handlePropChange}
							onDelete={handlePropDelete}
						/>
					</Tabs.TabPane>
				</Tabs>
			</Form>
		</Modal>
	);
};

export default TemplateDefinitionModal;
