// apps/vben5/packages/@abp/text-templating/src/components/definitions/TemplateContentModal.vue
<script setup lang="ts">
import type {
  TextTemplateContentDto,
  TextTemplateDefinitionDto,
} from '../../types';

import { computed, defineAsyncComponent, ref } from 'vue';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { MarkdownViewer } from '@abp/components/vditor';
import { useAbpStore } from '@abp/core';
import {
  Alert,
  Modal as AntdvModal,
  Button,
  Card,
  message,
} from 'ant-design-vue';

import { useTemplateContentsApi } from '../../api/useTemplateContentsApi';

const emits = defineEmits<{
  (event: 'change', data: TextTemplateContentDto): void;
}>();

const { cancel, getApi, restoreToDefaultApi, updateApi } =
  useTemplateContentsApi();

const abpStore = useAbpStore();
const textTemplate = ref<TextTemplateDefinitionDto>();

const getCardTitle = computed(() => {
  if (!textTemplate.value) {
    return '';
  }
  return `${$t('AbpTextTemplating.DisplayName:Name')} - ${textTemplate.value.name}`;
});

const [Form, formApi] = useVbenForm({
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  layout: 'vertical',
  schema: [
    {
      component: 'Textarea',
      componentProps: {
        autoSize: {
          minRows: 20,
        },
        showCount: true,
      },
      fieldName: 'content',
      label: $t('AbpTextTemplating.DisplayName:Content'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  confirmText: $t('AbpTextTemplating.SaveContent'),
  fullscreen: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('TemplateDefinitionModal has closed!');
  },
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  onOpenChange: async (isOpen: boolean) => {
    textTemplate.value = undefined;
    if (isOpen) {
      const textTemplateDefine = modalApi.getData<TextTemplateDefinitionDto>();
      textTemplate.value = textTemplateDefine;
      await onGet();
    }
  },
});
const [TemplateContentCurtuleModal, curtuleModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./TemplateContentCurtuleModal.vue'),
  ),
});

async function onGet() {
  try {
    modalApi.setState({ loading: true });
    const textTemplateDefine = modalApi.getData<TextTemplateDefinitionDto>();
    const culture = textTemplateDefine.isInlineLocalized
      ? undefined
      : abpStore.application?.localization.currentCulture.cultureName;
    const dto = await getApi({ culture, name: textTemplateDefine.name });
    formApi.setFieldValue('content', dto.content);
  } finally {
    modalApi.setState({ loading: false });
  }
}

function onRestoreToDefault() {
  AntdvModal.confirm({
    centered: true,
    content: $t('AbpTextTemplating.RestoreToDefaultMessage'),
    onOk: async () => {
      await restoreToDefaultApi(textTemplate.value!.name, {});
      message.success($t('AbpTextTemplating.TemplateContentRestoredToDefault'));
      await onGet();
    },
    title: $t('AbpTextTemplating.RestoreToDefault'),
  });
}

function onCustomizePerCulture() {
  curtuleModalApi.setData(textTemplate.value);
  curtuleModalApi.open();
}

async function onSubmit(values: Record<string, string>) {
  try {
    modalApi.setState({ submitting: true });
    const textTemplateDefine = modalApi.getData<TextTemplateDefinitionDto>();
    const culture = textTemplateDefine.isInlineLocalized
      ? undefined
      : abpStore.application?.localization.currentCulture.cultureName;
    const dto = await updateApi(textTemplateDefine.name, {
      content: values.content!,
      culture,
    });
    emits('change', dto);
    message.success($t('AbpTextTemplating.TemplateContentUpdated'));
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="$t('AbpTextTemplating.EditContents')">
    <Alert v-if="textTemplate?.isInlineLocalized" type="warning">
      <template #message>
        <MarkdownViewer
          :value="$t('AbpTextTemplating.InlineContentDescription')" />
      </template>
    </Alert>
    <Card :title="getCardTitle">
      <template #extra>
        <div class="flex flex-row gap-2">
          <Button danger type="primary" @click="onRestoreToDefault">
            {{ $t('AbpTextTemplating.RestoreToDefault') }}
          </Button>
          <Button type="dashed" @click="onCustomizePerCulture">
            {{ $t('AbpTextTemplating.CustomizePerCulture') }}
          </Button>
        </div>
      </template>
      <Form />
    </Card>
    <TemplateContentCurtuleModal :title="getCardTitle" />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/text-templating/template-content-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, Button, Card, Alert, Space } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown"; // Used for MarkdownViewer replacement
import useAbpStore from "@/store/abpCoreStore";
import { getApi, restoreToDefaultApi, updateApi } from "@/api/text-templating/template-contents";
import type { TextTemplateContentDto } from "#/text-templating/contents";
import type { TextTemplateDefinitionDto } from "#/text-templating/definitions";
import TemplateContentCurtuleModal from "./template-content-curtule-modal";

interface Props {
	visible: boolean;
	onClose: () => void;
	templateDefinition?: TextTemplateDefinitionDto;
	onChange?: (data: TextTemplateContentDto) => void;
}

const TemplateContentModal: React.FC<Props> = ({ visible, onClose, templateDefinition, onChange }) => {
	const { t: $t } = useTranslation();
	const application = useAbpStore((state) => state.application);
	const [form] = Form.useForm();

	const [modal, contextHolder] = Modal.useModal();
	const [submitting, setSubmitting] = useState(false);
	const [loading, setLoading] = useState(false);
	const [curtuleModalVisible, setCurtuleModalVisible] = useState(false);

	useEffect(() => {
		if (visible && templateDefinition) {
			fetchContent();
		}
	}, [visible, templateDefinition]);

	const fetchContent = async () => {
		if (!templateDefinition) return;
		try {
			setLoading(true);
			const culture = templateDefinition.isInlineLocalized
				? undefined
				: application?.localization.currentCulture.cultureName;

			const dto = await getApi({
				name: templateDefinition.name,
				culture,
			});
			form.setFieldsValue({ content: dto.content });
		} finally {
			setLoading(false);
		}
	};

	const handleSave = async () => {
		if (!templateDefinition) return;
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const culture = templateDefinition.isInlineLocalized
				? undefined
				: application?.localization.currentCulture.cultureName;

			const dto = await updateApi(templateDefinition.name, {
				content: values.content,
				culture,
			});

			toast.success($t("AbpTextTemplating.TemplateContentUpdated"));
			onChange?.(dto);
			onClose();
		} catch (e) {
			console.error(e);
		} finally {
			setSubmitting(false);
		}
	};

	const handleRestore = () => {
		if (!templateDefinition) return;
		modal.confirm({
			title: $t("AbpTextTemplating.RestoreToDefault"),
			content: $t("AbpTextTemplating.RestoreToDefaultMessage"),
			onOk: async () => {
				await restoreToDefaultApi(templateDefinition.name, {});
				toast.success($t("AbpTextTemplating.TemplateContentRestoredToDefault"));
				fetchContent();
			},
		});
	};

	const cardTitle = templateDefinition
		? `${$t("AbpTextTemplating.DisplayName:Name")} - ${templateDefinition.name}`
		: "";

	return (
		<>
			{contextHolder}
			<Modal
				title={$t("AbpTextTemplating.EditContents")}
				open={visible}
				onCancel={onClose}
				onOk={handleSave}
				confirmLoading={submitting}
				width="80%"
				style={{ top: 20 }}
				okText={$t("AbpTextTemplating.SaveContent")}
				destroyOnClose
			>
				{templateDefinition?.isInlineLocalized && (
					<Alert
						type="warning"
						className="mb-4"
						message={<ReactMarkdown>{$t("AbpTextTemplating.InlineContentDescription")}</ReactMarkdown>}
					/>
				)}

				<Card
					title={cardTitle}
					loading={loading}
					extra={
						<Space>
							<Button danger type="primary" onClick={handleRestore}>
								{$t("AbpTextTemplating.RestoreToDefault")}
							</Button>
							<Button onClick={() => setCurtuleModalVisible(true)}>
								{$t("AbpTextTemplating.CustomizePerCulture")}
							</Button>
						</Space>
					}
				>
					<Form form={form} layout="vertical">
						<Form.Item name="content" label={$t("AbpTextTemplating.DisplayName:Content")} rules={[{ required: true }]}>
							<Input.TextArea autoSize={{ minRows: 20 }} showCount />
						</Form.Item>
					</Form>
				</Card>
			</Modal>

			<TemplateContentCurtuleModal
				visible={curtuleModalVisible}
				onClose={() => setCurtuleModalVisible(false)}
				templateDefinition={templateDefinition}
				onChange={(data) => {
					// If data changed in sub-modal, refresh current modal content
					fetchContent();
					onChange?.(data);
				}}
			/>
		</>
	);
};

export default TemplateContentModal;
