// apps/vben5/packages/@abp/settings/src/components/settings/UserSetting.vue
<script setup lang="ts">
import type { SettingsUpdateInput } from '../../types';

import { getUserSettingsApi, setUserSettingsApi } from '../../api/settings';
import SettingForm from './SettingForm.vue';

defineOptions({
  name: 'UserSettingForm',
});

async function onGet() {
  const { items } = await getUserSettingsApi();
  return items;
}

async function onSubmit(input: SettingsUpdateInput) {
  await setUserSettingsApi(input);
}
</script>

<template>
  <SettingForm :get-api="onGet" :submit-api="onSubmit" />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/settings/settings/user-setting.tsx
import type { SettingsUpdateInput } from "#/management/settings/settings";
import { getUserSettingsApi, setUserSettingsApi } from "@/api/management/settings/settings";
import SettingForm from "./setting-form";

const UserSetting: React.FC = () => {
	const handleGet = async () => {
		const { items } = await getUserSettingsApi();
		return items;
	};

	const handleSubmit = async (input: SettingsUpdateInput) => {
		await setUserSettingsApi(input);
	};

	return <SettingForm getApi={handleGet} submitApi={handleSubmit} onChange={() => {}} />;
};

export default UserSetting;
