// apps/react-admin/src/pages/saas/tenants/tenant-modal.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Modal, Form, Input, Select, Checkbox, DatePicker, Tabs, Row, Col } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import dayjs from "dayjs";
import { createApi, updateApi, getApi, checkConnectionString } from "@/api/saas/tenants";
import { getPagedListApi as getEditionsApi } from "@/api/saas/editions";
import type { TenantDto, TenantConnectionStringDto, TenantCreateDto } from "#/saas/tenants";
import type { EditionDto } from "#/saas/editions";
import TenantConnectionStringsList from "./tenant-connection-strings-list";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: TenantDto) => void;
	tenantId?: string;
	dataBaseOptions: { label: string; value: string }[];
}

const TenantModal: React.FC<Props> = ({ visible, onClose, onChange, tenantId, dataBaseOptions }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	const [activeTab, setActiveTab] = useState("basic");
	const [loading, setLoading] = useState(false);
	const [submitting, setSubmitting] = useState(false);

	const [editions, setEditions] = useState<EditionDto[]>([]);
	// Local state for connection strings when creating a new tenant
	const [localConnectionStrings, setLocalConnectionStrings] = useState<TenantConnectionStringDto[]>([]);

	useEffect(() => {
		if (visible) {
			setActiveTab("basic");
			form.resetFields();
			setLocalConnectionStrings([]);
			fetchEditions();

			if (tenantId) {
				fetchTenant(tenantId);
			} else {
				form.setFieldsValue({
					isActive: true,
					useSharedDatabase: true,
				});
			}
		}
	}, [visible, tenantId]);

	const fetchTenant = async (id: string) => {
		try {
			setLoading(true);
			const dto = await getApi(id);
			form.setFieldsValue({
				...dto,
				enableTime: dto.enableTime ? dayjs(dto.enableTime) : null,
				disableTime: dto.disableTime ? dayjs(dto.disableTime) : null,
			});
		} finally {
			setLoading(false);
		}
	};

	const fetchEditions = async () => {
		const { items } = await getEditionsApi({ maxResultCount: 100 });
		setEditions(items);
	};

	const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const name = e.target.value;
		// Auto-fill admin email if creating and email not manually modified (simplified logic)
		if (!tenantId) {
			const currentEmail = form.getFieldValue("adminEmailAddress");
			if (!currentEmail || currentEmail.includes("@")) {
				form.setFieldValue("adminEmailAddress", `admin@${name || "domain"}.com`);
			}
		}
	};

	const handleLocalConnectionAdd = async (data: TenantConnectionStringDto) => {
		setLocalConnectionStrings((prev) => {
			const exists = prev.find((x) => x.name === data.name);
			if (exists) {
				return prev.map((x) => (x.name === data.name ? { ...x, value: data.value } : x));
			}
			return [...prev, data];
		});
	};

	const handleLocalConnectionDelete = async (data: TenantConnectionStringDto) => {
		setLocalConnectionStrings((prev) => prev.filter((x) => x.name !== data.name));
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			// Check default connection string if not shared
			if (!tenantId && !values.useSharedDatabase) {
				await checkConnectionString({
					connectionString: values.defaultConnectionString,
					provider: values.provider,
				});
			}

			const submitData = {
				...values,
				enableTime: values.enableTime ? values.enableTime.format("YYYY-MM-DD") : null,
				disableTime: values.disableTime ? values.disableTime.format("YYYY-MM-DD") : null,
			};

			// Add local connection strings if creating
			if (!tenantId) {
				(submitData as TenantCreateDto).connectionStrings = localConnectionStrings;
			}

			const api = tenantId ? updateApi(tenantId, submitData) : createApi(submitData);

			const res = await api;
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (e) {
			console.error(e);
		} finally {
			setSubmitting(false);
		}
	};

	// Watch for useSharedDatabase to conditionally render tab content
	const useSharedDatabase = Form.useWatch("useSharedDatabase", form);

	return (
		<Modal
			title={tenantId ? `${$t("AbpSaas.Tenants")} - ${form.getFieldValue("name") || ""}` : $t("AbpSaas.NewTenant")}
			open={visible}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			width={600}
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item name="isActive" valuePropName="checked">
					<Checkbox>{$t("AbpSaas.DisplayName:IsActive")}</Checkbox>
				</Form.Item>

				<Form.Item name="name" label={$t("AbpSaas.DisplayName:TenantName")} rules={[{ required: true }]}>
					<Input autoComplete="off" onChange={handleNameChange} />
				</Form.Item>

				{!tenantId && (
					<>
						<Form.Item
							name="adminEmailAddress"
							label={$t("AbpSaas.DisplayName:AdminEmailAddress")}
							rules={[{ required: true, type: "email" }]}
						>
							<Input autoComplete="off" />
						</Form.Item>
						<Form.Item
							name="adminPassword"
							label={$t("AbpSaas.DisplayName:AdminPassword")}
							rules={[{ required: true }]}
						>
							<Input.Password autoComplete="off" />
						</Form.Item>
					</>
				)}

				<Form.Item name="editionId" label={$t("AbpSaas.DisplayName:EditionName")}>
					<Select
						allowClear
						showSearch
						optionFilterProp="label"
						options={editions.map((e) => ({ label: e.displayName, value: e.id }))}
					/>
				</Form.Item>

				<Row gutter={16}>
					<Col span={12}>
						<Form.Item name="enableTime" label={$t("AbpSaas.DisplayName:EnableTime")}>
							<DatePicker className="w-full" />
						</Form.Item>
					</Col>
					<Col span={12}>
						<Form.Item name="disableTime" label={$t("AbpSaas.DisplayName:DisableTime")}>
							<DatePicker className="w-full" />
						</Form.Item>
					</Col>
				</Row>

				{!tenantId && (
					<Form.Item name="useSharedDatabase" valuePropName="checked">
						<Checkbox>{$t("AbpSaas.DisplayName:UseSharedDatabase")}</Checkbox>
					</Form.Item>
				)}

				{/* Dedicated Database Configuration Section */}
				{!tenantId && !useSharedDatabase && (
					<div className="border p-4 rounded mb-4 bg-gray-50">
						<Form.Item name="provider" label={$t("AbpSaas.DisplayName:DataBaseProvider")}>
							<Select options={dataBaseOptions} />
						</Form.Item>
						<Form.Item name="defaultConnectionString" label={$t("AbpSaas.DisplayName:DefaultConnectionString")}>
							<Input.TextArea autoSize={{ minRows: 2 }} />
						</Form.Item>

						<div className="mt-4">
							<h4>{$t("AbpSaas.ConnectionStrings")}</h4>
							<TenantConnectionStringsList
								data={localConnectionStrings}
								dataBaseOptions={dataBaseOptions}
								onAdd={handleLocalConnectionAdd}
								onDelete={handleLocalConnectionDelete}
							/>
						</div>
					</div>
				)}
			</Form>
		</Modal>
	);
};

export default TenantModal;

// apps/vben5/packages/@abp/saas/src/components/tenants/TenantModal.vue
<script setup lang="ts">
import type { FormExpose } from 'ant-design-vue/es/form/Form';

import type { EditionDto } from '../../types';
import type {
  TenantConnectionStringDto,
  TenantCreateDto,
  TenantDto,
  TenantUpdateDto,
} from '../../types/tenants';

import { computed, onMounted, ref, useTemplateRef } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useValidation } from '@abp/core';
import {
  Checkbox,
  DatePicker,
  Form,
  Input,
  InputPassword,
  message,
  Select,
  Textarea,
} from 'ant-design-vue';
import dayjs from 'dayjs';
import debounce from 'lodash.debounce';

import { useEditionsApi } from '../../api/useEditionsApi';
import { useTenantsApi } from '../../api/useTenantsApi';
import ConnectionStringTable from './ConnectionStringTable.vue';

defineProps<{
  dataBaseOptions: { label: string; value: string }[];
}>();
const emits = defineEmits<{
  (event: 'change', val: TenantDto): void;
}>();
const FormItem = Form.Item;

const defaultModel = {
  connectionStrings: [],
  isActive: true,
  useSharedDatabase: true,
} as unknown as TenantDto;

const { fieldDoNotValidEmailAddress, fieldRequired } = useValidation();
const form = useTemplateRef<FormExpose>('form');
const tenant = ref({ ...defaultModel });
const editions = ref<EditionDto[]>([]);
const activeTabKey = ref('basic');

const getFormRules = computed(() => {
  return {
    adminEmailAddress: [
      ...fieldRequired({
        name: 'AdminEmailAddress',
        prefix: 'DisplayName',
        resourceName: 'AbpSaas',
      }),
      ...fieldDoNotValidEmailAddress({
        name: 'AdminEmailAddress',
        prefix: 'DisplayName',
        resourceName: 'AbpSaas',
      }),
    ],
    adminPassword: fieldRequired({
      name: 'AdminPassword',
      prefix: 'DisplayName',
      resourceName: 'AbpSaas',
    }),
    defaultConnectionString: fieldRequired({
      name: 'DefaultConnectionString',
      prefix: 'DisplayName',
      resourceName: 'AbpSaas',
    }),
    name: fieldRequired({
      name: 'TenantName',
      prefix: 'DisplayName',
      resourceName: 'AbpSaas',
    }),
    provider: fieldRequired({
      name: 'DataBaseProvider',
      prefix: 'DisplayName',
      resourceName: 'AbpSaas',
    }),
  };
});
/** 启用时间不可晚于禁用时间 */
const getDisabledEnableTime = (current: dayjs.Dayjs) => {
  if (!tenant.value.disableTime) {
    return false;
  }
  return (
    current &&
    current > dayjs(tenant.value.disableTime).add(-1, 'day').endOf('day')
  );
};
/** 禁用时间不可早于启用时间 */
const getDisabledDisableTime = (current: dayjs.Dayjs) => {
  if (!tenant.value.enableTime) {
    return false;
  }
  return current && current < dayjs(tenant.value.enableTime).endOf('day');
};

const { cancel, checkConnectionString, createApi, getApi, updateApi } =
  useTenantsApi();
const { getPagedListApi: getEditions } = useEditionsApi();

const [Modal, modalApi] = useVbenModal({
  class: 'w-[600px]',
  onClosed: cancel,
  async onConfirm() {
    await form.value?.validate();
    await onSubmit();
  },
  async onOpenChange(isOpen) {
    activeTabKey.value = 'basic';
    if (isOpen) {
      await onGet();
    }
  },
  title: $t('AbpSaas.Tenants'),
});

async function onGet() {
  const { id } = modalApi.getData<TenantDto>();
  if (!id) {
    tenant.value = { ...defaultModel };
    modalApi.setState({ title: $t('AbpSaas.NewTenant') });
    return;
  }
  try {
    modalApi.setState({ loading: true });
    const editionDto = await getApi(id);
    modalApi.setState({
      title: `${$t('AbpSaas.Tenants')} - ${editionDto.name}`,
    });
    tenant.value = editionDto;
  } finally {
    modalApi.setState({ loading: false });
  }
}

async function onSubmit() {
  try {
    modalApi.setState({ submitting: true });
    if (!tenant.value.id && !tenant.value.useSharedDatabase) {
      await checkConnectionString({
        connectionString: tenant.value.defaultConnectionString,
        provider: tenant.value.provider,
      });
    }
    const api = tenant.value.id
      ? updateApi(tenant.value.id, tenant.value as TenantUpdateDto)
      : createApi(tenant.value as unknown as TenantCreateDto);
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}

function onNameChange(name?: string) {
  if (
    !tenant.value.id &&
    (!tenant.value.adminEmailAddress ||
      !tenant.value.adminEmailAddress?.endsWith(`@${name}.com`))
  ) {
    tenant.value.adminEmailAddress = `admin@${name}.com`;
  }
  form.value?.clearValidate('adminEmailAddress');
}

function onConnectionChange(data: TenantConnectionStringDto) {
  return new Promise<void>((resolve) => {
    tenant.value.connectionStrings ??= [];
    let connectionString = tenant.value.connectionStrings.find(
      (x: TenantConnectionStringDto) => x.name === data.name,
    );
    if (connectionString) {
      connectionString.value = data.value;
    } else {
      connectionString = data;
      tenant.value.connectionStrings = [
        ...tenant.value.connectionStrings,
        data,
      ];
    }
    resolve();
  });
}

function onConnectionDelete(data: TenantConnectionStringDto) {
  return new Promise<void>((resolve) => {
    tenant.value.connectionStrings ??= [];
    tenant.value.connectionStrings = tenant.value.connectionStrings.filter(
      (x: TenantConnectionStringDto) => x.name !== data.name,
    );
    resolve();
  });
}

const onSearchEditions = debounce(async (filter?: string) => {
  const { items } = await getEditions({ filter });
  editions.value = items;
}, 500);

onMounted(onSearchEditions);
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :model="tenant"
      :label-col="{ span: 6 }"
      :wapper-col="{ span: 18 }"
      :rules="getFormRules"
    >
      <FormItem name="isActive" :label="$t('AbpSaas.DisplayName:IsActive')">
        <Checkbox v-model:checked="tenant.isActive">
          {{ $t('AbpSaas.DisplayName:IsActive') }}
        </Checkbox>
      </FormItem>
      <FormItem name="name" :label="$t('AbpSaas.DisplayName:TenantName')">
        <Input
          v-model:value="tenant.name"
          @change="(e) => onNameChange(e.target.value)"
          autocomplete="off"
        />
      </FormItem>
      <FormItem
        v-if="!tenant.id"
        name="adminEmailAddress"
        :label="$t('AbpSaas.DisplayName:AdminEmailAddress')"
        :label-col="{ span: 8 }"
        :wapper-col="{ span: 16 }"
      >
        <Input
          type="email"
          v-model:value="tenant.adminEmailAddress"
          autocomplete="off"
        />
      </FormItem>
      <FormItem
        v-if="!tenant.id"
        name="adminPassword"
        :label="$t('AbpSaas.DisplayName:AdminPassword')"
      >
        <InputPassword
          v-model:value="tenant.adminPassword"
          autocomplete="off"
        />
      </FormItem>
      <FormItem name="editionId" :label="$t('AbpSaas.DisplayName:EditionName')">
        <Select
          :options="editions"
          :field-names="{ label: 'displayName', value: 'id' }"
          v-model:value="tenant.editionId"
          allow-clear
          show-search
          :filter-option="false"
          @search="onSearchEditions"
        />
      </FormItem>
      <FormItem name="enableTime" :label="$t('AbpSaas.DisplayName:EnableTime')">
        <DatePicker
          class="w-full"
          value-format="YYYY-MM-DD"
          :disabled-date="getDisabledEnableTime"
          v-model:value="tenant.enableTime"
        />
      </FormItem>
      <FormItem
        name="disableTime"
        :label="$t('AbpSaas.DisplayName:DisableTime')"
      >
        <DatePicker
          class="w-full"
          value-format="YYYY-MM-DD"
          :disabled-date="getDisabledDisableTime"
          v-model:value="tenant.disableTime"
        />
      </FormItem>
      <FormItem
        v-if="!tenant.id"
        name="useSharedDatabase"
        :label="$t('AbpSaas.DisplayName:UseSharedDatabase')"
      >
        <Checkbox v-model:checked="tenant.useSharedDatabase">
          {{ $t('AbpSaas.DisplayName:UseSharedDatabase') }}
        </Checkbox>
      </FormItem>
      <template v-if="!tenant.id && !tenant.useSharedDatabase">
        <FormItem
          name="provider"
          :label="$t('AbpSaas.DisplayName:DataBaseProvider')"
        >
          <Select :options="dataBaseOptions" v-model:value="tenant.provider" />
        </FormItem>
        <FormItem
          name="defaultConnectionString"
          :label="$t('AbpSaas.DisplayName:DefaultConnectionString')"
        >
          <Textarea
            :auto-size="{ minRows: 2 }"
            v-model:value="tenant.defaultConnectionString"
          />
        </FormItem>
        <ConnectionStringTable
          :data-base-options="dataBaseOptions"
          :connection-strings="tenant.connectionStrings"
          :submit="onConnectionChange"
          :delete="onConnectionDelete"
        />
      </template>
    </Form>
  </Modal>
</template>

<style scoped></style>
