// apps/vben5/packages/@abp/auditing/src/components/entity-changes/EntityChangeTable.vue
<script setup lang="ts">
import type { VxeGridDefines, VxeGridPropTypes } from 'vxe-table';

import type {
  EntityChangeDto,
  PropertyChange,
} from '../../types/entity-changes';

import { computed, reactive, watchEffect } from 'vue';

import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { Tag } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

import { useAuditlogs } from '../../hooks/useAuditlogs';

defineOptions({
  name: 'EntityChangeTable',
});

const props = defineProps<{
  data: EntityChangeDto[];
  showUserName?: boolean;
}>();

const { getChangeTypeColor, getChangeTypeValue } = useAuditlogs();

/** 实体变更表格分页配置 */
const pagerConfig = reactive<VxeGridPropTypes.PagerConfig>({
  currentPage: 1,
  pageSize: 10,
  pageSizes: [10, 25, 50, 100],
  total: 0,
});
/** 实体变更表格数据列配置 */
const columnsConfig = reactive<VxeGridPropTypes.Columns<EntityChangeDto>>([
  {
    align: 'left',
    field: 'propertyChanges',
    slots: {
      content: 'changes',
    },
    type: 'expand',
  },
  {
    align: 'left',
    field: 'userName',
    title: $t('AbpAuditLogging.UserName'),
    visible: props.showUserName,
    width: 100,
  },
  {
    align: 'center',
    field: 'changeType',
    slots: { default: 'type' },
    sortable: true,
    title: $t('AbpAuditLogging.ChangeType'),
    width: 100,
  },
  {
    align: 'left',
    field: 'changeTime',
    formatter: ({ cellValue }) => {
      return cellValue ? formatToDateTime(cellValue) : cellValue;
    },
    sortable: true,
    title: $t('AbpAuditLogging.StartTime'),
    width: 200,
  },
  {
    align: 'left',
    field: 'entityTypeFullName',
    sortable: true,
    title: $t('AbpAuditLogging.EntityTypeFullName'),
    width: 'auto',
  },
  {
    align: 'left',
    field: 'entityId',
    sortable: true,
    title: $t('AbpAuditLogging.EntityId'),
    width: 280,
  },
  {
    align: 'left',
    field: 'entityTenantId',
    sortable: true,
    title: $t('AbpAuditLogging.TenantId'),
    width: 280,
  },
]);
/** 属性变更表格数据列配置 */
const subColumnsConfig = reactive<VxeGridPropTypes.Columns<PropertyChange>>([
  {
    align: 'left',
    field: 'propertyName',
    sortable: true,
    title: $t('AbpAuditLogging.PropertyName'),
    width: 120,
  },
  {
    align: 'left',
    className: 'font-medium text-green-600',
    field: 'newValue',
    sortable: true,
    title: $t('AbpAuditLogging.NewValue'),
    width: 200,
  },
  {
    align: 'left',
    className: 'font-medium text-red-600',
    field: 'originalValue',
    sortable: true,
    title: $t('AbpAuditLogging.OriginalValue'),
    width: 200,
  },
  {
    align: 'left',
    field: 'propertyTypeFullName',
    sortable: true,
    title: $t('AbpAuditLogging.PropertyTypeFullName'),
    width: 220,
  },
]);
/** 实体变更表格数据源(计算分页) */
const getEntityChanges = computed(() => {
  const entityChanges = props.data ?? [];
  const current = pagerConfig.currentPage ?? 1;
  const pageSize = pagerConfig.pageSize ?? 10;
  return entityChanges.slice((current - 1) * pageSize, pageSize * current);
});
/** 页码变更事件 */
function onPageChange(
  params: VxeGridDefines.PageChangeEventParams<EntityChangeDto>,
) {
  pagerConfig.currentPage = params.currentPage;
  pagerConfig.pageSize = params.pageSize;
}
watchEffect(() => {
  pagerConfig.total = props.data.length;
});
</script>

<template>
  <VxeGrid
    :columns="columnsConfig"
    :data="getEntityChanges"
    :expand-config="{
      padding: true,
    }"
    :pager-config="pagerConfig"
    @page-change="onPageChange"
  >
    <template #type="{ row }">
      <Tag :color="getChangeTypeColor(row.changeType)">
        {{ getChangeTypeValue(row.changeType) }}
      </Tag>
    </template>
    <template #changes="{ row }">
      <VxeGrid
        :border="true"
        :columns="subColumnsConfig"
        :data="row.propertyChanges"
      />
    </template>
  </VxeGrid>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/auditing/entity-change-table.tsx
import { formatToDateTime } from "@/utils/abp";
import { useTranslation } from "react-i18next";
import type { EntityChangeDto, PropertyChange, ChangeType } from "#/management/auditing/entity-changes";
import { Tag, Table, Card } from "antd";
import type { ColumnsType } from "antd/es/table";
import { useState, useMemo } from "react";
import { useAuditLogs } from "@/hooks/abp/auditing/use-audit-logs";
import Scrollbar from "@/components/scrollbar";

interface EntityChangeTableProps {
	data: EntityChangeDto[];
	showUserName?: boolean;
}

export const EntityChangeTable: React.FC<EntityChangeTableProps> = ({ data, showUserName = false }) => {
	const [pageSize, setPageSize] = useState(10);
	const [current, setCurrent] = useState(1);
	const { t } = useTranslation();
	const { getChangeTypeColor, getChangeTypeValue } = useAuditLogs();

	const columns: ColumnsType<EntityChangeDto> = [
		showUserName && {
			title: t("AbpAuditLogging.UserName"),
			dataIndex: "userName",
			align: "center",
			width: 100, // 设置列宽
		},
		{
			title: t("AbpAuditLogging.ChangeType"),
			dataIndex: "changeType",
			sorter: true,
			align: "center",
			width: 120, // 设置列宽
			render: (type: ChangeType) => <Tag color={getChangeTypeColor(type)}>{getChangeTypeValue(type)}</Tag>,
		},
		{
			title: t("AbpAuditLogging.StartTime"),
			dataIndex: "changeTime",
			sorter: true,
			width: 200, // 设置列宽
			render: (value: Date) => value && formatToDateTime(value),
		},
		{
			title: t("AbpAuditLogging.EntityTypeFullName"),
			dataIndex: "entityTypeFullName",
			ellipsis: true,
			sorter: true,
			width: 400, // 设置列宽
		},
		{
			title: t("AbpAuditLogging.EntityId"),
			dataIndex: "entityId",
			sorter: true,
			width: 312, // 设置列宽
		},
		{
			title: t("AbpAuditLogging.TenantId"),
			dataIndex: "entityTenantId",
			sorter: true,
			width: 312, // 设置列宽
		},
	].filter(Boolean) as ColumnsType<EntityChangeDto>;

	const propertyColumns: ColumnsType<PropertyChange> = [
		{
			title: t("AbpAuditLogging.PropertyName"),
			dataIndex: "propertyName",
			sorter: true,
			width: 150, // 设置列宽
		},
		{
			title: t("AbpAuditLogging.NewValue"),
			dataIndex: "newValue",
			sorter: true,
			className: "font-medium text-success",
			width: 250, // 设置列宽
		},
		{
			title: t("AbpAuditLogging.OriginalValue"),
			dataIndex: "originalValue",
			sorter: true,
			className: "font-medium text-error",
			width: 250, // 设置列宽
		},
		{
			title: t("AbpAuditLogging.PropertyTypeFullName"),
			dataIndex: "propertyTypeFullName",
			sorter: true,
			width: 250, // 设置列宽
		},
	];

	const paginatedData = useMemo(() => {
		const startIndex = (current - 1) * pageSize;
		return data.slice(startIndex, startIndex + pageSize);
	}, [data, current, pageSize]);

	return (
		<Card>
			<Scrollbar>
				<div className="flex flex-col space-y-4">
					<div className="w-auto">
						<Table
							columns={columns}
							dataSource={paginatedData}
							rowKey="id"
							tableLayout="fixed" //https://github.com/ant-design/ant-design/issues/39437#issuecomment-1344152456
							pagination={{
								current,
								pageSize,
								total: data.length,
								onChange: (page, size) => {
									setCurrent(page);
									setPageSize(size);
								},
								showSizeChanger: true,
								pageSizeOptions: ["10", "25", "50", "100"],
							}}
							expandable={{
								expandedRowRender: (record) => (
									<div>
										<Table
											tableLayout="fixed"
											columns={propertyColumns}
											dataSource={record.propertyChanges}
											pagination={false}
											rowKey="propertyName"
											bordered
											className="w-2/3"
										/>
									</div>
								),
							}}
						/>
					</div>
				</div>
			</Scrollbar>
		</Card>
	);
};
