// apps/vben5/packages/@abp/features/src/components/definitions/groups/FeatureGroupDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { FeatureGroupDefinitionDto } from '../../../types/groups';

import { defineAsyncComponent, h, onMounted, ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { sortby, useLocalization, useLocalizationSerializer } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useFeatureGroupDefinitionsApi } from '../../../api/useFeatureGroupDefinitionsApi';
import {
  FeatureDefinitionsPermissions,
  GroupDefinitionsPermissions,
} from '../../../constants/permissions';

defineOptions({
  name: 'FeatureGroupDefinitionTable',
});

const MenuItem = Menu.Item;

const featureGroups = ref<FeatureGroupDefinitionDto[]>([]);

const { Lr } = useLocalization();
const { hasAccessByCodes } = useAccess();
const { deserialize } = useLocalizationSerializer();
const { deleteApi, getListApi } = useFeatureGroupDefinitionsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<FeatureGroupDefinitionDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      sortable: true,
      title: $t('AbpFeatureManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      sortable: true,
      title: $t('AbpFeatureManagement.DisplayName:DisplayName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
      visible: hasAccessByCodes([
        FeatureDefinitionsPermissions.Create,
        GroupDefinitionsPermissions.Delete,
        GroupDefinitionsPermissions.Update,
      ]),
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }) => {
        let items = sortby(featureGroups.value, sort.field);
        if (sort.order === 'desc') {
          items = items.toReversed();
        }
        const result = {
          totalCount: featureGroups.value.length,
          items: items.slice(
            (page.currentPage - 1) * page.pageSize,
            page.currentPage * page.pageSize,
          ),
        };
        return new Promise((resolve) => {
          resolve(result);
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<FeatureGroupDefinitionDto> = {
  sortChange: () => {
    gridApi.query();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [FeatureGroupDefinitionModal, groupModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./FeatureGroupDefinitionModal.vue'),
  ),
});
const [FeatureDefinitionModal, defineModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('../features/FeatureDefinitionModal.vue'),
  ),
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input);
    featureGroups.value = items.map((item) => {
      const localizableString = deserialize(item.displayName);
      return {
        ...item,
        displayName: Lr(localizableString.resourceName, localizableString.name),
      };
    });
    setTimeout(() => gridApi.reload(), 100);
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onCreate() {
  groupModalApi.setData({});
  groupModalApi.open();
}

function onUpdate(row: FeatureGroupDefinitionDto) {
  groupModalApi.setData(row);
  groupModalApi.open();
}

function onMenuClick(row: FeatureGroupDefinitionDto, info: MenuInfo) {
  switch (info.key) {
    case 'features': {
      defineModalApi.setData({
        groupName: row.name,
      });
      defineModalApi.open();
      break;
    }
  }
}

function onDelete(row: FeatureGroupDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('AbpFeatureManagement.GroupDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[GroupDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('AbpFeatureManagement.GroupDefinitions:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[GroupDefinitionsPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[GroupDefinitionsPermissions.Delete]"
          :disabled="row.isStatic"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="hasAccessByCodes([FeatureDefinitionsPermissions.Create])"
                key="features"
                :icon="h(PlusOutlined)"
              >
                {{ $t('AbpFeatureManagement.FeatureDefinitions:AddNew') }}
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <FeatureGroupDefinitionModal @change="() => onGet()" />
  <FeatureDefinitionModal />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/features/definitions-groups/feature-group-definition-table.tsx
import { useCallback, useRef, useState } from "react";
import { Button, Card, Dropdown, Modal } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, EllipsisOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { FeatureGroupDefinitionDto } from "#/management/features/groups";
import { type ActionType, ProTable, type ProColumns } from "@ant-design/pro-table";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { deleteApi, getListApi } from "@/api/management/features/feature-group-definitions";
import {
	FeatureDefinitionsPermissions,
	GroupDefinitionsPermissions,
} from "@/constants/management/features/permissions";
import FeatureGroupDefinitionModal from "./feature-group-definition-modal";
import { useLocalizer } from "@/hooks/abp/use-localization";
import { toast } from "sonner";
import { Iconify } from "@/components/icon";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import FeatureDefinitionModal from "../definitions-features/feature-definition-modal";

const FeatureGroupDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();
	const { deserialize } = localizationSerializer();

	// Modal states
	const [groupModalVisible, setGroupModalVisible] = useState(false);
	const [featureModalVisible, setFeatureModalVisible] = useState(false);
	const [selectedGroup, setSelectedGroup] = useState<FeatureGroupDefinitionDto>();
	const [selectedGroupForFeature, setSelectedGroupForFeature] = useState<string>();

	const { Lr } = useLocalizer(
		undefined,
		useCallback(() => {
			actionRef.current?.reload();
			setFeatureModalVisible(false);
			setGroupModalVisible(false);
		}, []),
	);

	const [searchParams, setSearchParams] = useState<{ filter?: string }>({});

	// Fetch List
	const { data, isLoading } = useQuery({
		queryKey: ["featureGroups", searchParams],
		queryFn: async () => {
			const { items } = await getListApi(searchParams);
			return items.map((item) => {
				const localizableString = deserialize(item.displayName);
				return {
					...item,
					displayName: Lr(localizableString.resourceName, localizableString.name),
				};
			});
		},
	});

	// Delete Group
	const { mutateAsync: deleteGroup } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["featureGroups"] });
		},
	});

	const handleCreate = () => {
		setSelectedGroup(undefined);
		setGroupModalVisible(true);
	};

	const handleUpdate = (group: FeatureGroupDefinitionDto) => {
		setSelectedGroup(group);
		setGroupModalVisible(true);
	};

	const handleDelete = (group: FeatureGroupDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", {
				0: group.name,
			}),
			onOk: () => deleteGroup(group.name),
		});
	};

	const handleMenuClick = (key: string, group: FeatureGroupDefinitionDto) => {
		if (key === "features") {
			setSelectedGroupForFeature(group.name);
			setFeatureModalVisible(true);
		}
	};

	const columns: ProColumns<FeatureGroupDefinitionDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpFeatureManagement.DisplayName:Name"),
			dataIndex: "name",
			width: "auto",
			hideInSearch: true,
			sorter: true,
		},
		{
			title: $t("AbpFeatureManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: "auto",
			hideInSearch: true,
			sorter: true,
		},
		{
			title: $t("AbpUi.Actions"),
			width: 220,
			fixed: "right",
			hideInSearch: true,
			render: (_, record) => (
				<div className="flex flex-row">
					<div className={`${record.isStatic ? "w-full" : "basis-1/3"}`}>
						<Button
							type="link"
							icon={<EditOutlined />}
							block
							disabled={!hasAccessByCodes([GroupDefinitionsPermissions.Update])}
							onClick={() => handleUpdate(record)}
						>
							{$t("AbpUi.Edit")}
						</Button>
					</div>
					{!record.isStatic && (
						<>
							<div className="basis-1/3">
								<Button
									type="link"
									danger
									icon={<DeleteOutlined />}
									block
									disabled={!hasAccessByCodes([GroupDefinitionsPermissions.Delete])}
									onClick={() => handleDelete(record)}
								>
									{$t("AbpUi.Delete")}
								</Button>
							</div>
							<div className="basis-1/3">
								<Dropdown
									menu={{
										items: [
											hasAccessByCodes([FeatureDefinitionsPermissions.Create])
												? {
														key: "features",
														icon: <Iconify icon="ant-design:gold-outlined" />,
														label: $t("AbpFeatureManagement.FeatureDefinitions:AddNew"),
													}
												: null,
										].filter((item) => item !== null),
										onClick: ({ key }) => handleMenuClick(key as string, record),
									}}
								>
									<Button type="link" icon={<EllipsisOutlined />} />
								</Dropdown>
							</div>
						</>
					)}
				</div>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<FeatureGroupDefinitionDto>
					headerTitle={$t("AbpFeatureManagement.GroupDefinitions")}
					actionRef={actionRef}
					columns={columns}
					dataSource={data}
					loading={isLoading}
					rowKey="name"
					pagination={{
						showSizeChanger: true,
						total: data?.length,
					}}
					search={{
						labelWidth: "auto",
						span: 12,
						defaultCollapsed: true,
					}}
					toolBarRender={() => [
						hasAccessByCodes([GroupDefinitionsPermissions.Create]) && (
							<Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("AbpFeatureManagement.GroupDefinitions:AddNew")}
							</Button>
						),
					]}
					request={async (params) => {
						const { filter } = params;
						setSearchParams({ filter });
						await queryClient.invalidateQueries({
							queryKey: ["featureGroups"],
						});
						return { data, success: true, total: data?.length };
					}}
				/>
			</Card>
			<FeatureGroupDefinitionModal
				visible={groupModalVisible}
				groupName={selectedGroup?.name}
				onClose={() => setGroupModalVisible(false)}
				onChange={() => {
					setGroupModalVisible(false);
					actionRef.current?.reload();
				}}
			/>
			<FeatureDefinitionModal
				visible={featureModalVisible}
				onClose={() => setFeatureModalVisible(false)}
				onChange={() => {
					setFeatureModalVisible(false);
					actionRef.current?.reload();
				}}
				groupName={selectedGroupForFeature}
			/>
		</>
	);
};
//TODO 添加功能-给自添加分组
export default FeatureGroupDefinitionTable;
