// apps/vben5/packages/@abp/features/src/components/definitions/groups/FeatureGroupDefinitionModal.vue
<script setup lang="ts">
import type { PropertyInfo } from '@abp/ui';
import type { FormInstance } from 'ant-design-vue';

import type { FeatureGroupDefinitionDto } from '../../../types/groups';

import { defineEmits, defineOptions, ref, toValue, useTemplateRef } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { LocalizableInput, PropertyTable } from '@abp/ui';
import { Form, Input, message, Tabs } from 'ant-design-vue';

import { useFeatureGroupDefinitionsApi } from '../../../api/useFeatureGroupDefinitionsApi';

defineOptions({
  name: 'FeatureGroupDefinitionModal',
});
const emits = defineEmits<{
  (event: 'change', data: FeatureGroupDefinitionDto): void;
}>();

const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

type TabKeys = 'basic' | 'props';

const defaultModel = {} as FeatureGroupDefinitionDto;

const isEditModel = ref(false);
const activeTab = ref<TabKeys>('basic');
const form = useTemplateRef<FormInstance>('form');
const formModel = ref<FeatureGroupDefinitionDto>({ ...defaultModel });

const { cancel, createApi, getApi, updateApi } =
  useFeatureGroupDefinitionsApi();
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('FeatureGroupDefinitionModal has closed!');
  },
  onConfirm: async () => {
    await form.value?.validate();
    const api = isEditModel.value
      ? updateApi(formModel.value.name, toValue(formModel))
      : createApi(toValue(formModel));
    modalApi.setState({ confirmLoading: true, loading: true });
    api
      .then((res) => {
        message.success($t('AbpUi.SavedSuccessfully'));
        emits('change', res);
        modalApi.close();
      })
      .finally(() => {
        modalApi.setState({ confirmLoading: false, loading: false });
      });
  },
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      isEditModel.value = false;
      activeTab.value = 'basic';
      formModel.value = { ...defaultModel };
      modalApi.setState({
        showConfirmButton: true,
        title: $t('AbpFeatureManagement.GroupDefinitions:AddNew'),
      });
      try {
        modalApi.setState({ loading: true });
        const { name } = modalApi.getData<FeatureGroupDefinitionDto>();
        name && (await onGet(name));
      } finally {
        modalApi.setState({ loading: false });
      }
    }
  },
  title: $t('AbpFeatureManagement.GroupDefinitions:AddNew'),
});
async function onGet(name: string) {
  isEditModel.value = true;
  const dto = await getApi(name);
  formModel.value = dto;
  modalApi.setState({
    showConfirmButton: !dto.isStatic,
    title: `${$t('AbpFeatureManagement.GroupDefinitions')} - ${dto.name}`,
  });
}
function onPropChange(prop: PropertyInfo) {
  formModel.value.extraProperties ??= {};
  formModel.value.extraProperties[prop.key] = prop.value;
}
function onPropDelete(prop: PropertyInfo) {
  formModel.value.extraProperties ??= {};
  delete formModel.value.extraProperties[prop.key];
}
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <Tabs v-model:active-key="activeTab">
        <!-- 基本信息 -->
        <TabPane key="basic" :tab="$t('AbpFeatureManagement.BasicInfo')">
          <FormItem
            :label="$t('AbpFeatureManagement.DisplayName:Name')"
            name="name"
            required
          >
            <Input
              v-model:value="formModel.name"
              :disabled="formModel.isStatic"
              autocomplete="off"
            />
          </FormItem>
          <FormItem
            :label="$t('AbpFeatureManagement.DisplayName:DisplayName')"
            name="displayName"
            required
          >
            <LocalizableInput
              v-model:value="formModel.displayName"
              :disabled="formModel.isStatic"
            />
          </FormItem>
        </TabPane>
        <!-- 属性 -->
        <TabPane key="props" :tab="$t('AbpFeatureManagement.Properties')">
          <PropertyTable
            :data="formModel.extraProperties"
            :disabled="formModel.isStatic"
            @change="onPropChange"
            @delete="onPropDelete"
          />
        </TabPane>
      </Tabs>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/features/definitions-groups/feature-group-definition-modal.tsx
import { useEffect, useState } from "react";
import { Form, Input, Modal, Tabs } from "antd";
import { useTranslation } from "react-i18next";
import type { FeatureGroupDefinitionDto } from "#/management/features/groups";
import type { PropertyInfo } from "@/components/abp/properties/types";
import { createApi, getApi, updateApi } from "@/api/management/features/feature-group-definitions";
import LocalizableInput from "@/components/abp/localizable-input/localizable-input";
import PropertyTable from "@/components/abp/properties/property-table";
import { toast } from "sonner";
import { useMutation, useQueryClient } from "@tanstack/react-query";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: FeatureGroupDefinitionDto) => void;
	groupName?: string;
}

type TabKeys = "basic" | "props";

const defaultModel: FeatureGroupDefinitionDto = {} as FeatureGroupDefinitionDto;

const FeatureGroupDefinitionModal: React.FC<Props> = ({ visible, onClose, onChange, groupName }) => {
	const { t: $t } = useTranslation();
	const queryClient = useQueryClient();
	const [form] = Form.useForm();
	const [formModel, setFormModel] = useState<FeatureGroupDefinitionDto>({
		...defaultModel,
	});
	const [isEditModel, setIsEditModel] = useState(false);
	const [activeTab, setActiveTab] = useState<TabKeys>("basic");

	// Fetch Group Details( mutate for GET request to allow manual triggering )
	const { mutateAsync: fetchGroup, isPending: isFetching } = useMutation({
		mutationFn: getApi,
		onMutate: () => {
			setIsEditModel(true);
		},
		onSuccess: (dto) => {
			setFormModel(dto);
			form.setFieldsValue(dto);
		},
	});

	// Create Group
	const { mutateAsync: createGroup, isPending: isCreating } = useMutation({
		mutationFn: createApi,
		onSuccess: (res) => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["featureGroups"] });
			onChange(res);
			onClose();
		},
	});

	// Update Group
	const { mutateAsync: updateGroup, isPending: isUpdating } = useMutation({
		mutationFn: (data: FeatureGroupDefinitionDto) => updateApi(data.name, data),
		onSuccess: (res) => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["featureGroups"] });
			onChange(res);
			onClose();
		},
	});

	useEffect(() => {
		if (visible) {
			setIsEditModel(false);
			setActiveTab("basic");
			setFormModel({ ...defaultModel });
			form.resetFields();

			if (groupName) {
				fetchGroup(groupName);
			}
		}
	}, [visible, groupName]);

	const handleOk = async () => {
		try {
			const values = await form.validateFields();
			const submitData = {
				...values,
				extraProperties: formModel.extraProperties,
			};

			if (isEditModel) {
				await updateGroup(submitData);
			} else {
				await createGroup(submitData);
			}
		} catch (error) {
			console.error(error);
		}
	};

	const handlePropChange = (prop: PropertyInfo) => {
		setFormModel((prev) => ({
			...prev,
			extraProperties: {
				...prev.extraProperties,
				[prop.key]: prop.value,
			},
		}));
	};

	const handlePropDelete = (prop: PropertyInfo) => {
		setFormModel((prev) => {
			const newProps = { ...prev.extraProperties };
			delete newProps[prop.key];
			return {
				...prev,
				extraProperties: newProps,
			};
		});
	};

	return (
		<Modal
			title={
				isEditModel
					? `${$t("AbpFeatureManagement.GroupDefinitions")} - ${formModel.name}`
					: $t("AbpFeatureManagement.GroupDefinitions:AddNew")
			}
			open={visible}
			onCancel={onClose}
			onOk={handleOk}
			confirmLoading={isCreating || isUpdating || isFetching}
			okButtonProps={{ disabled: formModel.isStatic }}
			width="50%"
		>
			<Form form={form} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
				<Tabs activeKey={activeTab} onChange={(key) => setActiveTab(key as TabKeys)}>
					<Tabs.TabPane key="basic" tab={$t("AbpFeatureManagement.BasicInfo")}>
						<Form.Item label={$t("AbpFeatureManagement.DisplayName:Name")} name="name" rules={[{ required: true }]}>
							<Input disabled={formModel.isStatic} autoComplete="off" />
						</Form.Item>
						<Form.Item
							label={$t("AbpFeatureManagement.DisplayName:DisplayName")}
							name="displayName"
							rules={[{ required: true }]}
						>
							<LocalizableInput disabled={formModel.isStatic} />
						</Form.Item>
					</Tabs.TabPane>
					<Tabs.TabPane key="props" tab={$t("AbpFeatureManagement.Properties")}>
						<PropertyTable
							data={formModel.extraProperties}
							disabled={formModel.isStatic}
							onChange={handlePropChange}
							onDelete={handlePropDelete}
						/>
					</Tabs.TabPane>
				</Tabs>
			</Form>
		</Modal>
	);
};

export default FeatureGroupDefinitionModal;
