// apps/react-admin/src/components/abp/localizable-input/localizable-input.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { Form, Input, Select } from "antd";
import type { DefaultOptionType } from "antd/es/select";
import { useTranslation } from "react-i18next";
import { isNullOrWhiteSpace } from "@/utils/string";
import type { LocalizableStringInfo } from "#/abp-core/global";
import useAbpStore from "@/store/abpCoreStore";
import { localizationSerializer } from "@/utils/abp/localization-serializer";

interface Props {
	allowClear?: boolean;
	disabled?: boolean;
	value?: string;
	onChange?: (value: string) => void;
}

interface State {
	displayName?: string;
	displayNames: DefaultOptionType[];
	resourceName?: string;
}

const LocalizableInput: React.FC<Props> = ({ allowClear, disabled, value, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const abpStore = useAbpStore();
	const { deserialize, serialize } = localizationSerializer();

	const [state, setState] = useState<State>({
		displayNames: [],
		displayName: undefined,
		resourceName: undefined,
	});

	const isFixed = useMemo(() => {
		return state.resourceName === "Fixed";
	}, [state.resourceName]);

	const resources = useMemo(() => {
		if (!abpStore.localization) {
			return [];
		}

		const sources = Object.keys(abpStore.localization.resources).map((key) => ({
			label: key,
			value: key,
		}));

		return [
			{
				label: $t("component.localizable_input.resources.fiexed.group"),
				options: [
					{
						label: $t("component.localizable_input.resources.fiexed.label"),
						value: "Fixed",
					},
				],
				value: "F",
			},
			{
				label: $t("component.localizable_input.resources.localization.group"),
				options: sources,
				value: "R",
			},
		];
	}, [abpStore.localization, $t]);

	const triggerDisplayNameChange = useCallback(
		(displayName?: string) => {
			if (!displayName) return;

			let updateValue = "";
			if (isFixed) {
				updateValue = `F:${displayName}`;
			} else if (!isNullOrWhiteSpace(state.resourceName)) {
				const info: LocalizableStringInfo = {
					name: displayName,
					resourceName: state.resourceName ?? "",
				};
				updateValue = serialize(info);
			}

			onChange?.(updateValue);
			form.setFieldValue("localizableInput", updateValue);
		},
		[isFixed, state.resourceName, serialize, onChange, form],
	);

	const handleDisplayNameChange = (value?: string) => {
		setState((prev) => ({ ...prev, displayName: value }));
		triggerDisplayNameChange(value);
	};

	const localizationResources = abpStore.localization?.resources;
	const handleResourceChange = useCallback(
		(value?: string, triggerChanged = false) => {
			const newDisplayNames: DefaultOptionType[] = [];

			if (value && localizationResources?.[value]) {
				Object.keys(localizationResources[value].texts).forEach((key) => {
					const labelText = localizationResources[value]?.texts[key];
					newDisplayNames.push({
						label: labelText ?? key,
						value: key,
					});
				});
			}

			setState((prev) => ({
				...prev,
				displayNames: newDisplayNames,
				displayName: undefined,
				resourceName: value,
			}));

			if (triggerChanged) {
				triggerDisplayNameChange(undefined);
			}
		},
		[localizationResources, triggerDisplayNameChange],
	);
	useEffect(() => {
		if (value) {
			const info = deserialize(value);
			if (state.resourceName !== info.resourceName) {
				handleResourceChange(isNullOrWhiteSpace(info.resourceName) ? undefined : info.resourceName, false);
			}
			if (state.displayName !== info.name) {
				setState((prev) => ({
					...prev,
					displayName: isNullOrWhiteSpace(info.name) ? undefined : info.name,
				}));
			}
		}
	}, [value]);

	return (
		<div className="w-full">
			<Form.Item noStyle>
				<Input.Group>
					<div className="flex flex-row gap-4">
						<div className="basis-2/5">
							<Select
								value={state.resourceName}
								allowClear={allowClear}
								disabled={disabled}
								options={resources}
								placeholder={$t("component.localizable_input.placeholder")}
								className="w-full"
								onChange={(value) => handleResourceChange(value?.toString(), true)}
							/>
						</div>
						<div className="basis-3/5">
							{isFixed ? (
								<Input
									allowClear={allowClear}
									disabled={disabled}
									placeholder={$t("component.localizable_input.resources.fiexed.placeholder")}
									value={state.displayName}
									autoComplete="off"
									className="w-full"
									onChange={(e) => handleDisplayNameChange(e.target.value)}
								/>
							) : (
								<Select
									allowClear={allowClear}
									disabled={disabled}
									options={state.displayNames}
									placeholder={$t("component.localizable_input.resources.localization.placeholder")}
									value={state.displayName}
									className="w-full"
									onChange={(value) => handleDisplayNameChange(value?.toString())}
								/>
							)}
						</div>
					</div>
				</Input.Group>
			</Form.Item>
		</div>
	);
};

export default LocalizableInput;

// apps/vue/src/components/Abp/LocalizableInput/LocalizableInput.vue
<template>
  <div style="width: 100%">
    <ItemReset>
      <InputGroup>
        <Row :gutter="4">
          <Col :span="8">
            <Select
              :class="`${prefixCls}__resource`"
              :disabled="props.disabled"
              :allow-clear="props.allowClear"
              :placeholder="t('component.localizable_input.placeholder')"
              v-model:value="state.resourceName"
              :options="getResources"
              @change="(value) => handleResourceChange(value?.toString(), true)"
            />
          </Col>
          <Col :span="16">
            <Input
              v-if="getIsFixed"
              :class="`${prefixCls}__name`"
              :disabled="props.disabled"
              :allow-clear="props.allowClear"
              :placeholder="t('component.localizable_input.resources.fiexed.placeholder')"
              :value="state.displayName"
              @change="(e) => handleDisplayNameChange(e.target.value)"
            />
            <Select
              v-else
              :class="`${prefixCls}__name`"
              :disabled="props.disabled"
              :allow-clear="props.allowClear"
              :placeholder="t('component.localizable_input.resources.localization.placeholder')"
              :value="state.displayName"
              :options="state.displayNames"
              @change="handleDisplayNameChange"
            />
          </Col>
        </Row>
      </InputGroup>
    </ItemReset>
  </div>
</template>

<script setup lang="ts">
  import type { DefaultOptionType } from 'ant-design-vue/lib/select';
  import { computed, watch, shallowReactive } from 'vue';
  import { Form, Row, Col, Input, Select } from 'ant-design-vue';
  import { propTypes } from '/@/utils/propTypes';
  import { useI18n } from '/@/hooks/web/useI18n';
  import { useDesign } from '/@/hooks/web/useDesign';
  import { useLocalizationSerializer } from '/@/hooks/abp/useLocalizationSerializer';
  import { useAbpStoreWithOut } from '/@/store/modules/abp';
  import { isNullOrWhiteSpace } from '/@/utils/strings';

  const ItemReset = Form.ItemRest;
  const InputGroup = Input.Group;
  interface State {
    resourceName?: string,
    displayName?: string,
    displayNames: DefaultOptionType[],
  } 

  const emits = defineEmits(['update:value', 'change']);
  const props = defineProps({
    value: propTypes.string,
    allowClear: propTypes.bool.def(false),
    disabled: propTypes.bool.def(false),
  });
  const { t } = useI18n();
  const abpStore = useAbpStoreWithOut();
  const { prefixCls } = useDesign('localizable-input');
  const formItemContext = Form.useInjectFormItemContext();
  const { values: resources } = abpStore.getApplication.localization;
  const { deserialize, serialize } = useLocalizationSerializer();
  const state = shallowReactive<State>({
    displayNames: [] as any[],
  });
  const getIsFixed = computed(() => {
    return state.resourceName === 'Fixed';
  });
  const getResources = computed(() => {
    const sources = Object.keys(resources).map((key) => {
      return {
        label: key,
        value: key,
      }
    });
    return [
      {
        label: t('component.localizable_input.resources.fiexed.group'),
        value: 'F',
        options: [{
          label: t('component.localizable_input.resources.fiexed.label'),
          value: 'Fixed',
        }]
      },
      {
        label: t('component.localizable_input.resources.localization.group'),
        value: 'R',
        options: sources,
      }
    ];
  });
  watch(
    () => props.value,
    (value) => {
      const info = deserialize(value);
      if (state.resourceName !== info.resourceName) {
        state.resourceName = isNullOrWhiteSpace(info.resourceName) ? undefined : info.resourceName;
        handleResourceChange(state.resourceName, false);
      }
      if (state.displayName !== info.name) {
        state.displayName = isNullOrWhiteSpace(info.name) ? undefined : info.name;
      }
    },
    {
      immediate: true,
    }
  );

  function handleResourceChange(value?: string, triggerChanged?: boolean) {
    state.displayNames = [];
    if (value && resources[value]) {
      state.displayNames = Object.keys(resources[value]).map((key) => {
        return {
          label: resources[value][key] ? String(resources[value][key]) : key,
          value: key,
        };
      }); 
    }
    state.displayName = undefined;
    if (triggerChanged === true) {
      triggerDisplayNameChange(state.displayName);
    }
  }

  function handleDisplayNameChange(value?: string) {
    triggerDisplayNameChange(value);
  }

  function triggerDisplayNameChange(value?: string) {
    const inputValue = value === undefined ? '' : value;
    let updateValue = '';
    if (getIsFixed.value) {
      updateValue = !isNullOrWhiteSpace(value) ? `F:${value}` : 'F:' ;
    } else if (!isNullOrWhiteSpace(state.resourceName)) {
      const info: LocalizableStringInfo = {
        resourceName: state.resourceName ?? '',
        name: inputValue,
      };
      updateValue = serialize(info);
    }
    emits('change', updateValue);
    emits('update:value', updateValue);
    formItemContext.onFieldChange();
  }
</script>

<style lang="less" scoped>
  @prefix-cls: ~'@{namespace}-localizable-input';

  .@{prefix-cls} {
    &__resource {
      width: 100% !important;
    }

    &__name {
      width: 100% !important;
    }
  }
</style>
