// apps/react-admin/src/pages/webhooks/send-attempts/webhook-send-attempt-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Tag, Dropdown, Modal, Space, Card } from "antd";
import { EditOutlined, DeleteOutlined, EllipsisOutlined, SendOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getPagedListApi, reSendApi, bulkDeleteApi, bulkReSendApi } from "@/api/webhooks/send-attempts";
import { getPagedListApi as getTenantsApi } from "@/api/saas/tenants";
import type { WebhookSendRecordDto } from "#/webhooks/send-attempts";
import { WebhooksSendAttemptsPermissions } from "@/constants/webhooks/permissions"; // Adjust
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { formatToDateTime } from "@/utils/abp";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";
import WebhookSendAttemptDrawer from "./webhook-send-attempt-drawer";
import { useHttpStatusCodeMap } from "@/hooks/abp/fake-hooks/use-http-status-code-map";
import { HttpStatusCode } from "@/constants/request/http-status";

const WebhookSendAttemptTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const { getHttpStatusColor, httpStatusCodeMap } = useHttpStatusCodeMap();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();

	const [drawerVisible, setDrawerVisible] = useState(false);
	const [selectedRecordId, setSelectedRecordId] = useState<string | undefined>();
	const [selectedKeys, setSelectedKeys] = useState<React.Key[]>([]);

	// Mutation for single resend
	const { mutateAsync: resend } = useMutation({
		mutationFn: reSendApi,
		onSuccess: () => {
			toast.success($t("WebhooksManagement.SuccessfullySent"));
			actionRef.current?.reload();
		},
	});

	// Bulk mutations
	const { mutateAsync: bulkResend } = useMutation({
		mutationFn: bulkReSendApi,
		onSuccess: () => {
			toast.success($t("WebhooksManagement.SuccessfullySent"));
			actionRef.current?.reload();
		},
	});

	const { mutateAsync: bulkDelete } = useMutation({
		mutationFn: bulkDeleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			setSelectedKeys([]);
			actionRef.current?.reload();
		},
	});

	const handleShow = (row: WebhookSendRecordDto) => {
		setSelectedRecordId(row.id);
		setDrawerVisible(true);
	};

	const handleDelete = (row: WebhookSendRecordDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: $t("WebhooksManagement.SelectedItems") }),
			onOk: async () => {
				await deleteApi(row.id);
				toast.success($t("AbpUi.DeletedSuccessfully"));
				actionRef.current?.reload();
			},
		});
	};

	const handleSend = (row: WebhookSendRecordDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("WebhooksManagement.ItemWillBeResendMessageWithFormat", {
				0: $t("WebhooksManagement.SelectedItems"),
			}),
			onOk: () => resend(row.id),
		});
	};

	const handleBulkSend = () => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("WebhooksManagement.ItemWillBeResendMessageWithFormat", {
				0: $t("WebhooksManagement.SelectedItems"),
			}),
			onOk: () => bulkResend({ recordIds: selectedKeys as string[] }),
		});
	};

	const handleBulkDelete = () => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: $t("WebhooksManagement.SelectedItems") }),
			onOk: () => bulkDelete({ recordIds: selectedKeys as string[] }),
		});
	};

	const httpStatusOptions = Object.keys(httpStatusCodeMap).map((key) => ({
		label: httpStatusCodeMap[Number(key)],
		value: key,
	}));

	const columns: ProColumns<WebhookSendRecordDto>[] = [
		{
			title: $t("WebhooksManagement.DisplayName:TenantId"),
			dataIndex: "tenantId",
			width: 200,
			sorter: true,
			valueType: "select",
			request: async ({ keyWords }) => {
				// Simple search logic for ProTable Select
				const res = await getTenantsApi({ filter: keyWords, maxResultCount: 20 });
				return res.items.map((t) => ({ label: t.name, value: t.id }));
			},
			fieldProps: {
				showSearch: true,
				allowClear: true,
			},
		},
		{
			title: $t("WebhooksManagement.DisplayName:ResponseStatusCode"),
			dataIndex: "responseStatusCode",
			width: 150,
			sorter: true,
			valueType: "select",
			fieldProps: { options: httpStatusOptions },
			render: (_, row) => (
				<Tag color={getHttpStatusColor(row.responseStatusCode || HttpStatusCode.InternalServerError)}>
					{httpStatusCodeMap[row.responseStatusCode || HttpStatusCode.InternalServerError] || row.responseStatusCode}
				</Tag>
			),
		},
		{
			title: $t("WebhooksManagement.DisplayName:CreationTime"),
			dataIndex: "creationTime",
			width: 180,
			sorter: true,
			valueType: "dateRange",
			render: (_, row) => formatToDateTime(row.creationTime),
		},
		{
			title: $t("WebhooksManagement.DisplayName:Response"),
			dataIndex: "response",
			width: 300,
			sorter: true,
			ellipsis: true,
			hideInSearch: true,
		},
		{
			title: $t("WebhooksManagement.DisplayName:State"),
			dataIndex: "state", // Mapped to filter
			hideInTable: true,
			valueType: "select",
			valueEnum: {
				true: { text: $t("WebhooksManagement.ResponseState:Successed"), status: "Success" },
				false: { text: $t("WebhooksManagement.ResponseState:Failed"), status: "Error" },
			},
		},
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 150,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleShow(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[WebhooksSendAttemptsPermissions.Default],
					)}
					{withAccessChecker(
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>,
						[WebhooksSendAttemptsPermissions.Delete],
					)}
					<Dropdown
						menu={{
							items: [
								hasAccessByCodes([WebhooksSendAttemptsPermissions.Resend])
									? {
											key: "send",
											label: $t("WebhooksManagement.Resend"),
											icon: <SendOutlined className="text-green-500" />,
											onClick: () => handleSend(record),
										}
									: null,
							].filter(Boolean) as any,
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<WebhookSendRecordDto>
					headerTitle={$t("WebhooksManagement.SendAttempts")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					rowSelection={{
						selectedRowKeys: selectedKeys,
						onChange: (keys) => setSelectedKeys(keys),
					}}
					search={{ labelWidth: "auto", defaultCollapsed: true }}
					toolBarRender={() => [
						selectedKeys.length > 0 && hasAccessByCodes([WebhooksSendAttemptsPermissions.Resend]) && (
							<Button key="resend" type="primary" icon={<SendOutlined />} onClick={handleBulkSend}>
								{$t("WebhooksManagement.Resend")}
							</Button>
						),
						selectedKeys.length > 0 && hasAccessByCodes([WebhooksSendAttemptsPermissions.Delete]) && (
							<Button key="delete" danger type="primary" icon={<DeleteOutlined />} onClick={handleBulkDelete}>
								{$t("AbpUi.Delete")}
							</Button>
						),
					]}
					request={async (params, sorter) => {
						const { current, pageSize, creationTime, ...filters } = params;
						const [beginCreationTime, endCreationTime] = creationTime || [];

						const sorting =
							sorter && Object.keys(sorter).length > 0
								? Object.keys(sorter)
										.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
										.join(", ")
								: undefined;

						const query = await queryClient.fetchQuery({
							queryKey: ["sendAttempts", params, sorter],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									sorting: sorting,
									beginCreationTime,
									endCreationTime,
									...filters,
								}),
						});

						return {
							data: query.items,
							total: query.totalCount,
							success: true,
						};
					}}
					pagination={{ defaultPageSize: 10, showSizeChanger: true }}
				/>
			</Card>
			<WebhookSendAttemptDrawer
				visible={drawerVisible}
				recordId={selectedRecordId}
				onClose={() => setDrawerVisible(false)}
			/>
		</>
	);
};

export default WebhookSendAttemptTable;

// apps/vben5/packages/@abp/webhooks/src/components/send-attempts/WebhookSendAttemptTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { WebhookSendRecordDto } from '../../types/sendAttempts';

import { defineAsyncComponent, h, ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useHttpStatusCodeMap } from '@abp/request';
import { useTenantsApi } from '@abp/saas';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal, Tag } from 'ant-design-vue';
import debounce from 'lodash.debounce';

import { useSendAttemptsApi } from '../../api/useSendAttemptsApi';
import { WebhooksSendAttemptsPermissions } from '../../constants/permissions';

defineOptions({
  name: 'WebhookSendAttemptTable',
});

const MenuItem = Menu.Item;
const SendMessageIcon = createIconifyIcon('ant-design:send-outlined');

const { hasAccessByCodes } = useAccess();
const { getPagedListApi: getTenantsApi } = useTenantsApi();
const {
  bulkDeleteApi,
  bulkReSendApi,
  cancel,
  deleteApi,
  getPagedListApi,
  reSendApi,
} = useSendAttemptsApi();
const { getHttpStatusColor, httpStatusCodeMap } = useHttpStatusCodeMap();

const tenantFilter = ref<string>();
const selectedKeys = ref<string[]>([]);

const httpStatusOptions = Object.keys(httpStatusCodeMap).map((key) => {
  return {
    label: httpStatusCodeMap[Number(key)],
    value: key,
  };
});

const formOptions: VbenFormProps = {
  collapsed: true,
  collapsedRows: 3,
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  fieldMappingTime: [
    [
      'creationTime',
      ['beginCreationTime', 'endCreationTime'],
      ['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59'],
    ],
  ],
  schema: [
    {
      component: 'ApiSelect',
      componentProps: () => {
        return {
          allowClear: true,
          api: getTenantsApi,
          filterOption: false,
          labelField: 'normalizedName',
          onSearch: debounce((filter?: string) => {
            tenantFilter.value = filter;
          }, 500),
          params: {
            filter: tenantFilter.value || undefined,
          },
          resultField: 'items',
          showSearch: true,
          valueField: 'id',
        };
      },
      fieldName: 'tenantId',
      label: $t('WebhooksManagement.DisplayName:TenantId'),
    },
    {
      component: 'RangePicker',
      fieldName: 'creationTime',
      label: $t('WebhooksManagement.DisplayName:CreationTime'),
    },
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        options: [
          {
            label: $t('WebhooksManagement.ResponseState:Successed'),
            value: 'true',
          },
          {
            label: $t('WebhooksManagement.ResponseState:Failed'),
            value: 'false',
          },
        ],
      },
      fieldName: 'state',
      label: $t('WebhooksManagement.DisplayName:State'),
    },
    {
      component: 'Select',
      componentProps: {
        options: httpStatusOptions,
      },
      fieldName: 'responseStatusCode',
      label: $t('WebhooksManagement.DisplayName:ResponseStatusCode'),
    },
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
      },
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<WebhookSendRecordDto> = {
  columns: [
    {
      align: 'center',
      type: 'checkbox',
      width: 40,
    },
    {
      align: 'left',
      field: 'tenantId',
      minWidth: 150,
      sortable: true,
      title: $t('WebhooksManagement.DisplayName:TenantId'),
    },
    {
      align: 'left',
      field: 'responseStatusCode',
      minWidth: 150,
      slots: { default: 'responseStatusCode' },
      sortable: true,
      title: $t('WebhooksManagement.DisplayName:ResponseStatusCode'),
    },
    {
      align: 'left',
      field: 'creationTime',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      minWidth: 120,
      sortable: true,
      title: $t('WebhooksManagement.DisplayName:CreationTime'),
    },
    {
      align: 'center',
      field: 'response',
      minWidth: 300,
      sortable: true,
      title: $t('WebhooksManagement.DisplayName:Response'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        return await getPagedListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<WebhookSendRecordDto> = {
  checkboxAll: (params) => {
    selectedKeys.value = params.records.map((record) => record.id);
  },
  checkboxChange: (params) => {
    selectedKeys.value = params.records.map((record) => record.id);
  },
  sortChange: () => {
    gridApi.query();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [WebhookSendAttemptDrawer, drawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(
    () => import('./WebhookSendAttemptDrawer.vue'),
  ),
});

function onUpdate(row: WebhookSendRecordDto) {
  drawerApi.setData(row);
  drawerApi.open();
}

function onDelete(row: WebhookSendRecordDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessageWithFormat', [
      $t('WebhooksManagement.SelectedItems'),
    ]),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      await gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
async function onMenuClick(row: WebhookSendRecordDto, info: MenuInfo) {
  switch (info.key) {
    case 'send': {
      await onSend(row);
      break;
    }
  }
}
async function onSend(row: WebhookSendRecordDto) {
  Modal.confirm({
    centered: true,
    content: $t('WebhooksManagement.ItemWillBeResendMessageWithFormat', [
      $t('WebhooksManagement.SelectedItems'),
    ]),
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await reSendApi(row.id);
        message.success($t('WebhooksManagement.SuccessfullySent'));
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
async function onSendMany(keys: string[]) {
  Modal.confirm({
    centered: true,
    content: `${$t('WebhooksManagement.ItemWillBeResendMessageWithFormat', [$t('WebhooksManagement.SelectedItems')])}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await bulkReSendApi({ recordIds: keys });
        message.success($t('WebhooksManagement.SuccessfullySent'));
        // 重新查询
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
async function onDeleteMany(keys: string[]) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [$t('WebhooksManagement.SelectedItems')])}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await bulkDeleteApi({ recordIds: keys });
        message.success($t('AbpUi.DeletedSuccessfully'));
        // 清理选中的key
        selectedKeys.value = selectedKeys.value.filter(
          (key) => !keys.includes(key),
        );
        // 重新查询
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
</script>

<template>
  <Grid :table-title="$t('WebhooksManagement.SendAttempts')">
    <template #toolbar-tools>
      <div v-if="selectedKeys.length > 0" class="flex flex-row gap-2">
        <Button
          v-if="hasAccessByCodes([WebhooksSendAttemptsPermissions.Resend])"
          :icon="h(SendMessageIcon)"
          type="primary"
          @click="onSendMany(selectedKeys)"
        >
          {{ $t('WebhooksManagement.Resend') }}
        </Button>
        <Button
          v-if="hasAccessByCodes([WebhooksSendAttemptsPermissions.Delete])"
          :icon="h(DeleteOutlined)"
          type="primary"
          danger
          @click="onDeleteMany(selectedKeys)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
    <template #responseStatusCode="{ row }">
      <Tag :color="getHttpStatusColor(row.responseStatusCode)">
        {{ httpStatusCodeMap[row.responseStatusCode] }}
      </Tag>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          v-if="hasAccessByCodes([WebhooksSendAttemptsPermissions.Default])"
          :icon="h(EditOutlined)"
          type="link"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="hasAccessByCodes([WebhooksSendAttemptsPermissions.Delete])"
          :icon="h(DeleteOutlined)"
          danger
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="
                  hasAccessByCodes([WebhooksSendAttemptsPermissions.Resend])
                "
                key="send"
              >
                <div class="flex flex-row items-center gap-[4px]">
                  <SendMessageIcon color="green" />
                  {{ $t('WebhooksManagement.Resend') }}
                </div>
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <WebhookSendAttemptDrawer />
</template>

<style lang="scss" scoped></style>
