// apps/react-admin/src/pages/webhooks/send-attempts/webhook-send-attempt-drawer.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Drawer, Form, Input, Checkbox, Tabs, Tag } from "antd";
import { useTranslation } from "react-i18next";
import { getApi } from "@/api/webhooks/send-attempts";
import { getApi as getSubscriptionApi } from "@/api/webhooks/subscriptions";
import { getApi as getTenantApi } from "@/api/saas/tenants";
import type { WebhookSendRecordDto } from "#/webhooks/send-attempts";
import type { WebhookSubscriptionDto } from "#/webhooks/subscriptions";
import type { TenantDto } from "#/saas/tenants";
import { WebhookSubscriptionPermissions } from "@/constants/webhooks/permissions"; // Adjust path
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { formatToDateTime } from "@/utils/abp";

import Editor from "@/components/editor";
import { useHttpStatusCodeMap } from "@/hooks/abp/fake-hooks/use-http-status-code-map";
import JsonEdit from "@/components/abp/common/json-edit";

interface Props {
	visible: boolean;
	onClose: () => void;
	recordId?: string;
}

const WebhookSendAttemptDrawer: React.FC<Props> = ({ visible, onClose, recordId }) => {
	const { t: $t } = useTranslation();

	const { getHttpStatusColor, httpStatusCodeMap } = useHttpStatusCodeMap();
	const [activeTab, setActiveTab] = useState("basic");
	const [loading, setLoading] = useState(false);
	const [formModel, setFormModel] = useState<WebhookSendRecordDto>();
	const [webhookSubscription, setWebhookSubscription] = useState<WebhookSubscriptionDto>();
	const [webhookTenant, setWebhookTenant] = useState<TenantDto>();

	useEffect(() => {
		if (visible && recordId) {
			initData(recordId);
		} else {
			setFormModel(undefined);
			setWebhookSubscription(undefined);
			setWebhookTenant(undefined);
		}
	}, [visible, recordId]);

	const initData = async (id: string) => {
		try {
			setLoading(true);
			const dto = await getApi(id);
			setFormModel(dto);

			const [sub, tenant] = await Promise.all([
				fetchSubscription(dto.webhookSubscriptionId),
				fetchTenant(dto.tenantId),
			]);
			setWebhookSubscription(sub);
			setWebhookTenant(tenant);
		} finally {
			setLoading(false);
		}
	};

	const fetchSubscription = async (id: string) => {
		if (hasAccessByCodes([WebhookSubscriptionPermissions.Default])) {
			return await getSubscriptionApi(id);
		}
		return undefined;
	};

	const fetchTenant = async (id?: string) => {
		if (id && hasAccessByCodes(["AbpSaas.Tenants"])) {
			return await getTenantApi(id);
		}
		return undefined;
	};

	return (
		<Drawer
			title={$t("WebhooksManagement.SendAttempts")}
			open={visible}
			onClose={onClose}
			width="50%"
			destroyOnClose
			loading={loading}
		>
			{formModel && (
				<Form layout="vertical">
					<Tabs activeKey={activeTab} onChange={setActiveTab}>
						{/* Basic Info Tab */}
						<Tabs.TabPane key="basic" tab={$t("WebhooksManagement.BasicInfo")}>
							{webhookTenant && (
								<Form.Item label={$t("WebhooksManagement.DisplayName:TenantId")}>
									<Input value={webhookTenant.name} disabled />
								</Form.Item>
							)}

							<Form.Item>
								<Checkbox checked={formModel.sendExactSameData} disabled>
									{$t("WebhooksManagement.DisplayName:SendExactSameData")}
								</Checkbox>
							</Form.Item>

							<Form.Item label={$t("WebhooksManagement.DisplayName:CreationTime")}>
								<Input value={formatToDateTime(formModel.creationTime)} disabled />
							</Form.Item>

							<Form.Item label={$t("WebhooksManagement.DisplayName:RequestHeaders")}>
								<JsonEdit data={formModel.requestHeaders || ""} />
							</Form.Item>

							{formModel.responseStatusCode && (
								<Form.Item label={$t("WebhooksManagement.DisplayName:ResponseStatusCode")}>
									<Tag color={getHttpStatusColor(formModel.responseStatusCode)}>
										{httpStatusCodeMap[formModel.responseStatusCode] || formModel.responseStatusCode}
									</Tag>
								</Form.Item>
							)}

							<Form.Item label={$t("WebhooksManagement.DisplayName:ResponseHeaders")}>
								<JsonEdit data={formModel.responseHeaders || ""} />
							</Form.Item>

							<Form.Item label={$t("WebhooksManagement.DisplayName:Response")}>
								<Editor value={formModel.response ?? ""} readOnly sample hiddleToolbar />
								{/* <Input.TextArea value={formModel.response} autoSize={{ minRows: 5 }} readOnly /> */}
							</Form.Item>
						</Tabs.TabPane>

						{/* Event Tab */}
						<Tabs.TabPane key="event" tab={$t("WebhooksManagement.WebhookEvent")}>
							<Form.Item label={$t("WebhooksManagement.DisplayName:WebhookEventId")}>
								<Input value={formModel.webhookEventId} disabled />
							</Form.Item>

							<Form.Item label={$t("WebhooksManagement.DisplayName:WebhookName")}>
								<Input value={formModel.webhookEvent?.webhookName} disabled />
							</Form.Item>

							<Form.Item label={$t("WebhooksManagement.DisplayName:CreationTime")}>
								<Input value={formatToDateTime(formModel.webhookEvent?.creationTime)} disabled />
							</Form.Item>

							<Form.Item label={$t("WebhooksManagement.DisplayName:Data")}>
								<JsonEdit data={formModel.webhookEvent?.data || ""} />
							</Form.Item>
						</Tabs.TabPane>

						{/* Subscriber Tab */}
						{webhookSubscription && (
							<Tabs.TabPane key="subscriber" tab={$t("WebhooksManagement.Subscriptions")}>
								<Form.Item>
									<Checkbox checked={webhookSubscription.isActive} disabled>
										{$t("WebhooksManagement.DisplayName:IsActive")}
									</Checkbox>
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:WebhookSubscriptionId")}>
									<Input value={webhookSubscription.id} disabled />
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:WebhookUri")}>
									<Input value={webhookSubscription.webhookUri} disabled />
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:Description")}>
									<Input.TextArea value={webhookSubscription.description} autoSize={{ minRows: 2 }} disabled />
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:Secret")}>
									<Input.Password value={webhookSubscription.secret} disabled />
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:CreationTime")}>
									<Input value={formatToDateTime(webhookSubscription.creationTime)} disabled />
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:Webhooks")}>
									{webhookSubscription.webhooks?.map((w) => (
										<Tag key={w} color="blue">
											{w}
										</Tag>
									))}
								</Form.Item>

								<Form.Item label={$t("WebhooksManagement.DisplayName:Headers")}>
									<JsonEdit data={webhookSubscription.headers || ""} />
								</Form.Item>
							</Tabs.TabPane>
						)}
					</Tabs>
				</Form>
			)}
		</Drawer>
	);
};

export default WebhookSendAttemptDrawer;

// apps/vben5/packages/@abp/webhooks/src/components/send-attempts/WebhookSendAttemptDrawer.vue
<script setup lang="ts">
import type { TenantDto } from '@abp/saas';

import type { WebhookSendRecordDto, WebhookSubscriptionDto } from '../../types';

import { ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer } from '@vben/common-ui';

import { CodeEditor } from '@abp/components/codeeditor';
import { Tinymce } from '@abp/components/tinymce';
import { formatToDateTime, isNullOrWhiteSpace } from '@abp/core';
import { useHttpStatusCodeMap } from '@abp/request';
import { useTenantsApi } from '@abp/saas';
import {
  Checkbox,
  DatePicker,
  Form,
  Input,
  InputPassword,
  Tabs,
  Tag,
  Textarea,
} from 'ant-design-vue';

import { useSendAttemptsApi, useSubscriptionsApi } from '../../api';
import { WebhookSubscriptionPermissions } from '../../constants/permissions';

const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

type TabKey = 'basic' | 'event' | 'subscriber';

const activeTabKey = ref<TabKey>('basic');
const formModel = ref<WebhookSendRecordDto>();
const webhookSubscription = ref<WebhookSubscriptionDto>();
const webhookTenant = ref<TenantDto>();

const { hasAccessByCodes } = useAccess();
const { getApi } = useSendAttemptsApi();
const { getApi: getTenantApi } = useTenantsApi();
const { getApi: getSubscriptionApi } = useSubscriptionsApi();
const { getHttpStatusColor, httpStatusCodeMap } = useHttpStatusCodeMap();

const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-1/2',
  async onOpenChange(isOpen) {
    formModel.value = undefined;
    webhookTenant.value = undefined;
    webhookSubscription.value = undefined;
    if (isOpen) {
      await onInit();
    }
  },
});

async function onInit() {
  const dto = drawerApi.getData<WebhookSendRecordDto>();
  if (isNullOrWhiteSpace(dto.id)) {
    return;
  }
  const [sendRecordDto, subscriptionDto, tenantDto] = await Promise.all([
    getApi(dto.id),
    onInitSubscription(dto.webhookSubscriptionId),
    onInitTenant(dto.tenantId),
  ]);
  formModel.value = sendRecordDto;
  webhookSubscription.value = subscriptionDto;
  webhookTenant.value = tenantDto;
}

async function onInitSubscription(subscriptionId: string) {
  if (!hasAccessByCodes([WebhookSubscriptionPermissions.Default])) {
    return undefined;
  }
  return await getSubscriptionApi(subscriptionId);
}

async function onInitTenant(tenantId?: string) {
  // TODO: 公开saas模块常量?
  if (isNullOrWhiteSpace(tenantId) || !hasAccessByCodes(['AbpSaas.Tenants'])) {
    return undefined;
  }
  return await getTenantApi(tenantId);
}
</script>

<template>
  <Drawer :title="$t('WebhooksManagement.SendAttempts')">
    <Form :model="formModel" layout="vertical">
      <Tabs v-if="formModel" v-model:active-key="activeTabKey">
        <TabPane key="basic" :tab="$t('WebhooksManagement.BasicInfo')">
          <FormItem
            v-if="webhookTenant"
            name="tenantId"
            :label="$t('WebhooksManagement.DisplayName:TenantId')"
          >
            <Input :value="webhookTenant.name" disabled />
          </FormItem>
          <FormItem name="sendExactSameData">
            <Checkbox :checked="formModel.sendExactSameData" disabled>
              {{ $t('WebhooksManagement.DisplayName:SendExactSameData') }}
            </Checkbox>
          </FormItem>
          <FormItem
            name="creationTime"
            :label="$t('WebhooksManagement.DisplayName:CreationTime')"
          >
            <DatePicker
              class="w-full"
              value-format="YYYY-MM-DD HH:mm:ss"
              :value="formModel.creationTime"
              disabled
              show-time
            />
          </FormItem>
          <FormItem
            name="requestHeaders"
            :label="$t('WebhooksManagement.DisplayName:RequestHeaders')"
          >
            <CodeEditor :value="formModel.requestHeaders" readonly />
          </FormItem>
          <FormItem
            v-if="formModel.responseStatusCode"
            name="responseStatusCode"
            :label="$t('WebhooksManagement.DisplayName:ResponseStatusCode')"
          >
            <Tag :color="getHttpStatusColor(formModel.responseStatusCode)">
              {{ httpStatusCodeMap[formModel.responseStatusCode] }}
            </Tag>
          </FormItem>
          <FormItem
            name="responseHeaders"
            :label="$t('WebhooksManagement.DisplayName:ResponseHeaders')"
          >
            <CodeEditor :value="formModel.responseHeaders" readonly />
          </FormItem>
          <FormItem
            name="response"
            :label="$t('WebhooksManagement.DisplayName:Response')"
          >
            <Tinymce
              :value="formModel.response"
              :toolbar="[]"
              :plugins="[]"
              readonly
            />
          </FormItem>
        </TabPane>
        <TabPane key="event" :tab="$t('WebhooksManagement.WebhookEvent')">
          <FormItem
            name="webhookEventId"
            :label="$t('WebhooksManagement.DisplayName:WebhookEventId')"
          >
            <Input :value="formModel.webhookEventId" disabled />
          </FormItem>
          <FormItem
            :name="['webhookEvent', 'webhookName']"
            :label="$t('WebhooksManagement.DisplayName:WebhookName')"
          >
            <Input :value="formModel.webhookEvent.webhookName" disabled />
          </FormItem>
          <FormItem
            :name="['webhookEvent', 'creationTime']"
            :label="$t('WebhooksManagement.DisplayName:CreationTime')"
          >
            <DatePicker
              class="w-full"
              value-format="YYYY-MM-DD HH:mm:ss"
              :value="formModel.webhookEvent.creationTime"
              disabled
              show-time
            />
          </FormItem>
          <FormItem
            :name="['webhookEvent', 'data']"
            :label="$t('WebhooksManagement.DisplayName:Data')"
          >
            <CodeEditor :value="formModel.webhookEvent.data" readonly />
          </FormItem>
        </TabPane>
        <TabPane
          v-if="webhookSubscription"
          key="subscriber"
          :tab="$t('WebhooksManagement.Subscriptions')"
        >
          <FormItem>
            <Checkbox :checked="webhookSubscription.isActive" disabled>
              {{ $t('WebhooksManagement.DisplayName:IsActive') }}
            </Checkbox>
          </FormItem>
          <FormItem
            :label="$t('WebhooksManagement.DisplayName:WebhookSubscriptionId')"
          >
            <Input :value="webhookSubscription.id" disabled />
          </FormItem>
          <FormItem :label="$t('WebhooksManagement.DisplayName:WebhookUri')">
            <Input :value="webhookSubscription.webhookUri" disabled />
          </FormItem>
          <FormItem :label="$t('WebhooksManagement.DisplayName:Description')">
            <Textarea
              :auto-size="{ minRows: 3 }"
              :value="webhookSubscription.description"
              disabled
            />
          </FormItem>
          <FormItem :label="$t('WebhooksManagement.DisplayName:Secret')">
            <InputPassword :value="webhookSubscription.secret" disabled />
          </FormItem>
          <FormItem :label="$t('WebhooksManagement.DisplayName:CreationTime')">
            <DatePicker
              class="w-full"
              value-format="YYYY-MM-DD HH:mm:ss"
              :value="formatToDateTime(webhookSubscription.creationTime)"
              disabled
              show-time
            />
          </FormItem>
          <FormItem :label="$t('WebhooksManagement.DisplayName:Webhooks')">
            <template
              v-for="webhook in webhookSubscription.webhooks"
              :key="webhook"
            >
              <Tag color="blue">
                {{ webhook }}
              </Tag>
            </template>
          </FormItem>
          <FormItem :label="$t('WebhooksManagement.DisplayName:Headers')">
            <CodeEditor :value="webhookSubscription.headers" readonly />
          </FormItem>
        </TabPane>
      </Tabs>
    </Form>
  </Drawer>
</template>

<style scoped></style>
