// apps/react-admin/src/components/abp/account/basic-settings.tsx
import { useEffect, useState } from "react";
import { Card, Form, Input, Avatar, Upload, Button } from "antd";
import { UploadOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { ProfileDto, UpdateProfileDto } from "#/account/profile";
import type { UploadChangeParam, UploadProps } from "antd/es/upload";
import { useUserInfo } from "@/store/userStore";
import { faker } from "@faker-js/faker";
import { useAbpSettings } from "@/hooks/abp/use-abp-settings";

interface Props {
	profile: ProfileDto;
	onSubmit: (profile: UpdateProfileDto) => void;
}

const BasicSettings: React.FC<Props> = ({ profile, onSubmit }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const { isTrue } = useAbpSettings();
	const userInfo = useUserInfo();

	const [formModel, setFormModel] = useState<ProfileDto>({} as ProfileDto);

	useEffect(() => {
		setFormModel({ ...profile });
		form.setFieldsValue(profile);
	}, [profile]);

	const handleAvatarChange = (_param: UploadChangeParam) => {
		// TODO: Wait for OSS module integration
		console.warn("Waiting for OSS module integration...");
	};

	const handleBeforeUpload: UploadProps["beforeUpload"] = () => {
		console.warn("Waiting for OSS module integration...");
		return false;
	};

	const handleSubmit = () => {
		onSubmit(formModel);
	};

	return (
		<Card bordered={false} title={$t("abp.account.settings.basic.title")}>
			<div className="flex flex-row">
				<div className="basis-2/4">
					<Form
						form={form}
						labelCol={{ span: 6 }}
						wrapperCol={{ span: 18 }}
						onValuesChange={(_, values) => setFormModel(values)}
					>
						<Form.Item label={$t("AbpAccount.DisplayName:UserName")} name="userName" rules={[{ required: true }]}>
							<Input disabled={!isTrue("Abp.Identity.User.IsUserNameUpdateEnabled")} autoComplete="off" />
						</Form.Item>
						<Form.Item label={$t("AbpAccount.DisplayName:Email")} name="email" rules={[{ required: true }]}>
							<Input disabled={!isTrue("Abp.Identity.User.IsEmailUpdateEnabled")} autoComplete="off" type="email" />
						</Form.Item>
						<Form.Item label={$t("AbpAccount.DisplayName:Surname")} name="surname">
							<Input autoComplete="off" />
						</Form.Item>
						<Form.Item label={$t("AbpAccount.DisplayName:Name")} name="name">
							<Input autoComplete="off" />
						</Form.Item>
						<Form.Item>
							<div className="flex flex-col items-center">
								<Button style={{ minWidth: 100 }} type="primary" onClick={handleSubmit}>
									{$t("AbpUi.Submit")}
								</Button>
							</div>
						</Form.Item>
					</Form>
				</div>
				<div className="basis-2/4">
					<div className="flex flex-col items-center">
						<p>{$t("AbpUi.ProfilePicture")}</p>
						<Avatar size={100} icon={<img src={userInfo?.avatar ?? faker.image.avatarGitHub()} alt="" />} />
						<Upload beforeUpload={handleBeforeUpload} fileList={[]} name="file" onChange={handleAvatarChange}>
							<Button className="mt-4">
								<UploadOutlined />
								{$t("abp.account.settings.changeAvatar")}
							</Button>
						</Upload>
					</div>
				</div>
			</div>
		</Card>
	);
};

export default BasicSettings;

// apps/vben5/packages/@abp/account/src/components/components/BasicSettings.vue
<script setup lang="ts">
import type { UploadChangeParam } from 'ant-design-vue';
import type { FileType } from 'ant-design-vue/es/upload/interface';

import type { ProfileDto, UpdateProfileDto } from '../../types/profile';

import { computed, ref, toValue, watchEffect } from 'vue';

import { $t } from '@vben/locales';
import { preferences } from '@vben/preferences';
import { useUserStore } from '@vben/stores';

import { useSettings } from '@abp/core';
import { UploadOutlined } from '@ant-design/icons-vue';
import { Avatar, Button, Card, Form, Input, Upload } from 'ant-design-vue';

const props = defineProps<{
  profile: ProfileDto;
}>();
const emits = defineEmits<{
  (event: 'submit', profile: UpdateProfileDto): void;
}>();
const FormItem = Form.Item;

const formModel = ref({} as ProfileDto);

const userStore = useUserStore();
const { isTrue } = useSettings();

const avatar = computed(() => {
  return userStore.userInfo?.avatar ?? preferences.app.defaultAvatar;
});
function onAvatarChange(_param: UploadChangeParam) {
  // TODO: oss模块集成后完成
  console.warn('等待oss模块集成完成...');
}
function onBeforeUpload(_file: FileType) {
  console.warn('等待oss模块集成完成...');
  return false;
}
function onSubmit() {
  emits('submit', toValue(formModel));
}
watchEffect(() => {
  formModel.value = { ...props.profile };
});
</script>

<template>
  <Card :bordered="false" :title="$t('abp.account.settings.basic.title')">
    <div class="flex flex-row">
      <div class="basis-2/4">
        <Form
          :label-col="{ span: 6 }"
          :model="formModel"
          :wrapper-col="{ span: 18 }"
        >
          <FormItem
            :label="$t('AbpAccount.DisplayName:UserName')"
            name="userName"
            required
          >
            <Input
              v-model:value="formModel.userName"
              :disabled="!isTrue('Abp.Identity.User.IsUserNameUpdateEnabled')"
              autocomplete="off"
            />
          </FormItem>
          <FormItem
            :label="$t('AbpAccount.DisplayName:Email')"
            name="email"
            required
          >
            <Input
              v-model:value="formModel.email"
              :disabled="!isTrue('Abp.Identity.User.IsEmailUpdateEnabled')"
              autocomplete="off"
              type="email"
            />
          </FormItem>
          <FormItem
            :label="$t('AbpAccount.DisplayName:Surname')"
            name="surname"
          >
            <Input v-model:value="formModel.surname" autocomplete="off" />
          </FormItem>
          <FormItem :label="$t('AbpAccount.DisplayName:Name')" name="name">
            <Input v-model:value="formModel.name" autocomplete="off" />
          </FormItem>
          <FormItem>
            <div class="flex flex-col items-center">
              <Button style="min-width: 100px" type="primary" @click="onSubmit">
                {{ $t('AbpUi.Submit') }}
              </Button>
            </div>
          </FormItem>
        </Form>
      </div>
      <div class="basis-2/4">
        <div class="flex flex-col items-center">
          <p>{{ $t('AbpUi.ProfilePicture') }}</p>
          <Avatar :size="100">
            <template #icon>
              <img :src="avatar" alt="" />
            </template>
          </Avatar>
          <Upload
            :before-upload="onBeforeUpload"
            :file-list="[]"
            name="file"
            @change="onAvatarChange"
          >
            <Button class="mt-4">
              <UploadOutlined />
              {{ $t('abp.account.settings.changeAvatar') }}
            </Button>
          </Upload>
        </div>
      </div>
    </div>
  </Card>
</template>

<style scoped></style>
