// apps/react-admin/src/components/abp/account/email-confirm-modal.tsx
import { useState } from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import { useMutation } from "@tanstack/react-query";
import { confirmEmailApi } from "@/api/account/profile";
import { toast } from "sonner";

interface Props {
	visible: boolean;
	onSuccess: () => void;
	onClose: () => void;
	initialState: {
		confirmToken: string;
		email: string;
		returnUrl?: string;
		userId: string;
	};
}

const EmailConfirmModal: React.FC<Props> = ({ visible, onClose, onSuccess, initialState }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [confirmLoading, setConfirmLoading] = useState(false);

	const { mutateAsync: confirmEmail } = useMutation({
		mutationFn: confirmEmailApi,
		onSuccess: () => {
			toast.success($t("AbpAccount.YourEmailIsSuccessfullyConfirm"));
			onSuccess();
			onClose();
			if (initialState.returnUrl) {
				window.location.href = initialState.returnUrl;
			}
		},
		onSettled: () => {
			setConfirmLoading(false);
		},
	});

	const handleSubmit = async () => {
		try {
			setConfirmLoading(true);
			await confirmEmail({
				confirmToken: decodeURIComponent(initialState.confirmToken),
			});
		} catch (error) {
			console.error("Email confirmation failed:", error);
		}
	};

	return (
		<Modal
			open={visible}
			title={$t("AbpAccount.EmailConfirm")}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={confirmLoading}
		>
			<Form form={form} initialValues={initialState}>
				<Form.Item label={$t("AbpAccount.DisplayName:Email")} name="email">
					<Input readOnly />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default EmailConfirmModal;

// apps/vben5/packages/@abp/account/src/components/components/EmailConfirmModal.vue
<script setup lang="ts">
import { ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Form, Input, message } from 'ant-design-vue';

import { useProfileApi } from '../../api/useProfileApi';

const FormItem = Form.Item;

interface State {
  confirmToken: string;
  email: string;
  returnUrl?: string;
  userId: string;
}
const formModel = ref({} as State);

const { cancel, confirmEmailApi } = useProfileApi();
const [Modal, modalApi] = useVbenModal({
  onClosed: cancel,
  onConfirm: onSubmit,
  onOpenChange(isOpen) {
    if (isOpen) {
      const state = modalApi.getData<State>();
      formModel.value = state;
    }
  },
  title: $t('AbpAccount.EmailConfirm'),
});
async function onSubmit() {
  try {
    modalApi.setState({ confirmLoading: true });
    await confirmEmailApi({
      confirmToken: encodeURIComponent(formModel.value.confirmToken),
    });
    message.success($t('AbpAccount.YourEmailIsSuccessfullyConfirm'));
    modalApi.close();
    if (formModel.value.returnUrl) {
      window.location.href = formModel.value.returnUrl;
    }
  } finally {
    modalApi.setState({ confirmLoading: false });
  }
}
</script>

<template>
  <Modal>
    <Form :model="formModel">
      <FormItem :label="$t('AbpAccount.DisplayName:Email')">
        <Input v-model:value="formModel.email" readonly />
      </FormItem>
    </Form>
  </Modal>
</template>

<style scoped></style>
