// apps/react-admin/src/components/abp/account/session-settings.tsx
import { Card, Modal } from "antd";
import { useTranslation } from "react-i18next";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { IdentitySessionDto } from "#/management/identity/sessions";
import { getSessionsApi, revokeSessionApi } from "@/api/account/my-session";
import { toast } from "sonner";
import UserSessionTable from "@/pages/management/identity/sessions/user-session-table";

const SessionSettings: React.FC = () => {
	const { t: $t } = useTranslation();
	const [modal, contextHolder] = Modal.useModal();
	const queryClient = useQueryClient();

	// Fetch sessions
	const { data: sessions = [] } = useQuery({
		queryKey: ["mySessions"],
		queryFn: async () => {
			const { items } = await getSessionsApi();
			return items;
		},
	});

	// Revoke session mutation
	const { mutateAsync: revokeSession } = useMutation({
		mutationFn: revokeSessionApi,
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ["mySessions"] });
			toast.success($t("AbpIdentity.SuccessfullyRevoked"));
		},
	});

	const handleRevoke = (session: IdentitySessionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpIdentity.SessionWillBeRevokedMessage"),
			centered: true,
			onOk: () => revokeSession(session.sessionId),
		});
	};

	return (
		<>
			{contextHolder}
			<Card bordered={false} title={$t("abp.account.settings.sessionSettings")}>
				<UserSessionTable sessions={sessions} onRevoke={handleRevoke} />
			</Card>
		</>
	);
};

export default SessionSettings;

// apps/vben5/packages/@abp/account/src/components/components/SessionSettings.vue
<script setup lang="ts">
import type { IdentitySessionDto } from '@abp/identity';

import { onMounted, ref } from 'vue';

import { $t } from '@vben/locales';

import { UserSessionTable } from '@abp/identity';
import { Card, message, Modal } from 'ant-design-vue';

import { useMySessionApi } from '../../api/useMySessionApi';

const { cancel, getSessionsApi, revokeSessionApi } = useMySessionApi();

const sessions = ref<IdentitySessionDto[]>([]);

async function getSessions() {
  const { items } = await getSessionsApi();
  sessions.value = items;
}

async function onRevoke(session: IdentitySessionDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpIdentity.SessionWillBeRevokedMessage'),
    iconType: 'warning',
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await revokeSessionApi(session.sessionId);
      message.success($t('AbpIdentity.SuccessfullyRevoked'));
      await getSessions();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(getSessions);
</script>

<template>
  <Card :bordered="false" :title="$t('abp.account.settings.sessionSettings')">
    <UserSessionTable :sessions="sessions" @revoke="onRevoke" />
  </Card>
</template>

<style scoped></style>
