// apps/vben5/packages/@abp/openiddict/src/components/tokens/TokenTable.vue
<script setup lang="ts">
import type { VxeGridProps } from '@abp/ui';
import type { SelectValue } from 'ant-design-vue/es/select';

import type { VbenFormProps } from '@vben/common-ui';

import type { OpenIddictApplicationDto } from '../../types';
import type { OpenIddictTokenDto } from '../../types/tokens';

import { defineAsyncComponent, h, onMounted, ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import { DeleteOutlined, EditOutlined } from '@ant-design/icons-vue';
import { Button, message, Modal, Select } from 'ant-design-vue';
import debounce from 'lodash.debounce';

import { useApplicationsApi } from '../../api/useApplicationsApi';
import { useTokensApi } from '../../api/useTokensApi';
import { TokensPermissions } from '../../constants/permissions';

defineOptions({
  name: 'TokenTable',
});

const CheckIcon = createIconifyIcon('ant-design:check-outlined');
const CloseIcon = createIconifyIcon('ant-design:close-outlined');

const { hasAccessByCodes } = useAccess();
const { getPagedListApi: getApplications } = useApplicationsApi();
const { deleteApi, getPagedListApi } = useTokensApi();

const applications = ref<OpenIddictApplicationDto[]>([]);
const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: true,
  collapsedRows: 2,
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 在label后显示一个冒号
    colon: true,
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  fieldMappingTime: [
    ['creationTime', ['beginCreationTime', 'endCreationTime'], 'YYYY-MM-DD'],
    [
      'expirationDate',
      ['beginExpirationDate', 'endExpirationDate'],
      'YYYY-MM-DD',
    ],
  ],
  handleReset: onFormReset,
  schema: [
    {
      component: 'Select',
      fieldName: 'clientId',
      formItemClass: 'col-span-1/3 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:ClientId'),
    },
    {
      component: 'RangePicker',
      fieldName: 'creationTime',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:CreationTime'),
    },
    {
      component: 'RangePicker',
      fieldName: 'expirationDate',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:ExpirationDate'),
    },
    {
      component: 'Input',
      fieldName: 'subject',
      formItemClass: 'col-span-1/3 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:Subject'),
    },
    {
      component: 'Input',
      fieldName: 'status',
      formItemClass: 'col-span-1/3 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:Status'),
    },
    {
      component: 'Input',
      fieldName: 'type',
      formItemClass: 'col-span-1/3 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:Type'),
    },
    {
      component: 'Input',
      fieldName: 'referenceId',
      formItemClass: 'col-span-1/3 items-baseline',
      label: $t('AbpOpenIddict.DisplayName:ReferenceId'),
    },
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<OpenIddictTokenDto> = {
  columns: [
    {
      align: 'left',
      field: 'applicationId',
      minWidth: 300,
      title: $t('AbpOpenIddict.DisplayName:ApplicationId'),
    },
    {
      align: 'left',
      field: 'subject',
      minWidth: 300,
      title: $t('AbpOpenIddict.DisplayName:Subject'),
    },
    {
      align: 'left',
      field: 'type',
      minWidth: 150,
      title: $t('AbpOpenIddict.DisplayName:Type'),
    },
    {
      align: 'left',
      field: 'status',
      minWidth: 150,
      title: $t('AbpOpenIddict.DisplayName:Status'),
    },
    {
      align: 'left',
      field: 'creationDate',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      minWidth: 200,
      title: $t('AbpOpenIddict.DisplayName:CreationDate'),
    },
    {
      align: 'left',
      field: 'expirationDate',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      minWidth: 200,
      title: $t('AbpOpenIddict.DisplayName:ExpirationDate'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: hasAccessByCodes([TokensPermissions.Delete]),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        return await getPagedListApi({
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};
const [TokenModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./TokenModal.vue')),
});

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridOptions,
});

const onSearchClient = debounce(async (filter?: string) => {
  const { items } = await getApplications({
    filter,
    maxResultCount: 25,
  });
  applications.value = items;
}, 500);

function onChangeClient(value?: SelectValue) {
  gridApi.formApi.setFieldValue('clientId', value);
}

function onUpdate(row: OpenIddictTokenDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: OpenIddictTokenDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessage')}`,
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onFormReset() {
  gridApi.formApi.resetForm();
  gridApi.formApi.submitForm();
}
onMounted(onSearchClient);
</script>

<template>
  <Grid :table-title="$t('AbpOpenIddict.Tokens')">
    <template #form-clientId="{ modelValue }">
      <Select
        :default-active-first-option="false"
        :field-names="{ label: 'clientId', value: 'id' }"
        :filter-option="false"
        :options="applications"
        :placeholder="$t('ui.placeholder.select')"
        :value="modelValue"
        allow-clear
        class="w-full"
        show-search
        @change="onChangeClient"
        @search="onSearchClient"
      />
    </template>
    <template #required="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.required" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #static="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.isStatic" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <div class="basis-1/2">
          <Button
            :icon="h(EditOutlined)"
            block
            type="link"
            @click="onUpdate(row)"
          >
            {{ $t('AbpUi.Edit') }}
          </Button>
        </div>
        <div class="basis-1/2">
          <Button
            :icon="h(DeleteOutlined)"
            block
            danger
            type="link"
            v-access:code="[TokensPermissions.Delete]"
            @click="onDelete(row)"
          >
            {{ $t('AbpUi.Delete') }}
          </Button>
        </div>
      </div>
    </template>
  </Grid>
  <TokenModal @change="() => gridApi.query()" />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/openiddict/tokens/token-table.tsx
import { useRef, useState, useTransition } from "react";
import { Button, Card, Modal, Select, Space } from "antd";
import { EditOutlined, DeleteOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import type { OpenIddictTokenDto } from "#/openiddict/tokens";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { formatToDateTime } from "@/utils/abp";
import { getPagedListApi as getApplications } from "@/api/openiddict/applications";
import { deleteApi, getPagedListApi } from "@/api/openiddict/tokens";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { TokensPermissions } from "@/constants/openiddict/permissions";
import TokenModal from "./token-modal";
import { toast } from "sonner";

const TokenTable = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();

	// Modal states
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedToken, setSelectedToken] = useState<OpenIddictTokenDto>();

	const [searchText, setSearchText] = useState("");
	const [isPending, startTransition] = useTransition();

	const { data: applications = [] } = useQuery({
		queryKey: ["applications", searchText],
		queryFn: () =>
			getApplications({
				maxResultCount: 25,
				filter: searchText,
			}).then((res) => res.items),
		enabled: !isPending,
	});

	// Delete mutation
	const { mutateAsync: deleteToken } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["tokens"] });
			actionRef.current?.reload();
		},
	});

	const handleDelete = (token: OpenIddictTokenDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: () => deleteToken(token.id),
		});
	};

	const columns: ProColumns<OpenIddictTokenDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ClientId"),
			dataIndex: "clientId",
			valueType: "text",
			hideInTable: true,
			renderFormItem: () => (
				<Select
					showSearch
					allowClear
					filterOption={false}
					options={applications.map((app) => ({
						label: app.clientId,
						value: app.id,
					}))}
					onSearch={(value) => {
						startTransition(() => {
							setSearchText(value);
						});
					}}
					placeholder={$t("ui.placeholder.select")}
				/>
			),
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ApplicationId"),
			dataIndex: "applicationId",
			width: 300,
			ellipsis: true,
			hideInSearch: true,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:Subject"),
			dataIndex: "subject",
			ellipsis: true,
			width: 300,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:Type"),
			dataIndex: "type",
			width: 150,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:Status"),
			dataIndex: "status",
			width: 150,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:CreationDate"),
			dataIndex: "creationDate",
			render: (_, record) => (record.creationDate ? formatToDateTime(record.creationDate) : "-"),
			width: 200,
			valueType: "dateRange",
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ExpirationDate"),
			dataIndex: "expirationDate",
			render: (_, record) => (record.expirationDate ? formatToDateTime(record.expirationDate) : "-"),
			width: 200,
			valueType: "dateRange",
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ReferenceId"),
			dataIndex: "referenceId",
			valueType: "text",
			hideInTable: true,
		},

		hasAccessByCodes([TokensPermissions.Delete])
			? {
					title: $t("AbpUi.Actions"),
					width: 220,
					fixed: "right",
					hideInSearch: true,
					render: (_, record) => (
						<Space>
							<Button
								type="link"
								icon={<EditOutlined />}
								onClick={() => {
									setSelectedToken(record);
									setModalVisible(true);
								}}
							>
								{$t("AbpUi.Edit")}
							</Button>
							<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
								{$t("AbpUi.Delete")}
							</Button>
						</Space>
					),
				}
			: {},
	];

	return (
		<>
			{contextHolder}
			<Space direction="vertical" size="large" className="w-full">
				<Card>
					<ProTable<OpenIddictTokenDto>
						headerTitle={$t("AbpOpenIddict.Tokens")}
						actionRef={actionRef}
						rowKey="id"
						columns={columns}
						request={async (params, sorter) => {
							const { current, pageSize, creationDate, expirationDate, filter, ...filters } = params;
							const [startCreationTime, endCreationTime] = creationDate || [];
							const [startExpirationTime, endExpirationTime] = expirationDate || [];
							const query = await queryClient.fetchQuery({
								queryKey: ["tokens", params, sorter],
								queryFn: () =>
									getPagedListApi({
										maxResultCount: pageSize,
										skipCount: ((current || 1) - 1) * (pageSize || 0),
										beginCreationTime: startCreationTime,
										endCreationTime: endCreationTime,
										beginExpirationDate: startExpirationTime,
										endExpirationDate: endExpirationTime,
										filter: filter,
										...filters,
									}),
							});

							return {
								data: query.items,
								success: true,
								total: query.totalCount,
							};
						}}
						pagination={{
							showSizeChanger: true,
						}}
						search={{
							defaultCollapsed: true,
							labelWidth: "auto",
						}}
						scroll={{ x: "max-content" }}
					/>
				</Card>
			</Space>
			<TokenModal
				visible={modalVisible}
				tokenId={selectedToken?.id}
				onClose={() => {
					setModalVisible(false);
					setSelectedToken(undefined);
				}}
			/>
		</>
	);
};

export default TokenTable;
