// apps/vben5/packages/@abp/openiddict/src/components/tokens/TokenModal.vue
<script setup lang="ts">
import type { OpenIddictTokenDto } from '../../types/tokens';

import { useAccess } from '@vben/access';
import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  type IdentityUserDto,
  userLookupApi,
  UserLookupPermissions,
} from '@abp/identity';
import { CodeEditor } from '@abp/ui';

import { getApi as getApplication } from '../../api/applications';
import { getApi as getAuthorization } from '../../api/tokens';

defineOptions({
  name: 'TokenModal',
});

const { hasAccessByCodes } = useAccess();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  schema: [
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'applicationId',
      label: $t('AbpOpenIddict.DisplayName:ApplicationId'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'authorizationId',
      label: $t('AbpOpenIddict.DisplayName:AuthorizationId'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'subject',
      label: $t('AbpOpenIddict.DisplayName:Subject'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'type',
      label: $t('AbpOpenIddict.DisplayName:Type'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'status',
      label: $t('AbpOpenIddict.DisplayName:Status'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'creationDate',
      label: $t('AbpOpenIddict.DisplayName:CreationDate'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'expirationDate',
      label: $t('AbpOpenIddict.DisplayName:ExpirationDate'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'redemptionDate',
      label: $t('AbpOpenIddict.DisplayName:RedemptionDate'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'referenceId',
      label: $t('AbpOpenIddict.DisplayName:ReferenceId'),
    },
    {
      component: 'Input',
      componentProps: {
        readonly: true,
      },
      fieldName: 'payload',
      label: $t('AbpOpenIddict.DisplayName:Payload'),
    },
  ],

  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      try {
        modalApi.setState({ loading: true });
        const { id } = modalApi.getData<OpenIddictTokenDto>();
        await onGet(id);
      } finally {
        modalApi.setState({ loading: false });
      }
    }
  },
  showConfirmButton: false,
  title: $t('AbpOpenIddict.Tokens'),
});

async function onGet(id: string) {
  const authorization = await getAuthorization(id);
  const application = await getApplication(authorization.applicationId!);
  let subjectInfo: IdentityUserDto | undefined;
  if (hasAccessByCodes([UserLookupPermissions.Default])) {
    subjectInfo = await userLookupApi.findByIdApi(authorization.subject!);
  }
  formApi.setValues({
    ...authorization,
    applicationId: `${application.clientId}(${authorization.applicationId})`,
    subject: subjectInfo?.userName
      ? `${subjectInfo.userName}(${authorization.subject})`
      : authorization.subject,
  });
}
</script>

<template>
  <Modal>
    <Form>
      <template #payload="{ modelValue }">
        <CodeEditor :value="modelValue" readonly />
      </template>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/openiddict/tokens/token-modal.tsx
import { Form, Input, Modal } from "antd";
import { useTranslation } from "react-i18next";
import { useQuery } from "@tanstack/react-query";
import type { IdentityUserDto } from "#/management/identity/user";
import { getApi as getApplication } from "@/api/openiddict/applications";
import { getApi as getToken } from "@/api/openiddict/tokens";
import { findByIdApi } from "@/api/management/identity/user-lookup";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { UserLookupPermissions } from "@/constants/management/identity/permissions";
import JsonEdit from "@/components/abp/common/json-edit";
import { useEffect } from "react";
import { CircleLoading } from "@/components/loading";

interface Props {
	visible: boolean;
	tokenId?: string;
	onClose: () => void;
}

const TokenModal: React.FC<Props> = ({ visible, tokenId, onClose }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	// 获取Token详情和关联数据
	const { data: tokenData, isLoading } = useQuery({
		queryKey: ["token", tokenId],
		queryFn: async () => {
			if (!tokenId) {
				return Promise.reject(new Error("tokenId is undefined"));
			}

			const token = await getToken(tokenId);
			if (!token.applicationId) {
				return Promise.reject(new Error("token.applicationId is undefined"));
			}
			const application = await getApplication(token.applicationId);

			let subjectInfo: IdentityUserDto | undefined;
			if (hasAccessByCodes([UserLookupPermissions.Default])) {
				if (token.subject) {
					subjectInfo = await findByIdApi(token.subject);
				}
			}

			return {
				...token,
				applicationId: `${application.clientId}(${token.applicationId})`,
				subject: subjectInfo?.userName ? `${subjectInfo.userName}(${token.subject})` : token.subject,
			};
		},
		enabled: visible && !!tokenId,
	});

	// 更新表单数据
	useEffect(() => {
		if (tokenData && tokenData.id === tokenId) {
			form.setFieldsValue(tokenData);
		}
	}, [tokenData]);

	const formItems = [
		{
			name: "applicationId",
			label: $t("AbpOpenIddict.DisplayName:ApplicationId"),
			component: Input,
		},
		{
			name: "authorizationId",
			label: $t("AbpOpenIddict.DisplayName:AuthorizationId"),
			component: Input,
		},
		{
			name: "subject",
			label: $t("AbpOpenIddict.DisplayName:Subject"),
			component: Input,
		},
		{
			name: "type",
			label: $t("AbpOpenIddict.DisplayName:Type"),
			component: Input,
		},
		{
			name: "status",
			label: $t("AbpOpenIddict.DisplayName:Status"),
			component: Input,
		},
		{
			name: "creationDate",
			label: $t("AbpOpenIddict.DisplayName:CreationDate"),
			component: Input,
		},
		{
			name: "expirationDate",
			label: $t("AbpOpenIddict.DisplayName:ExpirationDate"),
			component: Input,
		},
		{
			name: "redemptionDate",
			label: $t("AbpOpenIddict.DisplayName:RedemptionDate"),
			component: Input,
		},
		{
			name: "referenceId",
			label: $t("AbpOpenIddict.DisplayName:ReferenceId"),
			component: Input,
		},
		{
			name: "payload",
			label: $t("AbpOpenIddict.DisplayName:Payload"),
			render: (value: string) => <JsonEdit data={value || ""} />,
		},
	];

	return (
		<Modal open={visible} title={$t("AbpOpenIddict.Tokens")} onCancel={onClose} footer={null} width="50%">
			{!!tokenId && visible && isLoading ? (
				<CircleLoading />
			) : (
				<Form
					form={form}
					layout="vertical"
					disabled // 表单只读
				>
					{formItems.map((item) => (
						<Form.Item key={item.name} name={item.name} label={item.label}>
							{item.render ? (
								item.render(form.getFieldValue(item.name))
							) : (
								<item.component className="w-full" readOnly />
							)}
						</Form.Item>
					))}
				</Form>
			)}
		</Modal>
	);
};

export default TokenModal;
