// apps/vben5/packages/@abp/auditing/src/components/audit-logs/AuditLogTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { AuditLogDto } from '../../types/audit-logs';

import { defineAsyncComponent, h, ref, toValue } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import { DeleteOutlined, EditOutlined } from '@ant-design/icons-vue';
import { Button, message, Modal, Tag } from 'ant-design-vue';

import { useAuditLogsApi } from '../../api/useAuditLogsApi';
import { AuditLogPermissions } from '../../constants/permissions';
import { useAuditlogs } from '../../hooks/useAuditlogs';
import { httpMethodOptions, httpStatusCodeOptions } from './mapping';

defineOptions({
  name: 'AuditLogTable',
});
const { deleteApi, deleteManyApi, getPagedListApi } = useAuditLogsApi();

const selectedKeys = ref<string[]>([]);
const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: true,
  collapsedRows: 2,
  fieldMappingTime: [
    [
      'executionTime',
      ['startTime', 'endTime'],
      ['YYYY-MM-DD HH:mm:ss', 'YYYY-MM-DD HH:mm:ss'],
    ],
  ],
  schema: [
    {
      component: 'RangePicker',
      componentProps: {
        showTime: true,
      },
      fieldName: 'executionTime',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpAuditLogging.ExecutionTime'),
    },
    {
      component: 'Input',
      fieldName: 'url',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpAuditLogging.RequestUrl'),
    },
    {
      component: 'Select',
      componentProps: {
        options: httpStatusCodeOptions,
      },
      fieldName: 'httpStatusCode',
      label: $t('AbpAuditLogging.HttpStatusCode'),
    },
    {
      component: 'Select',
      componentProps: {
        options: httpMethodOptions,
      },
      fieldName: 'httpMethod',
      label: $t('AbpAuditLogging.HttpMethod'),
    },
    {
      component: 'Input',
      fieldName: 'applicationName',
      label: $t('AbpAuditLogging.ApplicationName'),
    },
    {
      component: 'Input',
      fieldName: 'userName',
      label: $t('AbpAuditLogging.UserName'),
    },
    {
      component: 'Input',
      fieldName: 'clientId',
      label: $t('AbpAuditLogging.ClientId'),
    },
    {
      component: 'Input',
      fieldName: 'clientIpAddress',
      label: $t('AbpAuditLogging.ClientIpAddress'),
    },
    {
      component: 'InputNumber',
      fieldName: 'minExecutionDuration',
      label: $t('AbpAuditLogging.MinExecutionDuration'),
      labelWidth: 150,
    },
    {
      component: 'InputNumber',
      fieldName: 'maxExecutionDuration',
      label: $t('AbpAuditLogging.MaxExecutionDuration'),
      labelWidth: 150,
    },
    {
      component: 'Input',
      fieldName: 'correlationId',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpAuditLogging.CorrelationId'),
    },
    {
      component: 'Checkbox',
      componentProps: {
        render: () => {
          return h('span', $t('AbpAuditLogging.HasException'));
        },
      },
      fieldName: 'hasException',
      label: $t('AbpAuditLogging.HasException'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
  wrapperClass: 'grid-cols-4',
};

const gridOptions: VxeGridProps<AuditLogDto> = {
  columns: [
    {
      align: 'center',
      type: 'checkbox',
    },
    {
      align: 'left',
      field: 'url',
      slots: { default: 'url' },
      sortable: true,
      title: $t('AbpAuditLogging.RequestUrl'),
      width: 500,
    },
    {
      align: 'left',
      field: 'userName',
      sortable: true,
      title: $t('AbpAuditLogging.UserName'),
      width: 120,
    },
    {
      align: 'left',
      field: 'executionTime',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      sortable: true,
      title: $t('AbpAuditLogging.ExecutionTime'),
      width: 150,
    },
    {
      align: 'left',
      field: 'executionDuration',
      sortable: true,
      title: $t('AbpAuditLogging.ExecutionDuration'),
      width: 140,
    },
    {
      align: 'left',
      field: 'clientId',
      sortable: true,
      title: $t('AbpAuditLogging.ClientId'),
      width: 150,
    },
    {
      align: 'left',
      field: 'clientIpAddress',
      slots: { default: 'clientIpAddress' },
      sortable: true,
      title: $t('AbpAuditLogging.ClientIpAddress'),
      width: 150,
    },
    {
      align: 'left',
      field: 'applicationName',
      sortable: true,
      title: $t('AbpAuditLogging.ApplicationName'),
      width: 160,
    },
    {
      align: 'left',
      field: 'correlationId',
      sortable: true,
      title: $t('AbpAuditLogging.CorrelationId'),
      width: 160,
    },
    {
      align: 'left',
      field: 'tenantName',
      sortable: true,
      title: $t('AbpAuditLogging.TenantName'),
      width: 100,
    },
    {
      align: 'left',
      field: 'browserInfo',
      sortable: true,
      title: $t('AbpAuditLogging.BrowserInfo'),
      width: 300,
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        return await getPagedListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  sortConfig: {
    remote: true,
    allowBtn: true,
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<AuditLogDto> = {
  checkboxAll: (params) => {
    selectedKeys.value = params.records.map((x) => x.id);
  },
  checkboxChange: (params) => {
    selectedKeys.value = params.records.map((x) => x.id);
  },
  sortChange: () => {
    gridApi.query();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const { getHttpMethodColor, getHttpStatusCodeColor } = useAuditlogs();
const [AuditLogDrawer, logDrawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(
    () => import('./AuditLogDrawer.vue'),
  ),
});

function onUpdate(row: AuditLogDto) {
  logDrawerApi.setData(row);
  logDrawerApi.open();
}

async function onDelete(row: AuditLogDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessage'),
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onBulkDelete() {
  Modal.confirm({
    centered: true,
    content: $t('component.table.selectedItemWellBeDeleted'),
    onOk: async () => {
      await deleteManyApi({
        ids: toValue(selectedKeys),
      });
      selectedKeys.value = [];
      message.success($t('AbpUi.DeletedSuccessfully'));
      gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onFilter(field: string, value: any) {
  gridApi.formApi.setFieldValue(field, value);
  gridApi.formApi.validateAndSubmitForm();
}
</script>

<template>
  <Grid :table-title="$t('AbpAuditLogging.AuditLog')">
    <template #toolbar-tools>
      <Button
        v-if="selectedKeys.length > 0"
        :icon="h(DeleteOutlined)"
        danger
        ghost
        type="primary"
        v-access:code="[AuditLogPermissions.Delete]"
        @click="onBulkDelete"
      >
        {{ $t('AbpUi.Delete') }}
      </Button>
    </template>
    <template #clientIpAddress="{ row }">
      <Tag v-if="row.extraProperties?.Location" color="blue">
        {{ row.extraProperties?.Location }}
      </Tag>
      <span>{{ row.clientIpAddress }}</span>
    </template>
    <template #url="{ row }">
      <Tag
        :color="getHttpStatusCodeColor(row.httpStatusCode)"
        class="cursor-pointer"
        @click="onFilter('httpStatusCode', row.httpStatusCode)"
      >
        {{ row.httpStatusCode }}
      </Tag>
      <Tag
        :color="getHttpMethodColor(row.httpMethod)"
        class="ml-px cursor-pointer"
        @click="onFilter('httpMethod', row.httpMethod)"
      >
        {{ row.httpMethod }}
      </Tag>
      <a
        class="link"
        href="javaScript:void(0);"
        @click="onFilter('url', row.url)"
        >{{ row.url }}
      </a>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[AuditLogPermissions.Default]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpAuditLogging.ShowLogDialog') }}
        </Button>
        <Button
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[AuditLogPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
  </Grid>
  <AuditLogDrawer />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/management/audit-logs/audit-log-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Tag, Space, Card, Checkbox, type FormInstance, Tooltip } from "antd";
import { EditOutlined, DeleteOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import ProTable, { type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { formatToDateTime } from "@/utils/abp";
import type { AuditLogDto } from "#/management/auditing/audit-logs";
import { deleteApi, getPagedListApi } from "@/api/management/auditing/audit-logs";
import { httpMethodOptions, httpStatusCodeOptions } from "./mapping";
import AuditLogDrawer from "./audit-log-drawer";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { AuditLogPermissions } from "@/constants/management/auditing/permissions";
import { useAuditLogs } from "@/hooks/abp/auditing/use-audit-logs";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";
import { toast } from "sonner";
import DeleteModal from "@/components/abp/common/delete-modal";

const AuditLogTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const formRef = useRef<FormInstance>();
	const queryClient = useQueryClient();
	const [drawerVisible, setDrawerVisible] = useState(false);
	const [selectedLog, setSelectedLog] = useState<AuditLogDto | null>(null);
	const [deleteModalVisible, setDeleteModalVisible] = useState(false);
	const { getHttpMethodColor, getHttpStatusCodeColor } = useAuditLogs();

	const openDrawer = (log: AuditLogDto) => {
		setSelectedLog(log);
		setDrawerVisible(true);
	};

	const closeDrawer = () => {
		setDrawerVisible(false);
		setSelectedLog(null);
	};

	const { mutateAsync: deleteAuditLog } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["auditLogs"] });
		},
	});

	const handleDelete = (log: AuditLogDto) => {
		setSelectedLog(log);
		setDeleteModalVisible(true);
	};

	const confirmDelete = async () => {
		if (selectedLog) {
			await deleteAuditLog(selectedLog.id);
			actionRef.current?.reload();
			setDeleteModalVisible(false);
		}
	};

	const columns: ProColumns<AuditLogDto>[] = [
		{
			title: $t("AbpAuditLogging.RequestUrl"),
			dataIndex: "url",
			sorter: true,
			colSize: 2,
			order: 2,
			width: 500,
			ellipsis: true,
			render: (_, record) => (
				<>
					<Tag
						color={getHttpStatusCodeColor(record.httpStatusCode)}
						style={{ cursor: "pointer" }}
						onClick={() => onFilter("httpStatusCode", record.httpStatusCode)} // 点击标签触发筛选
					>
						<Tooltip title={$t("abp.manage.identity.filterHttpStatusCode")}>{record.httpStatusCode}</Tooltip>
					</Tag>
					<Tag
						color={getHttpMethodColor(record.httpMethod)}
						onClick={() => onFilter("httpMethod", record.httpMethod)}
						style={{ cursor: "pointer" }}
					>
						<Tooltip title={$t("abp.manage.identity.filterHttpMethod")}>{record.httpMethod}</Tooltip>
					</Tag>
					<Tooltip title={$t("abp.manage.identity.filterRequestUrl")}>
						<button
							type="button"
							onClick={() => onFilter("url", record.url)}
							style={{
								background: "none",
								border: "none",
								padding: 0,
								color: "blue",
								textDecoration: "underline",
								cursor: "pointer",
							}}
						>
							{record.url}
						</button>
					</Tooltip>
				</>
			),
		},
		{
			title: $t("AbpAuditLogging.UserName"),
			dataIndex: "userName",
			sorter: true,
			width: 120,
		},
		{
			title: $t("AbpAuditLogging.ExecutionTime"),
			dataIndex: "executionTime",
			valueType: "dateRange",
			sorter: true,
			order: 1,
			colSize: 2,
			width: 150,
			render: (_, record) => (record.executionTime ? formatToDateTime(record.executionTime) : record.executionTime),
		},
		{
			title: $t("AbpAuditLogging.HttpStatusCode"),
			dataIndex: "httpStatusCode",
			valueType: "select",
			fieldProps: {
				options: httpStatusCodeOptions,
			},
			hideInTable: true, // Only show in search form
		},
		{
			title: $t("AbpAuditLogging.HttpMethod"),
			dataIndex: "httpMethod",
			valueType: "select",
			fieldProps: {
				options: httpMethodOptions,
			},
			hideInTable: true, // Only show in search form
		},
		{
			title: $t("AbpAuditLogging.ExecutionDuration"),
			dataIndex: "executionDuration",
			sorter: true,
			hideInSearch: true,
			width: 140, //最长
		},
		{
			title: $t("AbpAuditLogging.MinExecutionDuration"),
			dataIndex: "minExecutionDuration",
			valueType: "digit",
			hideInTable: true,
		},
		{
			title: $t("AbpAuditLogging.MaxExecutionDuration"),
			dataIndex: "maxExecutionDuration",
			valueType: "digit",
			hideInTable: true,
		},
		{
			title: $t("AbpAuditLogging.ClientId"),
			dataIndex: "clientId",
			sorter: true,
			width: 150,
		},
		{
			title: $t("AbpAuditLogging.ClientIpAddress"),
			dataIndex: "clientIpAddress",
			sorter: true,
			width: 150,
			render: (_, record) => (
				<>
					{record.extraProperties?.Location && <Tag color="blue">{record.extraProperties.Location}</Tag>}
					<span>{record.clientIpAddress}</span>
				</>
			),
		},
		{
			title: $t("AbpAuditLogging.ApplicationName"),
			dataIndex: "applicationName",
			sorter: true,
			ellipsis: true,
			width: 160,
		},
		{
			title: $t("AbpAuditLogging.CorrelationId"),
			dataIndex: "correlationId",
			sorter: true,
			colSize: 2,
			width: 160,
		},
		{
			title: $t("AbpAuditLogging.TenantName"),
			dataIndex: "tenantName",
			sorter: true,
			width: 100,
			hideInSearch: true,
		},
		{
			title: $t("AbpAuditLogging.BrowserInfo"),
			dataIndex: "browserInfo",
			sorter: true,
			ellipsis: true,
			width: 300,
			hideInSearch: true,
		},
		{
			title: $t("AbpAuditLogging.HasException"),
			dataIndex: "hasException",
			valueType: "checkbox",
			hideInTable: true,
			renderFormItem: (_) => {
				return (
					<Checkbox
						onChange={(e) => {
							const value = e.target.checked; // 获取 Checkbox 的选中状态
							onFilter("hasException", value, false);
						}}
					/>
				);
			},
		},
		hasAccessByCodes([AuditLogPermissions.Default, AuditLogPermissions.Delete])
			? {
					title: $t("AbpUi.Actions"),
					key: "actions",
					align: "center",
					fixed: "right",
					hideInSearch: true,
					width: 220,
					render: (_, record) => (
						<div className="flex gap-1">
							{withAccessChecker(
								<Button type="link" icon={<EditOutlined />} onClick={() => openDrawer(record)}>
									{$t("AbpAuditLogging.ShowLogDialog")}
								</Button>,
								[AuditLogPermissions.Default],
							)}
							{withAccessChecker(
								<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
									{$t("AbpUi.Delete")}
								</Button>,
								[AuditLogPermissions.Delete],
							)}
						</div>
					),
				}
			: {},
	];

	const onFilter = (field: string, value: any, shouldSubmit = true) => {
		// 使用 formRef 更新查询条件
		if (formRef.current) {
			formRef.current.setFieldsValue({
				[field]: value,
			});
		}
		if (shouldSubmit) {
			// 触发表格刷新
			formRef.current?.submit();
		}
	};

	return (
		<>
			<Space direction="vertical" size="large" className="w-full">
				<Card>
					<ProTable<AuditLogDto>
						headerTitle={$t("AbpAuditLogging.AuditLog")}
						actionRef={actionRef}
						formRef={formRef} //search form
						rowKey="id"
						columns={columns}
						request={async (params, sorter) => {
							const { current, pageSize, executionTime, ...filters } = params;
							const [startTime, endTime] = executionTime || [];
							const query = await queryClient.fetchQuery({
								//不用换，这样与antd结合比较好用
								queryKey: ["auditLogs", params, sorter],
								queryFn: () =>
									getPagedListApi({
										maxResultCount: pageSize,
										skipCount: ((current || 1) - 1) * (pageSize || 0),
										sorting: sorter
											? Object.keys(sorter)
													.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
													.join(", ")
											: undefined,
										startTime: startTime || undefined,
										endTime: endTime || undefined,
										...filters,
									}),
							});
							return {
								data: query.items,
								total: query.totalCount,
							};
						}}
						pagination={{
							showSizeChanger: true,
						}}
						search={{
							labelWidth: "auto",
							defaultCollapsed: true,
						}}
						scroll={{ x: "max-content" }}
					/>
				</Card>
			</Space>
			{selectedLog && <AuditLogDrawer visible={drawerVisible} onClose={closeDrawer} auditLog={selectedLog} />}
			<DeleteModal
				visible={deleteModalVisible}
				onConfirm={confirmDelete}
				onCancel={() => setDeleteModalVisible(false)}
			/>
		</>
	);
};

export default AuditLogTable;
