// apps/react-admin/src/components/abp/display-names/display-name-table.tsx
import { useState } from "react";
import { Button, Popconfirm } from "antd";
import { DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ProColumns } from "@ant-design/pro-table";
import type { DisplayNameInfo, DisplayNameProps } from "./types";
import DisplayNameModal from "./display-name-modal";

const DisplayNameTable: React.FC<DisplayNameProps> = ({ data, onChange, onDelete }) => {
	const { t: $t } = useTranslation();
	const [modalVisible, setModalVisible] = useState(false);

	const dataSource = Object.entries(data || {}).map(([culture, displayName]) => ({
		culture,
		displayName,
		key: culture,
	}));

	const columns: ProColumns<DisplayNameInfo>[] = [
		{
			title: $t("AbpOpenIddict.DisplayName:CultureName"),
			dataIndex: "culture",
			align: "left",
			width: 200,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:DisplayName"),
			dataIndex: "displayName",
			align: "left",
			width: 200,
		},
		{
			title: $t("AbpUi.Actions"),
			width: 180,
			fixed: "right",
			render: (_, record) => (
				<Popconfirm
					title={$t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: record.culture })}
					onConfirm={() => onDelete?.(record)}
				>
					<Button type="link" danger icon={<DeleteOutlined />} block>
						{$t("AbpUi.Delete")}
					</Button>
				</Popconfirm>
			),
		},
	];

	return (
		<>
			<ProTable<DisplayNameInfo>
				columns={columns}
				dataSource={dataSource}
				search={false}
				pagination={false}
				toolBarRender={() => [
					<Button key="add" type="primary" icon={<PlusOutlined />} onClick={() => setModalVisible(true)}>
						{$t("AbpOpenIddict.DisplayName:AddNew")}
					</Button>,
				]}
			/>

			<DisplayNameModal
				visible={modalVisible}
				onClose={() => setModalVisible(false)}
				onChange={(info) => {
					onChange?.(info);
					setModalVisible(false);
				}}
			/>
		</>
	);
};

export default DisplayNameTable;

// apps/vben5/packages/@abp/openiddict/src/components/display-names/DisplayNameTable.vue
<script setup lang="ts">
import type { VxeGridPropTypes } from 'vxe-table';

import type { DisplayNameInfo, DisplayNameProps } from './types';

import { computed, defineAsyncComponent, h, reactive } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, Popconfirm } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

defineOptions({
  name: 'DisplayNameTable',
});

const props = defineProps<DisplayNameProps>();
const emits = defineEmits<{
  (event: 'change' | 'delete', data: DisplayNameInfo): void;
}>();

const getDataResource = computed((): DisplayNameInfo[] => {
  if (!props.data) return [];
  return Object.keys(props.data).map((item) => {
    return {
      culture: item,
      displayName: props.data![item]!,
    };
  });
});

const columnsConfig = reactive<VxeGridPropTypes.Columns<DisplayNameInfo>>([
  {
    align: 'left',
    field: 'culture',
    minWidth: 200,
    title: $t('AbpOpenIddict.DisplayName:CultureName'),
  },
  {
    align: 'left',
    field: 'displayName',
    minWidth: 200,
    title: $t('AbpOpenIddict.DisplayName:DisplayName'),
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 180,
  },
]);

const [DisplayNameModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./DisplayNameModal.vue'),
  ),
});

function onCreate() {
  modalApi.open();
}

function onDelete(prop: DisplayNameInfo) {
  emits('delete', prop);
}

function onChange(prop: DisplayNameInfo) {
  emits('change', prop);
}
</script>

<template>
  <VxeGrid
    :columns="columnsConfig"
    :data="getDataResource"
    :toolbar-config="{ slots: { tools: 'toolbar_tools' } }">
    <template #toolbar_tools>
      <Button :icon="h(PlusOutlined)" type="primary" @click="onCreate">
        {{ $t('AbpOpenIddict.DisplayName:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Popconfirm
          :title="`${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.culture])}`"
          @confirm="onDelete(row)">
          <Button :icon="h(DeleteOutlined)" block danger type="link">
            {{ $t('AbpUi.Delete') }}
          </Button>
        </Popconfirm>
      </div>
    </template>
  </VxeGrid>
  <DisplayNameModal @change="onChange" />
</template>

<style scoped></style>
