// apps/vben5/packages/@abp/openiddict/src/components/display-names/DisplayNameModal.vue
<script setup lang="ts">
import type { DisplayNameInfo } from './types';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useAbpStore } from '@abp/core';

defineOptions({
  name: 'DisplayNameModal',
});

const emits = defineEmits<{
  (event: 'change', data: DisplayNameInfo): void;
}>();

const { application } = useAbpStore();

const [Form, formApi] = useVbenForm({
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Select',
      componentProps: {
        autocomplete: 'off',
        fieldNames: {
          label: 'displayName',
          value: 'cultureName',
        },
        options: application?.localization.languages,
      },
      fieldName: 'culture',
      label: $t('AbpOpenIddict.DisplayName:CultureName'),
      rules: 'required',
    },
    {
      component: 'Input',
      componentProps: {
        autocomplete: 'off',
      },
      fieldName: 'displayName',
      label: $t('AbpOpenIddict.DisplayName:DisplayName'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  title: $t('AbpOpenIddict.DisplayName:DisplayNames'),
});
function onSubmit(input: Record<string, any>) {
  emits('change', {
    culture: input.culture,
    displayName: input.displayName,
  });
  modalApi.close();
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/display-names/display-name-modal.tsx
import { Form, Input, Modal, Select } from "antd";
import { useTranslation } from "react-i18next";
import type { DisplayNameInfo } from "./types";
import useAbpStore from "@/store/abpCoreStore";

interface DisplayNameModalProps {
	visible: boolean;
	onClose: () => void;
	onChange: (data: DisplayNameInfo) => void;
}

const DisplayNameModal: React.FC<DisplayNameModalProps> = ({ visible, onClose, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const { application } = useAbpStore();

	const handleOk = async () => {
		try {
			const values = await form.validateFields();
			onChange({
				culture: values.culture,
				displayName: values.displayName,
			});
			form.resetFields();
			onClose();
		} catch (error) {
			console.error("Validation failed:", error);
		}
	};

	return (
		<Modal
			open={visible}
			title={$t("AbpOpenIddict.DisplayName:AddNew")}
			onCancel={onClose}
			onOk={handleOk}
			width="50%"
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item label={$t("AbpOpenIddict.DisplayName:CultureName")} name="culture" rules={[{ required: true }]}>
					<Select
						className="w-full"
						options={application?.localization.languages.map((lang) => ({
							label: lang.displayName,
							value: lang.cultureName,
						}))}
					/>
				</Form.Item>
				<Form.Item label={$t("AbpOpenIddict.DisplayName:DisplayName")} name="displayName" rules={[{ required: true }]}>
					<Input className="w-full" autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default DisplayNameModal;
