// apps/vben5/packages/@abp/features/src/components/state-check/FeatureStateCheck.vue
<script setup lang="ts">
import type {
  FeatureDefinitionDto,
  FeatureGroupDefinitionDto,
} from '../../types';

import { computed, onMounted, ref } from 'vue';

import {
  isNullOrWhiteSpace,
  listToTree,
  useLocalization,
  useLocalizationSerializer,
} from '@abp/core';
import { valueTypeSerializer } from '@abp/ui';
import { Checkbox, FormItemRest, TreeSelect } from 'ant-design-vue';

import { useFeatureDefinitionsApi } from '../../api/useFeatureDefinitionsApi';
import { useFeatureGroupDefinitionsApi } from '../../api/useFeatureGroupDefinitionsApi';

interface FeatureTreeData {
  checkable?: boolean;
  children: FeatureTreeData[];
  displayName: string;
  groupName: string;
  name: string;
}

const emits = defineEmits(['blur', 'change']);

const { getListApi: getFeaturesApi } = useFeatureDefinitionsApi();
const { getListApi: getFeatureGroupsApi } = useFeatureGroupDefinitionsApi();
const { deserialize } = useLocalizationSerializer();
const { Lr } = useLocalization();

const features = ref<FeatureDefinitionDto[]>([]);
const featureGroups = ref<FeatureGroupDefinitionDto[]>([]);
const modelValue = defineModel<{
  featureNames: string[];
  requiresAll: boolean;
}>({
  default: {
    featureNames: [],
    requiresAll: false,
  },
});

const getFeatureOptions = computed(() => {
  const featureOptions: FeatureTreeData[] = [];
  featureGroups.value.forEach((group) => {
    featureOptions.push({
      checkable: false,
      displayName: group.displayName,
      groupName: group.name,
      name: group.name,
      children: listToTree(
        features.value.filter((x) => x.groupName === group.name),
        {
          id: 'name',
          pid: 'parentName',
        },
      ),
    });
  });
  return featureOptions;
});
const getRequiredFeatures = computed(() => {
  const featureNames = modelValue.value?.featureNames ?? [];
  const requiredFeatures = features.value
    .filter((feature) => featureNames.includes(feature.name))
    .map((feature) => {
      return {
        label: feature.displayName,
        value: feature.name,
      };
    });
  return requiredFeatures;
});

function onChange() {
  emits('change', modelValue.value);
}

function onFeaturesChange(value: any[]) {
  modelValue.value.featureNames = value.map((item) => item.value);
  emits('change', modelValue.value);
}

async function onInit() {
  const [featureGroupRes, featuresRes] = await Promise.all([
    getFeatureGroupsApi(),
    getFeaturesApi(),
  ]);
  featureGroups.value = featureGroupRes.items.map((item) => {
    const displayName = deserialize(item.displayName);
    return {
      ...item,
      displayName: Lr(displayName.resourceName, displayName.name),
    };
  });
  features.value = featuresRes.items
    .filter((item) => {
      if (!isNullOrWhiteSpace(item.valueType)) {
        const valueType = valueTypeSerializer.deserialize(item.valueType);
        if (valueType.validator.name !== 'BOOLEAN') {
          return false;
        }
      }
      return true;
    })
    .map((item) => {
      const displayName = deserialize(item.displayName);
      const feature = {
        ...item,
        displayName: Lr(displayName.resourceName, displayName.name),
      };
      return feature;
    });
}

onMounted(onInit);
</script>

<template>
  <div class="flex w-full flex-col gap-5">
    <FormItemRest>
      <Checkbox
        v-model:checked="modelValue.requiresAll"
        @blur="emits('blur')"
        @change="onChange">
        {{ $t('component.simple_state_checking.requireFeatures.requiresAll') }}
      </Checkbox>
      <TreeSelect
        :tree-data="getFeatureOptions"
        allow-clear
        tree-checkable
        tree-check-strictly
        :field-names="{ label: 'displayName', value: 'name' }"
        :value="getRequiredFeatures"
        @blur="emits('blur')"
        @change="onFeaturesChange" />
    </FormItemRest>
  </div>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/features/state-check/feature-state-check.tsx
import type React from "react";
import { useMemo } from "react";
import { Checkbox, TreeSelect, Spin } from "antd";
import { useTranslation } from "react-i18next";
import { useQuery } from "@tanstack/react-query";
import { getListApi as getFeaturesApi } from "@/api/management/features/feature-definitions";
import { getListApi as getGroupsApi } from "@/api/management/features/feature-group-definitions";

import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { useLocalizer } from "@/hooks/abp/use-localization";

import { listToTree } from "@/utils/tree";
import { valueTypeSerializer } from "../../string-value-type";

interface ValueType {
	featureNames: string[];
	requiresAll: boolean;
}

interface FeatureStateCheckProps {
	value?: ValueType;
	onChange?: (value: ValueType) => void;
}

const FeatureStateCheck: React.FC<FeatureStateCheckProps> = ({
	value = { featureNames: [], requiresAll: false },
	onChange,
}) => {
	const { t: $t } = useTranslation();
	const { deserialize } = localizationSerializer();
	const { Lr } = useLocalizer();

	// 1. Fetch Data
	const { data: featureData, isLoading } = useQuery({
		queryKey: ["featureStateCheckData"],
		queryFn: async () => {
			const [groupsRes, featuresRes] = await Promise.all([getGroupsApi(), getFeaturesApi()]);

			// Filter: Only BOOLEAN features are relevant for state checking
			const validFeatures = featuresRes.items.filter((item) => {
				if (item.valueType) {
					try {
						const vt = valueTypeSerializer.deserialize(item.valueType);
						return vt.validator.name === "BOOLEAN";
					} catch {
						return false;
					}
				}
				return true;
			});

			// Prepare localized features list for lookup and tree building
			const features = validFeatures.map((f) => {
				const d = deserialize(f.displayName);
				return {
					...f,
					title: Lr(d.resourceName, d.name), // Localized Title
					key: f.name,
					value: f.name,
				};
			});

			// Prepare localized groups
			const groups = groupsRes.items.map((g) => {
				const d = deserialize(g.displayName);
				return {
					...g,
					title: Lr(d.resourceName, d.name),
				};
			});

			return { groups, features };
		},
		staleTime: Number.POSITIVE_INFINITY, // Config data rarely changes
	});

	// 2. Construct Tree Data
	const treeData = useMemo(() => {
		if (!featureData) return [];
		const { groups, features } = featureData;

		return groups.map((group) => {
			// Find features belonging to this group
			const groupFeatures = features.filter((f) => f.groupName === group.name);

			// Build hierarchy for features (parent/child)
			const children = listToTree(groupFeatures, { id: "name", pid: "parentName" });

			// Return Group Node
			return {
				title: group.title,
				value: group.name,
				key: group.name,
				selectable: false, // Cannot select the group itself
				checkable: false, // Cannot check the group itself
				disableCheckbox: true, // Visual disabled checkbox
				children: children,
			};
		});
	}, [featureData]);

	// 3. Map selected string[] to { label, value }[] for TreeSelect (Required for treeCheckStrictly)
	const treeValue = useMemo(() => {
		if (!featureData || !value.featureNames) return [];
		return value.featureNames.map((name) => {
			const feature = featureData.features.find((f) => f.name === name);
			return {
				label: feature?.title || name,
				value: name,
			};
		});
	}, [featureData, value.featureNames]);

	// 4. Handle Change
	const triggerChange = (changedValue: Partial<ValueType>) => {
		onChange?.({ ...value, ...changedValue });
	};

	const onTreeChange = (labeledValues: { label: React.ReactNode; value: string }[]) => {
		// Extract just the feature names (strings) to send back
		const names = labeledValues.map((item) => item.value);
		triggerChange({ featureNames: names });
	};

	if (isLoading) return <Spin className="my-2" />;

	return (
		<div className="flex flex-col gap-2 w-full">
			<Checkbox checked={value.requiresAll} onChange={(e) => triggerChange({ requiresAll: e.target.checked })}>
				{$t("component.simple_state_checking.requireFeatures.requiresAll")}
			</Checkbox>

			<TreeSelect
				treeData={treeData}
				value={treeValue} // Pass objects
				onChange={onTreeChange} // Receive objects
				allowClear
				treeCheckable
				treeCheckStrictly // Decouples parent/child selection logic
				showCheckedStrategy={TreeSelect.SHOW_ALL} // Show every selected node explicitly
				placeholder={$t("ui.placeholder.select")}
				style={{ width: "100%" }}
				treeDefaultExpandAll
			/>
		</div>
	);
};

export default FeatureStateCheck;
