// apps/vben5/packages/@abp/features/src/components/state-check/GlobalFeatureStateCheck.vue
<script setup lang="ts">
import { computed } from 'vue';

import { useAbpStore } from '@abp/core';
import { Checkbox, FormItemRest, Select } from 'ant-design-vue';

const emits = defineEmits(['blur', 'change']);

const modelValue = defineModel<{
  globalFeatureNames: string[];
  requiresAll: boolean;
}>({
  default: {
    globalFeatureNames: [],
    requiresAll: false,
  },
});

const abpStore = useAbpStore();

const getFeatureOptions = computed(() => {
  if (!abpStore.application?.globalFeatures) {
    return [];
  }
  return abpStore.application.globalFeatures.enabledFeatures.map((feature) => {
    return {
      label: feature,
      value: feature,
    };
  });
});

function onChange() {
  emits('change', modelValue.value);
}

function onFeaturesChange(value: any) {
  modelValue.value.globalFeatureNames = value;
  emits('change', modelValue.value);
}
</script>

<template>
  <div class="flex w-full flex-col gap-5">
    <FormItemRest>
      <Checkbox
        v-model:checked="modelValue.requiresAll"
        @blur="emits('blur')"
        @change="onChange">
        {{ $t('component.simple_state_checking.requireFeatures.requiresAll') }}
      </Checkbox>
      <Select
        :value="modelValue.globalFeatureNames"
        :options="getFeatureOptions"
        show-search
        mode="tags"
        @blur="emits('blur')"
        @change="onFeaturesChange" />
    </FormItemRest>
  </div>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/features/state-check/global-feature-state-check.tsx
import type React from "react";
import { useMemo } from "react";
import { Checkbox, Select } from "antd";
import { useTranslation } from "react-i18next";
import useAbpStore from "@/store/abpCoreStore";

interface ValueType {
	globalFeatureNames: string[];
	requiresAll: boolean;
}

interface GlobalFeatureStateCheckProps {
	value?: ValueType;
	onChange?: (value: ValueType) => void;
}

const GlobalFeatureStateCheck: React.FC<GlobalFeatureStateCheckProps> = ({
	value = { globalFeatureNames: [], requiresAll: false },
	onChange,
}) => {
	const { t: $t } = useTranslation();
	const application = useAbpStore((state) => state.application);

	const options = useMemo(() => {
		if (!application?.globalFeatures?.enabledFeatures) return [];
		return application.globalFeatures.enabledFeatures.map((f) => ({
			label: f,
			value: f,
		}));
	}, [application]);

	const triggerChange = (changedValue: Partial<ValueType>) => {
		onChange?.({ ...value, ...changedValue });
	};

	return (
		<div className="flex flex-col gap-4 w-full">
			<Checkbox checked={value.requiresAll} onChange={(e) => triggerChange({ requiresAll: e.target.checked })}>
				{$t("component.simple_state_checking.requireFeatures.requiresAll")}
			</Checkbox>
			<Select
				mode="tags"
				style={{ width: "100%" }}
				options={options}
				value={value.globalFeatureNames}
				onChange={(val) => triggerChange({ globalFeatureNames: val })}
				allowClear
			/>
		</div>
	);
};

export default GlobalFeatureStateCheck;
