// apps/react-admin/src/pages/platform/workbench/components/workbench-todo.tsx
import type React from "react";
import { Card, Checkbox, Empty } from "antd";
// Using custom type or interface from common-ui if available, else define locally
interface WorkbenchTodoItem {
	title: string;
	content: string;
	completed: boolean;
	date: string;
}

interface Props {
	items?: WorkbenchTodoItem[];
	title: string;
}

const WorkbenchTodo: React.FC<Props> = ({ items = [], title }) => {
	return (
		<Card title={title} className="min-h-[300px] shadow-sm">
			{items.length === 0 ? (
				<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} />
			) : (
				<ul className="divide-y divide-gray-100 w-full">
					{items.map((item) => (
						<li
							key={item.title}
							className={`flex justify-between gap-x-6 py-4 cursor-pointer hover:bg-gray-50 transition-colors px-2 ${
								item.completed ? "opacity-60" : ""
							}`}
						>
							<div className="flex min-w-0 items-start gap-x-4 flex-1">
								<Checkbox checked={item.completed} className="mt-1" />
								<div className="min-w-0 flex-auto">
									<p className={`text-sm font-semibold text-gray-900 ${item.completed ? "line-through" : ""}`}>
										{item.title}
									</p>
									<div
										className="mt-1 truncate text-xs text-gray-500"
										dangerouslySetInnerHTML={{ __html: item.content }}
									/>
								</div>
							</div>
							<div className="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
								<span className="text-xs text-gray-400 mt-1">{item.date}</span>
							</div>
						</li>
					))}
				</ul>
			)}
		</Card>
	);
};

export default WorkbenchTodo;

// apps/vben5/packages/@abp/platform/src/components/workbench/components/WorkbenchTodo.vue
<script setup lang="ts">
import type { WorkbenchTodoItem } from '@vben/common-ui';

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  VbenCheckbox,
} from '@vben-core/shadcn-ui';

interface Props {
  items?: WorkbenchTodoItem[];
  title: string;
}

defineOptions({
  name: 'WorkbenchTodo',
});

withDefaults(defineProps<Props>(), {
  items: () => [],
});
</script>

<template>
  <Card>
    <CardHeader class="py-4">
      <CardTitle class="text-lg">{{ title }}</CardTitle>
    </CardHeader>
    <slot v-if="items.length === 0" name="empty"></slot>
    <CardContent v-else class="flex flex-wrap p-5 pt-0">
      <ul class="divide-border w-full divide-y" role="list">
        <li
          v-for="item in items"
          :key="item.title"
          :class="{
            'select-none line-through opacity-60': item.completed,
          }"
          class="flex cursor-pointer justify-between gap-x-6 py-5"
        >
          <div class="flex min-w-0 items-center gap-x-4">
            <VbenCheckbox v-model:checked="item.completed" name="completed" />
            <div class="min-w-0 flex-auto">
              <p class="text-foreground text-sm font-semibold leading-6">
                {{ item.title }}
              </p>
              <!-- eslint-disable vue/no-v-html -->
              <p
                class="text-foreground/80 *:text-primary mt-1 truncate text-xs leading-5"
                v-html="item.content"
              ></p>
            </div>
          </div>
          <div class="hidden h-full shrink-0 sm:flex sm:flex-col sm:items-end">
            <span class="text-foreground/80 mt-6 text-xs leading-6">
              {{ item.date }}
            </span>
          </div>
        </li>
      </ul>
    </CardContent>
  </Card>
</template>
