// apps/react-admin/src/pages/platform/workbench/components/workbench-trends.tsx
import type React from "react";
import { Card, Empty, Avatar } from "antd";
import { Iconify } from "@/components/icon";

interface WorkbenchTrendItem {
	avatar?: string; // Icon string or image url
	title: string;
	content: string;
	date: string;
}

interface Props {
	items?: WorkbenchTrendItem[];
	title: string;
}

const WorkbenchTrends: React.FC<Props> = ({ items = [], title }) => {
	return (
		<Card title={title} className="h-full">
			{items.length === 0 ? (
				<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} />
			) : (
				<ul className="divide-y divide-gray-100 w-full">
					{items.map((item, index) => (
						<li
							key={`${item.title}-${index}`}
							className="flex justify-between gap-x-6 py-4 px-2 hover:bg-gray-50 transition-colors"
						>
							<div className="flex min-w-0 items-center gap-x-4">
								{/* Check if avatar is icon string or url */}
								{item.avatar?.includes(":") ? (
									<Avatar
										icon={<Iconify icon={item.avatar} />}
										className="bg-blue-100 text-blue-600 flex-none"
										size="large"
									/>
								) : (
									<Avatar src={item.avatar} size="large" className="flex-none" />
								)}

								<div className="min-w-0 flex-auto">
									<p className="text-sm font-semibold text-gray-900 leading-6">{item.title}</p>
									<div
										className="mt-1 truncate text-xs text-gray-500"
										dangerouslySetInnerHTML={{ __html: item.content }}
									/>
								</div>
							</div>
							<div className="hidden shrink-0 sm:flex sm:flex-col sm:items-end justify-center">
								<span className="text-xs text-gray-400">{item.date}</span>
							</div>
						</li>
					))}
				</ul>
			)}
		</Card>
	);
};

export default WorkbenchTrends;

// apps/vben5/packages/@abp/platform/src/components/workbench/components/WorkbenchTrends.vue
<script setup lang="ts">
import type { WorkbenchTrendItem } from '@vben/common-ui';

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  VbenIcon,
} from '@vben-core/shadcn-ui';

interface Props {
  items?: WorkbenchTrendItem[];
  title: string;
}

defineOptions({
  name: 'WorkbenchTrends',
});

withDefaults(defineProps<Props>(), {
  items: () => [],
});
</script>

<template>
  <Card>
    <CardHeader class="py-4">
      <CardTitle class="text-lg">{{ title }}</CardTitle>
    </CardHeader>
    <slot v-if="items.length === 0" name="empty"></slot>
    <CardContent v-else class="flex flex-wrap p-5 pt-0">
      <ul class="divide-border w-full divide-y" role="list">
        <li
          v-for="item in items"
          :key="item.title"
          class="flex justify-between gap-x-6 py-5">
          <div class="flex min-w-0 items-center gap-x-4">
            <VbenIcon
              :icon="item.avatar"
              alt=""
              class="size-10 flex-none rounded-full" />
            <div class="min-w-0 flex-auto">
              <p class="text-foreground text-sm font-semibold leading-6">
                {{ item.title }}
              </p>
              <!-- eslint-disable vue/no-v-html -->
              <p
                class="text-foreground/80 *:text-primary mt-1 truncate text-xs leading-5"
                v-html="item.content"></p>
            </div>
          </div>
          <div class="hidden h-full shrink-0 sm:flex sm:flex-col sm:items-end">
            <span class="text-foreground/80 mt-6 text-xs leading-6">
              {{ item.date }}
            </span>
          </div>
        </li>
      </ul>
    </CardContent>
  </Card>
</template>
