// apps/vben5/packages/@abp/openiddict/src/components/scopes/ScopeTable.vue
<script setup lang="ts">
import type { VbenFormProps, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { OpenIddictScopeDto } from '../../types/scopes';

import { defineAsyncComponent, h } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { AuditLogPermissions, EntityChangeDrawer } from '@abp/auditing';
import { formatToDateTime, useFeatures } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useScopesApi } from '../../api/useScopesApi';
import { ScopesPermissions } from '../../constants/permissions';

defineOptions({
  name: 'ScopeTable',
});

const MenuItem = Menu.Item;

const AuditLogIcon = createIconifyIcon('fluent-mdl2:compliance-audit');
const CheckIcon = createIconifyIcon('ant-design:check-outlined');
const CloseIcon = createIconifyIcon('ant-design:close-outlined');

const { isEnabled } = useFeatures();
const { hasAccessByCodes } = useAccess();
const { deleteApi, getPagedListApi } = useScopesApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<OpenIddictScopeDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('AbpOpenIddict.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AbpOpenIddict.DisplayName:DisplayName'),
    },
    {
      align: 'center',
      field: 'description',
      minWidth: 200,
      title: $t('AbpOpenIddict.DisplayName:Description'),
    },
    {
      align: 'center',
      field: 'creationTime',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      minWidth: 120,
      title: $t('AbpOpenIddict.DisplayName:CreationDate'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        return await getPagedListApi({
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};

const [ScopeModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(() => import('./ScopeModal.vue')),
});
const [ScopeChangeDrawer, scopeChangeDrawerApi] = useVbenDrawer({
  connectedComponent: EntityChangeDrawer,
});
const [Grid, { query }] = useVbenVxeGrid({
  formOptions,
  gridOptions,
});

const onCreate = () => {
  modalApi.setData({});
  modalApi.open();
};

const onUpdate = (row: OpenIddictScopeDto) => {
  modalApi.setData(row);
  modalApi.open();
};

const onDelete = (row: OpenIddictScopeDto) => {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.SuccessfullyDeleted'));
      query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
};
const onMenuClick = (row: OpenIddictScopeDto, info: MenuInfo) => {
  switch (info.key) {
    case 'entity-changes': {
      scopeChangeDrawerApi.setData({
        entityId: row.id,
        entityTypeFullName: 'Volo.Abp.OpenIddict.Scopes.OpenIddictScope',
        subject: row.name,
      });
      scopeChangeDrawerApi.open();
      break;
    }
  }
};
</script>

<template>
  <Grid :table-title="$t('AbpOpenIddict.Scopes')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[ScopesPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('AbpOpenIddict.Scopes:AddNew') }}
      </Button>
    </template>
    <template #required="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.required" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #static="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.isStatic" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[ScopesPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[ScopesPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown v-if="isEnabled('AbpAuditing.Logging.AuditLog')">
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="hasAccessByCodes([AuditLogPermissions.Default])"
                key="entity-changes"
                :icon="h(AuditLogIcon)"
              >
                {{ $t('AbpAuditLogging.EntitiesChanged') }}
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <ScopeModal @change="() => query()" />
  <ScopeChangeDrawer />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/openiddict/scopes/scope-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space } from "antd";
import { DeleteOutlined, EditOutlined, EllipsisOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import type { OpenIddictScopeDto } from "#/openiddict/scopes";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { ScopesPermissions } from "@/constants/openiddict/permissions";
import { AuditLogPermissions } from "@/constants/management/auditing/permissions";
import { Iconify } from "@/components/icon";
import { deleteApi, getPagedListApi } from "@/api/openiddict/scopes";
import { useFeatures } from "@/hooks/abp/use-abp-feature";
import { toast } from "sonner";
import ScopeModal from "./scope-modal";
import { EntityChangeDrawer } from "@/components/abp/auditing/entity-change-drawer";

const ScopeTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const { isEnabled } = useFeatures();
	const [modal, contextHolder] = Modal.useModal();

	// Modal visibility states
	const [modalVisible, setModalVisible] = useState(false);
	const [entityChangeDrawerVisible, setEntityChangeDrawerVisible] = useState(false);

	// Selected scope state
	const [selectedScope, setSelectedScope] = useState<OpenIddictScopeDto>();

	// Delete mutation
	const { mutateAsync: deleteScope } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["openIddict.scopes"] });
			actionRef.current?.reload();
		},
	});

	const handleMenuClick = (key: string, scope: OpenIddictScopeDto) => {
		setSelectedScope(scope);
		switch (key) {
			case "entity-changes":
				setEntityChangeDrawerVisible(true);
				break;
		}
	};

	const handleDelete = (scope: OpenIddictScopeDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: scope.name }),
			onOk: () => deleteScope(scope.id),
		});
	};

	const columns: ProColumns<OpenIddictScopeDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			hideInTable: true,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:Name"),
			dataIndex: "name",
			width: 150,
			hideInSearch: true,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 150,
			hideInSearch: true,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:Description"),
			dataIndex: "description",
			width: 200,
			hideInSearch: true,
			ellipsis: true,
		},
		{
			title: $t("AbpUi.Actions"),
			width: 220,
			fixed: "right",
			hideInSearch: true,
			render: (_, record) => (
				<Space split>
					{hasAccessByCodes([ScopesPermissions.Update]) && (
						<Button
							type="link"
							icon={<EditOutlined />}
							onClick={() => {
								setSelectedScope(record);
								setModalVisible(true);
							}}
						>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{hasAccessByCodes([ScopesPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
					{isEnabled("AbpAuditing.Logging.AuditLog") && hasAccessByCodes([AuditLogPermissions.Default]) && (
						<Dropdown
							menu={{
								items: [
									{
										key: "entity-changes",
										icon: <Iconify icon="fluent-mdl2:compliance-audit" />,
										label: $t("AbpAuditLogging.EntitiesChanged"),
									},
								],
								onClick: ({ key }) => handleMenuClick(key, record),
							}}
						>
							<Button type="link" icon={<EllipsisOutlined />} />
						</Dropdown>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<OpenIddictScopeDto>
					headerTitle={$t("AbpOpenIddict.Scopes")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					request={async (params) => {
						const { current, pageSize, filter } = params;
						const query = await queryClient.fetchQuery({
							queryKey: ["openIddict.scopes", params],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									filter: filter,
								}),
						});
						return {
							data: query.items,
							success: true,
							total: query.totalCount,
						};
					}}
					search={{
						span: 12,
						labelWidth: "auto",
					}}
					scroll={{ x: "max-content" }}
					toolBarRender={() => [
						hasAccessByCodes([ScopesPermissions.Create]) && (
							<Button
								type="primary"
								icon={<PlusOutlined />}
								onClick={() => {
									setSelectedScope(undefined);
									setModalVisible(true);
								}}
							>
								{$t("AbpOpenIddict.Scopes:AddNew")}
							</Button>
						),
					]}
				/>
			</Card>

			{/* Modals */}
			<ScopeModal
				visible={modalVisible}
				scopeId={selectedScope?.id}
				onClose={() => {
					setModalVisible(false);
					setSelectedScope(undefined);
				}}
				onChange={() => actionRef.current?.reload()}
			/>

			<EntityChangeDrawer
				open={entityChangeDrawerVisible}
				subject={selectedScope?.name}
				input={{
					entityId: selectedScope?.id,
					entityTypeFullName: "Volo.Abp.OpenIddict.Scopes.OpenIddictScope",
				}}
				onClose={() => {
					setEntityChangeDrawerVisible(false);
					setSelectedScope(undefined);
				}}
			/>
		</>
	);
};

export default ScopeTable;
