// apps/vben5/packages/@abp/openiddict/src/components/scopes/ScopeModal.vue
<script setup lang="ts">
import type { OpenIdConfiguration } from '@abp/core';
import type { FormInstance } from 'ant-design-vue';
import type { TransferItem } from 'ant-design-vue/es/transfer';

import type { OpenIddictScopeDto } from '../../types/scopes';
import type { DisplayNameInfo } from '../display-names/types';
import type { PropertyInfo } from '../properties/types';

import { computed, defineEmits, defineOptions, ref, toValue } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Form, Input, message, Tabs, Transfer } from 'ant-design-vue';

import { discoveryApi } from '../../api/openid';
import { createApi, getApi, updateApi } from '../../api/scopes';
import DisplayNameTable from '../display-names/DisplayNameTable.vue';
import PropertyTable from '../properties/PropertyTable.vue';

defineOptions({
  name: 'ScopeModal',
});
const emits = defineEmits<{
  (event: 'change', data: OpenIddictScopeDto): void;
}>();

const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

type TabKeys =
  | 'authorize'
  | 'basic'
  | 'description'
  | 'dispalyName'
  | 'props'
  | 'resource';

const defaultModel = {} as OpenIddictScopeDto;

const form = ref<FormInstance>();
const formModel = ref<OpenIddictScopeDto>({ ...defaultModel });
const openIdConfiguration = ref<OpenIdConfiguration>();
const activeTab = ref<TabKeys>('basic');

const getSupportClaims = computed((): TransferItem[] => {
  const types = openIdConfiguration.value?.claims_supported ?? [];
  return types.map((type) => {
    return {
      key: type,
      title: type,
    };
  });
});

const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await form.value?.validate();
    const api = formModel.value.id
      ? updateApi(formModel.value.id, toValue(formModel))
      : createApi(toValue(formModel));
    modalApi.setState({ confirmLoading: true, loading: true });
    api
      .then((res) => {
        message.success($t('AbpUi.SavedSuccessfully'));
        emits('change', res);
        modalApi.close();
      })
      .finally(() => {
        modalApi.setState({ confirmLoading: false, loading: false });
      });
  },
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      activeTab.value = 'basic';
      formModel.value = { ...defaultModel };
      modalApi.setState({
        title: $t('AbpOpenIddict.Scopes:AddNew'),
      });
      try {
        modalApi.setState({ loading: true });
        await onDiscovery();
        const { id } = modalApi.getData<OpenIddictScopeDto>();
        id && (await onGet(id));
      } finally {
        modalApi.setState({ loading: false });
      }
    }
  },
  title: $t('AbpOpenIddict.Scopes:AddNew'),
});
async function onGet(id: string) {
  const dto = await getApi(id);
  formModel.value = dto;
  modalApi.setState({
    title: `${$t('AbpOpenIddict.Scopes')} - ${dto.name}`,
  });
}
async function onDiscovery() {
  openIdConfiguration.value = await discoveryApi();
}
function onDescriptionChange(displayName: DisplayNameInfo) {
  formModel.value.descriptions ??= {};
  formModel.value.descriptions[displayName.culture] = displayName.displayName;
}
function onDescriptionDelete(displayName: DisplayNameInfo) {
  formModel.value.descriptions ??= {};
  delete formModel.value.descriptions[displayName.culture];
}
function onDisplayNameChange(displayName: DisplayNameInfo) {
  formModel.value.displayNames ??= {};
  formModel.value.displayNames[displayName.culture] = displayName.displayName;
}
function onDisplayNameDelete(displayName: DisplayNameInfo) {
  formModel.value.displayNames ??= {};
  delete formModel.value.displayNames[displayName.culture];
}
function onPropChange(prop: PropertyInfo) {
  formModel.value.properties ??= {};
  formModel.value.properties[prop.key] = prop.value;
}
function onPropDelete(prop: PropertyInfo) {
  formModel.value.properties ??= {};
  delete formModel.value.properties[prop.key];
}
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <Tabs v-model:active-key="activeTab">
        <!-- 基本信息 -->
        <TabPane key="basic" :tab="$t('AbpOpenIddict.BasicInfo')">
          <FormItem
            :label="$t('AbpOpenIddict.DisplayName:Name')"
            name="name"
            required
          >
            <Input v-model:value="formModel.name" autocomplete="off" />
          </FormItem>
        </TabPane>
        <!-- 显示名称 -->
        <TabPane key="dispalyName" :tab="$t('AbpOpenIddict.DisplayNames')">
          <FormItem
            :label="$t('AbpOpenIddict.DisplayName:DefaultDisplayName')"
            name="displayName"
          >
            <Input v-model:value="formModel.displayName" autocomplete="off" />
          </FormItem>
          <DisplayNameTable
            :data="formModel.displayNames"
            @change="onDisplayNameChange"
            @delete="onDisplayNameDelete"
          />
        </TabPane>
        <!-- 描述 -->
        <TabPane key="description" :tab="$t('AbpOpenIddict.Descriptions')">
          <FormItem
            :label="$t('AbpOpenIddict.DisplayName:DefaultDescription')"
            name="description"
          >
            <Input v-model:value="formModel.description" autocomplete="off" />
          </FormItem>
          <DisplayNameTable
            :data="formModel.descriptions"
            @change="onDescriptionChange"
            @delete="onDescriptionDelete"
          />
        </TabPane>
        <!-- 资源 -->
        <TabPane key="resource" :tab="$t('AbpOpenIddict.Resources')">
          <Transfer
            v-model:target-keys="formModel.resources"
            :data-source="getSupportClaims"
            :list-style="{
              width: '47%',
              height: '338px',
            }"
            :render="(item) => item.title"
            :titles="[
              $t('AbpOpenIddict.Assigned'),
              $t('AbpOpenIddict.Available'),
            ]"
            class="tree-transfer"
          />
        </TabPane>
        <!-- 属性 -->
        <TabPane key="props" :tab="$t('AbpOpenIddict.Propertites')">
          <PropertyTable
            :data="formModel.properties"
            @change="onPropChange"
            @delete="onPropDelete"
          />
        </TabPane>
      </Tabs>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/openiddict/scopes/scope-modal.tsx
import { useEffect, useState } from "react";
import { Form, Input, Modal, Tabs, Transfer } from "antd";
import { useTranslation } from "react-i18next";
import type { OpenIddictScopeDto, OpenIddictScopeUpdateDto } from "#/openiddict/scopes";
import type { DisplayNameInfo } from "@/components/abp/display-names/types";
import type { PropertyInfo } from "@/components/abp/properties/types";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createApi, getApi, updateApi } from "@/api/openiddict/scopes";
import { discoveryApi } from "@/api/openiddict/open-id";
import DisplayNameTable from "@/components/abp/display-names/display-name-table";
import PropertyTable from "@/components/abp/properties/property-table";
import { toast } from "sonner";
import { CircleLoading } from "@/components/loading";

interface Props {
	visible: boolean;
	scopeId?: string;
	onClose: () => void;
	onChange: (data: OpenIddictScopeDto) => void;
}

type TabKeys = "basic" | "displayName" | "description" | "resource" | "props";

const defaultModel = {
	name: "",
	extraProperties: {},
};

const ScopeModal: React.FC<Props> = ({ visible, scopeId, onClose, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const queryClient = useQueryClient();
	const [activeTab, setActiveTab] = useState<TabKeys>("basic");
	const [formModel, setFormModel] = useState<OpenIddictScopeUpdateDto>(defaultModel);

	// Fetch OpenID configuration
	const { data: openIdConfig } = useQuery({
		queryKey: ["openid-configuration"],
		queryFn: discoveryApi,
		enabled: visible,
	});

	// Fetch scope data if editing
	const { data: scopeData, isLoading } = useQuery({
		queryKey: ["scopeId", scopeId],
		queryFn: () => {
			if (!scopeId) {
				return Promise.reject(new Error("scopeId is undefined"));
			}
			return getApi(scopeId);
		},
		enabled: !!scopeId && visible,
	});

	useEffect(() => {
		if (scopeData && scopeData.id === scopeId) {
			setFormModel(scopeData);
			form.setFieldsValue(scopeData);
		}
	}, [scopeData]);

	useEffect(() => {
		if (visible) {
			setActiveTab("basic");
		}
	}, [visible]);

	// Create/Update mutations
	const { mutateAsync: createScope } = useMutation({
		mutationFn: createApi,
		onSuccess: (data) => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(data);
			onClose();
		},
	});

	const { mutateAsync: updateScope } = useMutation({
		mutationFn: ({ id, input }: { id: string; input: OpenIddictScopeUpdateDto }) => updateApi(id, input),
		onSuccess: (data) => {
			queryClient.invalidateQueries({ queryKey: ["scopeId", scopeId] });
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(data);
			onClose();
		},
	});

	const handleDisplayNameChange = (displayName: DisplayNameInfo) => {
		setFormModel((prev) => ({
			...prev,
			displayNames: {
				...prev.displayNames,
				[displayName.culture]: displayName.displayName,
			},
		}));
	};

	const handleDisplayNameDelete = (displayName: DisplayNameInfo) => {
		setFormModel((prev) => {
			const newDisplayNames = { ...prev.displayNames };
			delete newDisplayNames[displayName.culture];
			return {
				...prev,
				displayNames: newDisplayNames,
			};
		});
	};

	const handleDescriptionChange = (description: DisplayNameInfo) => {
		setFormModel((prev) => ({
			...prev,
			descriptions: {
				...prev.descriptions,
				[description.culture]: description.displayName,
			},
		}));
	};

	const handleDescriptionDelete = (description: DisplayNameInfo) => {
		setFormModel((prev) => {
			const newDescriptions = { ...prev.descriptions };
			delete newDescriptions[description.culture];
			return {
				...prev,
				descriptions: newDescriptions,
			};
		});
	};

	const handlePropertyChange = (prop: PropertyInfo) => {
		setFormModel((prev) => ({
			...prev,
			properties: {
				...prev.properties,
				[prop.key]: prop.value,
			},
		}));
	};

	const handlePropertyDelete = (prop: PropertyInfo) => {
		setFormModel((prev) => {
			const newProperties = { ...prev.properties };
			delete newProperties[prop.key];
			return {
				...prev,
				properties: newProperties,
			};
		});
	};

	const handleSubmit = async () => {
		try {
			await form.validateFields();
			if (scopeId) {
				await updateScope({ id: scopeId, input: formModel });
			} else {
				await createScope(formModel);
			}
		} catch (error) {
			console.error("Validation failed:", error);
		}
	};

	return (
		<Modal
			open={visible}
			title={scopeId ? `${$t("AbpOpenIddict.Scopes")} - ${formModel.name}` : $t("AbpOpenIddict.Scopes:AddNew")}
			onCancel={() => {
				onClose();
				form.resetFields();
				setFormModel(defaultModel);
				form.setFieldsValue(defaultModel);
			}}
			onClose={() => {
				onClose();
				form.resetFields();
				setFormModel(defaultModel);
				form.setFieldsValue(defaultModel);
			}}
			onOk={handleSubmit}
			width="50%"
			destroyOnClose
		>
			{!!scopeId && visible && isLoading ? (
				<CircleLoading />
			) : (
				<Form form={form} layout="horizontal" labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
					<Tabs activeKey={activeTab} onChange={(key) => setActiveTab(key as TabKeys)}>
						{/* Basic Info Tab */}
						<Tabs.TabPane key="basic" tab={$t("AbpOpenIddict.BasicInfo")}>
							<Form.Item label={$t("AbpOpenIddict.DisplayName:Name")} name="name" rules={[{ required: true }]}>
								<Input autoComplete="off" />
							</Form.Item>
						</Tabs.TabPane>

						{/* Display Names Tab */}
						<Tabs.TabPane key="displayName" tab={$t("AbpOpenIddict.DisplayNames")}>
							<Form.Item label={$t("AbpOpenIddict.DisplayName:DefaultDisplayName")} name="displayName">
								<Input autoComplete="off" />
							</Form.Item>
							<DisplayNameTable
								data={formModel.displayNames}
								onChange={handleDisplayNameChange}
								onDelete={handleDisplayNameDelete}
							/>
						</Tabs.TabPane>

						{/* Descriptions Tab */}
						<Tabs.TabPane key="description" tab={$t("AbpOpenIddict.Descriptions")}>
							<Form.Item label={$t("AbpOpenIddict.DisplayName:DefaultDescription")} name="description">
								<Input autoComplete="off" />
							</Form.Item>
							<DisplayNameTable
								data={formModel.descriptions}
								onChange={handleDescriptionChange}
								onDelete={handleDescriptionDelete}
							/>
						</Tabs.TabPane>

						{/* Resources Tab */}
						<Tabs.TabPane key="resource" tab={$t("AbpOpenIddict.Resources")}>
							<Transfer
								dataSource={openIdConfig?.claims_supported?.map((claim) => ({
									key: claim,
									title: claim,
								}))}
								targetKeys={formModel.resources || []}
								onChange={(targetKeys) => {
									const stringTargetKeys = targetKeys.map(String);
									setFormModel((prev) => ({
										...prev,
										resources: stringTargetKeys,
									}));
								}}
								render={(item) => item.title}
								listStyle={{
									width: "47%",
									height: "338px",
								}}
								titles={[$t("AbpOpenIddict.Assigned"), $t("AbpOpenIddict.Available")]}
							/>
						</Tabs.TabPane>

						{/* Properties Tab */}
						<Tabs.TabPane key="props" tab={$t("AbpOpenIddict.Propertites")}>
							<PropertyTable
								data={formModel.properties}
								onChange={handlePropertyChange}
								onDelete={handlePropertyDelete}
							/>
						</Tabs.TabPane>
					</Tabs>
				</Form>
			)}
		</Modal>
	);
};

export default ScopeModal;
