// apps/react-admin/src/pages/management/settings/settings/setting-form.tsx
import { useEffect, useState } from "react";
import { Card, Form, Tabs, Collapse, Input, InputNumber, DatePicker, Select, Checkbox, Button } from "antd";
import { useTranslation } from "react-i18next";
import {
	ValueType,
	type SettingDetail,
	type SettingGroup,
	type SettingsUpdateInput,
} from "#/management/settings/settings";
import { formatToDate } from "@/utils/abp";
import { SettingOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
import { toast } from "sonner";

interface Props {
	getApi: () => Promise<SettingGroup[]>;
	submitApi: (input: SettingsUpdateInput) => Promise<void>;
	onChange: (data: SettingsUpdateInput) => void;
	slots?: {
		[key: string]: React.FC<{
			detail: SettingDetail;
			onChange: (setting: SettingDetail) => void;
		}>;
	};
}

const defaultModel: SettingsUpdateInput = {
	settings: [],
};

const SettingForm: React.FC<Props> = ({ getApi, submitApi, onChange, slots }) => {
	const { t: $t } = useTranslation();
	// const [form] = Form.useForm();
	const [activeTab, setActiveTab] = useState(0);
	const [submitting, setSubmitting] = useState(false);
	const [settingGroups, setSettingGroups] = useState<SettingGroup[]>([]);
	const [settingsUpdateInput, setSettingsUpdateInput] = useState<SettingsUpdateInput>(defaultModel);

	useEffect(() => {
		fetchSettings();
	}, []);

	const fetchSettings = async () => {
		const groups = await getApi();
		setSettingGroups(groups);
	};

	const getExpandedCollapseKeys = (group: SettingGroup) => {
		return group.settings.map((setting) => setting.displayName);
	};

	const handleSubmit = async () => {
		if (settingsUpdateInput.settings.length === 0) return;

		try {
			setSubmitting(true);
			await submitApi(settingsUpdateInput);
			onChange(settingsUpdateInput);
			toast.success($t("AbpSettingManagement.SuccessfullySaved"));
		} finally {
			setSubmitting(false);
		}
	};

	const handleCheckChange = (setting: SettingDetail) => {
		setting.value = setting.value === "true" ? "false" : "true";
		handleValueChange(setting);
	};

	const handleDateChange = (date: any, setting: SettingDetail) => {
		setting.value = dayjs.isDayjs(date) ? formatToDate(date) : "";
		handleValueChange(setting);
	};

	const handleValueChange = (setting: SettingDetail) => {
		if (setting.valueType === ValueType.NoSet) return;

		setSettingsUpdateInput((prev) => {
			const newSettings = [...prev.settings];
			const index = newSettings.findIndex((s) => s.name === setting.name);

			if (index === -1) {
				newSettings.push({
					name: setting.name,
					value: String(setting.value),
				});
			} else {
				newSettings[index] = {
					...newSettings[index],
					value: String(setting.value),
				};
			}

			return { settings: newSettings };
		});
	};

	const renderSettingInput = (detail: SettingDetail) => {
		// 如果存在自定义槽位，优先使用槽位
		if (detail.slot && slots?.[detail.slot]) {
			const SlotComponent = slots[detail.slot];
			// return <SlotComponent detail={detail} onChange={(_)=>{}} />;
			return <SlotComponent detail={detail} onChange={handleValueChange} />;
		}

		switch (detail.valueType) {
			case ValueType.String:
				return detail.isEncrypted ? (
					<Input.Password
						value={detail.value}
						placeholder={detail.description}
						onChange={(e) => {
							detail.value = e.target.value;
							handleValueChange(detail);
						}}
					/>
				) : (
					<Input
						value={detail.value}
						placeholder={detail.description}
						onChange={(e) => {
							detail.value = e.target.value;
							handleValueChange(detail);
						}}
					/>
				);
			case ValueType.Number:
				return !detail.isEncrypted ? (
					<InputNumber
						className="w-full"
						value={detail.value}
						placeholder={detail.description}
						onChange={(value) => {
							detail.value = String(value);
							handleValueChange(detail);
						}}
					/>
				) : null;
			case ValueType.Date:
				return (
					<DatePicker
						className="w-full"
						placeholder={detail.description}
						value={detail.value ? dayjs(detail.value, "YYYY-MM-DD") : null}
						onChange={(date) => handleDateChange(date, detail)}
					/>
				);
			case ValueType.Option:
				return (
					<Select
						value={detail.value}
						onChange={(value) => {
							detail.value = value;
							handleValueChange(detail);
						}}
					>
						{detail.options?.map((option) => (
							<Select.Option key={option.value} value={option.value} disabled={option.value === detail.value}>
								{option.name}
							</Select.Option>
						))}
					</Select>
				);
			case ValueType.Boolean:
				return (
					<Checkbox checked={detail.value === "true"} onChange={() => handleCheckChange(detail)}>
						{detail.displayName}
					</Checkbox>
				);
			default:
				return null;
		}
	};

	return (
		<Card
			title={$t("AbpSettingManagement.Settings")}
			extra={
				settingsUpdateInput.settings.length > 0 && (
					<Button
						type="primary"
						icon={<SettingOutlined />}
						loading={submitting}
						onClick={handleSubmit}
						className="w-[100px]"
					>
						{$t("AbpUi.Submit")}
					</Button>
				)
			}
		>
			<Form labelCol={{ span: 5 }} wrapperCol={{ span: 15 }}>
				<Tabs activeKey={String(activeTab)} onChange={(key) => setActiveTab(Number(key))}>
					{settingGroups.map((group, index) => (
						// biome-ignore lint: reason
						<Tabs.TabPane key={index} tab={group.displayName}>
							<Collapse defaultActiveKey={getExpandedCollapseKeys(group)}>
								{group.settings.map((setting) => (
									<Collapse.Panel key={setting.displayName} header={setting.displayName}>
										{setting.details.map((detail) => (
											<Form.Item key={detail.name} label={detail.displayName} extra={detail.description}>
												{renderSettingInput(detail)}
											</Form.Item>
										))}
									</Collapse.Panel>
								))}
							</Collapse>
						</Tabs.TabPane>
					))}
				</Tabs>
			</Form>
		</Card>
	);
};

export default SettingForm;

// apps/vben5/packages/@abp/settings/src/components/settings/SettingForm.vue
<script setup lang="ts">
import type {
  SettingDetail,
  SettingGroup,
  SettingsUpdateInput,
} from '../../types';

import { computed, onMounted, ref, toValue } from 'vue';

import { $t } from '@vben/locales';

import { formatToDate } from '@abp/core';
import {
  Button,
  Card,
  Checkbox,
  Collapse,
  DatePicker,
  Form,
  Input,
  InputNumber,
  InputPassword,
  message,
  Select,
  Tabs,
} from 'ant-design-vue';
import dayjs from 'dayjs';

import { ValueType } from '../../types';

defineOptions({
  name: 'SettingForm',
});
const props = defineProps<{
  getApi: () => Promise<SettingGroup[]>;
  submitApi: (input: SettingsUpdateInput) => Promise<void>;
}>();
const emits = defineEmits<{
  (event: 'change', data: SettingsUpdateInput): void;
}>();
const FormItem = Form.Item;
const TabPane = Tabs.TabPane;
const CollapsePanel = Collapse.Panel;
const SelectOption = Select.Option;

const defaultModel: SettingsUpdateInput = {
  settings: [],
};

const activeTab = ref(0);
const submiting = ref(false);
const settingGroups = ref<SettingGroup[]>([]);
const settingsUpdateInput = ref<SettingsUpdateInput>({ ...defaultModel });

const getExpandedCollapseKeys = computed(() => {
  return (group: SettingGroup) => {
    const keys = group.settings.map((group) => {
      return group.displayName;
    });
    return keys;
  };
});

async function onGet() {
  settingGroups.value = await props.getApi();
}

async function onSubmit() {
  try {
    submiting.value = true;
    const input = toValue(settingsUpdateInput);
    await props.submitApi(input);
    emits('change', input);
    message.success($t('AbpSettingManagement.SuccessfullySaved'));
  } finally {
    submiting.value = false;
  }
}

function onCheckChange(setting: SettingDetail) {
  setting.value = setting.value === 'true' ? 'false' : 'true';
  onValueChange(setting);
}

function onDateChange(e: any, setting: SettingDetail) {
  setting.value = dayjs.isDayjs(e) ? formatToDate(e) : '';
  onValueChange(setting);
}

function onValueChange(setting: SettingDetail) {
  if (setting.valueType === ValueType.NoSet) {
    return;
  }
  const index = settingsUpdateInput.value.settings.findIndex(
    (s) => s.name === setting.name,
  );
  if (index === -1) {
    settingsUpdateInput.value.settings.push({
      name: setting.name,
      value: String(setting.value),
    });
  } else {
    settingsUpdateInput.value.settings[index]!.value = String(setting.value);
  }
}

onMounted(onGet);
</script>

<template>
  <Card :title="$t('AbpSettingManagement.Settings')">
    <template #extra>
      <div class="flex flex-row gap-1">
        <slot name="toolbar"></slot>
        <Button
          v-if="settingsUpdateInput.settings.length > 0"
          :loading="submiting"
          class="w-[100px]"
          post-icon="ant-design:setting-outlined"
          type="primary"
          @click="onSubmit"
        >
          {{ $t('AbpUi.Submit') }}
        </Button>
      </div>
    </template>
    <Form :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
      <Tabs v-model="activeTab">
        <TabPane
          v-for="(group, index) in settingGroups"
          :key="index"
          :tab="group.displayName"
        >
          <Collapse :default-active-key="getExpandedCollapseKeys(group)">
            <CollapsePanel
              v-for="setting in group.settings"
              :key="setting.displayName"
              :header="setting.displayName"
            >
              <template v-for="detail in setting.details" :key="detail.name">
                <slot
                  v-if="detail.slot"
                  :change="
                    detail.valueType === ValueType.Boolean
                      ? onCheckChange(detail)
                      : onValueChange(detail)
                  "
                  :detail="detail"
                  :name="detail.slot"
                ></slot>
                <FormItem
                  v-else
                  :extra="detail.description"
                  :label="detail.displayName"
                >
                  <template v-if="detail.valueType === ValueType.String">
                    <InputPassword
                      v-if="detail.isEncrypted"
                      v-model:value="detail.value"
                      :placeholder="detail.description"
                      @change="onValueChange(detail)"
                    />
                    <Input
                      v-else
                      v-model:value="detail.value"
                      :placeholder="detail.description"
                      type="text"
                      @change="onValueChange(detail)"
                    />
                  </template>
                  <InputNumber
                    v-else-if="
                      detail.valueType === ValueType.Number &&
                      !detail.isEncrypted
                    "
                    v-model:value="detail.value"
                    :placeholder="detail.description"
                    class="w-full"
                    @change="onValueChange(detail)"
                  />
                  <DatePicker
                    v-else-if="detail.valueType === ValueType.Date"
                    :placeholder="detail.description"
                    :value="
                      detail.value ? dayjs(detail.value, 'YYYY-MM-DD') : ''
                    "
                    style="width: 100%"
                    @change="onDateChange($event, detail)"
                  />
                  <Select
                    v-if="detail.valueType === ValueType.Option"
                    v-model:value="detail.value"
                    @change="onValueChange(detail)"
                  >
                    <SelectOption
                      v-for="option in detail.options"
                      :key="option.value"
                      :disabled="option.value === detail.value"
                    >
                      {{ option.name }}
                    </SelectOption>
                  </Select>
                  <Checkbox
                    v-if="detail.valueType === ValueType.Boolean"
                    :checked="detail.value === 'true'"
                    @change="onCheckChange(detail)"
                  >
                    {{ detail.displayName }}
                  </Checkbox>
                </FormItem>
              </template>
            </CollapsePanel>
          </Collapse>
        </TabPane>
      </Tabs>
    </Form>
  </Card>
</template>

<style scoped></style>
