// apps/vben5/packages/@abp/identity/src/components/users/UserTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { IdentityUserDto } from '../../types/users';

import { computed, defineAsyncComponent, h } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { AuditLogPermissions, EntityChangeDrawer } from '@abp/auditing';
import { formatToDateTime, useAbpStore, useFeatures } from '@abp/core';
import { PermissionModal } from '@abp/permissions';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  LockOutlined,
  PlusOutlined,
  UnlockOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useUsersApi } from '../../api/useUsersApi';
import {
  IdentitySessionPermissions,
  IdentityUserPermissions,
} from '../../constants/permissions';

defineOptions({
  name: 'UserTable',
});

const UserModal = defineAsyncComponent(() => import('./UserModal.vue'));
const LockModal = defineAsyncComponent(() => import('./UserLockModal.vue'));
const ClaimModal = defineAsyncComponent(() => import('./UserClaimModal.vue'));
const PasswordModal = defineAsyncComponent(
  () => import('./UserPasswordModal.vue'),
);

const MenuItem = Menu.Item;
const CheckIcon = createIconifyIcon('ant-design:check-outlined');
const CloseIcon = createIconifyIcon('ant-design:close-outlined');
const PasswordIcon = createIconifyIcon('carbon:password');
const MenuOutlined = createIconifyIcon('heroicons-outline:menu-alt-3');
const ClaimOutlined = createIconifyIcon('la:id-card-solid');
const PermissionsOutlined = createIconifyIcon('icon-park-outline:permissions');
const SessionIcon = createIconifyIcon('carbon:prompt-session');
const AuditLogIcon = createIconifyIcon('fluent-mdl2:compliance-audit');

const getLockEnd = computed(() => {
  return (row: IdentityUserDto) => {
    if (row.lockoutEnd) {
      const lockTime = new Date(row.lockoutEnd);
      if (lockTime) {
        // 锁定时间高于当前时间不显示
        const nowTime = new Date();
        return lockTime < nowTime;
      }
    }
    return true;
  };
});

const abpStore = useAbpStore();
const { isEnabled } = useFeatures();
const { hasAccessByCodes } = useAccess();
const { cancel, deleteApi, getPagedListApi, unLockApi } = useUsersApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<IdentityUserDto> = {
  columns: [
    {
      field: 'isActive',
      slots: { default: 'active' },
      title: $t('AbpIdentity.DisplayName:IsActive'),
    },
    {
      field: 'userName',
      minWidth: '100px',
      title: $t('AbpIdentity.DisplayName:UserName'),
    },
    {
      field: 'email',
      minWidth: '120px',
      title: $t('AbpIdentity.DisplayName:Email'),
    },
    { field: 'surname', title: $t('AbpIdentity.DisplayName:Surname') },
    { field: 'name', title: $t('AbpIdentity.DisplayName:Name') },
    { field: 'phoneNumber', title: $t('AbpIdentity.DisplayName:PhoneNumber') },
    {
      field: 'lockoutEnd',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      title: $t('AbpIdentity.LockoutEnd'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        return await getPagedListApi({
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<IdentityUserDto> = {
  cellClick: () => {},
};
const [UserEditModal, userModalApi] = useVbenModal({
  connectedComponent: UserModal,
});
const [UserLockModal, lockModalApi] = useVbenModal({
  connectedComponent: LockModal,
});
const [UserPasswordModal, pwdModalApi] = useVbenModal({
  connectedComponent: PasswordModal,
});
const [UserClaimModal, claimModalApi] = useVbenModal({
  connectedComponent: ClaimModal,
});
const [UserPermissionModal, permissionModalApi] = useVbenModal({
  connectedComponent: PermissionModal,
});
const [UserChangeDrawer, userChangeDrawerApi] = useVbenDrawer({
  connectedComponent: EntityChangeDrawer,
});
const [UserSessionDrawer, userSessionDrawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(
    () => import('./UserSessionDrawer.vue'),
  ),
});
const [Grid, { query }] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const handleAdd = () => {
  userModalApi.setData({});
  userModalApi.open();
};

const handleEdit = (row: IdentityUserDto) => {
  userModalApi.setData(row);
  userModalApi.open();
};

const handleDelete = (row: IdentityUserDto) => {
  Modal.confirm({
    centered: true,
    content: $t('AbpIdentity.UserDeletionConfirmationMessage', [row.userName]),
    onCancel: () => {
      cancel('User closed cancel delete modal.');
    },
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
};

const handleUnlock = async (row: IdentityUserDto) => {
  await unLockApi(row.id);
  await query();
};

const handleMenuClick = async (row: IdentityUserDto, info: MenuInfo) => {
  switch (info.key) {
    case 'claims': {
      claimModalApi.setData(row);
      claimModalApi.open();
      break;
    }
    case 'entity-changes': {
      userChangeDrawerApi.setData({
        entityId: row.id,
        entityTypeFullName: 'Volo.Abp.Identity.IdentityUser',
        subject: row.userName,
      });
      userChangeDrawerApi.open();
      break;
    }
    case 'lock': {
      lockModalApi.setData(row);
      lockModalApi.open();
      break;
    }
    case 'password': {
      pwdModalApi.setData(row);
      pwdModalApi.open();
      break;
    }
    case 'permissions': {
      const userId = abpStore.application?.currentUser.id;
      permissionModalApi.setData({
        displayName: row.userName,
        providerKey: row.id,
        providerName: 'U',
        readonly: userId === row.id,
      });
      permissionModalApi.open();
      break;
    }
    case 'session': {
      userSessionDrawerApi.setData(row);
      userSessionDrawerApi.open();
      break;
    }
    case 'unlock': {
      handleUnlock(row);
      break;
    }
  }
};
</script>

<template>
  <Grid :table-title="$t('AbpIdentity.Users')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[IdentityUserPermissions.Create]"
        @click="handleAdd"
      >
        {{ $t('AbpIdentity.NewUser') }}
      </Button>
    </template>
    <template #active="{ row }">
      <div class="flex flex-row justify-center">
        <div :class="row.isActive ? 'text-green-600' : 'text-red-600'">
          <CheckIcon v-if="row.isActive" />
          <CloseIcon v-else />
        </div>
      </div>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <div class="basis-1/3">
          <Button
            :icon="h(EditOutlined)"
            block
            type="link"
            v-access:code="[IdentityUserPermissions.Update]"
            @click="handleEdit(row)"
          >
            {{ $t('AbpUi.Edit') }}
          </Button>
        </div>
        <div class="basis-1/3">
          <Button
            :icon="h(DeleteOutlined)"
            block
            danger
            type="link"
            v-access:code="[IdentityUserPermissions.Delete]"
            @click="handleDelete(row)"
          >
            {{ $t('AbpUi.Delete') }}
          </Button>
        </div>
        <div class="basis-1/3">
          <Dropdown>
            <template #overlay>
              <Menu @click="(info) => handleMenuClick(row, info)">
                <MenuItem
                  v-if="
                    hasAccessByCodes([IdentityUserPermissions.Update]) &&
                    row.isActive &&
                    getLockEnd(row)
                  "
                  key="lock"
                  :icon="h(LockOutlined)"
                >
                  {{ $t('AbpIdentity.Lock') }}
                </MenuItem>
                <MenuItem
                  v-if="
                    hasAccessByCodes([IdentityUserPermissions.Update]) &&
                    row.isActive &&
                    !getLockEnd(row)
                  "
                  key="unlock"
                  :icon="h(UnlockOutlined)"
                >
                  {{ $t('AbpIdentity.UnLock') }}
                </MenuItem>
                <MenuItem
                  v-if="
                    hasAccessByCodes([
                      IdentityUserPermissions.ManagePermissions,
                    ])
                  "
                  key="permissions"
                  :icon="h(PermissionsOutlined)"
                >
                  {{ $t('AbpPermissionManagement.Permissions') }}
                </MenuItem>
                <MenuItem
                  v-if="hasAccessByCodes([IdentitySessionPermissions.Default])"
                  key="session"
                  :icon="h(SessionIcon)"
                >
                  {{ $t('AbpIdentity.IdentitySessions') }}
                </MenuItem>
                <MenuItem
                  v-if="
                    hasAccessByCodes([IdentityUserPermissions.ManageClaims])
                  "
                  key="claims"
                  :icon="h(ClaimOutlined)"
                >
                  {{ $t('AbpIdentity.ManageClaim') }}
                </MenuItem>
                <MenuItem
                  v-if="hasAccessByCodes([IdentityUserPermissions.Update])"
                  key="password"
                  :icon="h(PasswordIcon)"
                >
                  {{ $t('AbpIdentity.SetPassword') }}
                </MenuItem>
                <MenuItem
                  v-if="hasAccessByCodes(['Platform.Menu.ManageUsers'])"
                  key="menus"
                  :icon="h(MenuOutlined)"
                >
                  {{ $t('AppPlatform.Menu:Manage') }}
                </MenuItem>
                <MenuItem
                  v-if="
                    isEnabled('AbpAuditing.Logging.AuditLog') &&
                    hasAccessByCodes([AuditLogPermissions.Default])
                  "
                  key="entity-changes"
                  :icon="h(AuditLogIcon)"
                >
                  {{ $t('AbpAuditLogging.EntitiesChanged') }}
                </MenuItem>
              </Menu>
            </template>
            <Button :icon="h(EllipsisOutlined)" type="link" />
          </Dropdown>
        </div>
      </div>
    </template>
  </Grid>
  <UserLockModal @change="query" />
  <UserClaimModal @change="query" />
  <UserEditModal @change="() => query()" />
  <UserPasswordModal @change="query" />
  <UserPermissionModal />
  <UserSessionDrawer />
  <UserChangeDrawer />
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/management/identity/users/user-table.tsx
import { useRef, useState } from "react";
import { Button, Dropdown, Modal, Space, Tag } from "antd";
import {
	EditOutlined,
	DeleteOutlined,
	EllipsisOutlined,
	LockOutlined,
	UnlockOutlined,
	PlusOutlined,
} from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { IdentityUserDto } from "#/management/identity/user";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getPagedListApi, unLockApi } from "@/api/management/identity/users";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { IdentitySessionPermissions, IdentityUserPermissions } from "@/constants/management/identity/permissions";
import { AuditLogPermissions } from "@/constants/management/auditing/permissions";
import { Iconify } from "@/components/icon";
import { toast } from "sonner";
import { formatToDateTime } from "@/utils/abp";
import useAbpStore from "@/store/abpCoreStore";

// Modals
import UserModal from "./user-modal";
import UserLockModal from "./user-lock-modal";
import UserClaimModal from "./user-claim-modal";
import UserPasswordModal from "./user-password-modal";
import PermissionModal from "@/components/abp/permissions/permission-modal";
import { EntityChangeDrawer } from "@/components/abp/auditing/entity-change-drawer";
import Card from "@/components/card";
import { UserSessionDrawer } from "./user-session-drawer";
import MenuAllotModal from "@/pages/platform/menus/menu-allot-modal";
// Import the MenuAllotModal (Assuming it is in a shared folder or relative path)

const UserTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();
	const queryClient = useQueryClient();
	const abpStore = useAbpStore();

	// Modal visibility states
	const [userModalVisible, setUserModalVisible] = useState(false);
	const [lockModalVisible, setLockModalVisible] = useState(false);
	const [claimModalVisible, setClaimModalVisible] = useState(false);
	const [passwordModalVisible, setPasswordModalVisible] = useState(false);
	const [permissionModalVisible, setPermissionModalVisible] = useState(false);
	const [entityChangeDrawerVisible, setEntityChangeDrawerVisible] = useState(false);
	const [identitySessionsDrawerVisible, setIdentitySessionsDrawerVisible] = useState(false);
	const [menuModalVisible, setMenuModalVisible] = useState(false); // Added state for Menu Modal

	// Selected user state
	const [selectedUser, setSelectedUser] = useState<IdentityUserDto>();

	// Check if user is locked
	const isLocked = (user: IdentityUserDto) => {
		if (!user.lockoutEnd) return false;
		const lockTime = new Date(user.lockoutEnd);
		return lockTime > new Date();
	};

	// API Mutations
	const { mutateAsync: deleteUser } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["users"] });
		},
	});

	const { mutateAsync: unlockUser } = useMutation({
		mutationFn: unLockApi,
		onSuccess: () => {
			toast.success($t("AbpIdentity.SavedSuccessfully"));
			actionRef.current?.reload();
			queryClient.invalidateQueries({ queryKey: ["users"] });
		},
	});

	// Handle actions
	const handleMenuClick = (key: string, user: IdentityUserDto) => {
		setSelectedUser(user);
		switch (key) {
			case "lock":
				setLockModalVisible(true);
				break;
			case "unlock":
				modal.confirm({
					title: $t("AbpUi.AreYouSure"),
					onOk: () => unlockUser(user.id),
				});
				break;
			case "permissions":
				setPermissionModalVisible(true);
				break;
			case "session":
				setIdentitySessionsDrawerVisible(true);
				break;
			case "claims":
				setClaimModalVisible(true);
				break;
			case "password":
				setPasswordModalVisible(true);
				break;
			case "entity-changes":
				setEntityChangeDrawerVisible(true);
				break;
			case "menus": // Handle menu click
				setMenuModalVisible(true);
				break;
		}
	};

	const columns: ProColumns<IdentityUserDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			hideInTable: true,
		},
		{
			title: $t("AbpIdentity.DisplayName:IsActive"),
			dataIndex: "isActive",
			width: 100,
			align: "center",
			hideInSearch: true,
			render: (_, record) => (
				<Tag color={record.isActive ? "success" : "error"}>{record.isActive ? $t("AbpUi.Yes") : $t("AbpUi.No")}</Tag>
			),
		},
		{
			title: $t("AbpIdentity.DisplayName:UserName"),
			dataIndex: "userName",
			hideInSearch: true,
			width: 150,
		},
		{
			title: $t("AbpIdentity.DisplayName:Email"),
			dataIndex: "email",
			hideInSearch: true,
			width: 180,
			sorter: true,
		},
		{
			title: $t("AbpIdentity.DisplayName:PhoneNumber"),
			dataIndex: "phoneNumber",
			hideInSearch: true,
			width: 120,
		},
		{
			title: $t("AbpIdentity.DisplayName:Surname"),
			dataIndex: "surname",
			hideInSearch: true,
			width: 100,
		},
		{
			title: $t("AbpIdentity.DisplayName:Name"),
			dataIndex: "name",
			hideInSearch: true,

			width: 100,
		},
		{
			title: $t("AbpIdentity.LockoutEnd"),
			hideInSearch: true,
			dataIndex: "lockoutEnd",
			width: 160,
			render: (_, record) => (record.lockoutEnd ? formatToDateTime(record.lockoutEnd) : "-"),
		},
		{
			title: $t("AbpUi.Actions"),
			width: 200,
			hideInSearch: true,
			fixed: "right",
			render: (_, record) => (
				<Space>
					{hasAccessByCodes([IdentityUserPermissions.Update]) && (
						<Button
							type="link"
							icon={<EditOutlined />}
							onClick={() => {
								setSelectedUser(record);
								setUserModalVisible(true);
							}}
						>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{hasAccessByCodes([IdentityUserPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
					<Dropdown
						menu={{
							items: getDropdownItems(record),
							onClick: ({ key }) => handleMenuClick(key, record),
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	const handleDelete = (user: IdentityUserDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpIdentity.UserDeletionConfirmationMessage", { 0: user.userName }),
			onOk: () => deleteUser(user.id),
		});
	};

	const getDropdownItems = (record: IdentityUserDto) => {
		const items = [];

		// Lock/Unlock
		if (hasAccessByCodes([IdentityUserPermissions.Update])) {
			if (record.isActive && !isLocked(record)) {
				items.push({
					key: "lock",
					icon: <LockOutlined />,
					label: $t("AbpIdentity.Lock"),
				});
			}
			if (record.isActive && isLocked(record)) {
				items.push({
					key: "unlock",
					icon: <UnlockOutlined />,
					label: $t("AbpIdentity.UnLock"),
				});
			}
		}

		// Permissions
		if (hasAccessByCodes([IdentityUserPermissions.ManagePermissions])) {
			items.push({
				key: "permissions",
				icon: <Iconify icon="icon-park-outline:permissions" />,
				label: $t("AbpPermissionManagement.Permissions"),
			});
		}

		// Identity Sessions
		if (hasAccessByCodes([IdentitySessionPermissions.Default])) {
			items.push({
				key: "session",
				icon: <Iconify icon="carbon:prompt-session" />,
				label: $t("AbpIdentity.IdentitySessions"),
			});
		}

		// Claims
		if (hasAccessByCodes([IdentityUserPermissions.ManageClaims])) {
			items.push({
				key: "claims",
				icon: <Iconify icon="la:id-card-solid" />,
				label: $t("AbpIdentity.ManageClaim"),
			});
		}

		// Password
		if (hasAccessByCodes([IdentityUserPermissions.Update])) {
			items.push({
				key: "password",
				icon: <Iconify icon="carbon:password" />,
				label: $t("AbpIdentity.SetPassword"),
			});
		}

		// Menus (Added this section)
		if (hasAccessByCodes(["Platform.Menu.ManageUsers"])) {
			items.push({
				key: "menus",
				icon: <Iconify icon="heroicons-outline:menu-alt-3" />,
				label: $t("AppPlatform.Menu:Manage"),
			});
		}

		// Audit Log
		if (hasAccessByCodes([AuditLogPermissions.Default])) {
			items.push({
				key: "entity-changes",
				icon: <Iconify icon="fluent-mdl2:compliance-audit" />,
				label: $t("AbpAuditLogging.EntitiesChanged"),
			});
		}

		return items;
	};

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<IdentityUserDto>
					actionRef={actionRef}
					columns={columns}
					request={async (params) => {
						const { current, pageSize, filter } = params;
						const query = await queryClient.fetchQuery({
							queryKey: ["users", params],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									filter: filter,
								}),
						});
						return {
							data: query.items,
							total: query.totalCount,
						};
					}}
					rowKey="id"
					search={{
						span: 12,
						labelWidth: "auto",
					}}
					pagination={{
						showSizeChanger: true,
					}}
					toolBarRender={() => [
						hasAccessByCodes([IdentityUserPermissions.Create]) && (
							<Button
								type="primary"
								icon={<PlusOutlined />}
								onClick={() => {
									setSelectedUser(undefined);
									setUserModalVisible(true);
								}}
							>
								{$t("AbpIdentity.NewUser")}
							</Button>
						),
					]}
				/>
			</Card>

			{/* User Modal */}
			<UserModal
				visible={userModalVisible}
				userId={selectedUser?.id}
				onClose={() => {
					setUserModalVisible(false);
					setSelectedUser(undefined);
				}}
				onChange={() => actionRef.current?.reload()}
			/>

			{/* Lock Modal */}
			{selectedUser && (
				<UserLockModal
					visible={lockModalVisible}
					userId={selectedUser.id}
					onClose={() => {
						setLockModalVisible(false);
						setSelectedUser(undefined);
					}}
					onChange={() => {
						actionRef.current?.reload();
						queryClient.invalidateQueries({ queryKey: ["users"] });
					}}
				/>
			)}

			{/* Claim Modal */}
			{selectedUser && (
				<UserClaimModal
					visible={claimModalVisible}
					user={selectedUser}
					onClose={() => {
						setClaimModalVisible(false);
						setSelectedUser(undefined);
					}}
					onChange={() => actionRef.current?.reload()}
				/>
			)}

			{/* Password Modal */}
			{selectedUser && (
				<UserPasswordModal
					visible={passwordModalVisible}
					userId={selectedUser.id}
					onClose={() => {
						setPasswordModalVisible(false);
						setSelectedUser(undefined);
					}}
					onChange={() => actionRef.current?.reload()}
				/>
			)}

			{/* Permission Modal */}
			<PermissionModal
				visible={permissionModalVisible}
				providerKey={selectedUser?.id}
				providerName="U"
				displayName={selectedUser?.userName}
				readonly={abpStore.application?.currentUser.id === selectedUser?.id}
				onClose={() => {
					setPermissionModalVisible(false);
					setSelectedUser(undefined);
				}}
				onChange={() => actionRef.current?.reload()}
			/>
			{/* Session Drawer */}
			{selectedUser && (
				<UserSessionDrawer
					open={identitySessionsDrawerVisible}
					user={selectedUser}
					onClose={() => {
						setIdentitySessionsDrawerVisible(false);
						setSelectedUser(undefined);
					}}
				/>
			)}

			{/* Entity Change Drawer */}
			<EntityChangeDrawer
				open={entityChangeDrawerVisible}
				input={{
					entityId: selectedUser?.id,
					entityTypeFullName: "Volo.Abp.Identity.IdentityUser",
				}}
				subject={selectedUser?.userName}
				onClose={() => {
					setEntityChangeDrawerVisible(false);
					setSelectedUser(undefined);
				}}
			/>

			{/* Menu Allot Modal - Added for Users */}
			<MenuAllotModal
				visible={menuModalVisible}
				subject="user"
				identity={selectedUser?.id || ""}
				onClose={() => {
					setMenuModalVisible(false);
					setSelectedUser(undefined);
				}}
			/>
		</>
	);
};

export default UserTable;
