// apps/vben5/packages/@abp/identity/src/components/users/UserLockModal.vue
<!-- eslint-disable no-unused-vars -->
<script setup lang="ts">
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useVbenForm } from '@abp/ui';

import { lockApi } from '../../api/users';

defineOptions({
  name: 'UserLockModal',
});
const emits = defineEmits<{
  (event: 'change'): void;
}>();

enum LockType {
  Days = 86_400,
  Hours = 3600,
  Minutes = 60,
  Months = 2_678_400, // 按31天计算
  Seconds = 1,
  Years = 32_140_800, // 按31*12天计算
}

const [Form, formApi] = useVbenForm({
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      componentProps: {
        style: {
          display: 'none',
        },
      },
      fieldName: 'userId',
    },
    {
      component: 'InputNumber',
      fieldName: 'seconds',
      label: $t('AbpIdentity.LockTime'),
      rules: 'required',
    },
    {
      component: 'Select',
      componentProps: {
        options: [
          // TODO: 本地化
          { label: $t('LockType:Seconds'), value: LockType.Seconds },
          { label: $t('LockType:Minutes'), value: LockType.Minutes },
          { label: $t('LockType:Hours'), value: LockType.Hours },
          { label: $t('LockType:Days'), value: LockType.Days },
          { label: $t('LockType:Months'), value: LockType.Months },
          { label: $t('LockType:Years'), value: LockType.Years },
        ],
      },
      defaultValue: LockType.Seconds,
      fieldName: 'type',
      label: $t('AbpIdentity.LockType'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});

const [Modal, modalApi] = useVbenModal({
  closeOnClickModal: false,
  closeOnPressEscape: false,
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  async onOpenChange(isOpen: boolean) {
    if (isOpen) {
      const { id } = modalApi.getData<Record<string, any>>();
      formApi.setValues({
        userId: id,
      });
    }
  },
  title: $t('AbpIdentity.Lock'),
});

async function onSubmit(input: Record<string, any>) {
  try {
    modalApi.setState({
      confirmLoading: true,
    });
    const lockSeconds = input.type * input.seconds;
    await lockApi(input.userId, lockSeconds);
    emits('change');
    modalApi.close();
  } finally {
    modalApi.setState({
      confirmLoading: false,
    });
  }
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/users/user-lock-modal.tsx
import { Modal, Form, InputNumber, Select } from "antd";
import { useTranslation } from "react-i18next";
import { useMutation } from "@tanstack/react-query";
import { lockApi } from "@/api/management/identity/users";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: () => void;
	userId: string;
}

enum LockType {
	Seconds = 1,
	Minutes = 60,
	Hours = 3600,
	Days = 86400,
	Months = 2678400, // 按31天计算
	Years = 32140800, // 按31*12天计算
}

const UserLockModal: React.FC<Props> = ({ visible, onClose, onChange, userId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	// 锁定用户
	const { mutateAsync: lockUser, isPending } = useMutation({
		mutationFn: ({ id, seconds }: { id: string; seconds: number }) => lockApi(id, seconds),
		onSuccess: () => {
			onChange();
			onClose();
		},
	});

	const handleOk = async () => {
		try {
			const values = await form.validateFields();
			const lockSeconds = values.type * values.seconds;
			await lockUser({ id: userId, seconds: lockSeconds });
		} catch (error) {
			// Form validation error
		}
	};

	return (
		<Modal open={visible} title={$t("AbpIdentity.Lock")} onCancel={onClose} onOk={handleOk} confirmLoading={isPending}>
			<Form form={form} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} initialValues={{ type: LockType.Seconds }}>
				<Form.Item name="seconds" label={$t("AbpIdentity.LockTime")} rules={[{ required: true }]}>
					<InputNumber className="w-full" />
				</Form.Item>

				<Form.Item name="type" label={$t("AbpIdentity.LockType")} rules={[{ required: true }]}>
					<Select
						options={[
							{ label: $t("AbpIdentity.LockType:Seconds"), value: LockType.Seconds },
							{ label: $t("AbpIdentity.LockType:Minutes"), value: LockType.Minutes },
							{ label: $t("AbpIdentity.LockType:Hours"), value: LockType.Hours },
							{ label: $t("AbpIdentity.LockType:Days"), value: LockType.Days },
							{ label: $t("AbpIdentity.LockType:Months"), value: LockType.Months },
							{ label: $t("AbpIdentity.LockType:Years"), value: LockType.Years },
						]}
					/>
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default UserLockModal;
