// apps/vben5/packages/@abp/identity/src/components/users/UserSessionDrawer.vue
<script setup lang="ts">
import type { IdentitySessionDto, IdentityUserDto } from '../../types';

import { defineAsyncComponent, ref } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { message, Modal } from 'ant-design-vue';

import { useUserSessionsApi } from '../../api/useUserSessionsApi';

const UserSessionTable = defineAsyncComponent(
  () => import('../sessions/UserSessionTable.vue'),
);

const sessions = ref<IdentitySessionDto[]>([]);

const { cancel, getSessionsApi, revokeSessionApi } = useUserSessionsApi();

const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-[800px]',
  onCancel() {
    drawerApi.close();
    cancel();
  },
  onConfirm: async () => {},
  onOpenChange: async (isOpen: boolean) => {
    isOpen && (await onRefresh());
  },
  title: $t('AbpIdentity.IdentitySessions'),
});
async function onRefresh() {
  try {
    drawerApi.setState({ loading: true });
    const dto = drawerApi.getData<IdentityUserDto>();
    const { items } = await getSessionsApi({ userId: dto.id });
    sessions.value = items;
  } finally {
    drawerApi.setState({ loading: false });
  }
}
async function onRevoke(session: IdentitySessionDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpIdentity.SessionWillBeRevokedMessage'),
    iconType: 'warning',
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await revokeSessionApi(session.sessionId);
      message.success($t('AbpIdentity.SuccessfullyRevoked'));
      await onRefresh();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
</script>

<template>
  <Drawer>
    <UserSessionTable :sessions="sessions" @revoke="onRevoke" />
  </Drawer>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/users/user-session-drawer.tsx
import { Modal } from "antd";
import { useMutation, useQueryClient } from "@tanstack/react-query";

import { Drawer } from "antd";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import UserSessionTable from "../sessions/user-session-table";

import { toast } from "sonner";
import type { IdentitySessionDto } from "#/management/identity/sessions";
import type { IdentityUserDto } from "#/management/identity/user";
import { getSessionsApi, revokeSessionApi } from "@/api/management/identity/user-sessions";

interface UserSessionDrawerProps {
	open: boolean;
	onClose: () => void;
	user: IdentityUserDto;
}

export const UserSessionDrawer: React.FC<UserSessionDrawerProps> = ({ open, onClose, user }) => {
	const { t: $t } = useTranslation();
	const [modal, contextHolder] = Modal.useModal();
	const queryClient = useQueryClient();
	const queryKey = [`user-Sessions${user.id}`];
	// Fetch sessions
	const { data: sessions = [] } = useQuery({
		queryKey: queryKey,
		queryFn: async () => {
			const { items } = await getSessionsApi({ userId: user.id });
			return items;
		},
	});

	// Revoke session mutation
	const { mutateAsync: revokeSession } = useMutation({
		mutationFn: revokeSessionApi,
		onSuccess: () => {
			toast.success($t("AbpIdentity.SuccessfullyRevoked"));
			queryClient.refetchQueries({ queryKey: queryKey });
		},
	});

	const handleRevoke = (session: IdentitySessionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpIdentity.SessionWillBeRevokedMessage"),
			centered: true,
			onOk: () => revokeSession(session.sessionId),
		});
	};

	return (
		<>
			{contextHolder}
			<Drawer open={open} onClose={onClose} width={800}>
				<UserSessionTable sessions={sessions} onRevoke={handleRevoke} />
			</Drawer>
		</>
	);
};
