// apps/react-admin/src/pages/tasks/job-info-drawer.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Drawer, Form, Input, Select, Checkbox, InputNumber, DatePicker, Tabs, Space, Button, Spin } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import dayjs from "dayjs";
import { createApi, updateApi, getApi, getDefinitionsApi } from "@/api/tasks/job-infos";
import type { BackgroundJobInfoDto, BackgroundJobDefinitionDto } from "#/tasks/job-infos";
import { JobPriority, JobType } from "#/tasks/job-infos";
import { formatToDate } from "@/utils/abp";
import PropertyTable from "@/components/abp/properties/property-table";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: BackgroundJobInfoDto) => void;
	jobId?: string; // If provided, edit mode
}

const JobInfoDrawer: React.FC<Props> = ({ visible, onClose, onChange, jobId }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	const [activeTab, setActiveTab] = useState("basic");
	const [loading, setLoading] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const [jobDefinitions, setJobDefinitions] = useState<BackgroundJobDefinitionDto[]>([]);
	const [formModel, setFormModel] = useState<Partial<BackgroundJobInfoDto>>({});

	// Options
	const jobTypeOptions = [
		{ label: $t("BackgroundTasks.JobType:Once"), value: JobType.Once },
		{ label: $t("BackgroundTasks.JobType:Period"), value: JobType.Period },
		{ label: $t("BackgroundTasks.JobType:Persistent"), value: JobType.Persistent },
	];

	const jobPriorityOptions = [
		{ label: $t("BackgroundTasks.Priority:Low"), value: JobPriority.Low },
		{ label: $t("BackgroundTasks.Priority:BelowNormal"), value: JobPriority.BelowNormal },
		{ label: $t("BackgroundTasks.Priority:Normal"), value: JobPriority.Normal },
		{ label: $t("BackgroundTasks.Priority:AboveNormal"), value: JobPriority.AboveNormal },
		{ label: $t("BackgroundTasks.Priority:High"), value: JobPriority.High },
	];

	useEffect(() => {
		if (visible) {
			setActiveTab("basic");
			form.resetFields();
			if (jobId) {
				fetchJob(jobId);
			} else {
				fetchDefinitions();
				// Set Defaults
				const initial = {
					args: {},
					beginTime: formatToDate(new Date()),
					isEnabled: true,
					jobType: JobType.Once,
					priority: JobPriority.Normal,
				};
				setFormModel(initial);
				form.setFieldsValue({
					...initial,
					beginTime: dayjs(), // AntD needs dayjs object
				});
			}
		}
	}, [visible, jobId]);

	const fetchJob = async (id: string) => {
		try {
			setLoading(true);
			const dto = await getApi(id);
			setFormModel(dto);
			form.setFieldsValue({
				...dto,
				beginTime: dto.beginTime ? dayjs(dto.beginTime) : null,
				endTime: dto.endTime ? dayjs(dto.endTime) : null,
			});
		} finally {
			setLoading(false);
		}
	};

	const fetchDefinitions = async () => {
		const { items } = await getDefinitionsApi();
		setJobDefinitions(items);
	};

	const handleJobDefineChange = (jobName: string) => {
		const jobDefine = jobDefinitions.find((x) => x.name === jobName);
		if (jobDefine) {
			const params: Record<string, any> = {};
			jobDefine.paramters.forEach((param) => {
				params[param.name] = undefined;
			});

			const newModel = { ...formModel, args: params, type: jobDefine.name };
			setFormModel(newModel);
			form.setFieldsValue({ type: jobDefine.name }); // Sync specific field
		}
	};

	const handleParamChange = (record: { key: string; value: any }) => {
		setFormModel((prev) => ({
			...prev,
			args: { ...prev.args, [record.key]: record.value },
		}));
	};

	const handleDeleteParam = (record: { key: string }) => {
		setFormModel((prev) => {
			const newArgs = { ...prev.args };
			delete newArgs[record.key];
			return { ...prev, args: newArgs };
		});
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const submitData = {
				...formModel,
				...values,
				// Convert Dayjs back to string
				beginTime: values.beginTime ? values.beginTime.format("YYYY-MM-DD") : null,
				endTime: values.endTime ? values.endTime.format("YYYY-MM-DD") : null,
				args: formModel.args, // Args managed separately via PropertyTable
			};

			const api = jobId ? updateApi(jobId, submitData) : createApi(submitData);

			const res = await api;
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (e) {
			console.error(e);
		} finally {
			setSubmitting(false);
		}
	};

	return (
		<Drawer
			title={
				jobId
					? `${$t("TaskManagement.BackgroundJobs:Edit")} - ${formModel.name}`
					: $t("TaskManagement.BackgroundJobs:AddNew")
			}
			open={visible}
			onClose={onClose}
			width={800}
			extra={
				<Space>
					<Button onClick={onClose}>{$t("AbpUi.Cancel")}</Button>
					<Button type="primary" loading={submitting} onClick={handleSubmit}>
						{$t("AbpUi.Save")}
					</Button>
				</Space>
			}
		>
			<Spin spinning={loading}>
				<Form form={form} layout="horizontal" labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} autoComplete="off">
					<Tabs activeKey={activeTab} onChange={setActiveTab}>
						<Tabs.TabPane key="basic" tab={$t("TaskManagement.BasicInfo")}>
							{!jobId && (
								<Form.Item label={$t("TaskManagement.BackgroundJobs")} extra={$t("TaskManagement.BackgroundJobs")}>
									<Select
										allowClear
										options={jobDefinitions}
										fieldNames={{ label: "displayName", value: "name" }}
										onChange={handleJobDefineChange}
									/>
								</Form.Item>
							)}

							<Form.Item name="isEnabled" valuePropName="checked" label={$t("TaskManagement.DisplayName:IsEnabled")}>
								<Checkbox>{$t("TaskManagement.DisplayName:IsEnabled")}</Checkbox>
							</Form.Item>

							<Form.Item name="nodeName" label={$t("TaskManagement.DisplayName:NodeName")}>
								<Input autoComplete="off" data-lpignore="true" />
							</Form.Item>

							<Form.Item name="group" label={$t("TaskManagement.DisplayName:Group")} rules={[{ required: true }]}>
								<Input autoComplete="off" />
							</Form.Item>

							<Form.Item name="name" label={$t("TaskManagement.DisplayName:Name")} rules={[{ required: true }]}>
								<Input autoComplete="off" />
							</Form.Item>

							<Form.Item
								name="type"
								label={$t("TaskManagement.DisplayName:Type")}
								extra={$t("TaskManagement.Description:Type")}
								rules={[{ required: true }]}
							>
								<Input.TextArea autoSize={{ minRows: 3 }} />
							</Form.Item>

							<Form.Item
								name="beginTime"
								label={$t("TaskManagement.DisplayName:BeginTime")}
								rules={[{ required: true }]}
							>
								<DatePicker className="w-full" showTime />
							</Form.Item>

							<Form.Item name="endTime" label={$t("TaskManagement.DisplayName:EndTime")}>
								<DatePicker className="w-full" showTime />
							</Form.Item>

							<Form.Item
								name="jobType"
								label={$t("TaskManagement.DisplayName:JobType")}
								extra={$t("TaskManagement.Description:JobType")}
							>
								<Select options={jobTypeOptions} allowClear />
							</Form.Item>

							<Form.Item noStyle shouldUpdate={(prev, curr) => prev.jobType !== curr.jobType}>
								{({ getFieldValue }) =>
									getFieldValue("jobType") === JobType.Period ? (
										<Form.Item
											name="cron"
											label={$t("TaskManagement.DisplayName:Cron")}
											extra={$t("TaskManagement.Description:Cron")}
											rules={[{ required: true }]}
										>
											<Input />
										</Form.Item>
									) : (
										<Form.Item
											name="interval"
											label={$t("TaskManagement.DisplayName:Interval")}
											extra={$t("TaskManagement.Description:Interval")}
											rules={[{ required: true }]}
										>
											<InputNumber className="w-full" />
										</Form.Item>
									)
								}
							</Form.Item>

							<Form.Item
								name="maxCount"
								label={$t("TaskManagement.DisplayName:MaxCount")}
								extra={$t("TaskManagement.Description:MaxCount")}
							>
								<InputNumber className="w-full" />
							</Form.Item>

							<Form.Item
								name="maxTryCount"
								label={$t("TaskManagement.DisplayName:MaxTryCount")}
								extra={$t("TaskManagement.Description:MaxTryCount")}
							>
								<InputNumber className="w-full" />
							</Form.Item>

							<Form.Item
								name="priority"
								label={$t("TaskManagement.DisplayName:Priority")}
								extra={$t("TaskManagement.Description:Priority")}
							>
								<Select options={jobPriorityOptions} allowClear />
							</Form.Item>

							<Form.Item
								name="lockTimeOut"
								label={$t("TaskManagement.DisplayName:LockTimeOut")}
								extra={$t("TaskManagement.Description:LockTimeOut")}
							>
								<InputNumber className="w-full" />
							</Form.Item>

							<Form.Item name="description" label={$t("TaskManagement.DisplayName:Description")}>
								<Input.TextArea autoSize={{ minRows: 3 }} />
							</Form.Item>
						</Tabs.TabPane>

						<Tabs.TabPane key="paramters" tab={$t("TaskManagement.Paramters")}>
							<PropertyTable data={formModel.args} onChange={handleParamChange} onDelete={handleDeleteParam} />
						</Tabs.TabPane>
					</Tabs>
				</Form>
			</Spin>
		</Drawer>
	);
};

export default JobInfoDrawer;

// apps/vben5/packages/@abp/tasks/src/components/job-infos/JobInfoDrawer.vue
<script setup lang="ts">
import type { FormInstance } from 'ant-design-vue/lib/form';

import type {
  BackgroundJobDefinitionDto,
  BackgroundJobInfoDto,
} from '../../types/job-infos';

import { reactive, ref, useTemplateRef } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDate } from '@abp/core';
import { PropertyTable } from '@abp/ui';
import {
  Checkbox,
  DatePicker,
  Form,
  FormItem,
  Input,
  InputNumber,
  message,
  Select,
  Tabs,
  Textarea,
} from 'ant-design-vue';

import { useJobInfosApi } from '../../api/useJobInfosApi';
import { JobPriority, JobType } from '../../types/job-infos';

defineOptions({
  name: 'JobInfoDrawer',
});
const emits = defineEmits<{
  (event: 'change', data: BackgroundJobInfoDto): void;
}>();
const TabPane = Tabs.TabPane;
interface JobParamter {
  key: string;
  value: any;
}

const activedTab = ref('basic');
const jobTypeOptions = reactive([
  {
    label: $t('BackgroundTasks.JobType:Once'),
    value: JobType.Once,
  },
  {
    label: $t('BackgroundTasks.JobType:Period'),
    value: JobType.Period,
  },
  {
    label: $t('BackgroundTasks.JobType:Persistent'),
    value: JobType.Persistent,
  },
]);
const jobPriorityOptions = reactive([
  {
    label: $t('BackgroundTasks.Priority:Low'),
    value: JobPriority.Low,
  },
  {
    label: $t('BackgroundTasks.Priority:BelowNormal'),
    value: JobPriority.BelowNormal,
  },
  {
    label: $t('BackgroundTasks.Priority:Normal'),
    value: JobPriority.Normal,
  },
  {
    label: $t('BackgroundTasks.Priority:AboveNormal'),
    value: JobPriority.AboveNormal,
  },
  {
    label: $t('BackgroundTasks.Priority:High'),
    value: JobPriority.High,
  },
]);
const jobDefinetions = ref<BackgroundJobDefinitionDto[]>([]);
const form = useTemplateRef<FormInstance>('form');
const formModel = ref<BackgroundJobInfoDto>({} as BackgroundJobInfoDto);
const { createApi, getApi, getDefinitionsApi, updateApi } = useJobInfosApi();
const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-auto',
  onCancel() {
    drawerApi.close();
  },
  onConfirm: async () => {
    await onSubmit();
  },
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      try {
        formModel.value = {
          beginTime: formatToDate(new Date()),
          isEnabled: true,
          jobType: JobType.Once,
          priority: JobPriority.Normal,
        } as BackgroundJobInfoDto;
        drawerApi.setState({ loading: true });
        const dto = drawerApi.getData<BackgroundJobInfoDto>();
        if (dto?.id) {
          await onGet(dto.id);
        } else {
          await onInitDefaultJobs();
          drawerApi.setState({
            title: $t('TaskManagement.BackgroundJobs:AddNew'),
          });
        }
      } finally {
        drawerApi.setState({ loading: false });
      }
    }
  },
  title: $t('BackgroundJobs:Edit'),
});
async function onGet(id: string) {
  const dto = await getApi(id);
  formModel.value = dto;
  drawerApi.setState({
    title: `${$t('TaskManagement.BackgroundJobs:Edit')} - ${dto.name}`,
  });
}

async function onInitDefaultJobs() {
  const { items } = await getDefinitionsApi();
  jobDefinetions.value = items;
}

async function onSubmit() {
  await form.value?.validate();
  try {
    drawerApi.setState({ confirmLoading: true });
    const api = formModel.value?.id
      ? updateApi(formModel.value.id, formModel.value)
      : createApi(formModel.value);
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    drawerApi.close();
  } finally {
    drawerApi.setState({ confirmLoading: false });
  }
}

function onJobDefineChange(jobName: string) {
  formModel.value.args = {};
  const jobDefine = jobDefinetions.value.find((x) => x.name === jobName);
  if (jobDefine) {
    const params: Record<string, any> = {};
    jobDefine.paramters.forEach((param) => {
      params[param.name] = undefined;
    });
    formModel.value.args = params;
    formModel.value.type = jobDefine.name;
  }
}

function onEditParam(record: JobParamter) {
  formModel.value.args[record.key] = record.value;
}

function onDeleteParam(record: JobParamter) {
  delete formModel.value.args[record.key];
}
</script>

<template>
  <Drawer>
    <div style="width: 800px">
      <Form
        ref="form"
        :model="formModel"
        :label-col="{ span: 4 }"
        :wrapper-col="{ span: 18 }"
      >
        <Tabs v-model="activedTab">
          <TabPane key="basic" :tab="$t('TaskManagement.BasicInfo')">
            <FormItem
              v-if="!formModel.id"
              :label="$t('TaskManagement.BackgroundJobs')"
              :help="$t('TaskManagement.BackgroundJobs')"
            >
              <Select
                class="w-full"
                allow-clear
                :options="jobDefinetions"
                :field-names="{ label: 'displayName', value: 'name' }"
                @change="(val) => onJobDefineChange(val!.toString())"
              />
            </FormItem>
            <FormItem
              name="isEnabled"
              :label="$t('TaskManagement.DisplayName:IsEnabled')"
            >
              <Checkbox v-model:checked="formModel.isEnabled">
                {{ $t('TaskManagement.DisplayName:IsEnabled') }}
              </Checkbox>
            </FormItem>
            <FormItem
              name="nodeName"
              :label="$t('TaskManagement.DisplayName:NodeName')"
            >
              <Input
                v-model:value="formModel.nodeName"
                allow-clear
                autocomplete="off"
              />
            </FormItem>
            <FormItem
              name="group"
              required
              :label="$t('TaskManagement.DisplayName:Group')"
            >
              <Input
                v-model:value="formModel.group"
                allow-clear
                autocomplete="off"
              />
            </FormItem>
            <FormItem
              name="name"
              required
              :label="$t('TaskManagement.DisplayName:Name')"
            >
              <Input
                v-model:value="formModel.name"
                allow-clear
                autocomplete="off"
              />
            </FormItem>
            <FormItem
              name="type"
              required
              :label="$t('TaskManagement.DisplayName:Type')"
              :extra="$t('TaskManagement.Description:Type')"
            >
              <Textarea
                allow-clear
                v-model:value="formModel.type"
                :auto-size="{ minRows: 3 }"
              />
            </FormItem>
            <FormItem
              name="beginTime"
              required
              :label="$t('TaskManagement.DisplayName:BeginTime')"
            >
              <DatePicker
                class="w-full"
                value-format="YYYY-MM-DD"
                allow-clear
                v-model:value="formModel.beginTime"
              />
            </FormItem>
            <FormItem
              name="endTime"
              :label="$t('TaskManagement.DisplayName:EndTime')"
            >
              <DatePicker
                class="w-full"
                value-format="YYYY-MM-DD"
                allow-clear
                v-model:value="formModel.endTime"
              />
            </FormItem>
            <FormItem
              name="jobType"
              :label="$t('TaskManagement.DisplayName:JobType')"
              :extra="$t('TaskManagement.Description:JobType')"
            >
              <Select
                class="w-full"
                allow-clear
                v-model:value="formModel.jobType"
                :options="jobTypeOptions"
              />
            </FormItem>
            <FormItem
              v-if="formModel.jobType === JobType.Period"
              name="cron"
              required
              :label="$t('TaskManagement.DisplayName:Cron')"
              :extra="$t('TaskManagement.Description:Cron')"
            >
              <Input allow-clear v-model:value="formModel.cron" />
            </FormItem>
            <FormItem
              name="maxCount"
              :label="$t('TaskManagement.DisplayName:MaxCount')"
              :extra="$t('TaskManagement.Description:MaxCount')"
            >
              <InputNumber
                class="w-full"
                allow-clear
                v-model:value="formModel.maxCount"
              />
            </FormItem>
            <FormItem
              name="maxTryCount"
              :label="$t('TaskManagement.DisplayName:MaxTryCount')"
              :extra="$t('TaskManagement.Description:MaxTryCount')"
            >
              <InputNumber
                class="w-full"
                allow-clear
                v-model:value="formModel.maxTryCount"
              />
            </FormItem>
            <FormItem
              name="priority"
              :label="$t('TaskManagement.DisplayName:Priority')"
              :extra="$t('TaskManagement.Description:Priority')"
            >
              <Select
                class="w-full"
                allow-clear
                v-model:value="formModel.priority"
                :options="jobPriorityOptions"
              />
            </FormItem>
            <FormItem
              name="lockTimeOut"
              :label="$t('TaskManagement.DisplayName:LockTimeOut')"
              :extra="$t('TaskManagement.Description:LockTimeOut')"
            >
              <InputNumber
                class="w-full"
                allow-clear
                v-model:value="formModel.lockTimeOut"
              />
            </FormItem>
            <FormItem
              name="description"
              :label="$t('TaskManagement.DisplayName:Description')"
            >
              <Textarea
                allow-clear
                v-model:value="formModel.description"
                :auto-size="{ minRows: 3 }"
              />
            </FormItem>
          </TabPane>
          <TabPane key="paramters" :tab="$t('TaskManagement.Paramters')">
            <PropertyTable
              :data="formModel.args"
              @change="onEditParam"
              @delete="onDeleteParam"
            />
          </TabPane>
        </Tabs>
      </Form>
    </div>
  </Drawer>
</template>

<style scoped></style>
