// apps/react-admin/src/pages/tasks/job-info-detail-drawer.tsx
import type React from "react";
import { useEffect, useState } from "react";
import { Drawer, Tabs, Descriptions, Tag, Checkbox, List, Button, Popconfirm, Empty, Spin } from "antd";
import { DeleteOutlined, CheckCircleOutlined, CloseCircleOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { getApi } from "@/api/tasks/job-infos";
import { deleteApi as deleteJobLogApi, getPagedListApi as getJobLogsApi } from "@/api/tasks/job-logs";
import type { BackgroundJobInfoDto, BackgroundJobLogDto } from "#/tasks";
import { JobType } from "#/tasks/job-infos";
import { formatToDateTime } from "@/utils/abp";
import PropertyTable from "@/components/abp/properties/property-table";
import { useJobEnumsMap } from "@/hooks/abp/use-Job-enums-map";

interface Props {
	visible: boolean;
	onClose: () => void;
	jobId?: string;
}

const JobInfoDetailDrawer: React.FC<Props> = ({ visible, onClose, jobId }) => {
	const { t: $t } = useTranslation();
	const { jobPriorityColor, jobPriorityMap, jobSourceMap, jobStatusColor, jobStatusMap, jobTypeMap } = useJobEnumsMap();

	const [activeTabKey, setActiveTabKey] = useState("basic");
	const [loading, setLoading] = useState(false);
	const [jobInfo, setJobInfo] = useState<BackgroundJobInfoDto>();
	const [jobLogs, setJobLogs] = useState<BackgroundJobLogDto[]>([]);

	// Pagination State
	const [pagination, setPagination] = useState({
		current: 1,
		pageSize: 10,
		total: 0,
	});

	useEffect(() => {
		if (visible && jobId) {
			setActiveTabKey("basic");
			fetchJobInfo(jobId);
		} else {
			setJobInfo(undefined);
			setJobLogs([]);
		}
	}, [visible, jobId]);

	const fetchJobInfo = async (id: string) => {
		try {
			setLoading(true);
			setJobLogs([]);
			const data = await getApi(id);
			setJobInfo(data);
		} finally {
			setLoading(false);
		}
	};

	const fetchJobLogs = async (page = 1, pageSize = 10) => {
		if (!jobInfo?.id) return;
		try {
			setLoading(true);
			const result = await getJobLogsApi({
				jobId: jobInfo.id,
				maxResultCount: pageSize,
				skipCount: (page - 1) * pageSize,
			});
			setJobLogs(result.items);
			setPagination({
				current: page,
				pageSize: pageSize,
				total: result.totalCount,
			});
		} finally {
			setLoading(false);
		}
	};

	const handleTabChange = (key: string) => {
		setActiveTabKey(key);
		if (key === "logs") {
			fetchJobLogs(1, pagination.pageSize);
		}
	};

	const handleDeleteLog = async (logId: string) => {
		try {
			setLoading(true);
			await deleteJobLogApi(logId);
			toast.success($t("AbpUi.DeletedSuccessfully"));
			fetchJobLogs(pagination.current, pagination.pageSize);
		} finally {
			setLoading(false);
		}
	};

	return (
		<Drawer
			title={$t("TaskManagement.BackgroundJobDetail")}
			open={visible}
			onClose={onClose}
			width="50%"
			destroyOnClose
		>
			<Spin spinning={loading}>
				{jobInfo ? (
					<Tabs activeKey={activeTabKey} onChange={handleTabChange}>
						{/* Basic Info Tab */}
						<Tabs.TabPane key="basic" tab={$t("TaskManagement.BasicInfo")}>
							<Descriptions column={2} bordered size="small" labelStyle={{ minWidth: "120px" }}>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Status")}>
									<Tag color={jobStatusColor[jobInfo.status]}>{jobStatusMap[jobInfo.status]}</Tag>
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Source")}>
									{jobSourceMap[jobInfo.source]}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:IsEnabled")}>
									<Checkbox disabled checked={jobInfo.isEnabled} />
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Priority")}>
									<Tag color={jobPriorityColor[jobInfo.priority]}>{jobPriorityMap[jobInfo.priority]}</Tag>
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Group")}>{jobInfo.group}</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Name")}>{jobInfo.name}</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Description")} span={2}>
									{jobInfo.description}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Type")} span={2}>
									{jobInfo.type}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:CreationTime")}>
									{formatToDateTime(jobInfo.creationTime)}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:LockTimeOut")}>
									{jobInfo.lockTimeOut}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:BeginTime")}>
									{formatToDateTime(jobInfo.beginTime)}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:EndTime")}>
									{jobInfo.endTime ? formatToDateTime(jobInfo.endTime) : ""}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:JobType")}>
									{jobTypeMap[jobInfo.jobType]}
								</Descriptions.Item>
								{jobInfo.jobType === JobType.Period ? (
									<Descriptions.Item label={$t("TaskManagement.DisplayName:Cron")}>{jobInfo.cron}</Descriptions.Item>
								) : (
									<Descriptions.Item label={$t("TaskManagement.DisplayName:Interval")}>
										{jobInfo.interval}
									</Descriptions.Item>
								)}
								<Descriptions.Item label={$t("TaskManagement.DisplayName:LastRunTime")}>
									{jobInfo.lastRunTime ? formatToDateTime(jobInfo.lastRunTime) : ""}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:NextRunTime")}>
									{jobInfo.nextRunTime ? formatToDateTime(jobInfo.nextRunTime) : ""}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:TriggerCount")}>
									{jobInfo.triggerCount}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:MaxCount")}>
									{jobInfo.maxCount}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:TryCount")}>
									{jobInfo.tryCount}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:MaxTryCount")}>
									{jobInfo.maxTryCount}
								</Descriptions.Item>
								<Descriptions.Item label={$t("TaskManagement.DisplayName:Result")} span={2}>
									<pre className="whitespace-pre-wrap break-words">{jobInfo.result}</pre>
								</Descriptions.Item>
							</Descriptions>
						</Tabs.TabPane>

						{/* Parameters Tab */}
						<Tabs.TabPane key="paramters" tab={$t("TaskManagement.Paramters")}>
							<PropertyTable data={jobInfo.args} disabled />
						</Tabs.TabPane>

						{/* Logs Tab */}
						<Tabs.TabPane key="logs" tab={$t("TaskManagement.BackgroundJobLogs")}>
							<List
								itemLayout="vertical"
								size="default"
								bordered
								dataSource={jobLogs}
								pagination={{
									...pagination,
									onChange: (page, pageSize) => fetchJobLogs(page, pageSize),
									showSizeChanger: true,
								}}
								renderItem={(item) => (
									<List.Item
										key={item.id}
										extra={
											<Popconfirm
												title={$t("AbpUi.AreYouSure")}
												description={$t("AbpUi.ItemWillBeDeletedMessage")}
												onConfirm={() => handleDeleteLog(item.id)}
											>
												<Button type="link" danger icon={<DeleteOutlined />} />
											</Popconfirm>
										}
									>
										<List.Item.Meta
											avatar={
												!item.exception ? (
													<CheckCircleOutlined style={{ fontSize: 24, color: "seagreen" }} />
												) : (
													<CloseCircleOutlined style={{ fontSize: 24, color: "orangered" }} />
												)
											}
											title={jobInfo.name}
											description={formatToDateTime(item.runTime)}
										/>
										<pre className="whitespace-pre-wrap break-words">{item.exception ?? item.message}</pre>
									</List.Item>
								)}
							/>
						</Tabs.TabPane>
					</Tabs>
				) : (
					<Empty />
				)}
			</Spin>
		</Drawer>
	);
};

export default JobInfoDetailDrawer;

// apps/vben5/packages/@abp/tasks/src/components/job-infos/JobInfoDetailDrawer.vue
<script setup lang="ts">
import type { BackgroundJobInfoDto, BackgroundJobLogDto } from '../../types';

import { ref } from 'vue';

import { useVbenDrawer } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { PropertyTable } from '@abp/ui';
import {
  Button,
  Checkbox,
  Descriptions,
  DescriptionsItem,
  Empty,
  List,
  ListItem,
  ListItemMeta,
  message,
  Popconfirm,
  TabPane,
  Tabs,
  Tag,
} from 'ant-design-vue';

import { useJobInfosApi } from '../../api/useJobInfosApi';
import { useJobLogsApi } from '../../api/useJobLogsApi';
import { useJobEnumsMap } from '../../hooks/useJobEnumsMap';
import { JobType } from '../../types';

const DeleteOutlined = createIconifyIcon('ant-design:delete-outlined');
const SuccessIcon = createIconifyIcon('grommet-icons:status-good');
const FailedIcon = createIconifyIcon('grommet-icons:status-warning');

const { getApi } = useJobInfosApi();
const { deleteApi: deleteJobLogApi, getPagedListApi: getJobLogsApi } =
  useJobLogsApi();
const {
  jobPriorityColor,
  jobPriorityMap,
  jobSourceMap,
  jobStatusColor,
  jobStatusMap,
  jobTypeMap,
} = useJobEnumsMap();

const activeTabKey = ref('basic');
const jobInfo = ref<BackgroundJobInfoDto>();
const jobLogs = ref<BackgroundJobLogDto[]>([]);
const paginationInfo = ref({
  current: 1,
  pageSize: 10,
  show: true,
  totalCount: 0,
});
const [Drawer, drawerApi] = useVbenDrawer({
  class: 'w-1/2',
  onCancel() {
    drawerApi.close();
  },
  onClosed() {
    activeTabKey.value = 'basic';
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      await onGet();
    }
  },
  showConfirmButton: false,
});

async function onTabChange(activeKey: string) {
  if (activeKey === 'logs') {
    await onGetLogs(1);
  }
}

function onSizeChange() {}

async function onGet() {
  drawerApi.setState({ loading: true });
  try {
    jobLogs.value = [];
    const { id } = drawerApi.getData<BackgroundJobInfoDto>();
    jobInfo.value = await getApi(id);
  } finally {
    drawerApi.setState({ loading: false });
  }
}

async function onGetLogs(page?: number) {
  drawerApi.setState({ loading: true });
  try {
    const pageNumber = page ?? 1;
    paginationInfo.value.current = pageNumber;
    const { id } = drawerApi.getData<BackgroundJobInfoDto>();
    const jobLogResult = await getJobLogsApi({
      jobId: id,
      maxResultCount: paginationInfo.value.pageSize,
      skipCount: (pageNumber - 1) * paginationInfo.value.pageSize,
    });
    jobLogs.value = jobLogResult.items;
    paginationInfo.value.totalCount = jobLogResult.totalCount;
  } finally {
    drawerApi.setState({ loading: false });
  }
}

async function onDeleteLog(jobLog: BackgroundJobLogDto) {
  drawerApi.setState({ loading: true });
  try {
    await deleteJobLogApi(jobLog.id);
    message.success($t('AbpUi.DeletedSuccessfully'));
    await onGetLogs(paginationInfo.value.current);
  } finally {
    drawerApi.setState({ loading: false });
  }
}
</script>

<template>
  <Drawer :title="$t('TaskManagement.BackgroundJobDetail')">
    <Tabs
      v-if="jobInfo"
      v-model:active-key="activeTabKey"
      @change="(key) => onTabChange(key.toString())"
    >
      <TabPane key="basic" :tab="$t('TaskManagement.BasicInfo')">
        <Descriptions
          :colon="false"
          :column="2"
          bordered
          size="small"
          :label-style="{ minWidth: '120px' }"
        >
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:Status')">
            <Tag :color="jobStatusColor[jobInfo.status]">
              {{ jobStatusMap[jobInfo.status] }}
            </Tag>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:Source')">
            <span>{{ jobSourceMap[jobInfo.source] }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:IsEnabled')">
            <Checkbox disabled :checked="jobInfo.isEnabled" />
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:Priority')">
            <Tag :color="jobPriorityColor[jobInfo.priority]">
              {{ jobPriorityMap[jobInfo.priority] }}
            </Tag>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:Group')">
            <span>{{ jobInfo.group }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:Name')">
            <span>{{ jobInfo.name }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:Description')"
            :span="2"
          >
            <span>{{ jobInfo.description }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:Type')"
            :span="2"
          >
            <span>{{ jobInfo.type }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:CreationTime')"
          >
            <span>{{ formatToDateTime(jobInfo.creationTime) }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:LockTimeOut')"
          >
            <span>{{ jobInfo.lockTimeOut }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:BeginTime')">
            <span>{{ formatToDateTime(jobInfo.beginTime) }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:EndTime')">
            <span>{{
              jobInfo.endTime
                ? formatToDateTime(jobInfo.endTime)
                : jobInfo.endTime
            }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:JobType')">
            <span>{{ jobTypeMap[jobInfo.jobType] }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            v-if="jobInfo.jobType === JobType.Period"
            :label="$t('TaskManagement.DisplayName:Cron')"
          >
            <span>{{ jobInfo.cron }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            v-else
            :label="$t('TaskManagement.DisplayName:Interval')"
          >
            <span>{{ jobInfo.interval }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:LastRunTime')"
          >
            <span>{{
              jobInfo.lastRunTime
                ? formatToDateTime(jobInfo.lastRunTime)
                : jobInfo.lastRunTime
            }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:NextRunTime')"
          >
            <span>{{
              jobInfo.nextRunTime
                ? formatToDateTime(jobInfo.nextRunTime)
                : jobInfo.nextRunTime
            }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:TriggerCount')"
          >
            <span>{{ jobInfo.triggerCount }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:MaxCount')">
            <span>{{ jobInfo.maxCount }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:TryCount')">
            <span>{{ jobInfo.tryCount }}</span>
          </DescriptionsItem>
          <DescriptionsItem
            :label="$t('TaskManagement.DisplayName:MaxTryCount')"
          >
            <span>{{ jobInfo.maxTryCount }}</span>
          </DescriptionsItem>
          <DescriptionsItem :label="$t('TaskManagement.DisplayName:Result')">
            <span>{{ jobInfo.result }}</span>
          </DescriptionsItem>
        </Descriptions>
      </TabPane>
      <TabPane key="paramters" :tab="$t('TaskManagement.Paramters')">
        <PropertyTable :data="jobInfo.args" disabled />
      </TabPane>
      <TabPane key="logs" :tab="$t('TaskManagement.BackgroundJobLogs')">
        <List
          item-layout="vertical"
          size="default"
          bordered
          :data-source="jobLogs"
          :pagination="{
            current: paginationInfo.current,
            pageSize: paginationInfo.pageSize,
            total: paginationInfo.totalCount,
            showSizeChanger: paginationInfo.show,
            onChange: onGetLogs,
            onShowSizeChange: onSizeChange,
          }"
        >
          <template #renderItem="{ item }">
            <ListItem :key="item.id">
              <template #extra>
                <Popconfirm
                  placement="topLeft"
                  :title="$t('AbpUi.AreYouSure')"
                  :description="$t('AbpUi.ItemWillBeDeletedMessage')"
                  @confirm="onDeleteLog(item)"
                >
                  <Button block danger type="link">
                    <template #icon>
                      <DeleteOutlined class="inline size-5" />
                    </template>
                  </Button>
                </Popconfirm>
              </template>
              <ListItemMeta :description="item.message">
                <template #avatar>
                  <SuccessIcon
                    v-if="!item.exception"
                    class="size-8"
                    color="seagreen"
                  />
                  <FailedIcon v-else class="size-8" color="orangered" />
                </template>
                <template #title>
                  <span>{{ item.runTime }}</span>
                </template>
              </ListItemMeta>
              {{ item.exception ?? item.message }}
            </ListItem>
          </template>
        </List>
      </TabPane>
    </Tabs>
    <Empty v-else />
  </Drawer>
</template>

<style scoped></style>
