// apps/react-admin/src/pages/tasks/job-info-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Tag, Space, Dropdown, Modal, Checkbox, type FormInstance, Card } from "antd";
import {
	EditOutlined,
	DeleteOutlined,
	PlusOutlined,
	EllipsisOutlined,
	PauseCircleOutlined,
	PlayCircleOutlined,
	ThunderboltOutlined,
	StopOutlined,
} from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import ProTable, { type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useQueryClient } from "@tanstack/react-query";
import { formatToDateTime } from "@/utils/abp";
import {
	bulkDeleteApi,
	bulkStartApi,
	bulkStopApi,
	deleteApi,
	getPagedListApi,
	pauseApi,
	resumeApi,
	startApi,
	stopApi,
	triggerApi,
} from "@/api/tasks/job-infos";
import type { BackgroundJobInfoDto } from "#/tasks/job-infos";
import { JobSource, JobStatus } from "#/tasks/job-infos";
import { BackgroundJobsPermissions } from "@/constants/tasks/permissions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import JobInfoDrawer from "./job-info-drawer";
import JobInfoDetailDrawer from "./job-info-detail-drawer";
import { toast } from "sonner";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";
import { useJobEnumsMap } from "@/hooks/abp/use-Job-enums-map";

const JobInfoTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const formRef = useRef<FormInstance>(); // Ref to control the search form
	const queryClient = useQueryClient();
	const { jobPriorityColor, jobPriorityMap, jobStatusColor, jobStatusMap, jobTypeMap } = useJobEnumsMap();
	const [modal, contextHolder] = Modal.useModal();

	// Drawer States
	const [createDrawerVisible, setCreateDrawerVisible] = useState(false);
	const [detailDrawerVisible, setDetailDrawerVisible] = useState(false);
	const [selectedJobId, setSelectedJobId] = useState<string | undefined>();
	const [selectedKeys, setSelectedKeys] = useState<React.Key[]>([]);

	// Status Logic
	const allowPauseStatus = [JobStatus.Queuing, JobStatus.Running, JobStatus.FailedRetry];
	const allowResumeStatus = [JobStatus.Paused, JobStatus.Stopped];
	const allowTriggerStatus = [JobStatus.Queuing, JobStatus.Running, JobStatus.Completed, JobStatus.FailedRetry];
	const allowStartStatus = [JobStatus.None, JobStatus.Stopped, JobStatus.FailedRetry];
	const allowStopStatus = [JobStatus.Queuing, JobStatus.Running];

	// --- Helper to handle manual filter triggers ---
	const onFilter = (field: string, value: any, shouldSubmit = true) => {
		if (formRef.current) {
			formRef.current.setFieldsValue({
				[field]: value,
			});
			if (shouldSubmit) {
				formRef.current.submit();
			}
		}
	};

	// Actions
	const handleCreate = () => {
		setSelectedJobId(undefined);
		setCreateDrawerVisible(true);
	};

	const handleEdit = (row: BackgroundJobInfoDto) => {
		setSelectedJobId(row.id);
		setCreateDrawerVisible(true);
	};

	const handleShow = (row: BackgroundJobInfoDto) => {
		setSelectedJobId(row.id);
		setDetailDrawerVisible(true);
	};

	const handleStatusChange = (job: BackgroundJobInfoDto, api: (id: string) => Promise<void>, warningMsg: string) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: warningMsg,
			onOk: async () => {
				await api(job.id);
				toast.success($t("AbpUi.SavedSuccessfully"));
				actionRef.current?.reload();
			},
		});
	};

	const handleDelete = (row: BackgroundJobInfoDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: async () => {
				await deleteApi(row.id);
				toast.success($t("AbpUi.DeletedSuccessfully"));
				actionRef.current?.reload();
			},
		});
	};

	const handleBulkAction = (api: (input: { jobIds: string[] }) => Promise<void>, warningMsg: string) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: warningMsg,
			onOk: async () => {
				await api({ jobIds: selectedKeys as string[] });
				toast.success($t("AbpUi.SavedSuccessfully"));
				actionRef.current?.reload();
				setSelectedKeys([]);
			},
		});
	};

	const columns: ProColumns<BackgroundJobInfoDto>[] = [
		{
			title: $t("TaskManagement.DisplayName:Group"),
			dataIndex: "group",
			width: 150,
			sorter: true,
			fixed: "left",
		},
		{
			title: $t("TaskManagement.DisplayName:Name"),
			dataIndex: "name",
			width: 300,
			sorter: true,
			fixed: "left",
			render: (_, row) => (
				<Button type="link" onClick={() => handleShow(row)}>
					{row.name}
				</Button>
			),
		},
		{
			title: $t("TaskManagement.DisplayName:Description"),
			dataIndex: "description",
			width: 350,
			sorter: true,
		},
		{
			title: $t("TaskManagement.DisplayName:CreationTime"),
			dataIndex: "creationTime",
			width: 150,
			sorter: true,
			render: (_, row) => formatToDateTime(row.creationTime),
		},
		{
			title: $t("TaskManagement.DisplayName:Status"),
			dataIndex: "status",
			width: 120,
			sorter: true,
			valueType: "select",
			fieldProps: {
				options: Object.keys(jobStatusMap).map((k) => ({ label: jobStatusMap[Number(k)], value: Number(k) })),
			},
			render: (_, row) => <Tag color={jobStatusColor[row.status]}>{jobStatusMap[row.status]}</Tag>,
		},
		{
			title: $t("TaskManagement.DisplayName:Result"),
			dataIndex: "result",
			width: 200,
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("TaskManagement.DisplayName:LastRunTime"),
			dataIndex: "lastRunTime",
			width: 150,
			valueType: "dateRange",
			sorter: true,
			render: (_, row) => (row.lastRunTime ? formatToDateTime(row.lastRunTime) : ""),
		},
		{
			title: $t("TaskManagement.DisplayName:NextRunTime"),
			dataIndex: "nextRunTime",
			width: 150,
			sorter: true,
			hideInSearch: true,
			render: (_, row) => (row.nextRunTime ? formatToDateTime(row.nextRunTime) : ""),
		},
		{
			title: $t("TaskManagement.DisplayName:JobType"),
			dataIndex: "jobType",
			width: 150,
			sorter: true,
			valueType: "select",
			fieldProps: {
				options: Object.keys(jobTypeMap).map((k) => ({ label: jobTypeMap[Number(k)], value: Number(k) })),
			},
			render: (_, row) => <Tag color="blue">{jobTypeMap[row.jobType]}</Tag>,
		},
		{
			title: $t("TaskManagement.DisplayName:Priority"),
			dataIndex: "priority",
			width: 150,
			sorter: true,
			hideInSearch: true,
			render: (_, row) => <Tag color={jobPriorityColor[row.priority]}>{jobPriorityMap[row.priority]}</Tag>,
		},
		{
			title: $t("TaskManagement.DisplayName:Cron"),
			dataIndex: "cron",
			width: 150,
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("TaskManagement.DisplayName:TriggerCount"),
			dataIndex: "triggerCount",
			width: 100,
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("TaskManagement.DisplayName:TryCount"),
			dataIndex: "tryCount",
			width: 150,
			sorter: true,
			hideInSearch: true,
		},
		{
			// Custom search filters not shown in table
			title: $t("TaskManagement.DisplayName:BeginTime"),
			dataIndex: "time",
			valueType: "dateRange",
			hideInTable: true,
		},
		{
			title: $t("TaskManagement.DisplayName:IsAbandoned"),
			dataIndex: "isAbandoned",
			valueType: "checkbox",
			hideInTable: true,
			renderFormItem: () => (
				<Checkbox onChange={(e) => onFilter("isAbandoned", e.target.checked)}>
					{$t("TaskManagement.DisplayName:IsAbandoned")}
				</Checkbox>
			),
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 220,
			render: (_, row) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(row)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[BackgroundJobsPermissions.Update],
					)}

					{(row.source !== JobSource.System || hasAccessByCodes([BackgroundJobsPermissions.ManageSystemJobs])) &&
						withAccessChecker(
							<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(row)}>
								{$t("AbpUi.Delete")}
							</Button>,
							[BackgroundJobsPermissions.Delete],
						)}

					<Dropdown
						menu={{
							items: [
								allowPauseStatus.includes(row.status) && hasAccessByCodes([BackgroundJobsPermissions.Pause])
									? {
											key: "pause",
											label: $t("TaskManagement.BackgroundJobs:Pause"),
											icon: <PauseCircleOutlined />,
											onClick: () =>
												handleStatusChange(row, pauseApi, $t("TaskManagement.SelectJobWillBePauseMessage")),
										}
									: null,
								allowResumeStatus.includes(row.status) && hasAccessByCodes([BackgroundJobsPermissions.Resume])
									? {
											key: "resume",
											label: $t("TaskManagement.BackgroundJobs:Resume"),
											icon: <PlayCircleOutlined />,
											onClick: () =>
												handleStatusChange(row, resumeApi, $t("TaskManagement.SelectJobWillBeResumeMessage")),
										}
									: null,
								allowTriggerStatus.includes(row.status) && hasAccessByCodes([BackgroundJobsPermissions.Trigger])
									? {
											key: "trigger",
											label: $t("TaskManagement.BackgroundJobs:Trigger"),
											icon: <ThunderboltOutlined />,
											onClick: () =>
												handleStatusChange(row, triggerApi, $t("TaskManagement.SelectJobWillBeTriggerMessage")),
										}
									: null,
								allowStartStatus.includes(row.status) && hasAccessByCodes([BackgroundJobsPermissions.Start])
									? {
											key: "start",
											label: $t("TaskManagement.BackgroundJobs:Start"),
											icon: <PlayCircleOutlined />,
											onClick: () =>
												handleStatusChange(row, startApi, $t("TaskManagement.SelectJobWillBeStartMessage")),
										}
									: null,
								allowStopStatus.includes(row.status) && hasAccessByCodes([BackgroundJobsPermissions.Stop])
									? {
											key: "stop",
											label: $t("TaskManagement.BackgroundJobs:Stop"),
											icon: <StopOutlined />,
											onClick: () => handleStatusChange(row, stopApi, $t("TaskManagement.SelectJobWillBeStopMessage")),
										}
									: null,
							].filter(Boolean) as any,
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<BackgroundJobInfoDto>
					headerTitle={$t("TaskManagement.BackgroundJobs")}
					actionRef={actionRef}
					formRef={formRef}
					rowKey="id"
					columns={columns}
					rowSelection={{
						selectedRowKeys: selectedKeys,
						onChange: (keys) => setSelectedKeys(keys),
					}}
					search={{ labelWidth: "auto", defaultCollapsed: true }}
					scroll={{ x: 2000 }} // Wide table due to many columns
					toolBarRender={() => [
						selectedKeys.length > 0 && hasAccessByCodes([BackgroundJobsPermissions.Start]) && (
							<Button
								key="start"
								ghost
								type="primary"
								icon={<PlayCircleOutlined />}
								onClick={() => handleBulkAction(bulkStartApi, $t("TaskManagement.SelectJobWillBeStartMessage"))}
							>
								{$t("TaskManagement.BackgroundJobs:Start")}
							</Button>
						),
						selectedKeys.length > 0 && hasAccessByCodes([BackgroundJobsPermissions.Stop]) && (
							<Button
								key="stop"
								ghost
								danger
								type="primary"
								icon={<StopOutlined />}
								onClick={() => handleBulkAction(bulkStopApi, $t("TaskManagement.SelectJobWillBeStopMessage"))}
							>
								{$t("TaskManagement.BackgroundJobs:Pause")}
							</Button>
						),
						hasAccessByCodes([BackgroundJobsPermissions.Create]) && (
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("TaskManagement.BackgroundJobs:AddNew")}
							</Button>
						),
						selectedKeys.length > 0 && hasAccessByCodes([BackgroundJobsPermissions.Delete]) && (
							<Button
								key="delete"
								danger
								type="primary"
								icon={<DeleteOutlined />}
								onClick={() =>
									handleBulkAction(bulkDeleteApi, $t("TaskManagement.MultipleSelectJobsWillBeDeletedMessage"))
								}
							>
								{$t("AbpUi.Delete")}
							</Button>
						),
					]}
					request={async (params, sorter) => {
						const { current, pageSize, time, lastRunTime, ...filters } = params;
						const [beginTime, endTime] = time || [];
						const [beginLastRunTime, endLastRunTime] = lastRunTime || [];

						const query = await queryClient.fetchQuery({
							queryKey: ["jobInfos", params, sorter],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									sorting: sorter
										? Object.keys(sorter)
												.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
												.join(", ")
										: undefined,
									beginTime,
									endTime,
									beginLastRunTime,
									endLastRunTime,
									...filters,
								}),
						});
						return {
							data: query.items,
							total: query.totalCount,
							success: true,
						};
					}}
					pagination={{ defaultPageSize: 10, showSizeChanger: true }}
				/>
			</Card>
			<JobInfoDrawer
				visible={createDrawerVisible}
				onClose={() => setCreateDrawerVisible(false)}
				onChange={() => actionRef.current?.reload()}
				jobId={selectedJobId}
			/>

			<JobInfoDetailDrawer
				visible={detailDrawerVisible}
				onClose={() => setDetailDrawerVisible(false)}
				jobId={selectedJobId}
			/>
		</>
	);
};

export default JobInfoTable;

// apps/vben5/packages/@abp/tasks/src/components/job-infos/JobInfoTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { BackgroundJobInfoDto } from '../../types/job-infos';

import { defineAsyncComponent, h, ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import {
  Button,
  Dropdown,
  Menu,
  MenuItem,
  message,
  Modal,
  Tag,
} from 'ant-design-vue';

import { useJobInfosApi } from '../../api/useJobInfosApi';
import { BackgroundJobsPermissions } from '../../constants/permissions';
import { useJobEnumsMap } from '../../hooks/useJobEnumsMap';
import { JobSource, JobStatus, JobType } from '../../types/job-infos';

defineOptions({
  name: 'GdprTable',
});

const PauseIcon = createIconifyIcon('material-symbols:pause-outline');
const ResumeIcon = createIconifyIcon('material-symbols:resume-outline');
const StartIcon = createIconifyIcon('solar:restart-circle-outline');
const StopIcon = createIconifyIcon('solar:stop-circle-outline');
const TriggerIcon = createIconifyIcon('grommet-icons:trigger');

const allowPauseStatus = [
  JobStatus.Queuing,
  JobStatus.Running,
  JobStatus.FailedRetry,
];
const allowResumeStatus = [JobStatus.Paused, JobStatus.Stopped];
const allowTriggerStatus = [
  JobStatus.Queuing,
  JobStatus.Running,
  JobStatus.Completed,
  JobStatus.FailedRetry,
];
const allowStartStatus = [
  JobStatus.None,
  JobStatus.Stopped,
  JobStatus.FailedRetry,
];
const allowStopStatus = [JobStatus.Queuing, JobStatus.Running];

const selectedKeys = ref<string[]>([]);

const { hasAccessByCodes } = useAccess();
const {
  bulkDeleteApi,
  bulkStartApi,
  bulkStopApi,
  cancel,
  deleteApi,
  getPagedListApi,
  pauseApi,
  resumeApi,
  startApi,
  stopApi,
  triggerApi,
} = useJobInfosApi();
const {
  jobPriorityColor,
  jobPriorityMap,
  jobSourceMap,
  jobStatusColor,
  jobStatusMap,
  jobTypeMap,
} = useJobEnumsMap();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: true,
  collapsedRows: 2,
  fieldMappingTime: [
    [
      'time',
      ['beginTime', 'endTime'],
      ['YYYY-MM-DD HH:mm:ss', 'YYYY-MM-DD HH:mm:ss'],
    ],
    [
      'lastRunTime',
      ['beginLastRunTime', 'endLastRunTime'],
      ['YYYY-MM-DD HH:mm:ss', 'YYYY-MM-DD HH:mm:ss'],
    ],
  ],
  schema: [
    {
      component: 'Input',
      fieldName: 'group',
      label: $t('TaskManagement.DisplayName:Group'),
    },
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('TaskManagement.DisplayName:Name'),
    },
    {
      component: 'RangePicker',
      componentProps: {
        showTime: true,
      },
      fieldName: 'lastRunTime',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('TaskManagement.DisplayName:LastRunTime'),
    },
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        options: [
          {
            label: jobStatusMap[JobStatus.None],
            value: JobStatus.None,
          },
          {
            label: jobStatusMap[JobStatus.Running],
            value: JobStatus.Running,
          },
          {
            label: jobStatusMap[JobStatus.Completed],
            value: JobStatus.Completed,
          },
          {
            label: jobStatusMap[JobStatus.FailedRetry],
            value: JobStatus.FailedRetry,
          },
          {
            label: jobStatusMap[JobStatus.Paused],
            value: JobStatus.Paused,
          },
          {
            label: jobStatusMap[JobStatus.Queuing],
            value: JobStatus.Queuing,
          },
          {
            label: jobStatusMap[JobStatus.Stopped],
            value: JobStatus.Stopped,
          },
        ],
      },
      defaultValue: JobStatus.Running,
      fieldName: 'status',
      label: $t('TaskManagement.DisplayName:Status'),
    },
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        options: [
          {
            label: jobSourceMap[JobSource.None],
            value: JobSource.None,
          },
          {
            label: jobSourceMap[JobSource.User],
            value: JobSource.User,
          },
          {
            label: jobSourceMap[JobSource.System],
            value: JobSource.System,
          },
        ],
      },
      defaultValue: JobSource.User,
      fieldName: 'source',
      label: $t('TaskManagement.DisplayName:Source'),
    },
    {
      component: 'RangePicker',
      componentProps: {
        showTime: true,
      },
      fieldName: 'time',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('TaskManagement.DisplayName:BeginTime'),
    },
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        options: [
          {
            label: jobTypeMap[JobType.Once],
            value: JobType.Once,
          },
          {
            label: jobTypeMap[JobType.Period],
            value: JobType.Period,
          },
          {
            label: jobTypeMap[JobType.Persistent],
            value: JobType.Persistent,
          },
        ],
      },
      fieldName: 'jobType',
      label: $t('TaskManagement.DisplayName:JobType'),
    },
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
      },
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
    {
      component: 'Checkbox',
      componentProps: {
        render: () => {
          return h('span', $t('TaskManagement.DisplayName:IsAbandoned'));
        },
      },
      fieldName: 'isAbandoned',
      label: $t('TaskManagement.DisplayName:IsAbandoned'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  submitOnChange: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
  wrapperClass: 'grid-cols-4',
};
const gridOptions: VxeGridProps<BackgroundJobInfoDto> = {
  columns: [
    {
      align: 'center',
      fixed: 'left',
      type: 'checkbox',
    },
    {
      align: 'left',
      field: 'group',
      fixed: 'left',
      sortable: true,
      title: $t('TaskManagement.DisplayName:Group'),
      width: 150,
    },
    {
      align: 'left',
      field: 'name',
      fixed: 'left',
      slots: { default: 'name' },
      sortable: true,
      title: $t('TaskManagement.DisplayName:Name'),
      width: 300,
    },
    {
      align: 'left',
      field: 'description',
      sortable: true,
      title: $t('TaskManagement.DisplayName:Description'),
      width: 350,
    },
    {
      align: 'left',
      field: 'creationTime',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      sortable: true,
      title: $t('TaskManagement.DisplayName:CreationTime'),
      width: 150,
    },
    {
      align: 'left',
      field: 'status',
      slots: { default: 'status' },
      sortable: true,
      title: $t('TaskManagement.DisplayName:Status'),
      width: 100,
    },
    {
      align: 'left',
      field: 'result',
      sortable: true,
      title: $t('TaskManagement.DisplayName:Result'),
      width: 200,
    },
    {
      align: 'left',
      field: 'lastRunTime',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      sortable: true,
      title: $t('TaskManagement.DisplayName:LastRunTime'),
      width: 150,
    },
    {
      align: 'left',
      field: 'nextRunTime',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      sortable: true,
      title: $t('TaskManagement.DisplayName:NextRunTime'),
      width: 150,
    },
    {
      align: 'left',
      field: 'jobType',
      slots: { default: 'type' },
      sortable: true,
      title: $t('TaskManagement.DisplayName:JobType'),
      width: 150,
    },
    {
      align: 'left',
      field: 'priority',
      slots: { default: 'priority' },
      sortable: true,
      title: $t('TaskManagement.DisplayName:Priority'),
      width: 150,
    },
    {
      align: 'left',
      field: 'cron',
      sortable: true,
      title: $t('TaskManagement.DisplayName:Cron'),
      width: 150,
    },
    {
      align: 'left',
      field: 'triggerCount',
      sortable: true,
      title: $t('TaskManagement.DisplayName:TriggerCount'),
      width: 100,
    },
    {
      align: 'left',
      field: 'tryCount',
      sortable: true,
      title: $t('TaskManagement.DisplayName:TryCount'),
      width: 150,
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        return await getPagedListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    refresh: {
      code: 'query',
    },
  },
};
const gridEvents: VxeGridListeners<BackgroundJobInfoDto> = {
  checkboxAll: (params) => {
    selectedKeys.value = params.records.map((x) => x.id);
  },
  checkboxChange: (params) => {
    selectedKeys.value = params.records.map((x) => x.id);
  },
  sortChange: () => {
    gridApi.query();
  },
};
const [JobInfoDrawer, jobDrawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(() => import('./JobInfoDrawer.vue')),
});
const [JobInfoDetailDrawer, jobDetailDrawerApi] = useVbenDrawer({
  connectedComponent: defineAsyncComponent(
    () => import('./JobInfoDetailDrawer.vue'),
  ),
});
const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

function onShow(row: BackgroundJobInfoDto) {
  jobDetailDrawerApi.setData(row);
  jobDetailDrawerApi.open();
}

function onCreate() {
  jobDrawerApi.setData({});
  jobDrawerApi.open();
}

function onEdit(row: BackgroundJobInfoDto) {
  jobDrawerApi.setData(row);
  jobDrawerApi.open();
}

function onDelete(row: BackgroundJobInfoDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessage'),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      gridApi.setLoading(true);
      try {
        await deleteApi(row.id);
        message.success($t('AbpUi.DeletedSuccessfully'));
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onBulkDelete() {
  Modal.confirm({
    centered: true,
    content: $t('TaskManagement.MultipleSelectJobsWillBeDeletedMessage'),
    async onOk() {
      gridApi.setLoading(true);
      try {
        await bulkDeleteApi({
          jobIds: selectedKeys.value,
        });
        message.success($t('AbpUi.SavedSuccessfully'));
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onBulkStop() {
  Modal.confirm({
    centered: true,
    content: $t('TaskManagement.SelectJobWillBeStopMessage'),
    async onOk() {
      gridApi.setLoading(true);
      try {
        await bulkStopApi({
          jobIds: selectedKeys.value,
        });
        message.success($t('AbpUi.SavedSuccessfully'));
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onBulkStart() {
  Modal.confirm({
    centered: true,
    content: $t('TaskManagement.SelectJobWillBeStartMessage'),
    async onOk() {
      gridApi.setLoading(true);
      try {
        await bulkStartApi({
          jobIds: selectedKeys.value,
        });
        message.success($t('AbpUi.SavedSuccessfully'));
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onMenuClick(row: BackgroundJobInfoDto, info: MenuInfo) {
  switch (info.key) {
    case 'pause': {
      onJobStatusChange(
        row,
        pauseApi,
        $t('TaskManagement.SelectJobWillBePauseMessage'),
      );
      break;
    }
    case 'resume': {
      onJobStatusChange(
        row,
        resumeApi,
        $t('TaskManagement.SelectJobWillBeResumeMessage'),
      );
      break;
    }
    case 'start': {
      onJobStatusChange(
        row,
        startApi,
        $t('TaskManagement.SelectJobWillBeStartMessage'),
      );
      break;
    }
    case 'stop': {
      onJobStatusChange(
        row,
        stopApi,
        $t('TaskManagement.SelectJobWillBeStopMessage'),
      );
      break;
    }
    case 'trigger': {
      onJobStatusChange(
        row,
        triggerApi,
        $t('TaskManagement.SelectJobWillBeTriggerMessage'),
      );
      break;
    }
  }
}

function onJobStatusChange(
  job: BackgroundJobInfoDto,
  api: (jobId: string) => Promise<void>,
  warningMsg: string,
) {
  Modal.confirm({
    centered: true,
    content: warningMsg,
    async onOk() {
      gridApi.setLoading(true);
      try {
        await api(job.id);
        message.success($t('AbpUi.SavedSuccessfully'));
        await gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
</script>

<template>
  <Grid :table-title="$t('TaskManagement.BackgroundJobs')">
    <template #toolbar-tools>
      <div class="flex flex-row gap-4">
        <Button
          v-if="selectedKeys.length > 0"
          :icon="h(StartIcon)"
          ghost
          type="primary"
          v-access:code="[BackgroundJobsPermissions.Start]"
          @click="onBulkStart"
        >
          {{ $t('TaskManagement.BackgroundJobs:Start') }}
        </Button>
        <Button
          v-if="selectedKeys.length > 0"
          :icon="h(StopIcon)"
          danger
          ghost
          type="primary"
          v-access:code="[BackgroundJobsPermissions.Stop]"
          @click="onBulkStop"
        >
          {{ $t('TaskManagement.BackgroundJobs:Pause') }}
        </Button>
        <Button
          :icon="h(PlusOutlined)"
          type="primary"
          v-access:code="[BackgroundJobsPermissions.Create]"
          @click="onCreate"
        >
          {{ $t('TaskManagement.BackgroundJobs:AddNew') }}
        </Button>
        <Button
          v-if="selectedKeys.length > 0"
          :icon="h(DeleteOutlined)"
          danger
          type="primary"
          v-access:code="[BackgroundJobsPermissions.Delete]"
          @click="onBulkDelete"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
    <template #name="{ row }">
      <Button type="link" @click="onShow(row)">{{ row.name }}</Button>
    </template>
    <template #status="{ row }">
      <Tag :color="jobStatusColor[row.status]">
        {{ jobStatusMap[row.status] }}
      </Tag>
    </template>
    <template #type="{ row }">
      <Tag color="blue">
        {{ jobTypeMap[row.jobType] }}
      </Tag>
    </template>
    <template #priority="{ row }">
      <Tag :color="jobPriorityColor[row.priority]">
        {{ jobPriorityMap[row.priority] }}
      </Tag>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          v-if="hasAccessByCodes([BackgroundJobsPermissions.Update])"
          :icon="h(EditOutlined)"
          block
          type="link"
          @click="onEdit(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          v-if="
            hasAccessByCodes([BackgroundJobsPermissions.Delete]) &&
            (row.source !== JobSource.System ||
              hasAccessByCodes([BackgroundJobsPermissions.ManageSystemJobs]))
          "
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="
                  allowPauseStatus.includes(row.status) &&
                  hasAccessByCodes([BackgroundJobsPermissions.Pause])
                "
                key="pause"
                :icon="h(PauseIcon)"
              >
                {{ $t('TaskManagement.BackgroundJobs:Pause') }}
              </MenuItem>
              <MenuItem
                v-if="
                  allowResumeStatus.includes(row.status) &&
                  hasAccessByCodes([BackgroundJobsPermissions.Resume])
                "
                key="resume"
                :icon="h(ResumeIcon)"
              >
                {{ $t('TaskManagement.BackgroundJobs:Resume') }}
              </MenuItem>
              <MenuItem
                v-if="
                  allowTriggerStatus.includes(row.status) &&
                  hasAccessByCodes([BackgroundJobsPermissions.Trigger])
                "
                key="trigger"
                :icon="h(TriggerIcon)"
              >
                {{ $t('TaskManagement.BackgroundJobs:Trigger') }}
              </MenuItem>
              <MenuItem
                v-if="
                  allowStartStatus.includes(row.status) &&
                  hasAccessByCodes([BackgroundJobsPermissions.Start])
                "
                key="start"
                :icon="h(StartIcon)"
              >
                {{ $t('TaskManagement.BackgroundJobs:Start') }}
              </MenuItem>
              <MenuItem
                v-if="
                  allowStopStatus.includes(row.status) &&
                  hasAccessByCodes([BackgroundJobsPermissions.Stop])
                "
                key="stop"
                :icon="h(StopIcon)"
              >
                {{ $t('TaskManagement.BackgroundJobs:Stop') }}
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <JobInfoDrawer />
  <JobInfoDetailDrawer />
</template>

<style lang="scss" scoped></style>
