// apps/react-admin/src/pages/oss/containers/container-table.tsx
import { useRef, useState } from "react";
import { Button, Modal, Space } from "antd";
import { DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useQueryClient, useMutation } from "@tanstack/react-query";
import { formatToDateTime } from "@/utils/abp";
import { deleteApi, getListApi } from "@/api/oss/containes";
import type { OssContainerDto } from "#/oss/containes";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";
import ContainerModal from "./container-modal";
import Card from "@/components/card";

const ContainerTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();

	const [createModalVisible, setCreateModalVisible] = useState(false);

	const { mutateAsync: deleteContainer } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["oss-containers"], exact: false });
		},
	});

	const handleCreate = () => {
		setCreateModalVisible(true);
	};

	const handleDelete = (row: OssContainerDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: async () => {
				await deleteContainer(row.name);
			},
		});
	};

	const columns: ProColumns<OssContainerDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpOssManagement.DisplayName:Name"),
			dataIndex: "name",
			sorter: true,
			minWidth: 150,
			hideInSearch: true,
		},
		{
			title: $t("AbpOssManagement.DisplayName:CreationDate"),
			dataIndex: "creationDate",
			sorter: true,
			minWidth: 150,
			hideInSearch: true,
			render: (_, row) => formatToDateTime(row.creationDate),
		},
		{
			title: $t("AbpOssManagement.DisplayName:LastModifiedDate"),
			dataIndex: "lastModifiedDate",
			sorter: true,
			minWidth: 150,
			hideInSearch: true,
			render: (_, row) => formatToDateTime(row.lastModifiedDate),
		},
		{
			title: $t("AbpOssManagement.DisplayName:Size"),
			dataIndex: "size",
			sorter: true,
			minWidth: 100,
			hideInSearch: true,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 150,
			render: (_, record) => (
				<Space>
					<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
						{$t("AbpUi.Delete")}
					</Button>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<OssContainerDto>
					headerTitle={$t("AbpOssManagement.Containers")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={{
						labelWidth: "auto",
					}}
					toolBarRender={() => [
						<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
							{$t("AbpOssManagement.Containers:Create")}
						</Button>,
					]}
					request={async (params, sorter) => {
						const { current, pageSize, filter } = params;
						const sorting =
							sorter && Object.keys(sorter).length > 0
								? Object.keys(sorter)
										.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
										.join(", ")
								: undefined;
						// that just how this api is.
						const query = await queryClient.fetchQuery({
							queryKey: ["oss-containers", params, sorter],
							queryFn: () =>
								getListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									sorting: sorting,
									prefix: filter, //?
								}),
						});

						return {
							data: query.containers,
							total: query.maxKeys,
							success: true,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<ContainerModal
				visible={createModalVisible}
				onClose={() => setCreateModalVisible(false)}
				onChange={() => queryClient.invalidateQueries({ queryKey: ["oss-containers"], exact: false })}
			/>
		</>
	);
};

export default ContainerTable;

// apps/vben5/packages/@abp/oss/src/components/containers/ContainerTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { OssContainerDto } from '../../types/containes';

import { defineAsyncComponent, h, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useContainesApi } from '../../api/useContainesApi';

defineOptions({
  name: 'ContainerTable',
});

const { cancel, deleteApi, getListApi } = useContainesApi();

const selectedKeys = ref<string[]>([]);

const formOptions: VbenFormProps = {
  collapsed: true,
  collapsedRows: 2,
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  schema: [
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
      },
      fieldName: 'filter',
      formItemClass: 'col-span-3 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<OssContainerDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'creationDate',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      minWidth: 120,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:CreationDate'),
    },
    {
      align: 'left',
      field: 'lastModifiedDate',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      minWidth: 120,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:LastModifiedDate'),
    },
    {
      align: 'left',
      field: 'size',
      minWidth: 150,
      sortable: true,
      title: $t('AbpOssManagement.DisplayName:Size'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 150,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        const res = await getListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
        return {
          totalCount: res.maxKeys,
          items: res.containers,
        };
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<OssContainerDto> = {
  checkboxAll: (params) => {
    selectedKeys.value = params.records.map((record) => record.name);
  },
  checkboxChange: (params) => {
    selectedKeys.value = params.records.map((record) => record.name);
  },
  sortChange: () => {
    gridApi.query();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [ContainerModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./ContainerModal.vue'),
  ),
});

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onDelete(row: OssContainerDto) {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name]),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      await gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
</script>

<template>
  <Grid :table-title="$t('AbpOssManagement.Containers')">
    <template #toolbar-tools>
      <Button :icon="h(PlusOutlined)" type="primary" @click="onCreate">
        {{ $t('AbpOssManagement.Containers:Create') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(DeleteOutlined)"
          danger
          block
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
      </div>
    </template>
  </Grid>
  <ContainerModal @change="() => gridApi.query()" />
</template>

<style lang="scss" scoped></style>
