// apps/vben5/packages/@abp/identity/src/components/claims/ClaimTable.vue
<script setup lang="ts">
import type { VxeGridProps } from '@abp/ui';

import type { IdentityClaimDto } from '../../types/claims';
import type { ClaimModalEvents, ClaimModalProps } from './types';

import { defineAsyncComponent, h } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useVbenVxeGrid } from '@abp/ui';
import { DeleteOutlined, EditOutlined } from '@ant-design/icons-vue';
import { Button, message, Popconfirm } from 'ant-design-vue';

defineOptions({
  name: 'ClaimTable',
});

const {
  createApi,
  createPolicy,
  deleteApi,
  deletePolicy,
  getApi,
  updateApi,
  updatePolicy,
} = defineProps<ClaimModalProps>();
const emits = defineEmits<ClaimModalEvents>();

const ClaimModal = defineAsyncComponent(() => import('./ClaimModal.vue'));

const gridOptions: VxeGridProps<IdentityClaimDto> = {
  columns: [
    {
      field: 'claimType',
      minWidth: 120,
      title: $t('AbpIdentity.DisplayName:ClaimType'),
    },
    {
      field: 'claimValue',
      title: $t('AbpIdentity.DisplayName:ClaimValue'),
      width: 'auto',
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 180,
    },
  ],
  exportConfig: {},
  keepSource: true,
  pagerConfig: {
    enabled: false,
  },
  proxyConfig: {
    ajax: {
      query: async () => {
        return await getApi();
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};
const [Grid, { query }] = useVbenVxeGrid({
  gridOptions,
});

const [ClaimEditModal, editModalApi] = useVbenModal({
  connectedComponent: ClaimModal,
});
function onCreate() {
  editModalApi.setData({});
  editModalApi.open();
}

async function onDelete(row: IdentityClaimDto) {
  await deleteApi({
    claimType: row.claimType,
    claimValue: row.claimValue,
  });
  message.success($t('AbpUi.DeletedSuccessfully'));
  query();
  emits('onDelete');
}

function onUpdate(row: IdentityClaimDto) {
  editModalApi.setData(row);
  editModalApi.open();
}
</script>

<template>
  <div>
    <Grid>
      <template #toolbar-tools>
        <Button type="primary" v-access:code="[createPolicy]" @click="onCreate">
          {{ $t('AbpIdentity.AddClaim') }}
        </Button>
      </template>
      <template #action="{ row }">
        <div class="flex flex-row">
          <div class="basis-1/2">
            <Button
              :icon="h(EditOutlined)"
              block
              type="link"
              v-access:code="[updatePolicy]"
              @click="onUpdate(row)"
            >
              {{ $t('AbpUi.Edit') }}
            </Button>
          </div>
          <div class="basis-1/2">
            <Popconfirm
              :title="$t('AbpIdentity.WillDeleteClaim', [row.claimType])"
              @confirm="onDelete(row)"
            >
              <Button
                :icon="h(DeleteOutlined)"
                block
                danger
                type="link"
                v-access:code="[deletePolicy]"
              >
                {{ $t('AbpUi.Delete') }}
              </Button>
            </Popconfirm>
          </div>
        </div>
      </template>
    </Grid>
    <ClaimEditModal
      :create-api="createApi"
      :create-policy="createPolicy"
      :delete-api="deleteApi"
      :delete-policy="deletePolicy"
      :update-api="updateApi"
      :update-policy="updatePolicy"
      @change="() => query()"
    />
  </div>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/claims/claim-table.tsx
import type React from "react";
import { useState, useRef } from "react";
import { Button, Popconfirm, Space } from "antd";
import { EditOutlined, DeleteOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import type { IdentityClaimDto } from "#/management/identity/claims";
import type { ClaimModalProps } from "./types";
import { toast } from "sonner";
import { withAccessChecker } from "@/utils/abp/access-checker";
import ClaimModal from "./claim-modal";

const ClaimTable: React.FC<ClaimModalProps> = ({
	createApi,
	createPolicy,
	deleteApi,
	deletePolicy,
	getApi,
	updateApi,
	updatePolicy,
	queryKey,
}) => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedClaim, setSelectedClaim] = useState<IdentityClaimDto | null>(null);

	const { data: claimsData } = useQuery({
		queryKey: queryKey,
		queryFn: getApi,
	});

	const { mutateAsync: deleteClaim } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: queryKey });
		},
	});

	const openModal = (claim?: IdentityClaimDto) => {
		setSelectedClaim(claim || null);
		setModalVisible(true);
	};

	const closeModal = () => {
		setModalVisible(false);
		setSelectedClaim(null);
	};

	const handleDelete = async (row: IdentityClaimDto) => {
		await deleteClaim({
			claimType: row.claimType,
			claimValue: row.claimValue,
		});
	};

	const columns: ProColumns<IdentityClaimDto>[] = [
		{
			title: $t("AbpIdentity.DisplayName:ClaimType"),
			dataIndex: "claimType",
			width: 120,
		},
		{
			title: $t("AbpIdentity.DisplayName:ClaimValue"),
			dataIndex: "claimValue",
			width: "auto",
		},
		{
			title: $t("AbpUi.Actions"),
			dataIndex: "action",
			fixed: "right",
			width: 180,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => openModal(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[updatePolicy],
					)}
					{withAccessChecker(
						<Popconfirm
							title={$t("AbpIdentity.WillDeleteClaim", { 0: record.claimType })}
							onConfirm={() => handleDelete(record)}
						>
							<Button type="link" danger icon={<DeleteOutlined />}>
								{$t("AbpUi.Delete")}
							</Button>
						</Popconfirm>,
						[deletePolicy],
					)}
				</Space>
			),
		},
	];

	return (
		<div>
			<ProTable<IdentityClaimDto>
				actionRef={actionRef}
				columns={columns}
				rowKey="id"
				search={false}
				dataSource={claimsData?.items}
				pagination={false}
				toolBarRender={() => [
					withAccessChecker(
						<Button type="primary" onClick={() => openModal()}>
							{$t("AbpIdentity.AddClaim")}
						</Button>,
						[createPolicy],
					),
				]}
			/>
			<ClaimModal
				visible={modalVisible}
				claim={selectedClaim || undefined}
				onClose={closeModal}
				onChange={() => {
					queryClient.invalidateQueries({ queryKey: queryKey });
					closeModal();
				}}
				createApi={createApi}
				updateApi={updateApi}
			/>
		</div>
	);
};

export default ClaimTable;
