// apps/vben5/packages/@abp/webhooks/src/components/definitions/groups/WebhookGroupDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { WebhookGroupDefinitionDto } from '../../../types/groups';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { useLocalization, useLocalizationSerializer } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useWebhookGroupDefinitionsApi } from '../../../api/useWebhookGroupDefinitionsApi';
import { GroupDefinitionsPermissions } from '../../../constants/permissions';

defineOptions({
  name: 'WebhookGroupDefinitionTable',
});

const MenuItem = Menu.Item;

const WebhookIcon = createIconifyIcon('material-symbols:webhook');

const permissionGroups = ref<WebhookGroupDefinitionDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const { Lr } = useLocalization();
const { deserialize } = useLocalizationSerializer();
const { deleteApi, getListApi } = useWebhookGroupDefinitionsApi();

const formOptions: VbenFormProps = {
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  showCollapseButton: true,
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<WebhookGroupDefinitionDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('WebhooksManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('WebhooksManagement.DisplayName:DisplayName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<WebhookGroupDefinitionDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [WebhookGroupDefinitionModal, groupModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./WebhookGroupDefinitionModal.vue'),
  ),
});
const [WebhookDefinitionModal, defineModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('../webhooks/WebhookDefinitionModal.vue'),
  ),
});

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input);
    pageState.total = items.length;
    permissionGroups.value = items.map((item) => {
      const localizableString = deserialize(item.displayName);
      return {
        ...item,
        displayName: Lr(localizableString.resourceName, localizableString.name),
      };
    });
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = permissionGroups.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  groupModalApi.setData({});
  groupModalApi.open();
}

function onUpdate(row: WebhookGroupDefinitionDto) {
  groupModalApi.setData(row);
  groupModalApi.open();
}

function onMenuClick(row: WebhookGroupDefinitionDto, info: MenuInfo) {
  switch (info.key) {
    case 'webhooks': {
      defineModalApi.setData({
        groupName: row.name,
      });
      defineModalApi.open();
      break;
    }
  }
}

function onDelete(row: WebhookGroupDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('WebhooksManagement.GroupDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[GroupDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('WebhooksManagement.GroupDefinitions:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <div :class="`${row.isStatic ? 'w-full' : 'basis-1/3'}`">
          <Button
            :icon="h(EditOutlined)"
            block
            type="link"
            v-access:code="[GroupDefinitionsPermissions.Update]"
            @click="onUpdate(row)"
          >
            {{ $t('AbpUi.Edit') }}
          </Button>
        </div>
        <template v-if="!row.isStatic">
          <div class="basis-1/3">
            <Button
              :icon="h(DeleteOutlined)"
              block
              danger
              type="link"
              v-access:code="[GroupDefinitionsPermissions.Delete]"
              @click="onDelete(row)"
            >
              {{ $t('AbpUi.Delete') }}
            </Button>
          </div>
          <div class="basis-1/3">
            <Dropdown>
              <template #overlay>
                <Menu @click="(info) => onMenuClick(row, info)">
                  <MenuItem key="webhooks" :icon="h(WebhookIcon)">
                    {{ $t('WebhooksManagement.Webhooks:AddNew') }}
                  </MenuItem>
                </Menu>
              </template>
              <Button :icon="h(EllipsisOutlined)" type="link" />
            </Dropdown>
          </div>
        </template>
      </div>
    </template>
  </Grid>
  <WebhookGroupDefinitionModal @change="() => onGet()" />
  <WebhookDefinitionModal />
</template>

<style scoped></style>

// apps/react-admin/src/pages/webhooks/definitions/groups/webhook-group-definition-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, EllipsisOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getListApi } from "@/api/webhooks/webhook-group-definitions";
import type { WebhookGroupDefinitionDto } from "#/webhooks/groups";
import { GroupDefinitionsPermissions } from "@/constants/webhooks/permissions"; // Adjust path as needed
import { withAccessChecker } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { useLocalizer } from "@/hooks/abp/use-localization";
import { Iconify } from "@/components/icon";

import WebhookGroupDefinitionModal from "./webhook-group-definition-modal";
import WebhookDefinitionModal from "../webhooks/webhook-definition-modal";

const WebhookGroupDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const { deserialize } = localizationSerializer();
	const { Lr } = useLocalizer();
	const [modal, contextHolder] = Modal.useModal();

	// Modal States
	const [groupModalVisible, setGroupModalVisible] = useState(false);
	const [webhookModalVisible, setWebhookModalVisible] = useState(false);
	const [selectedGroupName, setSelectedGroupName] = useState<string | undefined>();

	const { mutateAsync: deleteGroup } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["webhookGroups"] });
			actionRef.current?.reload();
		},
	});

	const handleCreate = () => {
		setSelectedGroupName(undefined);
		setGroupModalVisible(true);
	};

	const handleUpdate = (row: WebhookGroupDefinitionDto) => {
		setSelectedGroupName(row.name);
		setGroupModalVisible(true);
	};

	const handleDelete = (row: WebhookGroupDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: () => deleteGroup(row.name),
		});
	};

	const handleMenuClick = (key: string, row: WebhookGroupDefinitionDto) => {
		if (key === "webhooks") {
			setSelectedGroupName(row.name);
			setWebhookModalVisible(true);
		}
	};

	const columns: ProColumns<WebhookGroupDefinitionDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("WebhooksManagement.DisplayName:Name"),
			dataIndex: "name",
			width: "auto",
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("WebhooksManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: "auto",
			sorter: true,
			hideInSearch: true,
			render: (_, record) => {
				const localizableString = deserialize(record.displayName);
				return Lr(localizableString.resourceName, localizableString.name);
			},
		},
		{
			title: $t("AbpUi.Actions"),
			width: 220,
			fixed: "right",
			hideInSearch: true,
			render: (_, record) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[GroupDefinitionsPermissions.Update],
					)}

					{!record.isStatic &&
						withAccessChecker(
							<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
								{$t("AbpUi.Delete")}
							</Button>,
							[GroupDefinitionsPermissions.Delete],
						)}

					<Dropdown
						menu={{
							items: [
								{
									key: "webhooks",
									label: $t("WebhooksManagement.Webhooks:AddNew"),
									icon: <Iconify icon="material-symbols:webhook" />,
								},
							],
							onClick: ({ key }) => handleMenuClick(key, record),
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<WebhookGroupDefinitionDto>
					headerTitle={$t("WebhooksManagement.GroupDefinitions")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={{
						labelWidth: "auto",
					}}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("WebhooksManagement.GroupDefinitions:AddNew")}
							</Button>,
							[GroupDefinitionsPermissions.Create],
						),
					]}
					request={async (params) => {
						const { current, pageSize, ...filters } = params;

						const { items } = await getListApi({
							filter: filters.filter,
						});

						return {
							data: items,
							total: items.length,
							success: true,
						};
					}}
					pagination={{
						defaultPageSize: 10,
						showSizeChanger: true,
					}}
				/>
			</Card>
			<WebhookGroupDefinitionModal
				visible={groupModalVisible}
				groupName={selectedGroupName}
				onClose={() => setGroupModalVisible(false)}
				onChange={() => {
					actionRef.current?.reload();
					queryClient.invalidateQueries({ queryKey: ["webhookGroups"] });
				}}
			/>

			<WebhookDefinitionModal
				visible={webhookModalVisible}
				groupName={selectedGroupName}
				onClose={() => setWebhookModalVisible(false)}
				onChange={() => {
					// actionRef.current?.reload();
				}}
			/>
		</>
	);
};

export default WebhookGroupDefinitionTable;
