// apps/react-admin/src/pages/management/localization/texts/localization-text-table.tsx
import { useRef, useState, useEffect } from "react";
import { Button, Card, Space, type FormInstance } from "antd";
import { EditOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import ProTable, { type ProColumns, type ActionType } from "@ant-design/pro-table";
import { getListApi } from "@/api/management/localization/texts";
import { getListApi as getLanguagesApi } from "@/api/management/localization/languages";
import { getListApi as getResourcesApi } from "@/api/management/localization/resources";
import type { TextDifferenceDto, TextDto } from "#/management/localization/texts";
import type { LanguageDto } from "#/management/localization/languages";
import type { ResourceDto } from "#/management/localization/resources";
import LocalizationTextModal from "./localization-text-modal";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { TextsPermissions } from "@/constants/management/localization/permissions";
import useAbpStore from "@/store/abpCoreStore";
import orderBy from "lodash.orderby";
import { useSetLocale } from "@/store/localeI18nStore";
import { getStringItem } from "@/utils/storage";
import { LocalEnum, StorageEnum } from "#/enum";

const LocalizationTextTable: React.FC = () => {
	const { t: $t, i18n } = useTranslation();
	const setLocale = useSetLocale();
	const currentLng = getStringItem(StorageEnum.I18N) || LocalEnum.en_US;

	const actionRef = useRef<ActionType>();
	// 2. Fix the type here: Change <Performance> to <ProFormInstance>
	const formRef = useRef<FormInstance>();

	// Modal State
	const [modalVisible, setModalVisible] = useState(false);
	const [currentRow, setCurrentRow] = useState<TextDifferenceDto | undefined>();

	// Filters Data
	const [languages, setLanguages] = useState<LanguageDto[]>([]);
	const [resources, setResources] = useState<ResourceDto[]>([]);

	const application = useAbpStore((state) => state.application);

	useEffect(() => {
		const initData = async () => {
			const [langRes, resRes] = await Promise.all([getLanguagesApi(), getResourcesApi()]);
			setLanguages(langRes.items);
			setResources(resRes.items);
		};
		initData();
	}, []);

	const handleOpenCreate = () => {
		setCurrentRow(undefined);
		setModalVisible(true);
	};

	const handleOpenEdit = (row: TextDifferenceDto) => {
		setCurrentRow(row);
		setModalVisible(true);
	};

	const handleDataChange = async (data: TextDto) => {
		actionRef.current?.reload();

		// If the modified text belongs to the current app culture, refresh the app configuration
		const currentAppCulture = application?.localization.currentCulture.cultureName;
		if (data.cultureName === currentAppCulture) {
			try {
				await setLocale(currentLng as LocalEnum, i18n);
			} catch (error) {
				console.error("Failed to refresh localization cache", error);
			}
		}
	};

	const columns: ProColumns<TextDifferenceDto>[] = [
		{
			title: $t("AbpLocalization.DisplayName:CultureName"),
			dataIndex: "cultureName",
			valueType: "select",
			fieldProps: {
				options: languages,
				fieldNames: { label: "displayName", value: "cultureName" },
				showSearch: true,
				optionFilterProp: "displayName",
			},
			hideInTable: true,
			initialValue: application?.localization.currentCulture.cultureName,
			formItemProps: {
				rules: [{ required: true }],
			},
		},
		{
			title: $t("AbpLocalization.DisplayName:TargetCultureName"),
			dataIndex: "targetCultureName",
			valueType: "select",
			fieldProps: {
				options: languages,
				fieldNames: { label: "displayName", value: "cultureName" },
				showSearch: true,
				optionFilterProp: "displayName",
			},
			hideInTable: true,
			initialValue: application?.localization.currentCulture.cultureName,
			formItemProps: {
				rules: [{ required: true }],
			},
		},
		{
			title: $t("AbpLocalization.DisplayName:ResourceName"),
			dataIndex: "resourceName",
			valueType: "select",
			fieldProps: {
				options: resources,
				fieldNames: { label: "displayName", value: "name" },
				showSearch: true,
				optionFilterProp: "displayName",
			},
			width: 150,
			sorter: true,
		},
		{
			title: $t("AbpLocalization.DisplayName:TargetValue"),
			dataIndex: "onlyNull",
			valueType: "select",
			hideInTable: true,
			fieldProps: {
				options: [
					{ label: $t("AbpLocalization.DisplayName:Any"), value: "false" },
					{ label: $t("AbpLocalization.DisplayName:OnlyNull"), value: "true" },
				],
			},
			initialValue: "false",
		},
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpLocalization.DisplayName:Key"),
			dataIndex: "key",
			width: 200,
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("AbpLocalization.DisplayName:Value"),
			dataIndex: "value",
			width: 300,
			sorter: true,
			hideInSearch: true,
			render: (dom) => <div className="break-all whitespace-pre-wrap">{dom}</div>,
		},
		{
			title: $t("AbpLocalization.DisplayName:TargetValue"),
			dataIndex: "targetValue",
			width: 300,
			sorter: true,
			hideInSearch: true,
			render: (dom) => <div className="break-all whitespace-pre-wrap">{dom}</div>,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 100,
			render: (_, record) => (
				<Space>
					{hasAccessByCodes([TextsPermissions.Update]) && (
						<Button type="link" icon={<EditOutlined />} onClick={() => handleOpenEdit(record)}>
							{$t("AbpUi.Edit")}
						</Button>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			<Space direction="vertical" size="large" className="w-full">
				<Card>
					<ProTable<TextDifferenceDto>
						headerTitle={$t("AbpLocalization.Texts")}
						actionRef={actionRef}
						formRef={formRef}
						rowKey={(record) => record.resourceName + record.key}
						columns={columns}
						search={{
							labelWidth: "auto",
							defaultCollapsed: false,
						}}
						toolBarRender={() => [
							hasAccessByCodes([TextsPermissions.Create]) && (
								<Button key="add" type="primary" icon={<PlusOutlined />} onClick={handleOpenCreate}>
									{$t("LocalizationManagement.Text:AddNew")}
								</Button>
							),
						]}
						request={async (params, sorter) => {
							// Provide defaults for required fields if they are missing (initial load)
							const requestParams: any = {
								...params,
								cultureName: params.cultureName || application?.localization.currentCulture.cultureName,
								targetCultureName: params.targetCultureName || application?.localization.currentCulture.cultureName,
								onlyNull: params.onlyNull || "false",
							};

							// Fetch Data
							const { items } = await getListApi(requestParams);

							let dataSource = [...items];

							// Client-side Sort
							if (sorter && Object.keys(sorter).length > 0) {
								const sortField = Object.keys(sorter)[0];
								const sortOrder = sorter[sortField] === "ascend" ? "asc" : "desc";
								dataSource = orderBy(dataSource, [sortField], [sortOrder]);
							}

							// Client-side Pagination
							const current = params.current || 1;
							const pageSize = params.pageSize || 10;
							const startIndex = (current - 1) * pageSize;
							const endIndex = startIndex + pageSize;
							const pageData = dataSource.slice(startIndex, endIndex);

							return {
								data: pageData,
								success: true,
								total: dataSource.length,
							};
						}}
						pagination={{
							defaultPageSize: 10,
							showSizeChanger: true,
						}}
						manualRequest={false}
					/>
				</Card>
			</Space>
			<LocalizationTextModal
				visible={modalVisible}
				data={currentRow}
				// Pass current form values as defaults for creation
				defaultTargetCulture={formRef.current?.getFieldValue("targetCultureName")}
				defaultResourceName={formRef.current?.getFieldValue("resourceName")}
				onClose={() => setModalVisible(false)}
				onChange={handleDataChange}
			/>
		</>
	);
};

export default LocalizationTextTable;

// apps/vben5/packages/@abp/localization/src/components/texts/LocalizationTextTable.vue
<script setup lang="ts">
import type { VbenFormProps, VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { LanguageDto, ResourceDto } from '../../types';
import type { TextDifferenceDto, TextDto } from '../../types/texts';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useAbpStore } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import { EditOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, Select } from 'ant-design-vue';

import { useLanguagesApi } from '../../api/useLanguagesApi';
import { useLocalizationsApi } from '../../api/useLocalizationsApi';
import { useResourcesApi } from '../../api/useResourcesApi';
import { useTextsApi } from '../../api/useTextsApi';
import { ResourcesPermissions } from '../../constants/permissions';

defineOptions({
  name: 'LocalizationTextTable',
});

const dataSource = ref<TextDifferenceDto[]>([]);
const resources = ref<ResourceDto[]>([]);
const languages = ref<LanguageDto[]>([]);
const targetValueOptions = reactive([
  {
    label: $t('AbpLocalization.DisplayName:Any'),
    value: 'false',
  },
  {
    label: $t('AbpLocalization.DisplayName:OnlyNull'),
    value: 'true',
  },
]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const abpStore = useAbpStore();
const { getListApi } = useTextsApi();
const { getListApi: getLanguagesApi } = useLanguagesApi();
const { getListApi: getResourcesApi } = useResourcesApi();
const { getLocalizationApi } = useLocalizationsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  collapsedRows: 2,
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  compact: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'cultureName',
      formItemClass: 'items-baseline',
      label: $t('AbpLocalization.DisplayName:CultureName'),
      rules: 'selectRequired',
    },
    {
      component: 'Input',
      fieldName: 'targetCultureName',
      formItemClass: 'items-baseline',
      label: $t('AbpLocalization.DisplayName:TargetCultureName'),
      rules: 'selectRequired',
    },
    {
      component: 'Input',
      fieldName: 'resourceName',
      label: $t('AbpLocalization.DisplayName:ResourceName'),
    },
    {
      component: 'Input',
      fieldName: 'onlyNull',
      label: $t('AbpLocalization.DisplayName:TargetValue'),
    },
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<TextDifferenceDto> = {
  columns: [
    {
      align: 'left',
      field: 'key',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:Key'),
    },
    {
      align: 'left',
      field: 'value',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:Value'),
    },
    {
      align: 'left',
      field: 'targetValue',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:TargetValue'),
    },
    {
      align: 'left',
      field: 'resourceName',
      minWidth: 150,
      title: $t('AbpLocalization.DisplayName:ResourceName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<TextDifferenceDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [LocalizationTextModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./LocalizationTextModal.vue'),
  ),
});

async function onInit() {
  const [languageRes, resourceRes] = await Promise.all([
    getLanguagesApi(),
    getResourcesApi(),
  ]);
  languages.value = languageRes.items;
  resources.value = resourceRes.items;
}

function onFieldChange(fieldName: string, value?: string) {
  gridApi.formApi.setFieldValue(fieldName, value);
}

async function onGet(input: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input as any);
    pageState.total = items.length;
    dataSource.value = items;
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = dataSource.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

async function onCreate() {
  const input = await gridApi.formApi.getValues();
  modalApi.setData({
    cultureName: input.targetCultureName,
    resourceName: input.resourceName,
  });
  modalApi.open();
}

function onUpdate(row: TextDifferenceDto) {
  modalApi.setData(row);
  modalApi.open();
}

async function onChange(data: TextDto) {
  const input = await gridApi.formApi.getValues();
  onGet(input);
  // 资源变化刷新本地多语言缓存
  const cultureName =
    abpStore.application!.localization.currentCulture.cultureName;
  if (data.cultureName === cultureName) {
    const localization = await getLocalizationApi({
      cultureName,
    });
    abpStore.setLocalization(localization);
  }
}

onMounted(onInit);
</script>

<template>
  <Grid :table-title="$t('AbpLocalization.Texts')">
    <template #form-cultureName="{ modelValue }">
      <Select
        class="w-full"
        allow-clear
        :options="languages"
        :value="modelValue"
        :field-names="{ label: 'displayName', value: 'cultureName' }"
        @change="(value) => onFieldChange('cultureName', value?.toString())"
      />
    </template>
    <template #form-targetCultureName="{ modelValue }">
      <Select
        class="w-full"
        allow-clear
        :options="languages"
        :value="modelValue"
        :field-names="{ label: 'displayName', value: 'cultureName' }"
        @change="
          (value) => onFieldChange('targetCultureName', value?.toString())
        "
      />
    </template>
    <template #form-resourceName="{ modelValue }">
      <Select
        class="w-full"
        allow-clear
        :options="resources"
        :value="modelValue"
        :field-names="{ label: 'displayName', value: 'name' }"
        @change="(value) => onFieldChange('resourceName', value?.toString())"
      />
    </template>
    <template #form-onlyNull="{ modelValue }">
      <Select
        class="w-full"
        allow-clear
        :options="targetValueOptions"
        :value="modelValue"
        @change="(value) => onFieldChange('onlyNull', value?.toString())"
      />
    </template>
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[ResourcesPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('LocalizationManagement.Text:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          v-access:code="[ResourcesPermissions.Update]"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
      </div>
    </template>
  </Grid>
  <LocalizationTextModal @change="onChange" />
</template>

<style scoped></style>
