// apps/vben5/packages/@abp/webhooks/src/components/definitions/webhooks/WebhookDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { WebhookDefinitionDto } from '../../../types/definitions';
import type { WebhookGroupDefinitionDto } from '../../../types/groups';

import { h, onMounted, reactive, ref } from 'vue';

import { $t } from '@vben/locales';

import {
  listToTree,
  useLocalization,
  useLocalizationSerializer,
} from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  CheckOutlined,
  CloseOutlined,
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal, Tag } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

import { useWebhookDefinitionsApi } from '../../../api/useWebhookDefinitionsApi';
import { useWebhookGroupDefinitionsApi } from '../../../api/useWebhookGroupDefinitionsApi';
import { WebhookDefinitionsPermissions } from '../../../constants/permissions';

defineOptions({
  name: 'WebhookDefinitionTable',
});

interface DefinitionItem {
  children: DefinitionItem[];
  description?: string;
  displayName: string;
  groupName: string;
  isEnabled: boolean;
  isStatic: boolean;
  name: string;
  requiredFeatures?: string[];
}
interface DefinitionGroup {
  displayName: string;
  items: DefinitionItem[];
  name: string;
}

const { Lr } = useLocalization();
const { deserialize } = useLocalizationSerializer();
const { getListApi: getGroupsApi } = useWebhookGroupDefinitionsApi();
const { deleteApi, getListApi: getDefinitionsApi } = useWebhookDefinitionsApi();

const definitionGroups = ref<DefinitionGroup[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<WebhookGroupDefinitionDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'group',
      slots: { content: 'group' },
      type: 'expand',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('WebhooksManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('WebhooksManagement.DisplayName:DisplayName'),
    },
  ],
  expandConfig: {
    padding: true,
    trigger: 'row',
  },
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};
const subGridColumns: VxeGridProps<WebhookDefinitionDto>['columns'] = [
  {
    align: 'center',
    type: 'seq',
    width: 50,
  },
  {
    align: 'left',
    field: 'isEnabled',
    minWidth: 120,
    slots: { default: 'isEnabled' },
    title: $t('WebhooksManagement.DisplayName:IsEnabled'),
  },
  {
    align: 'left',
    field: 'name',
    minWidth: 150,
    title: $t('WebhooksManagement.DisplayName:Name'),
    treeNode: true,
  },
  {
    align: 'left',
    field: 'displayName',
    minWidth: 120,
    title: $t('WebhooksManagement.DisplayName:DisplayName'),
  },
  {
    align: 'left',
    field: 'description',
    minWidth: 120,
    title: $t('WebhooksManagement.DisplayName:Description'),
  },
  {
    align: 'left',
    field: 'features',
    minWidth: 150,
    slots: { default: 'features' },
    title: $t('WebhooksManagement.DisplayName:RequiredFeatures'),
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 220,
  },
];

const gridEvents: VxeGridListeners<WebhookGroupDefinitionDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [GroupGrid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const groupRes = await getGroupsApi(input);
    const definitionRes = await getDefinitionsApi(input);
    pageState.total = groupRes.items.length;
    definitionGroups.value = groupRes.items.map((group) => {
      const localizableGroup = deserialize(group.displayName);
      const definitions = definitionRes.items
        .filter((definition) => definition.groupName === group.name)
        .map((definition) => {
          const displayName = deserialize(definition.displayName);
          const description = deserialize(definition.displayName);
          return {
            ...definition,
            description: Lr(description.resourceName, description.name),
            displayName: Lr(displayName.resourceName, displayName.name),
          };
        });
      return {
        ...group,
        displayName: Lr(localizableGroup.resourceName, localizableGroup.name),
        items: listToTree(definitions, {
          id: 'name',
          pid: 'parentName',
        }),
      };
    });
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = definitionGroups.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {}

function onUpdate(_row: WebhookDefinitionDto) {}

function onDelete(row: WebhookDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <GroupGrid :table-title="$t('WebhooksManagement.WebhookDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[WebhookDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('WebhooksManagement.Webhooks:AddNew') }}
      </Button>
    </template>
    <template #group="{ row: group }">
      <VxeGrid
        :columns="subGridColumns"
        :data="group.items"
        :tree-config="{
          trigger: 'row',
          rowField: 'name',
          childrenField: 'children',
        }"
      >
        <template #isEnabled="{ row }">
          <div class="flex flex-row justify-center">
            <CheckOutlined v-if="row.isEnabled" class="text-green-500" />
            <CloseOutlined v-else class="text-red-500" />
          </div>
        </template>
        <template #features="{ row }">
          <div class="flex flex-row justify-center gap-1">
            <template v-for="feature in row.features" :key="feature">
              <Tag color="blue">{{ feature }}</Tag>
            </template>
          </div>
        </template>
        <template #action="{ row: definition }">
          <div class="flex flex-row">
            <Button
              :icon="h(EditOutlined)"
              block
              type="link"
              v-access:code="[WebhookDefinitionsPermissions.Update]"
              @click="onUpdate(definition)"
            >
              {{ $t('AbpUi.Edit') }}
            </Button>
            <Button
              v-if="!definition.isStatic"
              :icon="h(DeleteOutlined)"
              block
              danger
              type="link"
              v-access:code="[WebhookDefinitionsPermissions.Delete]"
              @click="onDelete(definition)"
            >
              {{ $t('AbpUi.Delete') }}
            </Button>
          </div>
        </template>
      </VxeGrid>
    </template>
  </GroupGrid>
</template>

<style scoped></style>

// apps/react-admin/src/pages/webhooks/definitions/webhooks/webhook-definition-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Tag, Space, Modal, Table, Card } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, CheckOutlined, CloseOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getListApi as getDefinitionsApi } from "@/api/webhooks/webhook-definitions";
import { getListApi as getGroupsApi } from "@/api/webhooks/webhook-group-definitions";
import type { WebhookDefinitionDto } from "#/webhooks/definitions";
import type { WebhookGroupDefinitionDto } from "#/webhooks/groups";
import { WebhookDefinitionsPermissions } from "@/constants/webhooks/permissions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { useLocalizer } from "@/hooks/abp/use-localization";

import WebhookDefinitionModal from "./webhook-definition-modal";
import { listToTree } from "@/utils/tree";

// Extended interface to hold the nested items for display
interface ExtendedGroupDto extends WebhookGroupDefinitionDto {
	items: WebhookDefinitionDto[];
}

const WebhookDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const { deserialize } = localizationSerializer();
	const { Lr } = useLocalizer();
	const [modal, contextHolder] = Modal.useModal();

	const [modalVisible, setModalVisible] = useState(false);
	const [selectedDefinitionName, setSelectedDefinitionName] = useState<string | undefined>();

	const { mutateAsync: deleteDef } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			actionRef.current?.reload();
		},
	});

	const handleCreate = () => {
		setSelectedDefinitionName(undefined);
		setModalVisible(true);
	};

	const handleUpdate = (row: WebhookDefinitionDto) => {
		setSelectedDefinitionName(row.name);
		setModalVisible(true);
	};

	const handleDelete = (row: WebhookDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: () => deleteDef(row.name),
		});
	};

	// --- Sub-Table Columns (Definitions) ---
	const definitionColumns = [
		{
			title: $t("WebhooksManagement.DisplayName:IsEnabled"),
			dataIndex: "isEnabled",
			width: 100,
			align: "center" as const,
			render: (val: boolean) =>
				val ? <CheckOutlined className="text-green-500" /> : <CloseOutlined className="text-red-500" />,
		},
		{
			title: $t("WebhooksManagement.DisplayName:Name"),
			dataIndex: "name",
			width: 250,
		},
		{
			title: $t("WebhooksManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 200,
		},
		{
			title: $t("WebhooksManagement.DisplayName:Description"),
			dataIndex: "description",
			ellipsis: true,
		},
		{
			title: $t("WebhooksManagement.DisplayName:RequiredFeatures"),
			dataIndex: "requiredFeatures",
			width: 200,
			render: (features: string[]) => (
				<Space wrap>
					{features?.map((f) => (
						<Tag key={f} color="blue">
							{f}
						</Tag>
					))}
				</Space>
			),
		},
		{
			title: $t("AbpUi.Actions"),
			key: "actions",
			width: 150,
			fixed: "right" as const,
			render: (_: any, record: WebhookDefinitionDto) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[WebhookDefinitionsPermissions.Update],
					)}
					{!record.isStatic &&
						withAccessChecker(
							<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
								{$t("AbpUi.Delete")}
							</Button>,
							[WebhookDefinitionsPermissions.Delete],
						)}
				</Space>
			),
		},
	];

	// --- Main Table Columns (Groups) ---
	const columns: ProColumns<ExtendedGroupDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("WebhooksManagement.DisplayName:Name"),
			dataIndex: "name",
			width: 200,
			fixed: "left",
		},
		{
			title: $t("WebhooksManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<ExtendedGroupDto>
					headerTitle={$t("WebhooksManagement.WebhookDefinitions")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={{ labelWidth: "auto" }}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("WebhooksManagement.Webhooks:AddNew")}
							</Button>,
							[WebhookDefinitionsPermissions.Create],
						),
					]}
					// Nested Table Renderer
					expandable={{
						expandedRowRender: (record) => (
							<Table
								columns={definitionColumns}
								dataSource={record.items}
								pagination={false}
								rowKey="name"
								size="small"
								// Support tree structure within definitions (Vue logic used listToTree)
								expandable={{
									defaultExpandAllRows: true,
									childrenColumnName: "children",
								}}
							/>
						),
						defaultExpandAllRows: true, // Expand groups by default to match Vue behavior often used for categorization
					}}
					request={async (params) => {
						const { filter } = params;

						// 1. Fetch Groups and Definitions in parallel
						const [groupRes, defRes] = await Promise.all([getGroupsApi({ filter }), getDefinitionsApi({ filter })]);

						// 2. Process and merge data
						const data: ExtendedGroupDto[] = groupRes.items.map((group) => {
							// Localize Group Name
							const groupLocal = deserialize(group.displayName);

							// Filter definitions belonging to this group
							const groupDefinitions = defRes.items
								.filter((d) => d.groupName === group.name)
								.map((d) => {
									// Localize Definition fields
									const dName = deserialize(d.displayName);
									const dDesc = deserialize(d.description);
									return {
										...d,
										displayName: Lr(dName.resourceName, dName.name),
										description: dDesc ? Lr(dDesc.resourceName, dDesc.name) : "",
									};
								});

							// Build Tree for definitions (handling parent/child relationships if any)
							const definitionsTree = listToTree(groupDefinitions, { id: "name", pid: "parentName" });

							return {
								...group,
								displayName: Lr(groupLocal.resourceName, groupLocal.name),
								items: definitionsTree,
							};
						});

						return {
							data: data,
							success: true,
							total: groupRes.items.length,
						};
					}}
					pagination={false}
				/>
			</Card>
			<WebhookDefinitionModal
				visible={modalVisible}
				definitionName={selectedDefinitionName}
				onClose={() => setModalVisible(false)}
				onChange={() => actionRef.current?.reload()}
			/>
		</>
	);
};

export default WebhookDefinitionTable;
