// apps/vben5/packages/@abp/features/src/components/definitions/features/FeatureDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { FeatureDefinitionDto } from '../../../types/definitions';
import type { FeatureGroupDefinitionDto } from '../../../types/groups';

import { defineAsyncComponent, h, onMounted, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  listToTree,
  sortby,
  useLocalization,
  useLocalizationSerializer,
} from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  CheckOutlined,
  CloseOutlined,
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

import { useFeatureDefinitionsApi } from '../../../api/useFeatureDefinitionsApi';
import { useFeatureGroupDefinitionsApi } from '../../../api/useFeatureGroupDefinitionsApi';
import { GroupDefinitionsPermissions } from '../../../constants/permissions';

defineOptions({
  name: 'FeatureDefinitionTable',
});

interface FeatureVo {
  children: FeatureVo[];
  displayName: string;
  groupName: string;
  isEnabled: boolean;
  isStatic: boolean;
  name: string;
  parentName?: string;
  providers: string[];
  stateCheckers: string[];
}
interface FeatureGroupVo {
  displayName: string;
  features: FeatureVo[];
  name: string;
}

const featureGroups = ref<FeatureGroupVo[]>([]);

const { Lr } = useLocalization();
const { deserialize } = useLocalizationSerializer();
const { getListApi: getGroupsApi } = useFeatureGroupDefinitionsApi();
const { deleteApi, getListApi: getFeaturesApi } = useFeatureDefinitionsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<FeatureGroupDefinitionDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'group',
      slots: { content: 'group' },
      type: 'expand',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      sortable: true,
      title: $t('AbpFeatureManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      sortable: true,
      title: $t('AbpFeatureManagement.DisplayName:DisplayName'),
    },
  ],
  expandConfig: {
    padding: true,
    trigger: 'row',
  },
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }) => {
        let items = sortby(featureGroups.value, sort.field);
        if (sort.order === 'desc') {
          items = items.reverse();
        }
        const result = {
          totalCount: featureGroups.value.length,
          items: items.slice(
            (page.currentPage - 1) * page.pageSize,
            page.currentPage * page.pageSize,
          ),
        };
        return new Promise((resolve) => {
          resolve(result);
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};
const subGridColumns: VxeGridProps<FeatureDefinitionDto>['columns'] = [
  {
    align: 'center',
    type: 'seq',
    width: 50,
  },
  {
    align: 'left',
    field: 'name',
    minWidth: 150,
    sortable: true,
    title: $t('AbpFeatureManagement.DisplayName:Name'),
    treeNode: true,
  },
  {
    align: 'left',
    field: 'displayName',
    minWidth: 120,
    sortable: true,
    title: $t('AbpFeatureManagement.DisplayName:DisplayName'),
  },
  {
    align: 'left',
    field: 'description',
    minWidth: 120,
    sortable: true,
    title: $t('AbpFeatureManagement.DisplayName:Description'),
  },
  {
    align: 'left',
    field: 'isVisibleToClients',
    minWidth: 120,
    slots: { default: 'isVisibleToClients' },
    sortable: true,
    title: $t('AbpFeatureManagement.DisplayName:IsVisibleToClients'),
  },
  {
    align: 'left',
    field: 'isAvailableToHost',
    minWidth: 120,
    slots: { default: 'isAvailableToHost' },
    sortable: true,
    title: $t('AbpFeatureManagement.DisplayName:IsAvailableToHost'),
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 180,
  },
];

const gridEvents: VxeGridListeners<FeatureGroupDefinitionDto> = {
  sortChange: () => {
    gridApi.query();
  },
};

const [GroupGrid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [FeatureDefinitionModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./FeatureDefinitionModal.vue'),
  ),
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const groupRes = await getGroupsApi(input);
    const featureRes = await getFeaturesApi(input);
    featureGroups.value = groupRes.items.map((group) => {
      const localizableGroup = deserialize(group.displayName);
      const features = featureRes.items
        .filter((feature) => feature.groupName === group.name)
        .map((feature) => {
          const displayName = deserialize(feature.displayName);
          const description = deserialize(feature.displayName);
          return {
            ...feature,
            description: Lr(description.resourceName, description.name),
            displayName: Lr(displayName.resourceName, displayName.name),
          };
        });
      return {
        ...group,
        displayName: Lr(localizableGroup.resourceName, localizableGroup.name),
        features: listToTree(features, {
          id: 'name',
          pid: 'parentName',
        }),
      };
    });
    setTimeout(() => gridApi.reload(), 100);
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: FeatureDefinitionDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: FeatureDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <GroupGrid :table-title="$t('AbpFeatureManagement.FeatureDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[GroupDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('AbpFeatureManagement.FeatureDefinitions:AddNew') }}
      </Button>
    </template>
    <template #group="{ row: group }">
      <VxeGrid
        :columns="subGridColumns"
        :data="group.features"
        :tree-config="{
          trigger: 'row',
          rowField: 'name',
          childrenField: 'children',
        }"
      >
        <template #isVisibleToClients="{ row }">
          <div class="flex flex-row justify-center">
            <CheckOutlined
              v-if="row.isVisibleToClients"
              class="text-green-500"
            />
            <CloseOutlined v-else class="text-red-500" />
          </div>
        </template>
        <template #isAvailableToHost="{ row }">
          <div class="flex flex-row justify-center">
            <CheckOutlined
              v-if="row.isAvailableToHost"
              class="text-green-500"
            />
            <CloseOutlined v-else class="text-red-500" />
          </div>
        </template>
        <template #action="{ row: permission }">
          <div class="flex flex-row">
            <Button
              :icon="h(EditOutlined)"
              block
              type="link"
              v-access:code="[GroupDefinitionsPermissions.Update]"
              @click="onUpdate(permission)"
            >
              {{ $t('AbpUi.Edit') }}
            </Button>
            <Button
              v-if="!permission.isStatic"
              :icon="h(DeleteOutlined)"
              block
              danger
              type="link"
              v-access:code="[GroupDefinitionsPermissions.Delete]"
              @click="onDelete(permission)"
            >
              {{ $t('AbpUi.Delete') }}
            </Button>
          </div>
        </template>
      </VxeGrid>
    </template>
  </GroupGrid>
  <FeatureDefinitionModal @change="() => onGet()" />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/features/definitions-features/feature-definition-table.tsx
import { useCallback, useRef, useState } from "react";
import { Button, Card, Table, Modal } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, CheckOutlined, CloseOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { FeatureDefinitionDto } from "#/management/features/definitions";
import type { FeatureGroupDefinitionDto } from "#/management/features/groups";
import { type ActionType, ProTable, type ProColumns } from "@ant-design/pro-table";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { deleteApi, getListApi as getFeaturesApi } from "@/api/management/features/feature-definitions";
import { getListApi as getGroupsApi } from "@/api/management/features/feature-group-definitions";
import { GroupDefinitionsPermissions } from "@/constants/management/permissions";
import FeatureDefinitionModal from "./feature-definition-modal";
import { useLocalizer } from "@/hooks/abp/use-localization";
import { toast } from "sonner";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { listToTree } from "@/utils/tree";

interface FeatureGroupVo extends FeatureGroupDefinitionDto {
	features: FeatureDefinitionDto[];
}

const FeatureDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();
	const { deserialize } = localizationSerializer();

	// Modal States
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedFeature, setSelectedFeature] = useState<FeatureDefinitionDto>();

	const { Lr } = useLocalizer(
		undefined,
		useCallback(() => {
			actionRef.current?.reload();
			setModalVisible(false);
		}, []),
	);

	const [searchParams, setSearchParams] = useState<{ filter?: string }>({});

	// Fetch Logic: Combined Groups + Features
	const { data, isLoading } = useQuery({
		queryKey: ["featureDefinitions", searchParams],
		queryFn: async () => {
			// Fetch both
			const [groupRes, featureRes] = await Promise.all([getGroupsApi(searchParams), getFeaturesApi(searchParams)]);

			// Map and Nest
			const mappedGroups: FeatureGroupVo[] = groupRes.items.map((group) => {
				const localizableGroup = deserialize(group.displayName);

				// Find features belonging to this group
				const groupFeatures = featureRes.items
					.filter((f) => f.groupName === group.name)
					.map((f) => {
						const fDisplay = deserialize(f.displayName);
						const fDesc = deserialize(f.description);
						return {
							...f,
							displayName: Lr(fDisplay.resourceName, fDisplay.name),
							description: Lr(fDesc.resourceName, fDesc.name),
						};
					});

				return {
					...group,
					displayName: Lr(localizableGroup.resourceName, localizableGroup.name),
					features: listToTree(groupFeatures, { id: "name", pid: "parentName" }),
				};
			});

			return mappedGroups;
		},
	});

	// Delete Feature
	const { mutateAsync: deleteFeature } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["featureDefinitions"] });
		},
	});

	// Handlers
	const handleCreate = () => {
		setSelectedFeature(undefined);
		setModalVisible(true);
	};

	const handleUpdate = (feature: FeatureDefinitionDto) => {
		setSelectedFeature(feature);
		setModalVisible(true);
	};

	const handleDelete = (feature: FeatureDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: feature.name }),
			onOk: () => deleteFeature(feature.name),
		});
	};

	// Outer Table Columns (Groups)
	const groupColumns: ProColumns<FeatureGroupVo>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpFeatureManagement.DisplayName:Name"),
			dataIndex: "name",
			hideInSearch: true,
		},
		{
			title: $t("AbpFeatureManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			hideInSearch: true,
		},
	];

	// Inner Table Columns (Features)
	const expandedRowRender = (groupRecord: FeatureGroupVo) => {
		const featureColumns: any[] = [
			{
				title: $t("AbpFeatureManagement.DisplayName:Name"),
				dataIndex: "name",
				width: 200,
			},
			{
				title: $t("AbpFeatureManagement.DisplayName:DisplayName"),
				dataIndex: "displayName",
				width: 200,
			},
			{
				title: $t("AbpFeatureManagement.DisplayName:Description"),
				dataIndex: "description",
			},
			{
				title: $t("AbpFeatureManagement.DisplayName:IsVisibleToClients"),
				dataIndex: "isVisibleToClients",
				width: 150,
				align: "center",
				render: (val: boolean) =>
					val ? <CheckOutlined className="text-green-500" /> : <CloseOutlined className="text-red-500" />,
			},
			{
				title: $t("AbpFeatureManagement.DisplayName:IsAvailableToHost"),
				dataIndex: "isAvailableToHost",
				width: 150,
				align: "center",
				render: (val: boolean) =>
					val ? <CheckOutlined className="text-green-500" /> : <CloseOutlined className="text-red-500" />,
			},
			{
				title: $t("AbpUi.Actions"),
				width: 180,
				fixed: "right",
				render: (_: any, record: FeatureDefinitionDto) => (
					<div className="flex flex-row gap-2">
						<Button
							type="link"
							size="small"
							icon={<EditOutlined />}
							disabled={!hasAccessByCodes([GroupDefinitionsPermissions.Update])}
							onClick={() => handleUpdate(record)}
						>
							{$t("AbpUi.Edit")}
						</Button>
						{!record.isStatic && (
							<Button
								type="link"
								size="small"
								danger
								icon={<DeleteOutlined />}
								disabled={!hasAccessByCodes([GroupDefinitionsPermissions.Delete])}
								onClick={() => handleDelete(record)}
							>
								{$t("AbpUi.Delete")}
							</Button>
						)}
					</div>
				),
			},
		];

		return (
			<Table
				columns={featureColumns}
				dataSource={groupRecord.features}
				pagination={false}
				rowKey="name"
				// The tree logic is handled by 'children' property in data, Table detects it automatically
			/>
		);
	};

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<FeatureGroupVo>
					headerTitle={$t("AbpFeatureManagement.FeatureDefinitions")}
					actionRef={actionRef}
					columns={groupColumns}
					dataSource={data}
					loading={isLoading}
					rowKey="name"
					pagination={{
						showSizeChanger: true,
						total: data?.length,
					}}
					scroll={{ x: "max-content" }}
					search={{
						labelWidth: "auto",
						span: 12,
						defaultCollapsed: true,
					}}
					toolBarRender={() => [
						hasAccessByCodes([GroupDefinitionsPermissions.Create]) && (
							<Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("AbpFeatureManagement.FeatureDefinitions:AddNew")}
							</Button>
						),
					]}
					request={async (params) => {
						const { filter } = params;
						setSearchParams({ filter });
						// Invalidate to trigger useQuery refetch
						await queryClient.invalidateQueries({ queryKey: ["featureDefinitions"] });
						return { data, success: true, total: data?.length };
					}}
					expandable={{
						expandedRowRender,
						defaultExpandAllRows: false,
					}}
				/>
			</Card>

			<FeatureDefinitionModal
				visible={modalVisible}
				featureName={selectedFeature?.name}
				onClose={() => setModalVisible(false)}
				onChange={() => {
					setModalVisible(false);
					actionRef.current?.reload();
				}}
			/>
		</>
	);
};

export default FeatureDefinitionTable;
