// apps/vben5/packages/@abp/ui/src/components/simple-state-checking/SimpleStateChecking.vue
<script setup lang="ts">
import type { ColumnsType } from 'ant-design-vue/lib/table';

import type { PropType } from 'vue';

import type { SimplaCheckStateBase } from './interface';

import { computed, reactive, unref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { isNullOrUnDef, useSimpleStateCheck } from '@abp/core';
import { Button, Card, Col, Row, Table, Tag } from 'ant-design-vue';

import SimpleStateCheckingModal from './SimpleStateCheckingModal.vue';

const props = defineProps({
  allowDelete: {
    default: false,
    type: Boolean,
  },
  allowEdit: {
    default: false,
    type: Boolean,
  },
  disabled: {
    default: false,
    type: Boolean,
  },
  state: {
    required: true,
    type: Object as PropType<SimplaCheckStateBase>,
  },
  value: {
    default: '',
    type: String,
  },
});
const emits = defineEmits(['change', 'update:value']);
const DeleteOutlined = createIconifyIcon('ant-design:delete-outlined');
const EditOutlined = createIconifyIcon('ant-design:edit-outlined');

const simpleCheckerMap = reactive<{ [key: string]: string }>({
  A: $t('component.simple_state_checking.requireAuthenticated.title'),
  F: $t('component.simple_state_checking.requireFeatures.title'),
  G: $t('component.simple_state_checking.requireGlobalFeatures.title'),
  P: $t('component.simple_state_checking.requirePermissions.title'),
});

const { deserialize, deserializeArray, serializeArray } = useSimpleStateCheck();

const [Modal, modalApi] = useVbenModal({
  connectedComponent: SimpleStateCheckingModal,
});

const getTableColumns = computed(() => {
  const columns: ColumnsType = [
    {
      align: 'left',
      dataIndex: 'name',
      fixed: 'left',
      key: 'name',
      maxWidth: 150,
      title: $t('component.simple_state_checking.table.name'),
    },
    {
      align: 'left',
      dataIndex: 'properties',
      fixed: 'left',
      key: 'properties',
      title: $t('component.simple_state_checking.table.properties'),
    },
  ];
  return [
    ...columns,
    ...(props.disabled
      ? []
      : [
          {
            align: 'center',
            dataIndex: 'action',
            fixed: 'right',
            key: 'action',
            title: $t('component.simple_state_checking.table.actions'),
            width: 180,
          },
        ]),
  ];
});
const getSimpleCheckers = computed(() => {
  if (isNullOrUnDef(props.value) || props.value.length === 0) {
    return [];
  }
  const simpleCheckers = deserializeArray(props.value, props.state);
  return simpleCheckers;
});
const getStateCheckerOptions = computed(() => {
  const stateCheckers = unref(getSimpleCheckers);
  return Object.keys(simpleCheckerMap).map((key) => {
    return {
      disabled: stateCheckers.some((x) => (x as any).name === key),
      label: simpleCheckerMap[key],
      value: key,
    };
  });
});

function handleAddNew() {
  modalApi.setData({
    options: getStateCheckerOptions.value,
  });
  modalApi.open();
}

function handleEdit(record: any) {
  modalApi.setData({
    options: getStateCheckerOptions.value,
    record,
  });
  modalApi.open();
}

function onChange(record: any) {
  const stateChecker = deserialize(record, props.state)!;
  const stateCheckers = unref(getSimpleCheckers);
  const inputIndex = stateCheckers.findIndex(
    (x) => (x as any).name === record.name,
  );
  if (inputIndex === -1) {
    stateCheckers.push(stateChecker);
  } else {
    stateCheckers[inputIndex] = stateChecker;
  }
  const updateValue = serializeArray(stateCheckers);

  emits('change', updateValue);
  emits('update:value', updateValue);
}

function handleDelete(record: any) {
  const stateCheckers = unref(getSimpleCheckers);
  const filtedStateCheckers = stateCheckers.filter(
    (x) => (x as any).name !== record.name,
  );
  if (filtedStateCheckers.length === 0) {
    handleClean();
    return;
  }
  const serializedCheckers = serializeArray(filtedStateCheckers);
  emits('change', serializedCheckers);
  emits('update:value', serializedCheckers);
}

function handleClean() {
  emits('change', undefined);
  emits('update:value', undefined);
}
</script>

<template>
  <div class="w-full">
    <div class="card">
      <Card>
        <template #title>
          <Row>
            <Col :span="12">
              <span>{{ $t('component.simple_state_checking.title') }}</span>
            </Col>
            <Col :span="12">
              <div class="toolbar" v-if="!props.disabled">
                <Button type="primary" @click="handleAddNew">
                  {{ $t('component.simple_state_checking.actions.create') }}
                </Button>
                <Button danger @click="handleClean">
                  {{ $t('component.simple_state_checking.actions.clean') }}
                </Button>
              </div>
            </Col>
          </Row>
        </template>
        <Table :columns="getTableColumns" :data-source="getSimpleCheckers">
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'name'">
              <span>{{ simpleCheckerMap[record.name] }}</span>
            </template>
            <template v-else-if="column.key === 'properties'">
              <div v-if="record.name === 'F'">
                <Tag v-for="feature in record.featureNames" :key="feature">
                  {{ feature }}
                </Tag>
              </div>
              <div v-else-if="record.name === 'G'">
                <Tag
                  v-for="feature in record.globalFeatureNames"
                  :key="feature">
                  {{ feature }}
                </Tag>
              </div>
              <div v-else-if="record.name === 'P'">
                <Tag
                  v-for="permission in record.model.permissions"
                  :key="permission">
                  {{ permission }}
                </Tag>
              </div>
              <div v-else-if="record.name === 'A'">
                <span>{{
                  $t(
                    'component.simple_state_checking.requireAuthenticated.title',
                  )
                }}</span>
              </div>
            </template>
            <template v-else-if="column.key === 'action'">
              <div class="flex flex-row">
                <Button
                  v-if="props.allowEdit"
                  type="link"
                  @click="() => handleEdit(record)">
                  <template #icon>
                    <EditOutlined />
                  </template>
                  {{ $t('component.simple_state_checking.actions.update') }}
                </Button>
                <Button
                  v-if="props.allowDelete"
                  type="link"
                  @click="() => handleDelete(record)"
                  danger>
                  <template #icon>
                    <DeleteOutlined />
                  </template>
                  {{ $t('component.simple_state_checking.actions.delete') }}
                </Button>
              </div>
            </template>
          </template>
        </Table>
      </Card>
    </div>
  </div>
  <Modal @change="onChange" />
</template>

<style lang="less" scoped>
.card {
  .toolbar {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    margin-bottom: 8px;

    > * {
      margin-right: 8px;
    }
  }
}
</style>

// apps/react-admin/src/components/abp/simple-state-checking/simple-state-checking.tsx
import type React from "react";
import { useState, useMemo, useEffect } from "react";
import { Button, Card, Table, Tag, Space, Row, Col, Popconfirm } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { useSimpleStateCheck } from "@/hooks/abp/fake-hooks/use-simple-state-check"; //  TODO re hooks in this chain
import type { SimplaCheckStateBase } from "./interface";
import SimpleStateCheckingModal from "./simple-state-checking-modal";
import type { ColumnsType } from "antd/es/table";

interface SimpleStateCheckingProps {
	state: SimplaCheckStateBase;
	value?: string; // Serialized string
	onChange?: (value: string | undefined) => void;
	disabled?: boolean;
	allowEdit?: boolean;
	allowDelete?: boolean;
}

const SimpleStateChecking: React.FC<SimpleStateCheckingProps> = ({
	state,
	value,
	onChange,
	disabled = false,
	allowEdit = false,
	allowDelete = false,
}) => {
	const { t: $t } = useTranslation();
	const { deserializeArray, serializeArray, deserialize } = useSimpleStateCheck();

	// Local state to manage the list of checkers
	const [checkers, setCheckers] = useState<any[]>([]);
	const [modalVisible, setModalVisible] = useState(false);
	const [editingRecord, setEditingRecord] = useState<any>(null);

	// Sync prop value with local state
	useEffect(() => {
		if (!value || value.length === 0) {
			setCheckers([]);
		} else {
			const deserialized = deserializeArray(value, state);
			setCheckers(deserialized);
		}
	}, [value, state]);

	// Map for friendly names
	const simpleCheckerMap: Record<string, string> = {
		A: $t("component.simple_state_checking.requireAuthenticated.title"),
		F: $t("component.simple_state_checking.requireFeatures.title"),
		G: $t("component.simple_state_checking.requireGlobalFeatures.title"),
		P: $t("component.simple_state_checking.requirePermissions.title"),
	};

	const handleAddNew = () => {
		setEditingRecord(null);
		setModalVisible(true);
	};

	const handleEdit = (record: any) => {
		setEditingRecord(record);
		setModalVisible(true);
	};

	const handleUpdateCheckers = (newCheckers: any[]) => {
		setCheckers(newCheckers);
		const serialized = serializeArray(newCheckers);
		onChange?.(serialized); //TODO
	};

	const handleModalConfirm = (data: any) => {
		// 'data' comes in format { T: 'type', A: bool, N: [] } from the modal

		// Deserialize the simple object from modal back into the complex class instance used by the list
		const deserializedItem = deserialize(data, state);
		if (!deserializedItem) return;

		const updatedList = [...checkers];
		const existingIndex = updatedList.findIndex((x) => x.name === data.T);

		if (existingIndex > -1) {
			updatedList[existingIndex] = deserializedItem;
		} else {
			updatedList.push(deserializedItem);
		}

		handleUpdateCheckers(updatedList);
	};

	const handleDelete = (record: any) => {
		const updatedList = checkers.filter((x) => x.name !== record.name);
		handleUpdateCheckers(updatedList);
	};

	const handleClean = () => {
		handleUpdateCheckers([]);
	};

	const options = useMemo(() => {
		return Object.keys(simpleCheckerMap).map((key) => ({
			label: simpleCheckerMap[key],
			value: key,
			// Disable if this type already exists in the list (assuming 1 per type based on Vue logic findIndex)
			disabled: checkers.some((x) => x.name === key),
		}));
	}, [checkers, $t]);

	const columns: ColumnsType<any> = [
		{
			title: $t("component.simple_state_checking.table.name"),
			dataIndex: "name",
			key: "name",
			width: 150,
			render: (name) => simpleCheckerMap[name] || name,
		},
		{
			title: $t("component.simple_state_checking.table.properties"),
			key: "properties",
			render: (_, record) => {
				if (record.name === "F") {
					return (
						<Space wrap>
							{record.featureNames?.map((f: string) => (
								<Tag key={f}>{f}</Tag>
							))}
						</Space>
					);
				}
				if (record.name === "G") {
					return (
						<Space wrap>
							{record.globalFeatureNames?.map((f: string) => (
								<Tag key={f}>{f}</Tag>
							))}
						</Space>
					);
				}
				if (record.name === "P") {
					const permissions = record.model?.permissions || record.permissions || [];
					return (
						<Space wrap>
							{permissions.map((p: string) => (
								<Tag key={p}>{p}</Tag>
							))}
						</Space>
					);
				}
				if (record.name === "A") {
					return $t("component.simple_state_checking.requireAuthenticated.title");
				}
				return null;
			},
		},
	];

	if (!disabled) {
		columns.push({
			title: $t("component.simple_state_checking.table.actions"),
			key: "action",
			width: 180,
			render: (_, record) => (
				<Space>
					{allowEdit && (
						<Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(record)}>
							{$t("component.simple_state_checking.actions.update")}
						</Button>
					)}
					{allowDelete && (
						<Popconfirm title="Are you sure?" onConfirm={() => handleDelete(record)}>
							<Button type="link" danger icon={<DeleteOutlined />}>
								{$t("component.simple_state_checking.actions.delete")}
							</Button>
						</Popconfirm>
					)}
				</Space>
			),
		});
	}

	return (
		<div className="w-full">
			<Card
				title={
					<Row justify="space-between" align="middle">
						<Col>{$t("component.simple_state_checking.title")}</Col>
						<Col>
							{!disabled && (
								<Space>
									<Button type="primary" onClick={handleAddNew} icon={<PlusOutlined />}>
										{$t("component.simple_state_checking.actions.create")}
									</Button>
									<Button danger onClick={handleClean}>
										{$t("component.simple_state_checking.actions.clean")}
									</Button>
								</Space>
							)}
						</Col>
					</Row>
				}
			>
				<Table rowKey="name" columns={columns} dataSource={checkers} pagination={false} size="small" />
			</Card>

			<SimpleStateCheckingModal
				visible={modalVisible}
				onClose={() => setModalVisible(false)}
				onConfirm={handleModalConfirm}
				record={editingRecord}
				options={options}
			/>
		</div>
	);
};

export default SimpleStateChecking;
