// apps/react-admin/src/pages/management/identity/organization-units/organization-unit-tree.tsx
import { useEffect, useState } from "react";
import { Card, Button, Tree, Dropdown, Modal } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined, RedoOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { DataNode } from "antd/lib/tree";
import { useMutation, useQuery } from "@tanstack/react-query";
import { deleteApi, getChildrenApi, getRootListApi, moveTo } from "@/api/management/identity/organization-units";
import { Iconify } from "@/components/icon";
import { toast } from "sonner";
import OrganizationUnitModal from "./organization-unit-modal";
import PermissionModal from "@/components/abp/permissions/permission-modal";

interface Props {
	onSelected?: (id?: string) => void;
}

const OrganizationUnitTree: React.FC<Props> = ({ onSelected }) => {
	const { t: $t } = useTranslation();
	// const queryClient = useQueryClient(); //
	const [modal, contextHolder] = Modal.useModal();

	const [organizationUnits, setOrganizationUnits] = useState<DataNode[]>([]);
	const [loadedKeys, setLoadedKeys] = useState<string[]>([]);
	const [selectedKey, setSelectedKey] = useState<string>();

	// Modal states
	const [editModalVisible, setEditModalVisible] = useState(false);
	const [permissionModalVisible, setPermissionModalVisible] = useState(false);
	const [selectedUnit, setSelectedUnit] = useState<{ id?: string; parentId?: string }>();

	// 获取根节点列表
	const { refetch: refreshTree } = useQuery({
		queryKey: ["organizationUnits", "root"],
		queryFn: async () => {
			const { items } = await getRootListApi();
			setOrganizationUnits(
				items.map((item) => ({
					isLeaf: false,
					key: item.id,
					title: item.displayName,
					children: [],
				})),
			);
			setLoadedKeys([]);
			return items;
		},
	});

	// 移动节点
	const { mutateAsync: moveNode } = useMutation({
		mutationFn: ({ id, parentId }: { id: string; parentId?: string }) => moveTo(id, parentId),
		onSuccess: () => {
			refreshTree();
		},
	});

	// 删除节点
	const { mutateAsync: deleteNode } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			refreshTree();
		},
	});

	const updateTreeData = (list: DataNode[], key: React.Key, children: DataNode[]): DataNode[] => {
		return list.map((node) => {
			if (node.key === key) {
				return {
					...node,
					children, // 更新子节点
				};
			}
			if (node.children) {
				return {
					...node,
					children: updateTreeData(node.children, key, children), // 递归更新子节点
				};
			}
			return node;
		});
	};
	const findNodeById = (nodes: DataNode[], id?: string): DataNode | undefined => {
		if (!id) return undefined;

		for (const node of nodes) {
			if (node.key === id) return node;
			if (node.children) {
				const found = findNodeById(node.children, id);
				if (found) return found;
			}
		}
		return undefined;
	};
	useEffect(() => {
		onSelected?.(selectedKey);
	}, [selectedKey]);

	const handleMenuClick = async (key: string, id: string) => {
		switch (key) {
			case "create":
				setSelectedUnit({ parentId: id });
				setEditModalVisible(true);
				break;
			case "update":
				setSelectedUnit({ id });
				setEditModalVisible(true);
				break;
			case "permissions":
				// const unit = await getApi(id);
				setSelectedUnit({ id });
				setPermissionModalVisible(true);
				break;
			case "delete":
				modal.confirm({
					title: $t("AbpUi.AreYouSure"),
					content: $t("AbpUi.ItemWillBeDeletedMessage"),
					onOk: () => deleteNode(id),
				});
				break;
			case "refresh":
				refreshTree();
				break;
		}
	};

	const menuItems = [
		{
			key: "update",
			icon: <EditOutlined />,
			label: $t("AbpUi.Edit"),
		},
		{
			key: "create",
			icon: <PlusOutlined />,
			label: $t("AbpIdentity.OrganizationUnit:AddChildren"),
		},
		{
			key: "delete",
			icon: <DeleteOutlined />,
			label: $t("AbpUi.Delete"),
		},
		{
			key: "permissions",
			icon: <Iconify icon="icon-park-outline:permissions" />,
			label: $t("AbpPermissionManagement.Permissions"),
		},
		{
			key: "refresh",
			icon: <RedoOutlined />,
			label: $t("AbpIdentity.OrganizationUnit:RefreshRoot"),
		},
	];

	return (
		<>
			{contextHolder}
			<Card
				title={$t("AbpIdentity.OrganizationUnit:Tree")}
				extra={
					<Button
						type="primary"
						icon={<PlusOutlined />}
						onClick={() => {
							setSelectedUnit({});
							setEditModalVisible(true);
						}}
					>
						{$t("AbpIdentity.OrganizationUnit:AddRoot")}
					</Button>
				}
			>
				<Tree
					loadData={async (node) => {
						// 加载子节点
						const nodeKey = String(node.key);
						const { items } = await getChildrenApi({ id: nodeKey });
						node.isLeaf = items.length === 0;
						node.children = items.map((item): DataNode => {
							return {
								isLeaf: false,
								key: item.id,
								title: item.displayName,
								children: [],
							};
						});
						setOrganizationUnits((prevUnits) => updateTreeData(prevUnits, nodeKey, node.children || []));

						setLoadedKeys((prev) => [...prev, String(node.key)]);
					}}
					loadedKeys={loadedKeys}
					treeData={organizationUnits}
					blockNode
					draggable
					onDrop={(info) => {
						if (!info.dragNode.key) return;
						const dragKey = String(info.dragNode.key);
						const dropKey =
							info.dropPosition === -1
								? undefined // 作为根节点
								: String(info.node.key); // 作为子节点
						moveNode({ id: dragKey, parentId: dropKey });
					}}
					onRightClick={(_) => {}}
					onSelect={(selectedKeys) => {
						if (selectedKeys.length === 0) {
							setSelectedKey(undefined);
							return;
						}
						setSelectedKey(String(selectedKeys[0]));
					}}
					titleRender={(nodeData) => (
						<Dropdown
							trigger={["contextMenu"]}
							menu={{
								items: menuItems,
								onClick: ({ key }) => handleMenuClick(key, String(nodeData.key)),
							}}
						>
							<div className="flex items-center justify-between py-1 px-2 rounded cursor-pointer group">
								<span>{String(nodeData.title)}</span>
								<span className="invisible group-hover:visible text-gray-400">
									<Iconify icon="ph:mouse-right-click-light" />
								</span>
							</div>
						</Dropdown>
					)}
				/>
			</Card>
			<OrganizationUnitModal
				visible={editModalVisible}
				id={selectedUnit?.id}
				parentId={selectedUnit?.parentId}
				onClose={() => {
					setEditModalVisible(false);
					setSelectedUnit(undefined);
				}}
				onChange={() => {
					refreshTree();
				}}
			/>

			<PermissionModal
				visible={permissionModalVisible}
				providerKey={selectedUnit?.id}
				providerName="O"
				displayName={findNodeById(organizationUnits, selectedUnit?.id)?.title?.toString()}
				onClose={() => {
					setPermissionModalVisible(false);
					setSelectedUnit(undefined);
				}}
				onChange={() => {
					refreshTree();
				}}
			/>
		</>
	);
};

export default OrganizationUnitTree;

// apps/vben5/packages/@abp/identity/src/components/organization-units/OrganizationUnitTree.vue
<script setup lang="ts">
import type {
  AntTreeNodeDropEvent,
  DataNode,
  EventDataNode,
} from 'ant-design-vue/es/tree';
import type { Key } from 'ant-design-vue/es/vc-table/interface';

import { defineAsyncComponent, h, onMounted, ref, watchEffect } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { PermissionModal } from '@abp/permission';
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
  RedoOutlined,
} from '@ant-design/icons-vue';
import { Button, Card, Dropdown, Menu, Modal, Tree } from 'ant-design-vue';

import {
  deleteApi,
  getApi,
  getChildrenApi,
  getRootListApi,
  moveTo,
} from '../../api/organization-units';

defineOptions({
  name: 'OrganizationUnitTree',
});

const emits = defineEmits<{
  (event: 'selected', id?: string): void;
}>();

const MenuItem = Menu.Item;
const PermissionsOutlined = createIconifyIcon('icon-park-outline:permissions');
const OrganizationUnitModal = defineAsyncComponent(
  () => import('./OrganizationUnitModal.vue'),
);

interface ContextMenuActionMap {
  [key: string]: (id: string) => Promise<void> | void;
}
const actionsMap: ContextMenuActionMap = {
  create: onCreate,
  delete: onDelete,
  permissions: onPermissions,
  refresh: onRefresh,
  update: onUpdate,
};

const organizationUnits = ref<DataNode[]>([]);
const loadedKeys = ref<string[]>([]);
const selectedKey = ref<string>();

const [OrganizationUnitEditModal, editModalApi] = useVbenModal({
  connectedComponent: OrganizationUnitModal,
});
const [OrganizationUnitPermissionModal, permissionModalApi] = useVbenModal({
  connectedComponent: PermissionModal,
});

/** 刷新组织机构树 */
async function onRefresh() {
  loadedKeys.value = [];
  const { items } = await getRootListApi();
  organizationUnits.value = items.map((item) => {
    return {
      isLeaf: false,
      key: item.id,
      title: item.displayName,
      children: [],
    };
  });
}

/** 加载组织机构树节点 */
async function onLoad(node: EventDataNode) {
  const nodeKey = String(node.key);
  const { items } = await getChildrenApi({ id: nodeKey });
  node.dataRef!.isLeaf = items.length === 0;
  node.dataRef!.children = items.map((item): DataNode => {
    return {
      isLeaf: false,
      key: item.id,
      title: item.displayName,
      children: [],
    };
  });
  organizationUnits.value = [...organizationUnits.value];
  loadedKeys.value.push(nodeKey);
}

/** 右键点击事件 */
function onRightClick() {
  // 阻止默认事件
}

/** 创建组织机构树 */
function onCreate(parentId?: string) {
  editModalApi.setData({ parentId });
  editModalApi.open();
}

/** 编辑组织机构树 */
function onUpdate(id: string) {
  editModalApi.setData({ id });
  editModalApi.open();
}

/** 编辑组织机构树权限 */
async function onPermissions(id: string) {
  const dto = await getApi(id);
  permissionModalApi.setData({
    displayName: dto.displayName,
    providerKey: id,
    providerName: 'O',
  });
  permissionModalApi.open();
}

/** 删除组织机构 */
function onDelete(id: string) {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessage'),
    maskClosable: false,
    onOk: () => {
      return deleteApi(id).then(() => onRefresh());
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

/** 右键菜单点击事件 */
function onMenuClick(id: string, eventKey: Key) {
  actionsMap[eventKey]!(id);
}

/** 组织机构选择变化事件 */
function onSelectChange(selectedKeys: Key[]) {
  if (selectedKeys.length === 0) {
    selectedKey.value = undefined;
    return;
  }
  selectedKey.value = String(selectedKeys[0]);
}

/** 组织机构节点拖动事件 */
function onDrop(info: AntTreeNodeDropEvent) {
  if (!info.dragNode.eventKey) {
    return;
  }
  const eventKey = String(info.dragNode.eventKey);
  const api =
    info.dropPosition === -1
      ? moveTo(eventKey) // parent
      : moveTo(eventKey, String(info.node.eventKey)); // children
  api.then(() => onRefresh());
}

onMounted(onRefresh);

watchEffect(() => {
  emits('selected', selectedKey.value);
});
</script>

<template>
  <Card :title="$t('AbpIdentity.OrganizationUnit:Tree')">
    <template #extra>
      <Button :icon="h(PlusOutlined)" type="primary" @click="() => onCreate()">
        {{ $t('AbpIdentity.OrganizationUnit:AddRoot') }}
      </Button>
    </template>
    <Tree
      :load-data="onLoad"
      :loaded-keys="loadedKeys"
      :tree-data="organizationUnits"
      block-node
      draggable
      @drop="onDrop"
      @right-click="onRightClick"
      @select="onSelectChange"
    >
      <template #title="{ key: treeKey, title }">
        <Dropdown :trigger="['contextmenu']">
          <span> {{ title }}</span>
          <template #overlay>
            <Menu @click="({ key: menuKey }) => onMenuClick(treeKey, menuKey)">
              <MenuItem key="update" :icon="h(EditOutlined)">
                {{ $t('AbpUi.Edit') }}
              </MenuItem>
              <MenuItem key="create" :icon="h(PlusOutlined)">
                {{ $t('AbpIdentity.OrganizationUnit:AddChildren') }}
              </MenuItem>
              <MenuItem key="delete" :icon="h(DeleteOutlined)">
                {{ $t('AbpUi.Delete') }}
              </MenuItem>
              <MenuItem key="permissions" :icon="h(PermissionsOutlined)">
                {{ $t('AbpIdentity.Permissions') }}
              </MenuItem>
              <MenuItem key="refresh" :icon="h(RedoOutlined)">
                {{ $t('AbpIdentity.OrganizationUnit:RefreshRoot') }}
              </MenuItem>
            </Menu>
          </template>
        </Dropdown>
      </template>
    </Tree>
  </Card>
  <OrganizationUnitEditModal @change="onRefresh" />
  <OrganizationUnitPermissionModal />
</template>

<style scoped></style>
