// apps/react-admin/src/pages/management/identity/organization-units/organization-unit-page.tsx
import { useState } from "react";
import OrganizationUnitTree from "./organization-unit-tree";
import OrganizationUnitTable from "./organization-unit-table";

const OrganizationUnitPage = () => {
	const [selectedKey, setSelectedKey] = useState<string>();

	return (
		<div className="flex flex-row gap-2">
			<div className="basis-1/3">
				<OrganizationUnitTree onSelected={setSelectedKey} />
			</div>
			<div className="basis-2/3">
				<OrganizationUnitTable selectedKey={selectedKey} />
			</div>
		</div>
	);
};

export default OrganizationUnitPage;

// apps/vben5/packages/@abp/identity/src/components/organization-units/OrganizationUnitPage.vue
<script setup lang="ts">
import { ref } from 'vue';

import OrganizationUnitTable from './OrganizationUnitTable.vue';
import OrganizationUnitTree from './OrganizationUnitTree.vue';

defineOptions({
  name: 'OrganizationUnitPage',
});

const selectedKey = ref<string>();

const onSelected = (id?: string) => {
  selectedKey.value = id;
};
</script>

<template>
  <div class="flex flex-row gap-2">
    <div class="basis-1/3">
      <OrganizationUnitTree @selected="onSelected" />
    </div>
    <div class="basis-2/3">
      <OrganizationUnitTable :selected-key="selectedKey" />
    </div>
  </div>
</template>

<style scoped></style>
