// apps/react-admin/src/pages/management/identity/organization-units/organization-unit-table.tsx
import { useState } from "react";
import { Card, Tabs } from "antd";
import { useTranslation } from "react-i18next";
import OrganizationUnitRoleTable from "./organization-unit-role-table";
import OrganizationUnitUserTable from "./organization-unit-user-table";

interface Props {
	selectedKey?: string;
}

type TabKeys = "users" | "roles";

const OrganizationUnitTable: React.FC<Props> = ({ selectedKey }) => {
	const { t: $t } = useTranslation();
	const [activeTab, setActiveTab] = useState<TabKeys>("users");

	return (
		<Card>
			<Tabs activeKey={activeTab} onChange={(key) => setActiveTab(key as TabKeys)}>
				<Tabs.TabPane key="users" tab={$t("AbpIdentity.Users")} />
				<Tabs.TabPane key="roles" tab={$t("AbpIdentity.Roles")} />
			</Tabs>
			{activeTab === "users" ? (
				<OrganizationUnitUserTable selectedKey={selectedKey} />
			) : (
				<OrganizationUnitRoleTable selectedKey={selectedKey} />
			)}
		</Card>
	);
};

export default OrganizationUnitTable;

// apps/vben5/packages/@abp/identity/src/components/organization-units/OrganizationUnitTable.vue
<script setup lang="ts">
import { ref } from 'vue';

import { Card, Tabs } from 'ant-design-vue';

import OrganizationUnitRoleTable from './OrganizationUnitRoleTable.vue';
import OrganizationUnitUserTable from './OrganizationUnitUserTable.vue';

defineOptions({
  name: 'OrganizationUnitTable',
});

const props = defineProps<{
  selectedKey?: string;
}>();

const TabPane = Tabs.TabPane;

const activeTab = ref<'roles' | 'users'>('users');
</script>

<template>
  <Card>
    <Tabs v-model:active-key="activeTab">
      <TabPane key="users" :tab="$t('AbpIdentity.Users')" />
      <TabPane key="roles" :tab="$t('AbpIdentity.Roles')" />
    </Tabs>
    <OrganizationUnitUserTable
      v-if="activeTab === 'users'"
      :selected-key="props.selectedKey" />
    <OrganizationUnitRoleTable v-else :selected-key="props.selectedKey" />
  </Card>
</template>

<style scoped></style>
