// apps/react-admin/src/pages/management/identity/organization-units/organization-unit-user-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Modal } from "antd";
import { DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { IdentityUserDto } from "#/management/identity";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import { useMutation, useQuery } from "@tanstack/react-query";
import { addMembers, getUserListApi } from "@/api/management/identity/organization-units";
import { removeOrganizationUnitApi } from "@/api/management/identity/users";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { OrganizationUnitPermissions } from "@/constants/management/identity/permissions";
import SelectMemberModal from "./select-member-modal";
import { toast } from "sonner";

interface Props {
	selectedKey?: string;
}

const OrganizationUnitUserTable: React.FC<Props> = ({ selectedKey }) => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();
	const [memberModalVisible, setMemberModalVisible] = useState(false);

	// 获取用户列表
	const { data, isLoading, refetch } = useQuery({
		queryKey: ["organizationUnitUsers", selectedKey],
		queryFn: () => {
			if (!selectedKey) {
				return Promise.reject(new Error("selectedKey is undefined"));
			}
			return getUserListApi(selectedKey, {});
		},
		enabled: !!selectedKey,
	});

	// 添加成员
	const { mutateAsync: addUsers } = useMutation({
		mutationFn: (users: IdentityUserDto[]) => {
			if (!selectedKey) {
				return Promise.reject(new Error("selectedKey is undefined"));
			}
			return addMembers(selectedKey, { userIds: users.map((u) => u.id) });
		},
		onSuccess: () => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			refetch();
			actionRef.current?.reload();
			setMemberModalVisible(false);
		},
	});

	// 移除成员
	const { mutateAsync: removeUser } = useMutation({
		mutationFn: (userId: string) => {
			if (!selectedKey) {
				return Promise.reject(new Error("selectedKey is undefined"));
			}
			return removeOrganizationUnitApi(userId, selectedKey);
		},
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			refetch();
			actionRef.current?.reload();
		},
	});

	const columns: ProColumns<IdentityUserDto>[] = [
		{
			title: $t("AbpIdentity.DisplayName:UserName"),
			dataIndex: "userName",
			width: 100,
		},
		{
			title: $t("AbpIdentity.DisplayName:Email"),
			dataIndex: "email",
			width: 120,
		},
		{
			title: $t("AbpUi.Actions"),
			width: 120,
			fixed: "right",
			render: (_, record) => (
				<Button
					type="link"
					danger
					icon={<DeleteOutlined />}
					disabled={!hasAccessByCodes([OrganizationUnitPermissions.ManageUsers])}
					onClick={() => {
						modal.confirm({
							title: $t("AbpUi.AreYouSure"),
							content: $t("AbpIdentity.OrganizationUnit:AreYouSureRemoveUser", { 0: record.userName }),
							onOk: () => removeUser(record.id),
						});
					}}
				>
					{$t("AbpUi.Delete")}
				</Button>
			),
		},
	];

	const getAddMemberEnabled = selectedKey && hasAccessByCodes([OrganizationUnitPermissions.ManageUsers]);

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<IdentityUserDto>
					headerTitle={$t("AbpIdentity.Users")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					dataSource={data?.items}
					loading={isLoading}
					search={false}
					pagination={{
						showSizeChanger: true,
						total: data?.totalCount,
					}}
					toolBarRender={() => [
						getAddMemberEnabled && (
							<Button type="primary" icon={<PlusOutlined />} onClick={() => setMemberModalVisible(true)}>
								{$t("AbpIdentity.OrganizationUnit:AddMember")}
							</Button>
						),
					]}
				/>
			</Card>
			{selectedKey && (
				<SelectMemberModal
					visible={memberModalVisible}
					onClose={() => setMemberModalVisible(false)}
					onConfirm={addUsers}
					organizationUnitId={selectedKey}
				/>
			)}
		</>
	);
};

export default OrganizationUnitUserTable;

// apps/vben5/packages/@abp/identity/src/components/organization-units/OrganizationUnitUserTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { IdentityUserDto } from '../../types/users';

import { computed, defineAsyncComponent, h, nextTick, watch } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useVbenVxeGrid } from '@abp/ui';
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { Button, Modal } from 'ant-design-vue';

import { addMembers, getUserListApi } from '../../api/organization-units';
import { removeOrganizationUnit } from '../../api/users';
import { OrganizationUnitPermissions } from '../../constants/permissions';

defineOptions({
  name: 'OrganizationUnitUserTable',
});

const props = defineProps<{
  selectedKey?: string;
}>();

const SelectMemberModal = defineAsyncComponent(
  () => import('./SelectMemberModal.vue'),
);

const { hasAccessByCodes } = useAccess();

const getAddMemberEnabled = computed(() => {
  return (
    props.selectedKey &&
    hasAccessByCodes([OrganizationUnitPermissions.ManageUsers])
  );
});

const gridOptions: VxeGridProps<IdentityUserDto> = {
  columns: [
    {
      field: 'userName',
      minWidth: '100px',
      title: $t('AbpIdentity.DisplayName:UserName'),
    },
    {
      field: 'email',
      minWidth: '120px',
      title: $t('AbpIdentity.DisplayName:Email'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'actions' },
      title: $t('AbpUi.Actions'),
      width: 120,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        if (!props.selectedKey) {
          return {
            totalCount: 0,
            items: [],
          };
        }
        return await getUserListApi(props.selectedKey!, {
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<IdentityUserDto> = {
  cellClick: () => {},
};
const [Grid, { query, setLoading }] = useVbenVxeGrid({
  gridEvents,
  gridOptions,
});
const [MemberModal, userModalApi] = useVbenModal({
  connectedComponent: SelectMemberModal,
});

const onRefresh = () => {
  nextTick(query);
};

const onDelete = (row: IdentityUserDto) => {
  Modal.confirm({
    centered: true,
    content: $t('AbpIdentity.OrganizationUnit:AreYouSureRemoveUser', [
      row.userName,
    ]),
    onOk: () => {
      setLoading(true);
      return removeOrganizationUnit(row.id, props.selectedKey!)
        .then(onRefresh)
        .finally(() => setLoading(false));
    },
    title: $t('AbpUi.AreYouSure'),
  });
};

const onShowMember = () => {
  userModalApi.setData({
    id: props.selectedKey,
  });
  userModalApi.open();
};

const onCreateMember = (users: IdentityUserDto[]) => {
  userModalApi.setState({
    closable: false,
    confirmLoading: true,
  });
  addMembers(props.selectedKey!, {
    userIds: users.map((item) => item.id),
  })
    .then(() => {
      userModalApi.close();
      query();
    })
    .finally(() => {
      userModalApi.setState({
        closable: true,
        confirmLoading: false,
      });
    });
};

watch(() => props.selectedKey, onRefresh);
</script>

<template>
  <Grid :table-title="$t('AbpIdentity.Users')">
    <template #toolbar-tools>
      <Button
        v-if="getAddMemberEnabled"
        :icon="h(PlusOutlined)"
        type="primary"
        @click="onShowMember"
      >
        {{ $t('AbpIdentity.OrganizationUnit:AddMember') }}
      </Button>
    </template>
    <template #actions="{ row }">
      <Button
        :icon="h(DeleteOutlined)"
        danger
        type="link"
        v-access:code="[OrganizationUnitPermissions.ManageUsers]"
        @click="onDelete(row)"
      >
        {{ $t('AbpUi.Delete') }}
      </Button>
    </template>
  </Grid>
  <MemberModal @confirm="onCreateMember" />
</template>

<style scoped></style>
