// apps/react-admin/src/pages/openiddict/applications/application-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space } from "antd";
import { DeleteOutlined, EditOutlined, EllipsisOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import type { OpenIddictApplicationDto } from "#/openiddict/applications";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import { ApplicationsPermissions } from "@/constants/openiddict/permissions";
import { AuditLogPermissions } from "@/constants/management/auditing/permissions";
import { Iconify } from "@/components/icon";
import { deleteApi, getPagedListApi } from "@/api/openiddict/applications";
import { useFeatures } from "@/hooks/abp/use-abp-feature";
import { toast } from "sonner";
import ApplicationModal from "./application-modal";
import ApplicationSecretModal from "./application-secret-modal";
import PermissionModal from "@/components/abp/permissions/permission-modal";
import { EntityChangeDrawer } from "@/components/abp/auditing/entity-change-drawer";

const ApplicationTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const { isEnabled } = useFeatures();
	const [modal, contextHolder] = Modal.useModal();

	// Modal visibility states
	const [modalVisible, setModalVisible] = useState(false);
	const [secretModalVisible, setSecretModalVisible] = useState(false);
	const [permissionModalVisible, setPermissionModalVisible] = useState(false);
	const [entityChangeDrawerVisible, setEntityChangeDrawerVisible] = useState(false);

	// Selected application state
	const [selectedApp, setSelectedApp] = useState<OpenIddictApplicationDto>();

	// Delete mutation
	const { mutateAsync: deleteApplication } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			actionRef.current?.reload();
		},
	});

	const handleMenuClick = (key: string, app: OpenIddictApplicationDto) => {
		setSelectedApp(app);
		switch (key) {
			case "secret":
				setSecretModalVisible(true);
				break;
			case "permissions":
				setPermissionModalVisible(true);
				break;
			case "entity-changes":
				setEntityChangeDrawerVisible(true);
				break;
		}
	};

	const handleDelete = (app: OpenIddictApplicationDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: app.clientId }),
			onOk: () => deleteApplication(app.id),
		});
	};

	const columns: ProColumns<OpenIddictApplicationDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			hideInTable: true,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ClientId"),
			dataIndex: "clientId",
			width: 150,
			align: "left",
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 150,
			ellipsis: true,
			align: "left",
			hideInSearch: true,
			minWidth: 150,
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ConsentType"),
			dataIndex: "consentType",
			width: 200,
			hideInSearch: true,
			align: "center",
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ClientType"),
			dataIndex: "clientType",
			width: 120,
			hideInSearch: true,
			align: "center",
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ApplicationType"),
			dataIndex: "applicationType",
			width: 150,
			hideInSearch: true,
			align: "center",
		},
		{
			title: $t("AbpOpenIddict.DisplayName:ClientUri"),
			dataIndex: "clientUri",
			width: 150,
			hideInSearch: true,
			align: "left",
		},
		{
			title: $t("AbpOpenIddict.DisplayName:LogoUri"),
			dataIndex: "logoUri",
			width: 120,
			hideInSearch: true,
			align: "left",
		},
		{
			title: $t("AbpUi.Actions"),
			width: 220,
			fixed: "right",
			hideInSearch: true,
			render: (_, record) => (
				<Space split>
					{hasAccessByCodes([ApplicationsPermissions.Update]) && (
						<Button
							type="link"
							icon={<EditOutlined />}
							onClick={() => {
								setSelectedApp(record);
								setModalVisible(true);
							}}
						>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{hasAccessByCodes([ApplicationsPermissions.Delete]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
					<Dropdown
						menu={{
							items: getDropdownMenuItems(record),
							onClick: ({ key }) => handleMenuClick(key, record),
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	const getDropdownMenuItems = (record: OpenIddictApplicationDto) => {
		const items = [];

		if (record.clientType === "confidential" && hasAccessByCodes([ApplicationsPermissions.ManageSecret])) {
			items.push({
				key: "secret",
				icon: <Iconify icon="codicon:gist-secret" />,
				label: $t("AbpOpenIddict.GenerateSecret"),
			});
		}

		if (hasAccessByCodes([ApplicationsPermissions.ManagePermissions])) {
			items.push({
				key: "permissions",
				icon: <Iconify icon="icon-park-outline:permissions" />,
				label: $t("AbpOpenIddict.ManagePermissions"),
			});
		}

		if (isEnabled("AbpAuditing.Logging.AuditLog") && hasAccessByCodes([AuditLogPermissions.Default])) {
			items.push({
				key: "entity-changes",
				icon: <Iconify icon="fluent-mdl2:compliance-audit" />,
				label: $t("AbpAuditLogging.EntitiesChanged"),
			});
		}

		return items;
	};

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<OpenIddictApplicationDto>
					headerTitle={$t("AbpOpenIddict.Applications")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					scroll={{ x: "max-content" }}
					request={async (params) => {
						const { current, pageSize, filter } = params;
						const query = await queryClient.fetchQuery({
							queryKey: ["openIddict.applications", params],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									filter: filter,
								}),
						});
						return {
							data: query.items,
							success: true,
							total: query.totalCount,
						};
					}}
					search={{
						span: 12,
						labelWidth: "auto",
					}}
					toolBarRender={() => [
						hasAccessByCodes([ApplicationsPermissions.Create]) && (
							<Button
								type="primary"
								icon={<PlusOutlined />}
								onClick={() => {
									setSelectedApp(undefined);
									setModalVisible(true);
								}}
							>
								{$t("AbpOpenIddict.Applications:AddNew")}
							</Button>
						),
					]}
				/>
			</Card>
			{/* Modals */}
			<ApplicationModal
				visible={modalVisible}
				applicationId={selectedApp?.id}
				onClose={() => {
					setModalVisible(false);
					setSelectedApp(undefined);
				}}
				onChange={() => actionRef.current?.reload()}
			/>

			{selectedApp && (
				<ApplicationSecretModal
					visible={secretModalVisible}
					applicationId={selectedApp.id}
					clientId={selectedApp.clientId}
					onClose={() => {
						setSecretModalVisible(false);
						setSelectedApp(undefined);
					}}
					onChange={() => actionRef.current?.reload()}
				/>
			)}

			<PermissionModal
				visible={permissionModalVisible}
				providerName="C"
				providerKey={selectedApp?.clientId}
				displayName={selectedApp?.clientId}
				onClose={() => {
					setPermissionModalVisible(false);
					setSelectedApp(undefined);
				}}
			/>

			<EntityChangeDrawer
				open={entityChangeDrawerVisible}
				subject={selectedApp?.clientId}
				input={{
					entityId: selectedApp?.id,
					entityTypeFullName: "Volo.Abp.OpenIddict.Applications.OpenIddictApplication",
				}}
				onClose={() => {
					setEntityChangeDrawerVisible(false);
					setSelectedApp(undefined);
				}}
			/>
		</>
	);
};

export default ApplicationTable;

// apps/vben5/packages/@abp/openiddict/src/components/applications/ApplicationTable.vue
<script setup lang="ts">
import type { VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { OpenIddictApplicationDto } from '../../types/applications';

import { defineAsyncComponent, h } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenDrawer, useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { AuditLogPermissions, EntityChangeDrawer } from '@abp/auditing';
import { useFeatures } from '@abp/core';
import { PermissionModal } from '@abp/permissions';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useApplicationsApi } from '../../api/useApplicationsApi';
import { ApplicationsPermissions } from '../../constants/permissions';

defineOptions({
  name: 'ApplicationTable',
});

const MenuItem = Menu.Item;

const AuditLogIcon = createIconifyIcon('fluent-mdl2:compliance-audit');
const CheckIcon = createIconifyIcon('ant-design:check-outlined');
const CloseIcon = createIconifyIcon('ant-design:close-outlined');
const SecretIcon = createIconifyIcon('codicon:gist-secret');
const PermissionsOutlined = createIconifyIcon('icon-park-outline:permissions');

const { isEnabled } = useFeatures();
const { hasAccessByCodes } = useAccess();
const { deleteApi, getPagedListApi } = useApplicationsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<OpenIddictApplicationDto> = {
  columns: [
    {
      align: 'left',
      field: 'clientId',
      minWidth: 150,
      title: $t('AbpOpenIddict.DisplayName:ClientId'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AbpOpenIddict.DisplayName:DisplayName'),
    },
    {
      align: 'center',
      field: 'consentType',
      title: $t('AbpOpenIddict.DisplayName:ConsentType'),
      width: 200,
    },
    {
      align: 'center',
      field: 'clientType',
      title: $t('AbpOpenIddict.DisplayName:ClientType'),
      width: 120,
    },
    {
      align: 'center',
      field: 'applicationType',
      title: $t('AbpOpenIddict.DisplayName:ApplicationType'),
      width: 150,
    },
    {
      align: 'left',
      field: 'clientUri',
      title: $t('AbpOpenIddict.DisplayName:ClientUri'),
      width: 150,
    },
    {
      align: 'left',
      field: 'logoUri',
      title: $t('AbpOpenIddict.DisplayName:LogoUri'),
      width: 120,
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: hasAccessByCodes([
        ApplicationsPermissions.Update,
        ApplicationsPermissions.Delete,
      ]),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        return await getPagedListApi({
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};
const [ApplicationModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./ApplicationModal.vue'),
  ),
});
const [ApplicationSecretModal, secretModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./ApplicationSecretModal.vue'),
  ),
});
const [ApplicationPermissionModal, permissionModalApi] = useVbenModal({
  connectedComponent: PermissionModal,
});
const [ApplicationChangeDrawer, applicationChangeDrawerApi] = useVbenDrawer({
  connectedComponent: EntityChangeDrawer,
});

const [Grid, { query }] = useVbenVxeGrid({
  formOptions,
  gridOptions,
});

const onCreate = () => {
  modalApi.setData({});
  modalApi.open();
};

const onUpdate = (row: OpenIddictApplicationDto) => {
  modalApi.setData(row);
  modalApi.open();
};

const onDelete = (row: OpenIddictApplicationDto) => {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.clientId])}`,
    onOk: async () => {
      await deleteApi(row.id);
      message.success($t('AbpUi.DeletedSuccessfully'));
      query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
};

const onMenuClick = (row: OpenIddictApplicationDto, info: MenuInfo) => {
  switch (info.key) {
    case 'entity-changes': {
      applicationChangeDrawerApi.setData({
        entityId: row.id,
        entityTypeFullName:
          'Volo.Abp.OpenIddict.Applications.OpenIddictApplication',
        subject: row.clientId,
      });
      applicationChangeDrawerApi.open();
      break;
    }
    case 'permissions': {
      permissionModalApi.setData({
        displayName: row.clientId,
        providerKey: row.clientId,
        providerName: 'C',
      });
      permissionModalApi.open();
      break;
    }
    case 'secret': {
      secretModalApi.setData(row);
      secretModalApi.open();
      break;
    }
  }
};
</script>

<template>
  <Grid :table-title="$t('AbpOpenIddict.Applications')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[ApplicationsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('AbpOpenIddict.Applications:AddNew') }}
      </Button>
    </template>
    <template #required="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.required" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #static="{ row }">
      <div class="flex flex-row justify-center">
        <CheckIcon v-if="row.isStatic" class="text-green-500" />
        <CloseIcon v-else class="text-red-500" />
      </div>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <div class="basis-1/3">
          <Button
            :icon="h(EditOutlined)"
            block
            type="link"
            v-access:code="[ApplicationsPermissions.Update]"
            @click="onUpdate(row)"
          >
            {{ $t('AbpUi.Edit') }}
          </Button>
        </div>
        <div class="basis-1/3">
          <Button
            :icon="h(DeleteOutlined)"
            block
            danger
            type="link"
            v-access:code="[ApplicationsPermissions.Delete]"
            @click="onDelete(row)"
          >
            {{ $t('AbpUi.Delete') }}
          </Button>
        </div>
        <div class="basis-1/3">
          <Dropdown>
            <template #overlay>
              <Menu @click="(info) => onMenuClick(row, info)">
                <MenuItem
                  v-if="
                    row.clientType === 'confidential' &&
                    hasAccessByCodes([ApplicationsPermissions.ManageSecret])
                  "
                  key="secret"
                  :icon="h(SecretIcon)"
                >
                  {{ $t('AbpOpenIddict.GenerateSecret') }}
                </MenuItem>
                <MenuItem
                  v-if="
                    hasAccessByCodes([
                      ApplicationsPermissions.ManagePermissions,
                    ])
                  "
                  key="permissions"
                  :icon="h(PermissionsOutlined)"
                >
                  {{ $t('AbpOpenIddict.ManagePermissions') }}
                </MenuItem>
                <MenuItem
                  v-if="
                    isEnabled('AbpAuditing.Logging.AuditLog') &&
                    hasAccessByCodes([AuditLogPermissions.Default])
                  "
                  key="entity-changes"
                  :icon="h(AuditLogIcon)"
                >
                  {{ $t('AbpAuditLogging.EntitiesChanged') }}
                </MenuItem>
              </Menu>
            </template>
            <Button :icon="h(EllipsisOutlined)" type="link" />
          </Dropdown>
        </div>
      </div>
    </template>
  </Grid>
  <ApplicationModal @change="() => query()" />
  <ApplicationSecretModal @change="() => query()" />
  <ApplicationPermissionModal />
  <ApplicationChangeDrawer />
</template>

<style lang="scss" scoped></style>
