// apps/react-admin/src/pages/management/settings/settings/setting-form.tsx
import { useEffect, useState } from "react";
import { Card, Form, Tabs, Collapse, Input, InputNumber, DatePicker, Select, Checkbox, Button } from "antd";
import { useTranslation } from "react-i18next";
import {
	ValueType,
	type SettingDetail,
	type SettingGroup,
	type SettingsUpdateInput,
} from "#/management/settings/settings";
import { formatToDate } from "@/utils/abp";
import { SettingOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
import { toast } from "sonner";

interface Props {
	getApi: () => Promise<SettingGroup[]>;
	submitApi: (input: SettingsUpdateInput) => Promise<void>;
	onChange: (data: SettingsUpdateInput) => void;
	slots?: {
		[key: string]: React.FC<{
			detail: SettingDetail;
			onChange: (setting: SettingDetail) => void;
		}>;
	};
}

const defaultModel: SettingsUpdateInput = {
	settings: [],
};

const SettingForm: React.FC<Props> = ({ getApi, submitApi, onChange, slots }) => {
	const { t: $t } = useTranslation();
	// const [form] = Form.useForm();
	const [activeTab, setActiveTab] = useState(0);
	const [submitting, setSubmitting] = useState(false);
	const [settingGroups, setSettingGroups] = useState<SettingGroup[]>([]);
	const [settingsUpdateInput, setSettingsUpdateInput] = useState<SettingsUpdateInput>(defaultModel);

	useEffect(() => {
		fetchSettings();
	}, []);

	const fetchSettings = async () => {
		const groups = await getApi();
		setSettingGroups(groups);
	};

	const getExpandedCollapseKeys = (group: SettingGroup) => {
		return group.settings.map((setting) => setting.displayName);
	};

	const handleSubmit = async () => {
		if (settingsUpdateInput.settings.length === 0) return;

		try {
			setSubmitting(true);
			await submitApi(settingsUpdateInput);
			onChange(settingsUpdateInput);
			toast.success($t("AbpSettingManagement.SuccessfullySaved"));
		} finally {
			setSubmitting(false);
		}
	};

	const handleCheckChange = (setting: SettingDetail) => {
		setting.value = setting.value === "true" ? "false" : "true";
		handleValueChange(setting);
	};

	const handleDateChange = (date: any, setting: SettingDetail) => {
		setting.value = dayjs.isDayjs(date) ? formatToDate(date) : "";
		handleValueChange(setting);
	};

	const handleValueChange = (setting: SettingDetail) => {
		if (setting.valueType === ValueType.NoSet) return;

		setSettingsUpdateInput((prev) => {
			const newSettings = [...prev.settings];
			const index = newSettings.findIndex((s) => s.name === setting.name);

			if (index === -1) {
				newSettings.push({
					name: setting.name,
					value: String(setting.value),
				});
			} else {
				newSettings[index] = {
					...newSettings[index],
					value: String(setting.value),
				};
			}

			return { settings: newSettings };
		});
	};

	const renderSettingInput = (detail: SettingDetail) => {
		// 如果存在自定义槽位，优先使用槽位
		if (detail.slot && slots?.[detail.slot]) {
			const SlotComponent = slots[detail.slot];
			// return <SlotComponent detail={detail} onChange={(_)=>{}} />;
			return <SlotComponent detail={detail} onChange={handleValueChange} />;
		}

		switch (detail.valueType) {
			case ValueType.String:
				return detail.isEncrypted ? (
					<Input.Password
						value={detail.value}
						placeholder={detail.description}
						onChange={(e) => {
							detail.value = e.target.value;
							handleValueChange(detail);
						}}
					/>
				) : (
					<Input
						value={detail.value}
						placeholder={detail.description}
						onChange={(e) => {
							detail.value = e.target.value;
							handleValueChange(detail);
						}}
					/>
				);
			case ValueType.Number:
				return !detail.isEncrypted ? (
					<InputNumber
						className="w-full"
						value={detail.value}
						placeholder={detail.description}
						onChange={(value) => {
							detail.value = String(value);
							handleValueChange(detail);
						}}
					/>
				) : null;
			case ValueType.Date:
				return (
					<DatePicker
						className="w-full"
						placeholder={detail.description}
						value={detail.value ? dayjs(detail.value, "YYYY-MM-DD") : null}
						onChange={(date) => handleDateChange(date, detail)}
					/>
				);
			case ValueType.Option:
				return (
					<Select
						value={detail.value}
						onChange={(value) => {
							detail.value = value;
							handleValueChange(detail);
						}}
					>
						{detail.options?.map((option) => (
							<Select.Option key={option.value} value={option.value} disabled={option.value === detail.value}>
								{option.name}
							</Select.Option>
						))}
					</Select>
				);
			case ValueType.Boolean:
				return (
					<Checkbox checked={detail.value === "true"} onChange={() => handleCheckChange(detail)}>
						{detail.displayName}
					</Checkbox>
				);
			default:
				return null;
		}
	};

	return (
		<Card
			title={$t("AbpSettingManagement.Settings")}
			extra={
				settingsUpdateInput.settings.length > 0 && (
					<Button
						type="primary"
						icon={<SettingOutlined />}
						loading={submitting}
						onClick={handleSubmit}
						className="w-[100px]"
					>
						{$t("AbpUi.Submit")}
					</Button>
				)
			}
		>
			<Form labelCol={{ span: 5 }} wrapperCol={{ span: 15 }}>
				<Tabs activeKey={String(activeTab)} onChange={(key) => setActiveTab(Number(key))}>
					{settingGroups.map((group, index) => (
						// biome-ignore lint: reason
						<Tabs.TabPane key={index} tab={group.displayName}>
							<Collapse defaultActiveKey={getExpandedCollapseKeys(group)}>
								{group.settings.map((setting) => (
									<Collapse.Panel key={setting.displayName} header={setting.displayName}>
										{setting.details.map((detail) => (
											<Form.Item key={detail.name} label={detail.displayName} extra={detail.description}>
												{renderSettingInput(detail)}
											</Form.Item>
										))}
									</Collapse.Panel>
								))}
							</Collapse>
						</Tabs.TabPane>
					))}
				</Tabs>
			</Form>
		</Card>
	);
};

export default SettingForm;

// apps/vue/src/components/SettingManagement/src/SettingForm.vue
<template>
  <Card :title="L('Settings')">
    <Form :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
      <Tabs
        v-model:activeKey="activeTabKey"
        :tab-position="tabPosition"
        :style="tabsStyle.style"
        :tabBarStyle="tabsStyle.tabBarStyle"
      >
        <TabPane
          v-for="(group, tabIndex) in settingGroups"
          :key="tabIndex"
          :tab="group.displayName"
        >
          <Collapse :defaultActiveKey="expandedCollapseKeys(group)">
            <CollapsePanel
              v-for="setting in group.settings"
              :key="setting.displayName"
              :header="setting.displayName"
            >
              <template v-for="detail in setting.details" :key="detail.name">
                <slot
                  v-if="detail.slot"
                  :name="detail.slot"
                  :detail="detail"
                  :change="detail.valueType === 2 ? handleCheckChange : handleValueChange"
                />
                <FormItem v-else :label="detail.displayName" :extra="detail.description">
                  <!-- <Input type="text" v-model="detail.value" /> -->
                  <Password
                    v-if="detail.valueType === 0 && detail.isEncrypted"
                    v-model:value="detail.value"
                    :placeholder="detail.description"
                    @input="handleValueChange(detail)"
                  />
                  <BInput
                    v-if="detail.valueType === 0 && !detail.isEncrypted"
                    v-model:value="detail.value"
                    :placeholder="detail.description"
                    type="text"
                    @input="handleValueChange(detail)"
                  />
                  <BInput
                    v-if="detail.valueType === 1"
                    v-model:value="detail.value"
                    :placeholder="detail.description"
                    type="number"
                    @input="handleValueChange(detail)"
                  />
                  <DatePicker
                    v-if="detail.valueType === 3"
                    :value="detail.value ? dayjs(detail.value, 'YYYY-MM-DD') : ''"
                    :placeholder="detail.description"
                    style="width: 100%"
                    @change="handleDateChange($event, detail)"
                  />
                  <Select
                    v-if="detail.valueType === 5"
                    v-model:value="detail.value"
                    @change="handleValueChange(detail)"
                  >
                    <SelectOption
                      v-for="option in detail.options"
                      :key="option.value"
                      :disabled="option.value === detail.value"
                    >
                      {{ option.name }}
                    </SelectOption>
                  </Select>
                  <Checkbox
                    v-if="detail.valueType === 2"
                    :checked="detail.value === 'true'"
                    @change="handleCheckChange(detail)"
                  >
                    {{ detail.displayName }}
                  </Checkbox>
                </FormItem>
              </template>
            </CollapsePanel>
          </Collapse>
        </TabPane>
      </Tabs>
      <FormItem style="margin-top: 20px">
        <Button
          v-if="updateSetting.settings.length > 0"
          type="primary"
          style="width: 150px"
          postIcon="ant-design:setting-outlined"
          :loading="saving"
          @click="handleSubmit"
        >
          {{ sumbitButtonTitle }}
        </Button>
      </FormItem>
    </Form>
  </Card>
</template>

<script lang="ts" setup>
  import dayjs from 'dayjs';
  import { computed, ref, toRaw } from 'vue';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useTabsStyle } from '/@/hooks/component/useStyles';
  import { useLocalization } from '/@/hooks/abp/useLocalization';
  import {
    Button,
    Card,
    Checkbox,
    Tabs,
    Collapse,
    Form,
    Input,
    Select,
    DatePicker,
  } from 'ant-design-vue';
  import { Input as BInput } from '/@/components/Input';
  import { formatToDate } from '/@/utils/dateUtil';
  import { SettingGroup, SettingsUpdate } from '/@/api/settings-management/settings/model';

  const CollapsePanel = Collapse.Panel;
  const FormItem = Form.Item;
  const SelectOption = Select.Option;
  const TabPane = Tabs.TabPane;
  const Password = Input.Password;

  const emits = defineEmits(['change']);
  const props = defineProps({
    settingGroups: {
      type: Array as PropType<Array<SettingGroup>>,
      required: true,
    },
    saveApi: {
      type: Function as PropType<(...args: any) => Promise<any>>,
      required: true,
    },
    tabPosition: {
      type: String as PropType<'left' | 'right' | 'top' | 'bottom'>,
      default: 'top',
    },
  });

  const { L } = useLocalization('AbpSettingManagement');
  const activeTabKey = ref(0);
  const saving = ref(false);
  const updateSetting = ref(new SettingsUpdate());
  const { createMessage } = useMessage();
  const { success } = createMessage;

  const tabsStyle = useTabsStyle(
    props.tabPosition,
    {}, 
    {
      top: props.tabPosition === 'top' ? '80px' : '0'
    });
  const sumbitButtonTitle = computed(() => {
    if (saving.value) {
      return L('Save');
    }
    return L('Save');
  });
  const expandedCollapseKeys = computed(() => {
    return (group) => {
      const keys = group.settings.map((s) => {
        return s.displayName;
      });
      return keys;
    };
  });

  function handleCheckChange(setting) {
    if (setting.value === 'true') {
      setting.value = 'false';
    } else {
      setting.value = 'true';
    }
    handleValueChange(setting);
  }

  function handleDateChange(e, setting) {
    setting.value = dayjs.isDayjs(e) ? formatToDate(e) : '';
    handleValueChange(setting);
  }

  function handleValueChange(setting) {
    const index = updateSetting.value.settings.findIndex((s) => s.name === setting.name);
    if (index >= 0) {
      updateSetting.value.settings[index].value = setting.value;
    } else {
      updateSetting.value.settings.push({
        name: setting.name,
        value: setting.value,
      });
    }
  }

  function handleSubmit() {
    saving.value = true;
    props
      .saveApi(toRaw(updateSetting.value))
      .then(() => {
        success(L('SuccessfullySaved'));
        emits('change', toRaw(updateSetting.value));
      })
      .finally(() => {
        saving.value = false;
      });
  }
</script>
