// apps/react-admin/src/pages/platform/messages/email/email-message-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Tag, Space, Modal, Dropdown, Card } from "antd";
import { EditOutlined, DeleteOutlined, EllipsisOutlined, SendOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getPagedListApi, sendApi } from "@/api/platform/email-messages";
import type { EmailMessageDto } from "#/platform/messages";
import { MessageStatus } from "#/platform/messages";
import { EmailMessagesPermissions } from "@/constants/platform/permissions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { formatToDateTime } from "@/utils/abp";
import { antdOrderToAbpOrder } from "@/utils/abp/sort-order";

import EmailMessageModal from "./email-message-modal";

const EmailMessageTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();

	const [modalVisible, setModalVisible] = useState(false);
	const [selectedContent, setSelectedContent] = useState<string>("");

	// Mutations
	const { mutateAsync: deleteMessage } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			actionRef.current?.reload();
		},
	});

	const { mutateAsync: sendMessage } = useMutation({
		mutationFn: sendApi,
		onSuccess: () => {
			toast.success($t("AppPlatform.SuccessfullySent"));
			actionRef.current?.reload();
		},
	});

	// Handlers
	const handleViewContent = (row: EmailMessageDto) => {
		setSelectedContent(row.content);
		setModalVisible(true);
	};

	const handleDelete = (row: EmailMessageDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessage"),
			onOk: () => deleteMessage(row.id),
		});
	};

	const handleSend = (row: EmailMessageDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AppPlatform.MessageWillBeReSendWarningMessage"),
			onOk: () => sendMessage(row.id),
		});
	};

	const statusOptions = [
		{ label: $t("AppPlatform.MessageStatus:Pending"), value: MessageStatus.Pending, color: "warning" },
		{ label: $t("AppPlatform.MessageStatus:Sent"), value: MessageStatus.Sent, color: "success" },
		{ label: $t("AppPlatform.MessageStatus:Failed"), value: MessageStatus.Failed, color: "error" },
	];

	const columns: ProColumns<EmailMessageDto>[] = [
		{
			title: $t("AppPlatform.DisplayName:Provider"),
			dataIndex: "provider",
			width: 150,
			sorter: true,
		},
		{
			title: $t("AppPlatform.DisplayName:Status"),
			dataIndex: "status",
			width: 100,
			sorter: true,
			valueType: "select",
			fieldProps: {
				options: statusOptions,
			},
			render: (_, row) => {
				const option = statusOptions.find((o) => o.value === row.status);
				return <Tag color={option?.color}>{option?.label}</Tag>;
			},
		},
		{
			title: $t("AppPlatform.DisplayName:SendTime"),
			dataIndex: "sendTime",
			width: 180,
			sorter: true,
			valueType: "dateRange",
			render: (_, row) => formatToDateTime(row.sendTime),
		},
		{
			title: $t("AppPlatform.DisplayName:SendCount"),
			dataIndex: "sendCount",
			width: 100,
			sorter: true,
			align: "center",
			hideInSearch: true,
		},
		{
			title: $t("AppPlatform.DisplayName:Subject"),
			dataIndex: "subject",
			width: 200,
			sorter: true,
			ellipsis: true,
			hideInSearch: true,
		},
		{
			title: $t("AppPlatform.DisplayName:Content"),
			dataIndex: "content",
			width: 200,
			sorter: true,
			ellipsis: true,
			hideInSearch: true,
		},
		{
			title: $t("AppPlatform.DisplayName:From"),
			dataIndex: "from",
			width: 200,
			sorter: true,
			hideInSearch: true,
		},
		{
			title: $t("AppPlatform.DisplayName:Receiver"),
			dataIndex: "emailAddress", // Search field name is usually mapped to 'emailAddress' in input
			render: (_, row) => row.receiver,
			width: 200,
			sorter: true,
		},
		{
			title: $t("AppPlatform.DisplayName:CreationTime"),
			dataIndex: "creationTime",
			width: 180,
			sorter: true,
			valueType: "date",
			hideInSearch: true,
			render: (_, row) => formatToDateTime(row.creationTime),
		},
		{
			title: $t("AppPlatform.DisplayName:Reason"),
			dataIndex: "reason",
			width: 150,
			sorter: true,
			ellipsis: true,
			hideInSearch: true,
		},
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("AbpUi.Actions"),
			valueType: "option",
			fixed: "right",
			width: 220,
			render: (_, record) => (
				<Space>
					{/* Reuse Edit icon for 'View Content' to match Vue 'onUpdate' behavior which opens modal */}
					<Button type="link" icon={<EditOutlined />} onClick={() => handleViewContent(record)}>
						{$t("AbpUi.Edit")}
					</Button>

					{withAccessChecker(
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>,
						[EmailMessagesPermissions.Delete],
					)}

					<Dropdown
						menu={{
							items: [
								hasAccessByCodes([EmailMessagesPermissions.SendMessage])
									? {
											key: "send",
											label: $t("AppPlatform.SendMessage"),
											icon: <SendOutlined className="text-green-500" />,
											onClick: () => handleSend(record),
										}
									: null,
							].filter(Boolean) as any,
						}}
					>
						<Button type="link" icon={<EllipsisOutlined />} />
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<EmailMessageDto>
					headerTitle={$t("AppPlatform.EmailMessages")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					search={{ labelWidth: "auto", defaultCollapsed: true }}
					request={async (params, sorter) => {
						const { current, pageSize, sendTime, ...filters } = params;
						const [beginSendTime, endSendTime] = sendTime || [];

						const sorting =
							sorter && Object.keys(sorter).length > 0
								? Object.keys(sorter)
										.map((key) => `${key} ${antdOrderToAbpOrder(sorter[key])}`)
										.join(", ")
								: undefined;

						const query = await queryClient.fetchQuery({
							queryKey: ["emailMessages", params, sorter],
							queryFn: () =>
								getPagedListApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									sorting: sorting,
									beginSendTime,
									endSendTime,
									...filters,
								}),
						});

						return {
							data: query.items,
							total: query.totalCount,
							success: true,
						};
					}}
					pagination={{ defaultPageSize: 10, showSizeChanger: true }}
					scroll={{ x: "max-content" }}
				/>
			</Card>
			<EmailMessageModal visible={modalVisible} content={selectedContent} onClose={() => setModalVisible(false)} />
		</>
	);
};

export default EmailMessageTable;

// apps/vben5/packages/@abp/platform/src/components/messages/email/EmailMessageTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { EmailMessageDto } from '../../../types/messages';

import { defineAsyncComponent, h } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal, Tag } from 'ant-design-vue';

import { useEmailMessagesApi } from '../../../api/useEmailMessagesApi';
import { EmailMessagesPermissions } from '../../../constants/permissions';
import { MessageStatus } from '../../../types/messages';

defineOptions({
  name: 'EmailMessageTable',
});

const MenuItem = Menu.Item;
const SendMessageIcon = createIconifyIcon('ant-design:send-outlined');

const { hasAccessByCodes } = useAccess();
const { deleteApi, getPagedListApi, sendApi } = useEmailMessagesApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: true,
  collapsedRows: 2,
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 在label后显示一个冒号
    colon: true,
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  fieldMappingTime: [
    ['sendTime', ['beginSendTime', 'endSendTime'], 'YYYY-MM-DD'],
  ],
  schema: [
    {
      component: 'Select',
      componentProps: {
        options: [
          {
            label: $t('AppPlatform.MessageStatus:Pending'),
            value: MessageStatus.Pending,
          },
          {
            label: $t('AppPlatform.MessageStatus:Sent'),
            value: MessageStatus.Sent,
          },
          {
            label: $t('AppPlatform.MessageStatus:Failed'),
            value: MessageStatus.Failed,
          },
        ],
      },
      fieldName: 'status',
      label: $t('AppPlatform.DisplayName:Status'),
    },
    {
      component: 'Input',
      fieldName: 'emailAddress',
      label: $t('AppPlatform.DisplayName:Receiver'),
    },
    {
      component: 'RangePicker',
      fieldName: 'sendTime',
      label: $t('AppPlatform.DisplayName:SendTime'),
    },
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<EmailMessageDto> = {
  columns: [
    {
      align: 'left',
      field: 'provider',
      minWidth: 180,
      sortable: true,
      title: $t('AppPlatform.DisplayName:Provider'),
    },
    {
      align: 'left',
      field: 'status',
      minWidth: 150,
      slots: { default: 'status' },
      sortable: true,
      title: $t('AppPlatform.DisplayName:Status'),
    },
    {
      align: 'left',
      field: 'sendTime',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      minWidth: 150,
      sortable: true,
      title: $t('AppPlatform.DisplayName:SendTime'),
    },
    {
      align: 'center',
      field: 'sendCount',
      minWidth: 100,
      sortable: true,
      title: $t('AppPlatform.DisplayName:SendCount'),
    },
    {
      align: 'left',
      field: 'subject',
      minWidth: 180,
      sortable: true,
      title: $t('AppPlatform.DisplayName:Subject'),
    },
    {
      align: 'left',
      field: 'content',
      minWidth: 220,
      sortable: true,
      title: $t('AppPlatform.DisplayName:Content'),
    },
    {
      align: 'left',
      field: 'from',
      minWidth: 220,
      sortable: true,
      title: $t('AppPlatform.DisplayName:From'),
    },
    {
      align: 'left',
      field: 'receiver',
      minWidth: 150,
      sortable: true,
      title: $t('AppPlatform.DisplayName:Receiver'),
    },
    {
      align: 'left',
      field: 'creationTime',
      formatter: ({ cellValue }) => {
        return cellValue ? formatToDateTime(cellValue) : cellValue;
      },
      minWidth: 200,
      sortable: true,
      title: $t('AppPlatform.DisplayName:CreationTime'),
    },
    {
      align: 'left',
      field: 'reason',
      minWidth: 150,
      sortable: true,
      title: $t('AppPlatform.DisplayName:Reason'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      visible: hasAccessByCodes([EmailMessagesPermissions.Delete]),
      width: 220,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort }, formValues) => {
        const sorting = sort.order ? `${sort.field} ${sort.order}` : undefined;
        return await getPagedListApi({
          sorting,
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: {
      code: 'query',
    },
    zoom: true,
  },
};
const gridEvents: VxeGridListeners<EmailMessageDto> = {
  sortChange: () => {
    gridApi.query();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridOptions,
  gridEvents,
});

const [EmailMessageModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./EmailMessageModal.vue'),
  ),
});

function onUpdate(row: EmailMessageDto) {
  // console.warn('onUpdate is not implementation!', row);
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: EmailMessageDto) {
  Modal.confirm({
    afterClose: () => {
      gridApi.setLoading(false);
    },
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessage')}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await deleteApi(row.id);
        message.success($t('AbpUi.DeletedSuccessfully'));
        gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

async function onSend(row: EmailMessageDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AppPlatform.MessageWillBeReSendWarningMessage')}`,
    onOk: async () => {
      try {
        gridApi.setLoading(true);
        await sendApi(row.id);
        message.success($t('AppPlatform.SuccessfullySent'));
        gridApi.query();
      } finally {
        gridApi.setLoading(false);
      }
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
async function onMenuClick(row: EmailMessageDto, info: MenuInfo) {
  switch (info.key) {
    case 'send': {
      await onSend(row);
    }
  }
}
</script>

<template>
  <Grid :table-title="$t('AppPlatform.EmailMessages')">
    <template #status="{ row }">
      <Tag v-if="row.status === MessageStatus.Pending" color="warning">
        {{ $t('AppPlatform.MessageStatus:Pending') }}
      </Tag>
      <Tag v-else-if="row.status === MessageStatus.Sent" color="success">
        {{ $t('AppPlatform.MessageStatus:Sent') }}
      </Tag>
      <Tag v-else-if="row.status === MessageStatus.Failed" color="error">
        {{ $t('AppPlatform.MessageStatus:Failed') }}
      </Tag>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(EditOutlined)"
          block
          type="link"
          @click="onUpdate(row)"
        >
          {{ $t('AbpUi.Edit') }}
        </Button>
        <Button
          :icon="h(DeleteOutlined)"
          block
          danger
          type="link"
          v-access:code="[EmailMessagesPermissions.Delete]"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onMenuClick(row, info)">
              <MenuItem
                v-if="hasAccessByCodes([EmailMessagesPermissions.SendMessage])"
                key="send"
              >
                <div class="flex flex-row items-center gap-[4px]">
                  <SendMessageIcon color="green" />
                  {{ $t('AppPlatform.SendMessage') }}
                </div>
              </MenuItem>
            </Menu>
          </template>
          <Button :icon="h(EllipsisOutlined)" type="link" />
        </Dropdown>
      </div>
    </template>
  </Grid>
  <EmailMessageModal />
</template>

<style lang="scss" scoped></style>
