// apps/react-admin/src/pages/openiddict/applications/application-modal.tsx
import { useEffect, useState } from "react";
import { Form, Input, Modal, Select, Tabs, InputNumber, Checkbox, Transfer, Dropdown } from "antd";
import { DownOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import type { OpenIddictApplicationDto, OpenIddictApplicationUpdateDto } from "#/openiddict/applications";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createApi, getApi, updateApi } from "@/api/openiddict/applications";
import { discoveryApi } from "@/api/openiddict/open-id";
import type { DisplayNameInfo } from "@/components/abp/display-names/types";
import type { PropertyInfo } from "@/components/abp/properties/types";
import DisplayNameTable from "@/components/abp/display-names/display-name-table";
import PropertyTable from "@/components/abp/properties/property-table";
import UriTable from "./uri-table";
import { toast } from "sonner";
import { mergeDeepRight } from "ramda";
import { CircleLoading } from "@/components/loading";

interface Props {
	visible: boolean;
	applicationId?: string;
	onClose: () => void;
	onChange: (data: OpenIddictApplicationDto) => void;
}

type TabKeys = "basic" | "displayName" | "endpoint" | "tokens" | "scope" | "authorize" | "props";

const defaultModel = {
	clientId: "",
	applicationType: "web",
	clientType: "public",
	consentType: "explicit",
	requirements: {
		features: {
			requirePkce: false,
		},
	},
	extraProperties: {},
	settings: {
		tokenLifetime: {
			accessToken: 3600,
			authorizationCode: 600,
			identityToken: 3600,
			refreshToken: 86400,
			deviceCode: 600,
			userCode: 600,
		},
	},
};

const clientTypes = [
	{ label: "public", value: "public" },
	{ label: "confidential", value: "confidential" },
];

const applicationTypes = [
	{ label: "Web", value: "web" },
	{ label: "Native", value: "native" },
];

const consentTypes = [
	{ label: "explicit", value: "explicit" },
	{ label: "external", value: "external" },
	{ label: "implicit", value: "implicit" },
	{ label: "systematic", value: "systematic" },
];

const endpoints = [
	{ label: "authorization", value: "authorization" },
	{ label: "token", value: "token" },
	{ label: "logout", value: "logout" },
	{ label: "device", value: "device" },
	{ label: "revocation", value: "revocation" },
	{ label: "introspection", value: "introspection" },
];

// Token Tabs 相关表单配置
const tokenFormItems = [
	{
		name: ["settings", "tokenLifetime", "accessToken"],
		label: "AbpOpenIddict.DisplayName:AccessTokenLifetime",
		extra: "AbpOpenIddict.Description:AccessTokenLifetime",
		min: 300,
	},
	{
		name: ["settings", "tokenLifetime", "authorizationCode"],
		label: "AbpOpenIddict.DisplayName:AuthorizationCodeLifetime",
		extra: "AbpOpenIddict.Description:AuthorizationCodeLifetime",
		min: 300,
	},
	{
		name: ["settings", "tokenLifetime", "identityToken"],
		label: "AbpOpenIddict.DisplayName:IdentityTokenLifetime",
		extra: "AbpOpenIddict.Description:IdentityTokenLifetime",
		min: 300,
	},
	{
		name: ["settings", "tokenLifetime", "refreshToken"],
		label: "AbpOpenIddict.DisplayName:RefreshTokenLifetime",
		extra: "AbpOpenIddict.Description:RefreshTokenLifetime",
		min: 300,
	},
	{
		name: ["settings", "tokenLifetime", "deviceCode"],
		label: "AbpOpenIddict.DisplayName:DeviceCodeLifetime",
		extra: "AbpOpenIddict.Description:DeviceCodeLifetime",
		min: 300,
	},
	{
		name: ["settings", "tokenLifetime", "userCode"],
		label: "AbpOpenIddict.DisplayName:UserCodeLifetime",
		extra: "AbpOpenIddict.Description:UserCodeLifetime",
		min: 300,
	},
];

const ApplicationModal: React.FC<Props> = ({ visible, applicationId, onClose, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const queryClient = useQueryClient();
	const [activeTab, setActiveTab] = useState<TabKeys>("basic");
	const [formModel, setFormModel] = useState<OpenIddictApplicationUpdateDto>(defaultModel);
	const [uriState, setUriState] = useState({
		component: "RedirectUris",
	});

	// Fetch OpenID configuration
	const { data: openIdConfig } = useQuery({
		queryKey: ["openid-configuration"],
		queryFn: discoveryApi,
		enabled: visible,
	});

	const { data: applicationData, isLoading } = useQuery({
		queryKey: ["applicationId", applicationId],
		queryFn: () => {
			if (!applicationId) {
				return Promise.reject(new Error("applicationId is undefined"));
			}
			return getApi(applicationId);
		},
		enabled: !!applicationId && visible,
	});

	useEffect(() => {
		if (applicationData) {
			if (applicationData.id === applicationId) {
				setFormModel(applicationData); //将OpenIddictApplicationDto 转到 OpenIddictApplicationUpdateDto,注意这里的特殊，formModal的展示值和最后的请求值数据结构非常相似
				form.setFieldsValue(applicationData);
			}
		}
	}, [applicationData]);

	useEffect(() => {
		if (visible) {
			setActiveTab("basic");
		}
	}, [visible]);

	// Create/Update mutations
	const { mutateAsync: createApplication } = useMutation({
		mutationFn: createApi,
		onSuccess: (data) => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(data);
			onClose();
		},
	});

	const { mutateAsync: updateApplication } = useMutation({
		mutationFn: ({ id, input }: { id: string; input: OpenIddictApplicationUpdateDto }) => updateApi(id, input),
		onSuccess: (data) => {
			queryClient.invalidateQueries({ queryKey: ["applicationId", applicationId] });
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(data);
			onClose();
		},
	});

	const handleDisplayNameChange = (displayName: DisplayNameInfo) => {
		setFormModel((prev) => ({
			...prev,
			displayNames: {
				...prev.displayNames,
				[displayName.culture]: displayName.displayName,
			},
		}));
	};

	const handleDisplayNameDelete = (displayName: DisplayNameInfo) => {
		setFormModel((prev) => {
			const newDisplayNames = { ...prev.displayNames };
			delete newDisplayNames[displayName.culture];
			return {
				...prev,
				displayNames: newDisplayNames,
			};
		});
	};

	const handleUriChange = (uri: string) => {
		const fieldName = uriState.component === "RedirectUris" ? "redirectUris" : "postLogoutRedirectUris";

		setFormModel((prev) => ({
			...prev,
			[fieldName]: [...(prev[fieldName] || []), uri],
		}));
	};

	const handleUriDelete = (uri: string) => {
		const fieldName = uriState.component === "RedirectUris" ? "redirectUris" : "postLogoutRedirectUris";

		setFormModel((prev) => ({
			...prev,
			[fieldName]: (prev[fieldName] || []).filter((u) => u !== uri),
		}));
	};

	const handlePropertyChange = (prop: PropertyInfo) => {
		setFormModel((prev) => ({
			...prev,
			properties: {
				...prev.properties,
				[prop.key]: prop.value,
			},
		}));
	};

	const handlePropertyDelete = (prop: PropertyInfo) => {
		setFormModel((prev) => {
			const newProperties = { ...prev.properties };
			delete newProperties[prop.key];
			return {
				...prev,
				properties: newProperties,
			};
		});
	};

	const handleSubmit = async () => {
		try {
			await form.validateFields();
			if (applicationId) {
				await updateApplication({ id: applicationId, input: formModel });
			} else {
				await createApplication(formModel);
			}
		} catch (error) {
			console.error("Validation failed:", error);
		}
	};

	return (
		<Modal
			open={visible}
			title={
				applicationId
					? `${$t("AbpOpenIddict.Applications")} - ${formModel.clientId || ""}`
					: $t("AbpOpenIddict.Applications:AddNew")
			}
			onCancel={() => {
				onClose();
				form.resetFields();
				setFormModel(defaultModel);
				form.setFieldsValue(defaultModel); //两个同时设置，保持没有applicationId时，handleSubmit调用createApplication时的表单状态和请求数据一致
			}}
			onOk={handleSubmit}
			onClose={() => {
				onClose();
				form.resetFields();
				setFormModel(defaultModel);
				form.resetFields();
			}}
			width="50%"
			destroyOnClose
		>
			{!!applicationId && visible && isLoading ? (
				<CircleLoading />
			) : (
				<Form
					form={form}
					layout="horizontal"
					labelCol={{ span: 6 }}
					wrapperCol={{ span: 18 }}
					onValuesChange={(changedValues) => {
						setFormModel((prevModel) => {
							return mergeDeepRight(prevModel, changedValues);
						});
					}}
				>
					<Tabs activeKey={activeTab} onChange={(key) => setActiveTab(key as TabKeys)}>
						{/* Basic Info Tab */}
						<Tabs.TabPane key="basic" tab={$t("AbpOpenIddict.BasicInfo")}>
							<Form.Item
								label={$t("AbpOpenIddict.DisplayName:ApplicationType")}
								name="applicationType"
								rules={[{ required: true }]}
							>
								<Select options={applicationTypes} />
							</Form.Item>
							<Form.Item label={$t("AbpOpenIddict.DisplayName:ClientId")} name="clientId" rules={[{ required: true }]}>
								<Input autoComplete="off" />
							</Form.Item>
							<Form.Item label={$t("AbpOpenIddict.DisplayName:ClientType")} name="clientType">
								<Select options={clientTypes} />
							</Form.Item>
							{!applicationId && (
								<Form.Item
									label={$t("AbpOpenIddict.DisplayName:ClientSecret")}
									name="clientSecret"
									rules={[{ required: form.getFieldValue("clientType") === "confidential" }]}
								>
									<Input.Password autoComplete="off" />
								</Form.Item>
							)}
							<Form.Item label={$t("AbpOpenIddict.DisplayName:ClientUri")} name="clientUri">
								<Input />
							</Form.Item>
							<Form.Item label={$t("AbpOpenIddict.DisplayName:LogoUri")} name="logoUri">
								<Input autoComplete="off" />
							</Form.Item>
							<Form.Item
								label={$t("AbpOpenIddict.DisplayName:ConsentType")}
								name="consentType"
								labelCol={{ span: 4 }}
								wrapperCol={{ span: 20 }}
								initialValue={formModel.consentType}
							>
								<Select options={consentTypes} />
							</Form.Item>
						</Tabs.TabPane>

						{/* Display Names Tab */}
						<Tabs.TabPane key="displayName" tab={$t("AbpOpenIddict.DisplayNames")}>
							<Form.Item
								label={$t("AbpOpenIddict.DisplayName:DefaultDisplayName")}
								name="displayName"
								initialValue={formModel.displayName}
							>
								<Input autoComplete="off" />
							</Form.Item>

							<DisplayNameTable
								data={formModel.displayNames}
								onChange={handleDisplayNameChange}
								onDelete={handleDisplayNameDelete}
							/>
						</Tabs.TabPane>

						{/* Endpoints Tab */}
						<Tabs.TabPane
							key="endpoint"
							tab={
								<Dropdown
									menu={{
										onClick: ({ key }) => {
											setActiveTab("endpoint");
											setUriState({
												component: key as string,
											});
										},
										items: [
											{
												key: "RedirectUris",
												label: $t("AbpOpenIddict.DisplayName:RedirectUris"),
											},
											{
												key: "PostLogoutRedirectUris",
												label: $t("AbpOpenIddict.DisplayName:PostLogoutRedirectUris"),
											},
										].filter(Boolean),
									}}
								>
									<span>
										{$t("AbpOpenIddict.Endpoints")} <DownOutlined />
									</span>
								</Dropdown>
							}
						>
							<UriTable
								title={$t(
									uriState.component === "RedirectUris"
										? "AbpOpenIddict.DisplayName:RedirectUris"
										: "AbpOpenIddict.DisplayName:PostLogoutRedirectUris",
								)}
								uris={uriState.component === "RedirectUris" ? formModel.redirectUris : formModel.postLogoutRedirectUris}
								onChange={handleUriChange}
								onDelete={handleUriDelete}
							/>
						</Tabs.TabPane>

						{/* Tokens Tab  //！！！注意这个name的数组语法赋值*/}
						<Tabs.TabPane key="tokens" tab={$t("AbpOpenIddict.Tokens")}>
							{tokenFormItems.map((item) => (
								<Form.Item key={item.name.join(".")} label={$t(item.label)} name={item.name} extra={$t(item.extra)}>
									<InputNumber className="w-full" min={item.min} />
								</Form.Item>
							))}
						</Tabs.TabPane>

						{/* Scopes Tab */}
						<Tabs.TabPane key="scope" tab={$t("AbpOpenIddict.Scopes")}>
							<Transfer
								dataSource={openIdConfig?.scopes_supported?.map((scope) => ({
									key: scope,
									title: scope,
								}))}
								targetKeys={formModel.scopes || []}
								onChange={(targetKeys) => {
									const stringTargetKeys = targetKeys.map(String); // 转换成 string[]
									setFormModel((prev) => ({
										...prev,
										scopes: stringTargetKeys,
									}));
								}}
								render={(item) => item.title}
								listStyle={{
									width: "47%",
									height: "338px",
								}}
								titles={[$t("AbpOpenIddict.Assigned"), $t("AbpOpenIddict.Available")]}
							/>
						</Tabs.TabPane>

						{/* Authorization Tab */}
						<Tabs.TabPane key="authorize" tab={$t("AbpOpenIddict.Authorizations")}>
							<Form.Item
								label={$t("AbpOpenIddict.Requirements:PKCE")}
								name={["requirements", "features", "requirePkce"]} //antd数组赋值语法
								valuePropName="checked"
							>
								<Checkbox checked={formModel.requirements?.features.requirePkce}>
									{$t("AbpOpenIddict.Requirements:PKCE")}
								</Checkbox>
							</Form.Item>
							<Form.Item
								label={$t("AbpOpenIddict.DisplayName:Endpoints")}
								name="endpoints"
								labelCol={{ span: 4 }}
								wrapperCol={{ span: 20 }}
							>
								<Select mode="tags" options={endpoints} />
							</Form.Item>
							<Form.Item
								label={$t("AbpOpenIddict.DisplayName:GrantTypes")}
								name="grantTypes"
								labelCol={{ span: 4 }}
								wrapperCol={{ span: 20 }}
							>
								<Select
									mode="tags"
									options={openIdConfig?.grant_types_supported?.map((type) => ({
										label: type,
										value: type,
									}))}
								/>
							</Form.Item>
							<Form.Item
								label={$t("AbpOpenIddict.DisplayName:ResponseTypes")}
								name="responseTypes"
								labelCol={{ span: 4 }}
								wrapperCol={{ span: 20 }}
							>
								<Select
									mode="tags"
									options={openIdConfig?.response_types_supported?.map((type) => ({
										label: type,
										value: type,
									}))}
								/>
							</Form.Item>
						</Tabs.TabPane>

						{/* Properties Tab */}
						<Tabs.TabPane key="props" tab={$t("AbpOpenIddict.DisplayName:Properties")}>
							<PropertyTable //openiddict的自带Properties,不是abp的ExtraProperties,但还是用这个组件
								data={formModel.properties}
								onChange={handlePropertyChange}
								onDelete={handlePropertyDelete}
							/>
						</Tabs.TabPane>
					</Tabs>
				</Form>
			)}
		</Modal>
	);
};

export default ApplicationModal;

// apps/vue/src/views/openiddict/applications/components/ApplicationModal.vue
<template>
  <BasicModal
    @register="registerModal"
    :title="L('Applications')"
    :can-fullscreen="false"
    :width="800"
    :height="500"
    :close-func="handleBeforeClose"
    @ok="handleSubmit"
  >
    <Form
      ref="formRef"
      :model="state.application"
      :rules="state.formRules"
      :label-col="{ span: 6 }"
      :wrapper-col="{ span: 18 }"
    >
      <Tabs v-model:active-key="state.activeTab" @change="handleTabChange">
        <!-- Basic -->
        <TabPane key="basic" :tab="L('BasicInfo')">
          <FormItem name="applicationType" :label="L('DisplayName:ApplicationType')">
            <Select
              default-value="web"
              :options="applicationTypes"
              v-model:value="state.application.applicationType"
            />
          </FormItem>
          <FormItem name="clientId" :label="L('DisplayName:ClientId')">
            <Input :disabled="state.isEdit" v-model:value="state.application.clientId" />
          </FormItem>
          <FormItem name="clientType" :label="L('DisplayName:ClientType')">
            <Select
              :disabled="state.isEdit"
              default-value="public"
              :options="clientTypes"
              v-model:value="state.application.clientType"
            />
          </FormItem>
          <FormItem v-if="getShowSecret" name="clientSecret" :label="L('DisplayName:ClientSecret')">
            <Input v-model:value="state.application.clientSecret" />
          </FormItem>
          <FormItem name="clientUri" :label="L('DisplayName:ClientUri')">
            <Input v-model:value="state.application.clientUri" />
          </FormItem>
          <FormItem name="logoUri" :label="L('DisplayName:LogoUri')">
            <Input v-model:value="state.application.logoUri" />
          </FormItem>
          <FormItem
            name="consentType"
            :label="L('DisplayName:ConsentType')"
            :label-col="{ span: 4 }"
            :wrapper-col="{ span: 20 }"
          >
            <Select
              :options="consentTypes"
              default-value="explicit"
              v-model:value="state.application.consentType"
            />
          </FormItem>
        </TabPane>
        <!-- DisplayName -->
        <TabPane key="displayName" :tab="L('DisplayNames')">
          <FormItem name="displayName" :label="L('DisplayName:DefaultDisplayName')">
            <Input v-model:value="state.application.displayName" />
          </FormItem>
          <DisplayNameForm
            :displayNames="state.application.displayNames"
            @create="handleNewDisplayName"
            @delete="handleDelDisplayName"
          />
        </TabPane>
        <!-- Endpoints -->
        <TabPane key="endpoints">
          <template #tab>
            <Dropdown>
              <span
                >{{ L('Endpoints') }}
                <DownOutlined />
              </span>
              <template #overlay>
                <Menu @click="handleClickUrisMenu">
                  <MenuItem key="redirectUris">
                    {{ L('DisplayName:RedirectUris') }}
                  </MenuItem>
                  <MenuItem key="postLogoutRedirectUris">
                    {{ L('DisplayName:PostLogoutRedirectUris') }}
                  </MenuItem>
                </Menu>
              </template>
            </Dropdown>
          </template>
          <component
            :is="componentsRef[state.endPoint.component]"
            :uris="state.endPoint.uris"
            @create-redirect-uri="handleNewRedirectUri"
            @delete-redirect-uri="handleDelRedirectUri"
            @create-logout-uri="handleNewLogoutUri"
            @delete-logout-uri="handleDelLogoutUri"
          />
        </TabPane>
        <!-- Scopes -->
        <TabPane key="permissions" :tab="L('Scopes')">
          <ApplicationScope
            :scopes="state.application.scopes"
            :support-scopes="state.openIdConfiguration?.scopes_supported"
            @create="handleNewScope"
            @delete="handleDelScope"
          />
        </TabPane>
        <!-- Authorizations -->
        <TabPane key="authorizations" :tab="L('Authorizations')">
          <FormItem
            name="endpoints"
            :label="L('DisplayName:Endpoints')"
            :label-col="{ span: 4 }"
            :wrapper-col="{ span: 20 }"
          >
            <Select :options="endpoints" mode="tags" v-model:value="state.application.endpoints" />
          </FormItem>
          <FormItem
            name="grantTypes"
            :label="L('DisplayName:GrantTypes')"
            :label-col="{ span: 4 }"
            :wrapper-col="{ span: 20 }"
          >
            <Select
              :options="grantTypes"
              mode="tags"
              v-model:value="state.application.grantTypes"
            />
          </FormItem>
          <FormItem
            name="responseTypes"
            :label="L('DisplayName:ResponseTypes')"
            :label-col="{ span: 4 }"
            :wrapper-col="{ span: 20 }"
          >
            <Select
              :options="responseTypes"
              mode="tags"
              v-model:value="state.application.responseTypes"
            />
          </FormItem>
        </TabPane>
        <!-- Propertites -->
        <TabPane key="propertites" :tab="L('Propertites')">
          <PropertyForm
            :properties="state.application.properties"
            @create="handleNewProperty"
            @delete="handleDelProperty"
          />
        </TabPane>
      </Tabs>
    </Form>
  </BasicModal>
</template>

<script lang="ts" setup>
  import type { FormInstance } from 'ant-design-vue/lib/form';
  import { cloneDeep } from 'lodash-es';
  import { computed, nextTick, ref, unref, reactive, shallowRef, onMounted, watch } from 'vue';
  import { DownOutlined } from '@ant-design/icons-vue';
  import { Dropdown, Form, Menu, Input, Select, Tabs } from 'ant-design-vue';
  import { BasicModal, useModalInner } from '/@/components/Modal';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useValidation } from '/@/hooks/abp/useValidation';
  import { useLocalization } from '/@/hooks/abp/useLocalization';
  import { ApplicationState } from '../types/props';
  import { get, create, update} from '/@/api/openiddict/open-iddict-application';
  import { OpenIddictApplicationDto } from '/@/api/openiddict/open-iddict-application/model';
  import { discovery } from '/@/api/identity-server/discovery';
  import RedirectUri from './RedirectUri.vue';
  import PostLogoutRedirectUri from './PostLogoutRedirectUri.vue';
  import DisplayNameForm from '../../components/DisplayNames/DisplayNameForm.vue';
  import ApplicationScope from './ApplicationScope.vue';
  import PropertyForm from '../../components/Properties/PropertyForm.vue';

  const FormItem = Form.Item;
  const TabPane = Tabs.TabPane;
  const MenuItem = Menu.Item;

  const emits = defineEmits(['register', 'change']);
  const { L } = useLocalization(['AbpOpenIddict', 'AbpUi']);
  const { ruleCreator } = useValidation();
  const { createMessage, createConfirm } = useMessage();
  const componentsRef = shallowRef({
    redirectUris: RedirectUri,
    postLogoutRedirectUris: PostLogoutRedirectUri,
  });
  const formRef = ref<FormInstance>();
  const state = reactive<ApplicationState>({
    activeTab: 'basic',
    isEdit: false,
    entityChanged: false,
    application: {} as OpenIddictApplicationDto,
    formRules: {
      clientId: ruleCreator.fieldRequired({
        name: 'ClientId',
        prefix: 'DisplayName',
        resourceName: 'AbpOpenIddict',
        trigger: 'blur',
      }),
      clientSecret: ruleCreator.fieldRequired({
        name: 'ClientSecret',
        prefix: 'DisplayName',
        resourceName: 'AbpOpenIddict',
        trigger: 'blur',
      }),
      displayName: ruleCreator.fieldRequired({
        name: 'DisplayName',
        prefix: 'DisplayName',
        resourceName: 'AbpOpenIddict',
        trigger: 'blur',
      }),
    },
    endPoint: {
      component: '',
      uris: [],
    },
  });
  watch(
    () => state.application,
    () => {
      state.entityChanged = true;
    },
    {
      deep: true,
    },
  );
  const clientTypes = reactive([
    { label: 'public', value: 'public' },
    { label: 'confidential', value: 'confidential' },
  ]);
  const applicationTypes = reactive([
    { label: 'Web', value: 'web' },
    { label: 'Native', value: 'native' },
  ]);
  const consentTypes = reactive([
    { label: 'explicit', value: 'explicit' },
    { label: 'external', value: 'external' },
    { label: 'implicit', value: 'implicit' },
    { label: 'systematic', value: 'systematic' },
  ]);
  const endpoints = reactive([
    { label: 'authorization', value: 'authorization' },
    { label: 'token', value: 'token' },
    { label: 'logout', value: 'logout' },
    { label: 'device', value: 'device' },
    { label: 'revocation', value: 'revocation' },
    { label: 'introspection', value: 'introspection' },
  ]);
  const getShowSecret = computed(() => {
    return !state.isEdit && state.application.clientType === 'confidential';
  });
  const grantTypes = computed(() => {
    if (!state.openIdConfiguration) return [];
    const types = state.openIdConfiguration.grant_types_supported;
    return types.map((type) => {
      return {
        label: type,
        value: type,
      };
    });
  });
  const responseTypes = computed(() => {
    if (!state.openIdConfiguration) return [];
    const types = state.openIdConfiguration.response_types_supported;
    return types.map((type) => {
      return {
        label: type,
        value: type,
      };
    });
  });

  const [registerModal, { changeLoading, changeOkLoading, closeModal }] = useModalInner((data) => {
    nextTick(() => {
      fetch(data?.id);
    });
  });

  onMounted(initOpenidDiscovery);

  function initOpenidDiscovery() {
    discovery().then((openIdConfiuration) => {
      state.openIdConfiguration = openIdConfiuration;
    });
  }

  function fetch(id?: string) {
    state.activeTab = 'basic';
    state.isEdit = false;
    state.entityChanged = false;
    state.application = {} as OpenIddictApplicationDto;
    const form = unref(formRef);
    form?.resetFields();
    if (!id) {
      nextTick(() => {
        state.isEdit = false;
        state.entityChanged = false;
      });
      return;
    }
    changeLoading(true);
    get(id)
      .then((application) => {
        state.application = application;
        nextTick(() => {
          state.isEdit = true;
          state.entityChanged = false;
        });
      })
      .finally(() => {
        changeLoading(false);
      });
  }

  function handleTabChange(activeKey) {
    state.activeTab = activeKey;
    switch (activeKey) {
      case 'endpoints':
        if (!state.endPoint.component) {
          state.endPoint = {
            component: 'redirectUris',
            uris: state.application?.redirectUris,
          };
        }
        break;
    }
  }

  function handleNewLogoutUri(uri: string) {
    if (!state.application) {
      return;
    }
    state.application.postLogoutRedirectUris ??= [];
    state.application.postLogoutRedirectUris.push(uri);
  }

  function handleDelLogoutUri(uri: string) {
    if (!state.application || !state.application.postLogoutRedirectUris) {
      return;
    }
    const index = state.application.postLogoutRedirectUris.findIndex(
      (logoutUri) => logoutUri === uri,
    );
    index && state.application.postLogoutRedirectUris.splice(index);
  }

  function handleNewRedirectUri(uri: string) {
    if (!state.application) {
      return;
    }
    state.application.redirectUris ??= [];
    state.application.redirectUris.push(uri);
  }

  function handleDelRedirectUri(uri: string) {
    if (!state.application || !state.application.redirectUris) {
      return;
    }
    const index = state.application.redirectUris.findIndex((redirectUri) => redirectUri === uri);
    index && state.application.redirectUris.splice(index);
  }

  function handleNewDisplayName(record) {
    if (!state.application) {
      return;
    }
    state.application.displayNames ??= {};
    state.application.displayNames[record.culture] = record.displayName;
  }

  function handleDelDisplayName(record) {
    if (!state.application || !state.application.displayNames) {
      return;
    }
    delete state.application.displayNames[record.culture];
  }

  function handleNewProperty(record) {
    if (!state.application) {
      return;
    }
    state.application.properties ??= {};
    state.application.properties[record.key] = record.value;
  }

  function handleDelProperty(record) {
    if (!state.application || !state.application.properties) {
      return;
    }
    delete state.application.properties[record.key];
  }

  function handleNewScope(scopes: string[]) {
    if (!state.application) {
      return;
    }
    state.application.scopes ??= [];
    state.application.scopes.push(...scopes);
  }

  function handleDelScope(scopes: string[]) {
    if (!state.application || !state.application.scopes) {
      return;
    }
    state.application.scopes = state.application.scopes.filter((scope) => !scopes.includes(scope));
  }

  function handleClickUrisMenu(e) {
    state.endPoint = {
      component: e.key,
      uris: state.application[e.key],
    };
    state.activeTab = 'endpoints';
  }

  function handleBeforeClose(): Promise<boolean> {
    return new Promise((resolve) => {
      if (!state.entityChanged) {
        const form = unref(formRef);
        form?.resetFields();
        return resolve(true);
      }
      createConfirm({
        iconType: 'warning',
        title: L('AreYouSure'),
        content: L('AreYouSureYouWantToCancelEditingWarningMessage'),
        onOk: () => {
          const form = unref(formRef);
          form?.resetFields();
          resolve(true);
        },
        onCancel: () => {
          resolve(false);
        },
      });
    });
  }

  function handleSubmit() {
    const form = unref(formRef);
    form?.validate().then(() => {
      changeOkLoading(true);
      const api = state.application.id
        ? update(state.application.id, cloneDeep(state.application))
        : create(cloneDeep(state.application));
      api
        .then((res) => {
          createMessage.success(L('Successful'));
          emits('change', res);
          closeModal();
        })
        .finally(() => {
          changeOkLoading(false);
        });
    });
  }
</script>
