// apps/vben5/packages/@abp/identity/src/components/claim-types/ClaimTypeModal.vue
<script setup lang="ts">
import type { FormInstance } from 'ant-design-vue';
import type { DefaultOptionType } from 'ant-design-vue/es/select';

import type { IdentityClaimTypeDto } from '../../types/claim-types';

import { defineEmits, defineOptions, reactive, ref, toValue } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  Checkbox,
  Form,
  Input,
  message,
  Select,
  Textarea,
} from 'ant-design-vue';

import { createApi, getApi, updateApi } from '../../api/claim-types';
import { ValueType } from '../../types/claim-types';

defineOptions({
  name: 'ClaimTypeModal',
});
const emits = defineEmits<{
  (event: 'change', data: IdentityClaimTypeDto): void;
}>();

const FormItem = Form.Item;

const defaultModel = {
  required: false,
} as IdentityClaimTypeDto;

const form = ref<FormInstance>();
const formModel = ref<IdentityClaimTypeDto>({ ...defaultModel });
const valueTypeOptions = reactive<DefaultOptionType[]>([
  {
    label: 'String',
    value: ValueType.String,
  },
  {
    label: 'Int',
    value: ValueType.Int,
  },
  {
    label: 'Boolean',
    value: ValueType.Boolean,
  },
  {
    label: 'DateTime',
    value: ValueType.DateTime,
  },
]);

const [Modal, modalApi] = useVbenModal({
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await form.value?.validate();
    const api = formModel.value.id
      ? updateApi(formModel.value.id, toValue(formModel))
      : createApi(toValue(formModel));
    modalApi.setState({ loading: true });
    api
      .then((res) => {
        message.success($t('AbpUi.Success'));
        emits('change', res);
        modalApi.close();
      })
      .finally(() => {
        modalApi.setState({ loading: false });
      });
  },
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      const { values } = modalApi.getData<Record<string, any>>();
      if (values?.id) {
        modalApi.setState({ loading: true });
        return getApi(values.id)
          .then((dto) => {
            formModel.value = dto;
            modalApi.setState({
              title: `${$t('AbpIdentity.DisplayName:ClaimType')} - ${dto.name}`,
            });
          })
          .finally(() => {
            modalApi.setState({ loading: false });
          });
      }
      formModel.value = { ...defaultModel };
      modalApi.setState({
        title: $t('AbpIdentity.IdentityClaim:New'),
      });
    }
  },
  title: 'ClaimType',
});
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <FormItem
        :label="$t('AbpIdentity.IdentityClaim:Name')"
        name="name"
        required
      >
        <Input v-model:value="formModel.name" />
      </FormItem>
      <FormItem :label="$t('AbpIdentity.IdentityClaim:Required')">
        <Checkbox v-model:checked="formModel.required">
          {{ $t('AbpIdentity.IdentityClaim:Required') }}
        </Checkbox>
      </FormItem>
      <FormItem :label="$t('AbpIdentity.IdentityClaim:Regex')">
        <Input v-model:value="formModel.regex" />
      </FormItem>
      <FormItem :label="$t('AbpIdentity.IdentityClaim:RegexDescription')">
        <Input v-model:value="formModel.regexDescription" />
      </FormItem>
      <FormItem :label="$t('AbpIdentity.IdentityClaim:ValueType')">
        <Select
          v-model:value="formModel.valueType"
          :options="valueTypeOptions"
        />
      </FormItem>
      <FormItem :label="$t('AbpIdentity.IdentityClaim:Description')">
        <Textarea
          v-model:value="formModel.description"
          :auto-size="{ minRows: 2 }"
        />
      </FormItem>
    </Form>
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/identity/claim-types/claim-type-modal.tsx
import type React from "react";
import { useEffect } from "react";
import { Button, Checkbox, Form, Input, Modal, Select, Space } from "antd";
import { toast } from "sonner";
import { useTranslation } from "react-i18next";
import { ValueType, type IdentityClaimTypeDto } from "#/management/identity";
import { createApi, updateApi } from "@/api/management/identity/claim-types";
import { useMutation } from "@tanstack/react-query";

interface Props {
	visible: boolean;
	onClose: () => void;
	onSuccess: () => void;
	claimType?: IdentityClaimTypeDto;
}

const ClaimTypeModal: React.FC<Props> = ({ visible, onClose, onSuccess, claimType }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm<IdentityClaimTypeDto>();

	const { mutateAsync: createClaimType, isPending: isCreating } = useMutation({
		mutationFn: createApi,
		onSuccess: () => {
			toast.success($t("AbpUi.CreatedSuccessfully"));
			onSuccess();
			onClose();
		},
		onError: () => {
			toast.error($t("AbpUi.Error"));
		},
	});

	const { mutateAsync: updateClaimType, isPending: isUpdating } = useMutation({
		mutationFn: ({ id, data }: { id: string; data: IdentityClaimTypeDto }) => updateApi(id, data),
		onSuccess: () => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			onSuccess();
			onClose();
		},
		onError: () => {
			toast.error($t("AbpUi.Error"));
		},
	});

	const handleSave = async () => {
		try {
			const values = await form.validateFields();
			if (claimType?.id) {
				await updateClaimType({ id: claimType.id, data: values });
			} else {
				await createClaimType(values);
			}
		} catch (error) {
			// Form validation error, no need to handle
		}
	};

	useEffect(() => {
		if (visible && claimType) {
			form.setFieldsValue(claimType);
		} else {
			form.resetFields();
		}
	}, [visible, claimType, form]);

	return (
		<Modal
			title={
				claimType?.id
					? `${$t("AbpIdentity.DisplayName:ClaimType")} - ${claimType.name}`
					: $t("AbpIdentity.IdentityClaim:New")
			}
			footer={null}
			open={visible}
			onCancel={onClose}
			destroyOnClose
			centered
			confirmLoading={isCreating || isUpdating}
		>
			<Form form={form} layout="vertical" initialValues={{ required: false }}>
				<Form.Item label={$t("AbpIdentity.IdentityClaim:Name")} name="name" rules={[{ required: true }]}>
					<Input />
				</Form.Item>
				<Form.Item label={$t("AbpIdentity.IdentityClaim:Required")} name="required" valuePropName="checked">
					<Checkbox>{$t("AbpIdentity.IdentityClaim:Required")}</Checkbox>
				</Form.Item>
				<Form.Item label={$t("AbpIdentity.IdentityClaim:Regex")} name="regex">
					<Input />
				</Form.Item>
				<Form.Item label={$t("AbpIdentity.IdentityClaim:RegexDescription")} name="regexDescription">
					<Input />
				</Form.Item>
				<Form.Item label={$t("AbpIdentity.IdentityClaim:ValueType")} name="valueType">
					<Select
						options={[
							{ label: "String", value: ValueType.String },
							{ label: "Int", value: ValueType.Int },
							{ label: "Boolean", value: ValueType.Boolean },
							{ label: "DateTime", value: ValueType.DateTime },
						]}
					/>
				</Form.Item>
				<Form.Item label={$t("AbpIdentity.IdentityClaim:Description")} name="description">
					<Input.TextArea />
				</Form.Item>
				<Form.Item>
					<Space style={{ display: "flex", justifyContent: "flex-end" }}>
						<Button onClick={onClose}>{$t("AbpUi.Cancel")}</Button>
						<Button type="primary" onClick={handleSave}>
							{$t("AbpUi.Save")}
						</Button>
					</Space>
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default ClaimTypeModal;
