// apps/vben5/packages/@abp/notifications/src/components/my-notifilers/MyNotificationTable.vue
<script setup lang="ts">
import type { VbenFormProps, VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { Notification } from '../../types/notifications';

import { h, ref } from 'vue';

import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import { formatToDateTime } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import { DeleteOutlined, DownOutlined } from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal } from 'ant-design-vue';

import { useMyNotifilersApi } from '../../api/useMyNotifilersApi';
import { useNotificationSerializer } from '../../hooks';
import {
  NotificationReadState,
  NotificationType,
} from '../../types/notifications';

defineOptions({
  name: 'MyNotificationTable',
});
const { cancel, deleteMyNotifilerApi, getMyNotifilersApi, markReadStateApi } =
  useMyNotifilersApi();

const { deserialize } = useNotificationSerializer();

const MenuItem = Menu.Item;

const ReadIcon = createIconifyIcon('ic:outline-mark-email-read');
const UnReadIcon = createIconifyIcon('ic:outline-mark-email-unread');
const BookMarkIcon = createIconifyIcon('material-symbols:bookmark-outline');

const selectedKeys = ref<string[]>([]);

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  schema: [
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        options: [
          {
            label: $t('Notifications.Read'),
            value: NotificationReadState.Read,
          },
          {
            label: $t('Notifications.UnRead'),
            value: NotificationReadState.UnRead,
          },
        ],
      },
      defaultValue: NotificationReadState.UnRead,
      fieldName: 'readState',
      label: $t('Notifications.Notifications:State'),
    },
    {
      component: 'Input',
      componentProps: {
        allowClear: true,
      },
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<Notification> = {
  columns: [
    {
      align: 'center',
      type: 'checkbox',
      width: 40,
    },
    {
      align: 'left',
      field: 'type',
      formatter({ cellValue }) {
        const type = cellValue as NotificationType;
        switch (type) {
          case NotificationType.Application: {
            return $t('Notifications.NotificationType:Application');
          }
          case NotificationType.ServiceCallback: {
            return $t('Notifications.NotificationType:ServiceCallback');
          }
          case NotificationType.System: {
            return $t('Notifications.NotificationType:System');
          }
          case NotificationType.User: {
            return $t('Notifications.NotificationType:User');
          }
        }
      },
      minWidth: 50,
      title: $t('Notifications.Notifications:Type'),
    },
    {
      align: 'left',
      field: 'creationTime',
      formatter({ cellValue }) {
        return cellValue ? formatToDateTime(cellValue) : '';
      },
      minWidth: 120,
      title: $t('Notifications.Notifications:SendTime'),
    },
    {
      align: 'left',
      field: 'title',
      minWidth: 150,
      slots: { default: 'title' },
      title: $t('Notifications.Notifications:Title'),
    },
    {
      align: 'left',
      field: 'message',
      minWidth: 120,
      slots: { default: 'message' },
      title: $t('Notifications.Notifications:Content'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 200,
    },
  ],
  exportConfig: {},
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        const { totalCount, items } = await getMyNotifilersApi({
          maxResultCount: page.pageSize,
          skipCount: (page.currentPage - 1) * page.pageSize,
          ...formValues,
        });
        return {
          totalCount,
          items: items.map((item) => {
            const notification = deserialize(item);
            return {
              ...notification,
              id: item.id,
              state: item.state,
            };
          }),
        };
      },
    },
    response: {
      total: 'totalCount',
      list: 'items',
    },
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<Notification> = {
  checkboxAll: (params) => {
    selectedKeys.value = params.records.map((record) => record.id);
  },
  checkboxChange: (params) => {
    selectedKeys.value = params.records.map((record) => record.id);
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

/** 点击行标记已读 */
async function onClickRead(row: Notification) {
  await _onRead([row.id], NotificationReadState.Read);
}

/** 行标记阅读状态 */
async function onRowRead(row: Notification, info: MenuInfo) {
  switch (info.key) {
    case 'read': {
      return await _onRead([row.id], NotificationReadState.Read);
    }
    case 'un-read': {
      return await _onRead([row.id], NotificationReadState.UnRead);
    }
  }
}

/** 批量标记阅读状态 */
async function onBulkRead(info: MenuInfo) {
  switch (info.key) {
    case 'read': {
      await _onRead(selectedKeys.value, NotificationReadState.Read);
      break;
    }
    case 'un-read': {
      await _onRead(selectedKeys.value, NotificationReadState.UnRead);
      break;
    }
  }
  selectedKeys.value = [];
}

async function _onRead(idList: string[], state: NotificationReadState) {
  try {
    gridApi.setLoading(true);
    await markReadStateApi({
      idList,
      state,
    });
    await gridApi.reload();
  } finally {
    gridApi.setLoading(false);
  }
}

const onDelete = (row: Notification) => {
  Modal.confirm({
    centered: true,
    content: $t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.title]),
    onCancel: () => {
      cancel();
    },
    onOk: async () => {
      await deleteMyNotifilerApi(row.id);
      message.success($t('AbpUi.SuccessfullyDeleted'));
      await gridApi.query();
    },
    title: $t('AbpUi.AreYouSure'),
  });
};
</script>

<template>
  <Grid :table-title="$t('Notifications.Notifications')">
    <template #toolbar-tools>
      <Dropdown v-if="selectedKeys.length > 0">
        <template #overlay>
          <Menu @click="(info) => onBulkRead(info)">
            <MenuItem key="read">
              <div class="flex flex-row items-center gap-[4px]">
                <ReadIcon color="#00DD00" />
                {{ $t('Notifications.Read') }}
              </div>
            </MenuItem>
            <MenuItem key="un-read">
              <div class="flex flex-row items-center gap-[4px]">
                <UnReadIcon color="#FF7744" />
                {{ $t('Notifications.UnRead') }}
              </div>
            </MenuItem>
          </Menu>
        </template>
        <Button>
          <div class="flex flex-row items-center gap-[4px]">
            <BookMarkIcon />
            {{ $t('Notifications.MarkAs') }}
            <DownOutlined />
          </div>
        </Button>
      </Dropdown>
    </template>
    <template #title="{ row }">
      <div class="flex flex-row items-center gap-[4px]">
        <ReadIcon
          v-if="row.state === NotificationReadState.Read"
          class="size-5"
          color="#00DD00"
        />
        <UnReadIcon v-else class="size-5" color="#FF7744" />
        <a href="javascript:(0);" @click="onClickRead(row)">{{ row.title }}</a>
      </div>
    </template>
    <template #message="{ row }">
      <a href="javascript:(0);" @click="onClickRead(row)">{{ row.message }}</a>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <Button
          :icon="h(DeleteOutlined)"
          danger
          type="link"
          @click="onDelete(row)"
        >
          {{ $t('AbpUi.Delete') }}
        </Button>
        <Dropdown>
          <template #overlay>
            <Menu @click="(info) => onRowRead(row, info)">
              <MenuItem key="read">
                <div class="flex flex-row items-center gap-[4px]">
                  <ReadIcon color="#00DD00" />
                  {{ $t('Notifications.Read') }}
                </div>
              </MenuItem>
              <MenuItem key="un-read">
                <div class="flex flex-row items-center gap-[4px]">
                  <UnReadIcon color="#FF7744" />
                  {{ $t('Notifications.UnRead') }}
                </div>
              </MenuItem>
            </Menu>
          </template>
          <Button type="link">
            <div class="flex flex-row items-center gap-[4px]">
              <BookMarkIcon />
              {{ $t('Notifications.MarkAs') }}
              <DownOutlined />
            </div>
          </Button>
        </Dropdown>
      </div>
    </template>
  </Grid>
</template>

<style lang="scss" scoped></style>

// apps/react-admin/src/pages/management/notifications/my-notification-table.tsx
import { useRef, useState } from "react";
import { Button, Card, Dropdown, Modal, Space, type MenuProps } from "antd";
import { DeleteOutlined, DownOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { type Notification, NotificationReadState, NotificationType } from "#/notifications";
import {
	deleteMyNotifilerApi,
	getMyNotifilersApi,
	markReadStateApi,
} from "@/api/management/notifications/my-notifications";
import MyNotificationModal from "./my-notification-modal";
import { formatToDateTime } from "@/utils/abp";
import { Icon } from "@iconify/react";
import { toast } from "sonner";
import { useNotificationSerializer } from "@/utils/abp/notifications/useNotificationSerializer";

const MyNotificationTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const [modal, contextHolder] = Modal.useModal();
	const queryClient = useQueryClient();

	const { deserialize } = useNotificationSerializer();
	const [selectedRows, setSelectedRows] = useState<Notification[]>([]);
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedNotification, setSelectedNotification] = useState<Notification>();

	// Delete notification mutation
	const { mutateAsync: deleteNotification } = useMutation({
		mutationFn: deleteMyNotifilerApi,
		onSuccess: () => {
			toast.success($t("AbpUi.SuccessfullyDeleted"));
			queryClient.invalidateQueries({ queryKey: ["notifications"] });
			actionRef.current?.reload();
		},
	});

	// Mark read state mutation
	const { mutateAsync: markReadState } = useMutation({
		mutationFn: markReadStateApi,
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ["notifications"] });
			actionRef.current?.reload();
		},
	});

	const handleDelete = (notification: Notification) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: notification.title }),
			onOk: () => deleteNotification(notification.id),
		});
	};

	const handleRead = async (ids: string[], state: NotificationReadState) => {
		await markReadState({ idList: ids, state });
		queryClient.invalidateQueries({ queryKey: ["notifications"] });
		setSelectedRows([]);
	};

	const handleClickNotification = (notification: Notification) => {
		setSelectedNotification(notification);
		setModalVisible(true);
		handleRead([notification.id], NotificationReadState.Read);
	};

	const bulkActionMenu: MenuProps["items"] = [
		{
			key: "read",
			icon: <Icon icon="ic:outline-mark-email-read" color="#00DD00" />,
			label: $t("Notifications.Read"),
			onClick: () =>
				handleRead(
					selectedRows.map((row) => row.id),
					NotificationReadState.Read,
				),
		},
		{
			key: "unread",
			icon: <Icon icon="ic:outline-mark-email-unread" color="#FF7744" />,
			label: $t("Notifications.UnRead"),
			onClick: () =>
				handleRead(
					selectedRows.map((row) => row.id),
					NotificationReadState.UnRead,
				),
		},
	];

	const rowActionMenu = (record: Notification): MenuProps["items"] => [
		{
			key: "read",
			icon: <Icon icon="ic:outline-mark-email-read" color="#00DD00" />,
			label: $t("Notifications.Read"),
			onClick: () => handleRead([record.id], NotificationReadState.Read),
		},
		{
			key: "unread",
			icon: <Icon icon="ic:outline-mark-email-unread" color="#FF7744" />,
			label: $t("Notifications.UnRead"),
			onClick: () => handleRead([record.id], NotificationReadState.UnRead),
		},
	];

	const columns: ProColumns<Notification>[] = [
		{
			title: $t("Notifications.Notifications:State"),
			dataIndex: "readState",
			valueType: "select",
			fieldProps: {
				allowClear: true,
				options: [
					{
						label: $t("Notifications.Read"),
						value: NotificationReadState.Read,
					},
					{
						label: $t("Notifications.UnRead"),
						value: NotificationReadState.UnRead,
					},
				],
			},
			initialValue: NotificationReadState.UnRead,
			hideInTable: true,
		},
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true, // hide in table
		},
		{
			title: $t("Notifications.Notifications:Type"),
			dataIndex: "type",

			hideInSearch: true,
			valueEnum: {
				[NotificationType.Application]: $t("Notifications.NotificationType:Application"),
				[NotificationType.ServiceCallback]: $t("Notifications.NotificationType:ServiceCallback"),
				[NotificationType.System]: $t("Notifications.NotificationType:System"),
				[NotificationType.User]: $t("Notifications.NotificationType:User"),
			},
		},
		{
			title: $t("Notifications.Notifications:SendTime"),
			dataIndex: "creationTime",
			hideInSearch: true,
			render: (_, record) => formatToDateTime(record.creationTime),
		},
		{
			title: $t("Notifications.Notifications:Title"),
			dataIndex: "title",
			hideInSearch: true,
			render: (_, record) => (
				<div className="flex items-center gap-1">
					<Icon
						icon={
							record.state === NotificationReadState.Read
								? "ic:outline-mark-email-read"
								: "ic:outline-mark-email-unread"
						}
						className="text-xl"
						color={record.state === NotificationReadState.Read ? "#00DD00" : "#FF7744"}
					/>
					<button type="button" onClick={() => handleClickNotification(record)}>
						{record.title}
					</button>
				</div>
			),
		},
		{
			title: $t("Notifications.Notifications:Content"),
			dataIndex: "message",
			hideInSearch: true,
			render: (_, record) => (
				<button type="button" onClick={() => handleClickNotification(record)}>
					{record.message}
				</button>
			),
		},
		{
			title: $t("AbpUi.Actions"),
			fixed: "right",
			hideInSearch: true,
			width: 200,
			render: (_, record) => (
				<Space>
					<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
						{$t("AbpUi.Delete")}
					</Button>
					<Dropdown menu={{ items: rowActionMenu(record) }}>
						<Button type="link">
							<Space>
								<Icon icon="material-symbols:bookmark-outline" />
								{$t("Notifications.MarkAs")}
								<DownOutlined />
							</Space>
						</Button>
					</Dropdown>
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<Notification>
					headerTitle={$t("Notifications.Notifications")}
					actionRef={actionRef}
					rowKey="id"
					columns={columns}
					rowSelection={{
						onChange: (_, rows) => setSelectedRows(rows),
					}}
					toolBarRender={() => [
						selectedRows.length > 0 && (
							<Dropdown menu={{ items: bulkActionMenu }}>
								<Button>
									<Space>
										<Icon icon="material-symbols:bookmark-outline" />
										{$t("Notifications.MarkAs")}
										<DownOutlined />
									</Space>
								</Button>
							</Dropdown>
						),
					]}
					request={async (params) => {
						const { current, pageSize, filter, readState } = params;
						const query = await queryClient.fetchQuery({
							queryKey: ["notifications", params],
							queryFn: async () =>
								getMyNotifilersApi({
									maxResultCount: pageSize,
									skipCount: ((current || 1) - 1) * (pageSize || 0),
									filter,
									readState,
								}),
						});
						return {
							data: query.items.map((item) => {
								const notification = deserialize(item);
								return {
									...item,
									...notification,
								};
							}),
							success: true,
							total: query.totalCount,
						};
					}}
					pagination={{
						showSizeChanger: true,
					}}
					scroll={{ x: "max-content" }}
					search={{
						labelWidth: "auto",
						defaultCollapsed: false,
					}}
				/>
			</Card>
			<MyNotificationModal
				visible={modalVisible}
				notification={selectedNotification}
				onClose={() => setModalVisible(false)}
			/>
		</>
	);
};

export default MyNotificationTable;
