// apps/vben5/packages/@abp/notifications/src/components/my-notifilers/MyNotificationModal.vue
<script setup lang="ts">
import type { Notification } from '../../types/notifications';

import { ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';

import { Tinymce } from '@abp/components/tinymce';

const notification = ref<Notification>();

const [Modal, modalApi] = useVbenModal({
  onOpenChange(isOpen) {
    if (isOpen) {
      notification.value = modalApi.getData<Notification>();
    }
  },
  showConfirmButton: false,
});
</script>

<template>
  <Modal :title="notification?.title">
    <Tinymce
      :value="notification?.message"
      :plugins="[]"
      :toolbar="[]"
      readonly
      menubar="''"
    />
  </Modal>
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/notifications/my-notification-modal.tsx
import { Modal } from "antd";
import type { Notification } from "#/notifications";
import Editor from "@/components/editor";

interface Props {
	visible: boolean;
	notification?: Notification;
	onClose: () => void;
}

const MyNotificationModal: React.FC<Props> = ({ visible, notification, onClose }) => {
	return (
		<Modal open={visible} title={notification?.title} onCancel={onClose} footer={null}>
			<Editor
				id="notification-content"
				value={notification?.message ?? ""}
				readOnly
				sample // Use simple toolbar
				hiddleToolbar
			/>
		</Modal>
	);
};

export default MyNotificationModal;
