// apps/react-admin/src/pages/management/settings/definitions/setting-definition-table.tsx
import { useRef, useState, useCallback } from "react";
import { Button, Card, Modal, Space } from "antd";
import { EditOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { ProTable, type ActionType, type ProColumns } from "@ant-design/pro-table";
import type { SettingDefinitionDto } from "#/management/settings/definitions";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deleteApi, getListApi } from "@/api/management/settings/definitions";
import { SettingDefinitionsPermissions } from "@/constants/management/settings/permissions";
import { hasAccessByCodes } from "@/utils/abp/access-checker";
import SettingDefinitionModal from "./setting-definition-modal";
import { useLocalizer } from "@/hooks/abp/use-localization";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { toast } from "sonner";

const SettingDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	const queryClient = useQueryClient();
	const [modal, contextHolder] = Modal.useModal();
	const [modalVisible, setModalVisible] = useState(false);
	const [selectedSetting, setSelectedSetting] = useState<SettingDefinitionDto>();

	const { Lr } = useLocalizer(
		undefined,
		useCallback(() => {
			actionRef.current?.reload();
			setModalVisible(false);
		}, []),
	);

	const { deserialize } = localizationSerializer();

	// Delete mutation
	const { mutateAsync: deleteSetting } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			queryClient.invalidateQueries({ queryKey: ["settings"] });
			actionRef.current?.reload();
		},
	});

	const handleDelete = (setting: SettingDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: setting.name }),
			onOk: () => deleteSetting(setting.name),
		});
	};

	const columns: ProColumns<SettingDefinitionDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			hideInTable: true,
		},
		{
			title: $t("AbpSettingManagement.DisplayName:Name"),
			dataIndex: "name",
			width: 150,
			hideInSearch: true,
		},
		{
			title: $t("AbpSettingManagement.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 150,
			hideInSearch: true,
		},
		{
			title: $t("AbpUi.Actions"),
			width: 180,
			fixed: "right",
			hideInSearch: true,
			render: (_, record) => (
				<Space split>
					{hasAccessByCodes([SettingDefinitionsPermissions.Update]) && (
						<Button
							type="link"
							icon={<EditOutlined />}
							onClick={() => {
								setSelectedSetting(record);
								setModalVisible(true);
							}}
						>
							{$t("AbpUi.Edit")}
						</Button>
					)}
					{!record.isStatic && hasAccessByCodes([SettingDefinitionsPermissions.DeleteOrRestore]) && (
						<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
							{$t("AbpUi.Delete")}
						</Button>
					)}
				</Space>
			),
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<SettingDefinitionDto>
					headerTitle={$t("AbpSettingManagement.Settings")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					request={async (params) => {
						const { filter } = params;
						const query = await queryClient.fetchQuery({
							queryKey: ["settings", params],
							queryFn: async () => {
								const res = await getListApi({ filter });
								return res.items.map((item) => {
									const localizableString = deserialize(item.displayName);
									return {
										...item,
										displayName: Lr(localizableString.resourceName, localizableString.name),
									};
								});
							},
						});

						return {
							data: query,
							success: true,
							total: query.length,
						};
					}}
					search={{
						labelWidth: "auto",
						defaultCollapsed: false,
					}}
					toolBarRender={() => [
						hasAccessByCodes([SettingDefinitionsPermissions.Create]) && (
							<Button
								type="primary"
								icon={<PlusOutlined />}
								onClick={() => {
									setSelectedSetting(undefined);
									setModalVisible(true);
								}}
							>
								{$t("AbpSettingManagement.Definition:AddNew")}
							</Button>
						),
					]}
				/>
			</Card>
			<SettingDefinitionModal
				visible={modalVisible}
				settingName={selectedSetting?.name}
				onClose={() => {
					setModalVisible(false);
					setSelectedSetting(undefined);
				}}
				onChange={() => actionRef.current?.reload()}
			/>
		</>
	);
};

export default SettingDefinitionTable;

// apps/vben5/packages/@abp/settings/src/components/definitions/SettingDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';

import type { VbenFormProps } from '@vben/common-ui';

import type { SettingDefinitionDto } from '../../types/definitions';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useLocalization, useLocalizationSerializer } from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, message, Modal } from 'ant-design-vue';

import { useDefinitionsApi } from '../../api/useDefinitionsApi';
import { SettingDefinitionsPermissions } from '../../constants/permissions';

defineOptions({
  name: 'SettingDefinitionTable',
});

const permissionGroups = ref<SettingDefinitionDto[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const { Lr } = useLocalization();
const { deserialize } = useLocalizationSerializer();
const { deleteApi, getListApi } = useDefinitionsApi();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<SettingDefinitionDto> = {
  columns: [
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('AbpSettingManagement.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('AbpSettingManagement.DisplayName:DisplayName'),
    },
    {
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      title: $t('AbpUi.Actions'),
      width: 180,
    },
  ],
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};

const gridEvents: VxeGridListeners<SettingDefinitionDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [SettingDefinitionModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./SettingDefinitionModal.vue'),
  ),
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const { items } = await getListApi(input);
    pageState.total = items.length;
    permissionGroups.value = items.map((item) => {
      const localizableString = deserialize(item.displayName);
      return {
        ...item,
        displayName: Lr(localizableString.resourceName, localizableString.name),
      };
    });
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = permissionGroups.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: SettingDefinitionDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: SettingDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

onMounted(onGet);
</script>

<template>
  <Grid :table-title="$t('AbpSettingManagement.Settings')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[SettingDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('AbpSettingManagement.Definition:AddNew') }}
      </Button>
    </template>
    <template #action="{ row }">
      <div class="flex flex-row">
        <div :class="row.isStatic ? 'w-full' : 'basis-1/2'">
          <Button
            :icon="h(EditOutlined)"
            block
            type="link"
            v-access:code="[SettingDefinitionsPermissions.Update]"
            @click="onUpdate(row)"
          >
            {{ $t('AbpUi.Edit') }}
          </Button>
        </div>
        <div v-if="!row.isStatic" class="basis-1/2">
          <Button
            :icon="h(DeleteOutlined)"
            block
            danger
            type="link"
            v-access:code="[SettingDefinitionsPermissions.DeleteOrRestore]"
            @click="onDelete(row)"
          >
            {{ $t('AbpUi.Delete') }}
          </Button>
        </div>
      </div>
    </template>
  </Grid>
  <SettingDefinitionModal @change="() => onGet()" />
</template>

<style scoped></style>
