// apps/react-admin/src/pages/management/localization/resources/localization-resource-modal.tsx
import { useEffect, useState } from "react";
import { Modal, Form, Input, Checkbox } from "antd";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { createApi, updateApi, getApi } from "@/api/management/localization/resources";
import type { ResourceDto } from "#/management/localization/resources";

interface Props {
	visible: boolean;
	onClose: () => void;
	onChange: (data: ResourceDto) => void;
	resourceName?: string;
}

const defaultModel: ResourceDto = {
	displayName: "",
	enable: true,
	name: "",
} as ResourceDto;

const LocalizationResourceModal: React.FC<Props> = ({ visible, onClose, onChange, resourceName }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();
	const [loading, setLoading] = useState(false);
	const [submitting, setSubmitting] = useState(false);

	useEffect(() => {
		if (visible) {
			form.resetFields();
			if (resourceName) {
				fetchResource(resourceName);
			} else {
				form.setFieldsValue(defaultModel);
			}
		}
	}, [visible, resourceName, form]);

	const fetchResource = async (name: string) => {
		try {
			setLoading(true);
			const dto = await getApi(name);
			form.setFieldsValue(dto);
		} finally {
			setLoading(false);
		}
	};

	const handleSubmit = async () => {
		try {
			const values = await form.validateFields();
			setSubmitting(true);

			const api = resourceName ? updateApi(resourceName, values) : createApi(values);

			const res = await api;
			toast.success($t("AbpUi.SavedSuccessfully"));
			onChange(res);
			onClose();
		} catch (error) {
			console.error(error);
		} finally {
			setSubmitting(false);
		}
	};

	const modalTitle = resourceName
		? `${$t("AbpLocalization.Resources")} - ${resourceName}`
		: $t("LocalizationManagement.Resource:AddNew");

	return (
		<Modal
			open={visible}
			title={modalTitle}
			onCancel={onClose}
			onOk={handleSubmit}
			confirmLoading={submitting}
			loading={loading}
			destroyOnClose
			width="50%"
		>
			<Form form={form} layout="vertical" initialValues={defaultModel}>
				<Form.Item name="enable" valuePropName="checked">
					<Checkbox>{$t("LocalizationManagement.DisplayName:Enable")}</Checkbox>
				</Form.Item>
				<Form.Item label={$t("AbpLocalization.DisplayName:ResourceName")} name="name" rules={[{ required: true }]}>
					<Input disabled={!!resourceName} autoComplete="off" />
				</Form.Item>
				<Form.Item
					label={$t("AbpLocalization.DisplayName:DisplayName")}
					name="displayName"
					rules={[{ required: true }]}
				>
					<Input autoComplete="off" />
				</Form.Item>
				<Form.Item label={$t("AbpLocalization.DisplayName:Description")} name="description">
					<Input autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default LocalizationResourceModal;

// apps/vben5/packages/@abp/localization/src/components/resources/LocalizationResourceModal.vue
<script setup lang="ts">
import type { FormInstance } from 'ant-design-vue';

import type { ResourceDto } from '../../types/resources';

import { defineEmits, defineOptions, ref, toValue, useTemplateRef } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Checkbox, Form, Input, message } from 'ant-design-vue';

import { useResourcesApi } from '../../api/useResourcesApi';

defineOptions({
  name: 'LocalizationResourceModal',
});
const emits = defineEmits<{
  (event: 'change', data: ResourceDto): void;
}>();

const FormItem = Form.Item;

const defaultModel = {
  displayName: '',
  enable: true,
  name: '',
} as ResourceDto;

const form = useTemplateRef<FormInstance>('form');
const formModel = ref<ResourceDto>({ ...defaultModel });

const { cancel, createApi, getApi, updateApi } = useResourcesApi();
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onClosed() {
    cancel('LocalizationResourceModal has closed!');
  },
  onConfirm: onSubmit,
  onOpenChange: async (isOpen: boolean) => {
    if (isOpen) {
      formModel.value = { ...defaultModel };
      modalApi.setState({
        title: $t('LocalizationManagement.Resource:AddNew'),
      });
      const { name } = modalApi.getData<ResourceDto>();
      name && (await onGet(name));
    }
  },
  title: $t('LocalizationManagement.Resource:AddNew'),
});
async function onGet(name: string) {
  try {
    modalApi.setState({ loading: true });
    const dto = await getApi(name);
    formModel.value = dto;
    modalApi.setState({
      title: `${$t('AbpLocalization.Resources')} - ${dto.name}`,
    });
  } finally {
    modalApi.setState({ loading: false });
  }
}
async function onSubmit() {
  await form.value?.validate();
  try {
    modalApi.setState({ submitting: true });
    const input = toValue(formModel);
    const api = input.id ? updateApi(input.name, input) : createApi(input);
    const dto = await api;
    message.success($t('AbpUi.SavedSuccessfully'));
    emits('change', dto);
    modalApi.close();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal>
    <Form
      ref="form"
      :label-col="{ span: 6 }"
      :model="formModel"
      :wrapper-col="{ span: 18 }"
    >
      <FormItem
        :label="$t('LocalizationManagement.DisplayName:Enable')"
        name="enable"
      >
        <Checkbox v-model:checked="formModel.enable">
          {{ $t('LocalizationManagement.DisplayName:Enable') }}
        </Checkbox>
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:ResourceName')"
        name="name"
        required
      >
        <Input v-model:value="formModel.name" autocomplete="off" />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:DisplayName')"
        name="displayName"
        required
      >
        <Input v-model:value="formModel.displayName" autocomplete="off" />
      </FormItem>
      <FormItem
        :label="$t('AbpLocalization.DisplayName:Description')"
        name="description"
      >
        <Input v-model:value="formModel.description" autocomplete="off" />
      </FormItem>
    </Form>
  </Modal>
</template>

<style scoped></style>
