// apps/react-admin/src/components/abp/properties/property-modal.tsx
import type React from "react";
import { Modal, Form, Input } from "antd";
import { useTranslation } from "react-i18next";
import type { PropertyInfo } from "./types";

interface PropertyModalProps {
	visible: boolean;
	onClose: () => void;
	onChange: (data: PropertyInfo) => void;
}

const PropertyModal: React.FC<PropertyModalProps> = ({ visible, onClose, onChange }) => {
	const { t: $t } = useTranslation();
	const [form] = Form.useForm();

	const handleOk = async () => {
		try {
			const values = await form.validateFields();
			onChange({
				key: values.key,
				value: values.value,
			});
			form.resetFields();
			onClose();
		} catch (error) {
			console.error("Validation failed:", error);
		}
	};

	const handleCancel = () => {
		form.resetFields();
		onClose();
	};

	return (
		<Modal
			title={$t("component.extra_property_dictionary.title")}
			open={visible}
			onOk={handleOk}
			onCancel={handleCancel}
			width="50%"
			destroyOnClose
		>
			<Form form={form} layout="vertical">
				<Form.Item label={$t("component.extra_property_dictionary.key")} name="key" rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>
				<Form.Item label={$t("component.extra_property_dictionary.value")} name="value" rules={[{ required: true }]}>
					<Input autoComplete="off" />
				</Form.Item>
			</Form>
		</Modal>
	);
};

export default PropertyModal;

// apps/vben5/packages/@abp/ui/src/components/properties/PropertyModal.vue
<script setup lang="ts">
import type { PropertyInfo } from './types';

import { useVbenForm, useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

defineOptions({
  name: 'PropertyModal',
});

const emits = defineEmits<{
  (event: 'change', data: PropertyInfo): void;
}>();

const [Form, formApi] = useVbenForm({
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      componentProps: {
        autocomplete: 'off',
      },
      fieldName: 'key',
      label: $t('component.extra_property_dictionary.key'),
      rules: 'required',
    },
    {
      component: 'Input',
      componentProps: {
        autocomplete: 'off',
      },
      fieldName: 'value',
      label: $t('component.extra_property_dictionary.value'),
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});
const [Modal, modalApi] = useVbenModal({
  class: 'w-1/2',
  draggable: true,
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await formApi.validateAndSubmitForm();
  },
  title: $t('component.extra_property_dictionary.title'),
});
function onSubmit(input: Record<string, any>) {
  emits('change', {
    key: input.key,
    value: input.value,
  });
  modalApi.close();
}
</script>

<template>
  <Modal>
    <Form />
  </Modal>
</template>

<style scoped></style>
