// apps/vben5/packages/@abp/account/src/components/components/AuthenticatorSettings.vue
<script setup lang="ts">
import type { AuthenticatorDto } from '../../types';

import { onMounted, ref } from 'vue';

import { $t } from '@vben/locales';

import { Button, Card, List, message, Modal, Skeleton } from 'ant-design-vue';

import { useProfileApi } from '../../api/useProfileApi';
import AuthenticatorSteps from './AuthenticatorSteps.vue';

const ListItem = List.Item;
const ListItemMeta = List.Item.Meta;

const { getAuthenticatorApi, resetAuthenticatorApi } = useProfileApi();

const authenticator = ref<AuthenticatorDto>();
async function onGet() {
  const dto = await getAuthenticatorApi();
  authenticator.value = dto;
}
async function onReset() {
  Modal.confirm({
    centered: true,
    content: $t('AbpAccount.ResetAuthenticatorWarning'),
    iconType: 'warning',
    onOk: async () => {
      await resetAuthenticatorApi();
      await onGet();
      message.success($t('AbpAccount.YourAuthenticatorIsSuccessfullyReset'));
    },
    title: $t('AbpUi.AreYouSure'),
  });
}
onMounted(onGet);
</script>

<template>
  <Card
    :bordered="false"
    :title="$t('abp.account.settings.authenticatorSettings')"
  >
    <AuthenticatorSteps
      v-if="authenticator?.isAuthenticated === false"
      :authenticator="authenticator"
      @done="onGet"
    />
    <List v-else-if="authenticator?.isAuthenticated === true">
      <ListItem>
        <template #extra>
          <Button type="primary" @click="onReset">
            {{ $t('AbpAccount.ResetAuthenticator') }}
          </Button>
        </template>
        <ListItemMeta
          :description="$t('AbpAccount.ResetAuthenticatorDesc')"
          :title="$t('AbpAccount.ResetAuthenticator')"
        />
      </ListItem>
    </List>
    <Skeleton v-else />
  </Card>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/account/authenticator-settings.tsx
import { Button, Card, List, Skeleton, Modal } from "antd";
import { useTranslation } from "react-i18next";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getAuthenticatorApi, resetAuthenticatorApi } from "@/api/account/profile";
import AuthenticatorSteps from "./authenticator-steps";
import { toast } from "sonner";

const AuthenticatorSettings: React.FC = () => {
	const { t: $t } = useTranslation();
	const [modal, contextHolder] = Modal.useModal();
	const queryClient = useQueryClient();

	const { data: authenticator, isLoading } = useQuery({
		queryKey: ["authenticator"],
		queryFn: getAuthenticatorApi,
	});

	const { mutateAsync: resetAuthenticator } = useMutation({
		mutationFn: resetAuthenticatorApi,
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ["authenticator"] });
			toast.success($t("AbpAccount.YourAuthenticatorIsSuccessfullyReset"));
		},
	});

	const handleReset = () => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpAccount.ResetAuthenticatorWarning"),
			centered: true,
			onOk: () => resetAuthenticator(),
		});
	};

	if (isLoading) {
		return (
			<Card bordered={false} title={$t("abp.account.settings.authenticatorSettings")}>
				<Skeleton />
			</Card>
		);
	}

	return (
		<>
			{contextHolder}
			<Card bordered={false} title={$t("abp.account.settings.authenticatorSettings")}>
				{authenticator?.isAuthenticated === false ? (
					<AuthenticatorSteps
						authenticator={authenticator}
						onDone={() => queryClient.invalidateQueries({ queryKey: ["authenticator"] })}
					/>
				) : authenticator?.isAuthenticated === true ? (
					<List>
						<List.Item
							extra={
								<Button type="primary" onClick={handleReset}>
									{$t("AbpAccount.ResetAuthenticator")}
								</Button>
							}
						>
							<List.Item.Meta
								title={$t("AbpAccount.ResetAuthenticator")}
								description={$t("AbpAccount.ResetAuthenticatorDesc")}
							/>
						</List.Item>
					</List>
				) : null}
			</Card>
		</>
	);
};

export default AuthenticatorSettings;
