// apps/vben5/packages/@abp/account/src/components/components/SecuritySettings.vue
<script setup lang="ts">
import type { TwoFactorEnabledDto } from '../../types';
import type { UserInfo } from '../../types/user';

import { computed, onMounted, ref } from 'vue';

import { $t } from '@vben/locales';

import { Button, Card, List, Switch, Tag } from 'ant-design-vue';

import { useProfileApi } from '../../api/useProfileApi';

defineProps<{
  userInfo: null | UserInfo;
}>();
const emits = defineEmits<{
  (event: 'changePassword'): void;
  (event: 'changePhoneNumber'): void;
}>();
const ListItem = List.Item;
const ListItemMeta = List.Item.Meta;

const {
  changeTwoFactorEnabledApi,
  getTwoFactorEnabledApi,
  sendEmailConfirmLinkApi,
} = useProfileApi();
const twoFactor = ref<TwoFactorEnabledDto>();
const loading = ref(false);

const sendMailInternal = ref(0);
const getSendMailLoading = computed(() => {
  return sendMailInternal.value > 0;
});
const getSendMailTitle = computed(() => {
  if (sendMailInternal.value > 0) {
    return `${sendMailInternal.value} s`;
  }
  return $t('AbpAccount.ClickToValidation');
});

async function onGet() {
  const dto = await getTwoFactorEnabledApi();
  twoFactor.value = dto;
}
async function onTwoFactorChange(enabled: boolean) {
  try {
    loading.value = true;
    await changeTwoFactorEnabledApi({ enabled });
  } catch {
    twoFactor.value!.enabled = !enabled;
  } finally {
    loading.value = false;
  }
}
async function onValidateEmail(email: string) {
  sendMailInternal.value = 60;
  try {
    await sendEmailConfirmLinkApi({
      appName: 'VueVben5',
      email,
      returnUrl: window.location.href,
    });
    setInterval(() => {
      if (sendMailInternal.value <= 0) {
        return;
      }
      sendMailInternal.value -= 1;
    }, 1000);
  } catch {
    sendMailInternal.value = 0;
  }
}
onMounted(onGet);
</script>

<template>
  <Card :bordered="false" :title="$t('abp.account.settings.security.title')">
    <List item-layout="horizontal">
      <!-- 密码 -->
      <ListItem>
        <template #extra>
          <Button type="link" @click="emits('changePassword')">
            {{ $t('AbpUi.Edit') }}
          </Button>
        </template>
        <ListItemMeta
          :description="$t('abp.account.settings.security.passwordDesc')"
          :title="$t('abp.account.settings.security.password')"
        />
      </ListItem>
      <!-- 手机号码 -->
      <ListItem>
        <template #extra>
          <Button type="link" @click="emits('changePhoneNumber')">
            {{ $t('AbpUi.Edit') }}
          </Button>
        </template>
        <ListItemMeta>
          <template #title>
            {{ $t('abp.account.settings.security.phoneNumber') }}
          </template>
          <template #description>
            {{ userInfo?.phoneNumber }}
            <template v-if="!userInfo?.phoneNumber">
              <Tag color="warning">
                {{ $t('abp.account.settings.security.unSet') }}
              </Tag>
            </template>
            <template v-else>
              <Tag v-if="userInfo?.phoneNumberVerified" color="success">
                {{ $t('abp.account.settings.security.verified') }}
              </Tag>
              <Tag v-else color="warning">
                {{ $t('abp.account.settings.security.unVerified') }}
              </Tag>
            </template>
          </template>
        </ListItemMeta>
      </ListItem>
      <!-- 邮件 -->
      <ListItem>
        <template #extra>
          <Button
            v-if="userInfo?.email && !userInfo?.emailVerified"
            :disabled="getSendMailLoading"
            type="link"
            @click="onValidateEmail(userInfo.email)"
          >
            {{ getSendMailTitle }}
          </Button>
        </template>
        <ListItemMeta>
          <template #title>
            {{ $t('abp.account.settings.security.email') }}
          </template>
          <template #description>
            {{ userInfo?.email }}
            <Tag v-if="userInfo?.emailVerified" color="success">
              {{ $t('abp.account.settings.security.verified') }}
            </Tag>
            <Tag v-else color="warning">
              {{ $t('abp.account.settings.security.unVerified') }}
            </Tag>
          </template>
        </ListItemMeta>
      </ListItem>
      <!-- 二次认证 -->
      <ListItem v-if="twoFactor">
        <template #extra>
          <Switch
            v-model:checked="twoFactor.enabled"
            :loading="loading"
            @change="(checked) => onTwoFactorChange(Boolean(checked))"
          />
        </template>
        <ListItemMeta
          :description="$t('AbpAccount.TwoFactor')"
          :title="$t('AbpAccount.TwoFactor')"
        />
      </ListItem>
    </List>
  </Card>
</template>

<style scoped></style>

// apps/react-admin/src/components/abp/account/security-settings.tsx
import { useState, useEffect } from "react";
import { Card, List, Button, Tag, Switch } from "antd";
import { useTranslation } from "react-i18next";
import { useMutation, useQuery } from "@tanstack/react-query";
import { getTwoFactorEnabledApi, changeTwoFactorEnabledApi, sendEmailConfirmLinkApi } from "@/api/account/profile";
import type { UserInfo } from "#/account/user";

interface Props {
	userInfo: UserInfo | null;
	onChangePassword: () => void;
	onChangePhoneNumber: () => void;
}

const SecuritySettings: React.FC<Props> = ({ userInfo, onChangePassword, onChangePhoneNumber }) => {
	const { t: $t } = useTranslation();
	const [loading, setLoading] = useState(false);
	const [sendMailInterval, setSendMailInterval] = useState(0);
	let timer: NodeJS.Timeout;

	// Get two factor status
	const { data: twoFactor, refetch: refetchTwoFactor } = useQuery({
		queryKey: ["twoFactorEnabled"],
		queryFn: getTwoFactorEnabledApi,
	});

	// Change two factor mutation
	const { mutateAsync: changeTwoFactor } = useMutation({
		mutationFn: changeTwoFactorEnabledApi,
		onMutate: () => setLoading(true),
		onSettled: () => setLoading(false),
		onError: () => refetchTwoFactor(),
		onSuccess: () => refetchTwoFactor(),
	});

	// Send email confirmation mutation
	const { mutateAsync: sendEmailConfirm } = useMutation({
		mutationFn: (email: string) =>
			sendEmailConfirmLinkApi({
				appName: "ReactAdmin",
				email,
				returnUrl: window.location.href,
			}),
		onSuccess: () => {
			setSendMailInterval(60);
			timer = setInterval(() => {
				setSendMailInterval((prev) => {
					if (prev <= 0) {
						clearInterval(timer);
						return 0;
					}
					return prev - 1;
				});
			}, 1000);
		},
		onError: () => setSendMailInterval(0),
	});

	useEffect(() => {
		return () => {
			if (timer) clearInterval(timer);
		};
	}, []);

	const getSendMailTitle = () => {
		if (sendMailInterval > 0) {
			return `${sendMailInterval} s`;
		}
		return $t("AbpAccount.ClickToValidation");
	};

	return (
		<Card bordered={false} title={$t("abp.account.settings.security.title")}>
			<List>
				{/* Password */}
				<List.Item
					extra={
						<Button type="link" onClick={onChangePassword}>
							{$t("AbpUi.Edit")}
						</Button>
					}
				>
					<List.Item.Meta
						title={$t("abp.account.settings.security.password")}
						description={$t("abp.account.settings.security.passwordDesc")}
					/>
				</List.Item>

				{/* Phone Number */}
				<List.Item
					extra={
						<Button type="link" onClick={onChangePhoneNumber}>
							{$t("AbpUi.Edit")}
						</Button>
					}
				>
					<List.Item.Meta
						title={$t("abp.account.settings.security.phoneNumber")}
						description={
							<>
								{userInfo?.phoneNumber}
								{!userInfo?.phoneNumber ? (
									<Tag color="warning">{$t("abp.account.settings.security.unSet")}</Tag>
								) : userInfo?.phoneNumberVerified ? (
									<Tag color="success">{$t("abp.account.settings.security.verified")}</Tag>
								) : (
									<Tag color="warning">{$t("abp.account.settings.security.unVerified")}</Tag>
								)}
							</>
						}
					/>
				</List.Item>

				{/* Email */}
				<List.Item
					extra={
						userInfo?.email &&
						!userInfo?.emailVerified && (
							<Button type="link" disabled={sendMailInterval > 0} onClick={() => sendEmailConfirm(userInfo.email)}>
								{getSendMailTitle()}
							</Button>
						)
					}
				>
					<List.Item.Meta
						title={$t("abp.account.settings.security.email")}
						description={
							<>
								{userInfo?.email}
								{userInfo?.emailVerified ? (
									<Tag color="success">{$t("abp.account.settings.security.verified")}</Tag>
								) : (
									<Tag color="warning">{$t("abp.account.settings.security.unVerified")}</Tag>
								)}
							</>
						}
					/>
				</List.Item>

				{/* Two Factor Authentication */}
				{twoFactor && (
					<List.Item
						extra={
							<Switch
								checked={twoFactor.enabled}
								loading={loading}
								onChange={(checked) => changeTwoFactor({ enabled: checked })}
							/>
						}
					>
						<List.Item.Meta title={$t("AbpAccount.TwoFactor")} description={$t("AbpAccount.TwoFactor")} />
					</List.Item>
				)}
			</List>
		</Card>
	);
};

export default SecuritySettings;
