// apps/vben5/packages/@abp/features/src/components/features/FeatureModal.vue
<script setup lang="ts">
import type { SelectionStringValueType, Validator } from '@abp/core';
import type { FormInstance } from 'ant-design-vue/es/form/Form';

import type { FeatureGroupDto, UpdateFeaturesDto } from '../../types/features';

import { computed, ref, toValue, useTemplateRef } from 'vue';

import { useVbenModal } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { useValidation } from '@abp/core';
import {
  Card,
  Checkbox,
  Form,
  Input,
  InputNumber,
  message,
  Select,
  Tabs,
} from 'ant-design-vue';

import { useFeaturesApi } from '../../api/useFeaturesApi';

const FormItem = Form.Item;
const TabPane = Tabs.TabPane;

interface ModalState {
  displayName?: string;
  providerKey?: string;
  providerName: string;
  readonly?: boolean;
}

interface FormModel {
  groups: FeatureGroupDto[];
}

const activeTabKey = ref('');
const modelState = ref<ModalState>();
const formModel = ref<FormModel>({ groups: [] });
const form = useTemplateRef<FormInstance>('form');

const getModalTitle = computed(() => {
  if (modelState.value?.displayName) {
    return `${$t('AbpFeatureManagement.Features')} - ${modelState.value.displayName}`;
  }
  return $t('AbpFeatureManagement.Features');
});

const { getApi, updateApi } = useFeaturesApi();
const {
  fieldMustBeetWeen,
  fieldMustBeStringWithMinimumLengthAndMaximumLength,
  fieldRequired,
} = useValidation();

const [Modal, modalApi] = useVbenModal({
  centered: true,
  class: 'w-1/2',
  async onConfirm() {
    await form.value?.validate();
    await onSubmit();
  },
  async onOpenChange(isOpen) {
    if (isOpen) {
      formModel.value = { groups: [] };
      await onGet();
      if (formModel.value?.groups.length > 0) {
        activeTabKey.value = formModel.value.groups[0]?.name!;
      }
    }
  },
});
function mapFeatures(groups: FeatureGroupDto[]) {
  groups.forEach((group) => {
    group.features.forEach((feature) => {
      if (feature.valueType.name === 'SelectionStringValueType') {
        const valueType =
          feature.valueType as unknown as SelectionStringValueType;
        valueType.itemSource.items.forEach((valueItem) => {
          if (valueItem.displayText.resourceName === 'Fixed') {
            valueItem.displayName = valueItem.displayText.name;
            return;
          }
          valueItem.displayName = $t(
            `${valueItem.displayText.resourceName}.${valueItem.displayText.name}`,
          );
        });
      } else {
        switch (feature.valueType?.validator.name) {
          case 'BOOLEAN': {
            feature.value =
              String(feature.value).toLocaleLowerCase() === 'true';
            break;
          }
          case 'NUMERIC': {
            feature.value = Number(feature.value);
            break;
          }
        }
      }
    });
  });
  return groups;
}
function getFeatureInput(groups: FeatureGroupDto[]): UpdateFeaturesDto {
  const input: UpdateFeaturesDto = {
    features: [],
  };
  groups.forEach((g) => {
    g.features.forEach((f) => {
      if (f.value !== null) {
        input.features.push({
          name: f.name,
          value: String(f.value),
        });
      }
    });
  });
  return input;
}
function createRules(field: string, validator: Validator) {
  const featureRules: { [key: string]: any }[] = [];
  if (validator.properties) {
    switch (validator.name) {
      case 'NUMERIC': {
        featureRules.push(
          ...fieldMustBeetWeen({
            end: Number(validator.properties.MaxValue),
            name: field,
            start: Number(validator.properties.MinValue),
            trigger: 'change',
          }),
        );
        break;
      }
      case 'STRING': {
        if (
          validator.properties.AllowNull &&
          validator.properties.AllowNull.toLowerCase() === 'true'
        ) {
          featureRules.push(
            ...fieldRequired({
              name: field,
              trigger: 'blur',
            }),
          );
        }
        featureRules.push(
          ...fieldMustBeStringWithMinimumLengthAndMaximumLength({
            maximum: Number(validator.properties.MaxLength),
            minimum: Number(validator.properties.MinLength),
            name: field,
            trigger: 'blur',
          }),
        );
        break;
      }
      default: {
        break;
      }
    }
  }
  return featureRules;
}
async function onGet() {
  try {
    modalApi.setState({ loading: true });
    const state = modalApi.getData<ModalState>();
    const { groups } = await getApi({
      providerKey: state.providerKey,
      providerName: state.providerName,
    });
    formModel.value = {
      groups: mapFeatures(groups),
    };
    modelState.value = state;
  } finally {
    modalApi.setState({ loading: false });
  }
}
async function onSubmit() {
  try {
    modalApi.setState({ submitting: true });
    const model = toValue(formModel);
    const state = modalApi.getData<ModalState>();
    const input = getFeatureInput(model.groups);
    await updateApi(
      {
        providerKey: state.providerKey,
        providerName: state.providerName,
      },
      input,
    );
    message.success($t('AbpUi.SavedSuccessfully'));
    await onGet();
  } finally {
    modalApi.setState({ submitting: false });
  }
}
</script>

<template>
  <Modal :title="getModalTitle">
    <Form :model="formModel" ref="form">
      <Tabs tab-position="left" type="card" v-model:active-key="activeTabKey">
        <TabPane
          v-for="(group, gi) in formModel.groups"
          :key="group.name"
          :tab="group.displayName"
        >
          <Card :bordered="false" :title="group.displayName">
            <template
              v-for="(feature, fi) in group.features"
              :key="feature.name"
            >
              <FormItem
                v-if="feature.valueType !== null"
                :name="['groups', gi, 'features', fi, 'value']"
                :label="feature.displayName"
                :extra="feature.description"
                :rules="
                  createRules(feature.displayName, feature.valueType.validator)
                "
              >
                <Checkbox
                  v-if="
                    feature.valueType.name === 'ToggleStringValueType' &&
                    feature.valueType.validator.name === 'BOOLEAN'
                  "
                  v-model:checked="feature.value"
                >
                  {{ feature.displayName }}
                </Checkbox>
                <div
                  v-else-if="
                    feature.valueType.name === 'FreeTextStringValueType'
                  "
                >
                  <InputNumber
                    v-if="feature.valueType.validator.name === 'NUMERIC'"
                    style="width: 100%"
                    v-model:value="feature.value"
                  />
                  <Input
                    v-else
                    v-model:value="feature.value"
                    autocomplete="off"
                  />
                </div>
                <Select
                  v-else-if="
                    feature.valueType.name === 'SelectionStringValueType'
                  "
                  v-model:value="feature.value"
                  :options="feature.valueType.itemSource.items"
                  :field-names="{ label: 'displayName', value: 'value' }"
                />
              </FormItem>
            </template>
          </Card>
        </TabPane>
      </Tabs>
    </Form>
  </Modal>
</template>

<style lang="scss" scoped>
:deep(.ant-tabs) {
  height: 34rem;

  .ant-tabs-nav {
    width: 14rem;
  }

  .ant-tabs-content-holder {
    overflow: hidden auto !important;
  }
}
</style>

// apps/react-admin/src/components/abp/features/feature-modal.tsx
import type { Validator } from "#/abp-core";
import type React from "react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { getApi, updateApi } from "@/api/management/features/features";
import { useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import type { FeatureGroupDto, UpdateFeaturesDto } from "#/management/features/features";

import { Modal, Form, Tabs, Card, Input, InputNumber, Checkbox, Select, Spin } from "antd";
import { useValidation } from "@/hooks/abp/use-validation";
import { useLocalizer } from "@/hooks/abp/use-localization";

interface FeatureManagementModalProps {
	visible: boolean;
	onClose: () => void;
	providerName: string;
	providerKey?: string;
	displayName?: string; // For the modal title
}

// Helper Interface for Form Data Structure
export interface FeatureFormData {
	groups: FeatureGroupDto[];
}

const FeatureManagementModal: React.FC<FeatureManagementModalProps> = ({
	visible,
	onClose,
	providerName,
	providerKey,
	displayName,
}) => {
	const { t: $t } = useTranslation();
	const { Lr } = useLocalizer();
	const [form] = Form.useForm();

	// Validation Hook
	const { fieldMustBeetWeen, fieldMustBeStringWithMinimumLengthAndMaximumLength, fieldRequired } = useValidation();

	// State
	const [activeTabKey, setActiveTabKey] = useState<string>("");
	const [groups, setGroups] = useState<FeatureGroupDto[]>([]);

	// --- Helpers ---

	/**
	 * Generates AntD Form Rules based on ABP Validator metadata (custom hook)
	 */
	const createRules = (fieldLabel: string, validator: Validator) => {
		const rules: any[] = [];
		if (validator?.properties) {
			switch (validator.name) {
				case "NUMERIC": {
					rules.push(
						...fieldMustBeetWeen({
							name: fieldLabel,
							start: Number(validator.properties.MinValue),
							end: Number(validator.properties.MaxValue),
							trigger: "change",
						}),
					);
					break;
				}
				case "STRING": {
					if (validator.properties.AllowNull && String(validator.properties.AllowNull).toLowerCase() === "true") {
						rules.push(
							...fieldRequired({
								name: fieldLabel,
								trigger: "blur",
							}),
						);
					}
					rules.push(
						...fieldMustBeStringWithMinimumLengthAndMaximumLength({
							name: fieldLabel,
							minimum: Number(validator.properties.MinLength),
							maximum: Number(validator.properties.MaxLength),
							trigger: "blur",
						}),
					);
					break;
				}
				default:
					break;
			}
		}
		return rules;
	};

	/**
	 * Process raw API data for the UI
	 * 1. Localize Selection items
	 * 2. Convert string values to boolean/number for inputs
	 */
	const mapFeaturesForUi = (rawGroups: FeatureGroupDto[]) => {
		// Deep clone to avoid mutating read-only props if using strict mode
		const processedGroups = JSON.parse(JSON.stringify(rawGroups)) as FeatureGroupDto[];

		processedGroups.forEach((group) => {
			group.features.forEach((feature) => {
				// Handle Selection Localization
				if (feature.valueType?.name === "SelectionStringValueType") {
					const valueType: any = feature.valueType;
					if (valueType.itemSource?.items) {
						valueType.itemSource.items.forEach((item: any) => {
							if (item.displayText?.resourceName === "Fixed") {
								item.displayName = item.displayText.name;
							} else {
								item.displayName = Lr(item.displayText.resourceName, item.displayText.name);
							}
						});
					}
				}

				// Handle Value Conversion
				else if (feature.valueType?.validator) {
					switch (feature.valueType.validator.name) {
						case "BOOLEAN":
							feature.value = String(feature.value).toLowerCase() === "true";
							break;
						case "NUMERIC":
							feature.value = Number(feature.value);
							break;
						default:
							// Keep as string
							break;
					}
				}
			});
		});

		return processedGroups;
	};

	/**
	 * Convert Form Data back to DTO for API submission
	 */
	const getFeatureInput = (formValues: any): UpdateFeaturesDto => {
		const input: UpdateFeaturesDto = { features: [] };

		const formGroups = formValues.groups as FeatureGroupDto[];
		if (!formGroups) return input;

		formGroups.forEach((g) => {
			if (!g?.features) return;
			g.features.forEach((f) => {
				// Only include non-null values
				if (f.value !== null && f.value !== undefined) {
					input.features.push({
						name: f.name,
						value: String(f.value), // Convert back to string
					});
				}
			});
		});

		return input;
	};

	// --- API Hooks ---

	const { mutateAsync: fetchData, isPending: isLoading } = useMutation({
		mutationFn: async () => {
			if (!providerName) return;
			const res = await getApi({ providerName, providerKey });
			return res.groups;
		},
		onSuccess: (rawGroups) => {
			if (rawGroups) {
				const processed = mapFeaturesForUi(rawGroups);
				setGroups(processed);
				form.setFieldsValue({ groups: processed });

				// Set active tab to first group
				if (processed.length > 0 && !activeTabKey) {
					setActiveTabKey(processed[0].name);
				}
			}
		},
	});

	const { mutateAsync: updateData, isPending: isSaving } = useMutation({
		mutationFn: async (input: UpdateFeaturesDto) => {
			return updateApi({ providerName, providerKey }, input);
		},
		onSuccess: () => {
			toast.success($t("AbpUi.SavedSuccessfully"));
			onClose();
		},
	});

	// --- Effects ---

	useEffect(() => {
		if (visible) {
			form.resetFields();
			setGroups([]);
			setActiveTabKey("");
			fetchData();
		}
	}, [visible, providerName, providerKey]);

	// --- Handlers ---

	const handleOk = async () => {
		try {
			const values = await form.validateFields();
			const input = getFeatureInput(values);
			await updateData(input);
		} catch (e) {
			console.error("Validation Failed", e);
		}
	};

	// --- Renderers ---

	const renderFeatureInput = (feature: any, groupIndex: number, featureIndex: number) => {
		if (!feature.valueType) return null;

		const fieldName = ["groups", groupIndex, "features", featureIndex, "value"];
		const valueTypeName = feature.valueType.name;
		const validatorName = feature.valueType.validator?.name;

		// 1. Checkbox (Boolean)
		if (valueTypeName === "ToggleStringValueType" && validatorName === "BOOLEAN") {
			return (
				<Form.Item
					name={fieldName}
					valuePropName="checked"
					label={feature.displayName}
					extra={feature.description}
					rules={createRules(feature.displayName, feature.valueType.validator)}
				>
					<Checkbox>{feature.displayName}</Checkbox>
				</Form.Item>
			);
		}

		// 2. Select (Selection)
		if (valueTypeName === "SelectionStringValueType") {
			return (
				<Form.Item
					name={fieldName}
					label={feature.displayName}
					extra={feature.description}
					rules={createRules(feature.displayName, feature.valueType.validator)}
				>
					<Select
						options={feature.valueType.itemSource?.items || []}
						fieldNames={{ label: "displayName", value: "value" }}
					/>
				</Form.Item>
			);
		}

		// 3. Free Text (String or Numeric)
		if (valueTypeName === "FreeTextStringValueType") {
			return (
				<Form.Item
					name={fieldName}
					label={feature.displayName}
					extra={feature.description}
					rules={createRules(feature.displayName, feature.valueType.validator)}
				>
					{validatorName === "NUMERIC" ? <InputNumber style={{ width: "100%" }} /> : <Input autoComplete="off" />}
				</Form.Item>
			);
		}

		// Fallback
		return (
			<Form.Item name={fieldName} label={feature.displayName} extra={feature.description}>
				<Input />
			</Form.Item>
		);
	};

	const modalTitle = displayName
		? `${$t("AbpFeatureManagement.Features")} - ${displayName}`
		: $t("AbpFeatureManagement.Features");

	return (
		<Modal
			title={modalTitle}
			open={visible}
			onCancel={onClose}
			onOk={handleOk}
			confirmLoading={isSaving}
			centered
			width="50%"
			maskClosable={false}
			destroyOnClose
		>
			<Spin spinning={isLoading}>
				<Form form={form} layout="vertical">
					{/* We render hidden inputs for names to ensure they exist in the form values structure for getFeatureInput logic
					 */}
					{groups.map((g, gIdx) => (
						<div key={g.name} style={{ display: "none" }}>
							{g.features.map((f, fIdx) => (
								<Form.Item key={f.name} name={["groups", gIdx, "features", fIdx, "name"]} initialValue={f.name}>
									<Input />
								</Form.Item>
							))}
						</div>
					))}

					<Tabs
						tabPosition="left"
						activeKey={activeTabKey}
						onChange={setActiveTabKey}
						items={groups.map((group, groupIndex) => ({
							key: group.name,
							label: group.displayName,
							children: (
								<div className="h-[34rem] overflow-y-auto pr-2">
									<Card title={group.displayName} bordered={false}>
										{group.features.map((feature, featureIndex) => (
											<div key={feature.name}>{renderFeatureInput(feature, groupIndex, featureIndex)}</div>
										))}
									</Card>
								</div>
							),
						}))}
					/>
				</Form>
			</Spin>
		</Modal>
	);
};

export default FeatureManagementModal;
