// apps/vben5/packages/@abp/notifications/src/components/definitions/notifications/NotificationDefinitionTable.vue
<script setup lang="ts">
import type { VxeGridListeners, VxeGridProps } from '@abp/ui';
import type { MenuInfo } from 'ant-design-vue/es/menu/src/interface';

import type { VbenFormProps } from '@vben/common-ui';

import type { NotificationDefinitionDto } from '../../../types/definitions';
import type { NotificationGroupDefinitionDto } from '../../../types/groups';

import { defineAsyncComponent, h, onMounted, reactive, ref } from 'vue';

import { useAccess } from '@vben/access';
import { useVbenModal } from '@vben/common-ui';
import { createIconifyIcon } from '@vben/icons';
import { $t } from '@vben/locales';

import {
  listToTree,
  useLocalization,
  useLocalizationSerializer,
} from '@abp/core';
import { useVbenVxeGrid } from '@abp/ui';
import {
  CheckOutlined,
  CloseOutlined,
  DeleteOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
} from '@ant-design/icons-vue';
import { Button, Dropdown, Menu, message, Modal, Tag } from 'ant-design-vue';
import { VxeGrid } from 'vxe-table';

import { useNotificationDefinitionsApi } from '../../../api/useNotificationDefinitionsApi';
import { useNotificationGroupDefinitionsApi } from '../../../api/useNotificationGroupDefinitionsApi';
import {
  NotificationDefinitionsPermissions,
  NotificationPermissions,
} from '../../../constants/permissions';
import { useEnumMaps } from './useEnumMaps';

defineOptions({
  name: 'NotificationDefinitionTable',
});

interface DefinitionItem {
  allowSubscriptionToClients: boolean;
  children: DefinitionItem[];
  contentType: string;
  description?: string;
  displayName: string;
  groupName: string;
  isStatic: boolean;
  name: string;
  notificationLifetime: string;
  notificationType: string;
  providers?: string[];
  template?: string;
}
interface DefinitionGroup {
  displayName: string;
  items: DefinitionItem[];
  name: string;
}

const MenuItem = Menu.Item;
const SendIcon = createIconifyIcon('ant-design:send-outlined');

const { Lr } = useLocalization();
const { hasAccessByCodes } = useAccess();
const { deserialize } = useLocalizationSerializer();
const {
  notificationContentTypeMap,
  notificationLifetimeMap,
  notificationTypeMap,
} = useEnumMaps();
const { getListApi: getGroupsApi } = useNotificationGroupDefinitionsApi();
const { deleteApi, getListApi: getDefinitionsApi } =
  useNotificationDefinitionsApi();

const definitionGroups = ref<DefinitionGroup[]>([]);
const pageState = reactive({
  current: 1,
  size: 10,
  total: 0,
});

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  handleReset: onReset,
  async handleSubmit(params) {
    pageState.current = 1;
    await onGet(params);
  },
  schema: [
    {
      component: 'Input',
      fieldName: 'filter',
      formItemClass: 'col-span-2 items-baseline',
      label: $t('AbpUi.Search'),
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 按下回车时是否提交表单
  submitOnEnter: true,
};

const gridOptions: VxeGridProps<NotificationGroupDefinitionDto> = {
  columns: [
    {
      align: 'center',
      type: 'seq',
      width: 50,
    },
    {
      align: 'left',
      field: 'group',
      slots: { content: 'group' },
      type: 'expand',
      width: 50,
    },
    {
      align: 'left',
      field: 'name',
      minWidth: 150,
      title: $t('Notifications.DisplayName:Name'),
    },
    {
      align: 'left',
      field: 'displayName',
      minWidth: 150,
      title: $t('Notifications.DisplayName:DisplayName'),
    },
  ],
  expandConfig: {
    padding: true,
    trigger: 'row',
  },
  exportConfig: {},
  keepSource: true,
  toolbarConfig: {
    custom: true,
    export: true,
    refresh: false,
    zoom: true,
  },
};
const subGridColumns: VxeGridProps<NotificationDefinitionDto>['columns'] = [
  {
    align: 'center',
    type: 'seq',
    width: 50,
  },
  {
    align: 'left',
    field: 'name',
    minWidth: 150,
    title: $t('Notifications.DisplayName:Name'),
    treeNode: true,
  },
  {
    align: 'left',
    field: 'displayName',
    minWidth: 120,
    title: $t('Notifications.DisplayName:DisplayName'),
  },
  {
    align: 'left',
    field: 'description',
    minWidth: 120,
    title: $t('Notifications.DisplayName:Description'),
  },
  {
    align: 'left',
    field: 'allowSubscriptionToClients',
    minWidth: 120,
    slots: { default: 'allowSubscriptionToClients' },
    title: $t('Notifications.DisplayName:AllowSubscriptionToClients'),
  },
  {
    align: 'left',
    field: 'template',
    minWidth: 150,
    title: $t('Notifications.DisplayName:Template'),
  },
  {
    align: 'left',
    field: 'notificationLifetime',
    minWidth: 150,
    title: $t('Notifications.DisplayName:NotificationLifetime'),
  },
  {
    align: 'left',
    field: 'notificationType',
    minWidth: 150,
    title: $t('Notifications.DisplayName:NotificationType'),
  },
  {
    align: 'left',
    field: 'contentType',
    minWidth: 150,
    title: $t('Notifications.DisplayName:ContentType'),
  },
  {
    align: 'left',
    field: 'providers',
    minWidth: 150,
    slots: { default: 'providers' },
    title: $t('Notifications.DisplayName:Providers'),
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: $t('AbpUi.Actions'),
    width: 220,
  },
];

const gridEvents: VxeGridListeners<NotificationGroupDefinitionDto> = {
  pageChange(params) {
    pageState.current = params.currentPage;
    pageState.size = params.pageSize;
    onPageChange();
  },
};

const [GroupGrid, gridApi] = useVbenVxeGrid({
  formOptions,
  gridEvents,
  gridOptions,
});

const [NotificationDefinitionModal, modalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./NotificationDefinitionModal.vue'),
  ),
});
const [NotificationSendModal, sendModalApi] = useVbenModal({
  connectedComponent: defineAsyncComponent(
    () => import('./NotificationSendModal.vue'),
  ),
});

async function onGet(input?: Record<string, string>) {
  try {
    gridApi.setLoading(true);
    const groupRes = await getGroupsApi(input);
    const definitionRes = await getDefinitionsApi(input);
    pageState.total = groupRes.items.length;
    definitionGroups.value = groupRes.items.map((group) => {
      const localizableGroup = deserialize(group.displayName);
      const definitions = definitionRes.items
        .filter((definition) => definition.groupName === group.name)
        .map((definition) => {
          const displayName = deserialize(definition.displayName);
          const description = deserialize(definition.displayName);
          return {
            ...definition,
            contentType: notificationContentTypeMap[definition.contentType],
            description: Lr(description.resourceName, description.name),
            displayName: Lr(displayName.resourceName, displayName.name),
            notificationLifetime:
              notificationLifetimeMap[definition.notificationLifetime],
            notificationType: notificationTypeMap[definition.notificationType],
          };
        });
      return {
        ...group,
        displayName: Lr(localizableGroup.resourceName, localizableGroup.name),
        items: listToTree(definitions, {
          id: 'name',
          pid: 'parentName',
        }),
      };
    });
    onPageChange();
  } finally {
    gridApi.setLoading(false);
  }
}

async function onReset() {
  await gridApi.formApi.resetForm();
  const input = await gridApi.formApi.getValues();
  await onGet(input);
}

function onPageChange() {
  const items = definitionGroups.value.slice(
    (pageState.current - 1) * pageState.size,
    pageState.current * pageState.size,
  );
  gridApi.setGridOptions({
    data: items,
    pagerConfig: {
      currentPage: pageState.current,
      pageSize: pageState.size,
      total: pageState.total,
    },
  });
}

function onCreate() {
  modalApi.setData({});
  modalApi.open();
}

function onUpdate(row: NotificationDefinitionDto) {
  modalApi.setData(row);
  modalApi.open();
}

function onDelete(row: NotificationDefinitionDto) {
  Modal.confirm({
    centered: true,
    content: `${$t('AbpUi.ItemWillBeDeletedMessageWithFormat', [row.name])}`,
    onOk: async () => {
      await deleteApi(row.name);
      message.success($t('AbpUi.DeletedSuccessfully'));
      onGet();
    },
    title: $t('AbpUi.AreYouSure'),
  });
}

function onMenuClick(row: NotificationDefinitionDto, info: MenuInfo) {
  switch (info.key) {
    case 'send': {
      sendModalApi.setData(row);
      sendModalApi.open();
    }
  }
}

onMounted(onGet);
</script>

<template>
  <GroupGrid :table-title="$t('Notifications.NotificationDefinitions')">
    <template #toolbar-tools>
      <Button
        :icon="h(PlusOutlined)"
        type="primary"
        v-access:code="[NotificationDefinitionsPermissions.Create]"
        @click="onCreate"
      >
        {{ $t('Notifications.NotificationDefinitions:AddNew') }}
      </Button>
    </template>
    <template #group="{ row: group }">
      <VxeGrid
        :columns="subGridColumns"
        :data="group.items"
        :tree-config="{
          trigger: 'row',
          rowField: 'name',
          childrenField: 'children',
        }"
      >
        <template #allowSubscriptionToClients="{ row }">
          <div class="flex flex-row justify-center">
            <CheckOutlined
              v-if="row.allowSubscriptionToClients"
              class="text-green-500"
            />
            <CloseOutlined v-else class="text-red-500" />
          </div>
        </template>
        <template #providers="{ row }">
          <div class="flex flex-row justify-center gap-1">
            <template v-for="provider in row.providers" :key="provider">
              <Tag color="blue">{{ provider }}</Tag>
            </template>
          </div>
        </template>
        <template #action="{ row: definition }">
          <div class="flex flex-row">
            <Button
              :icon="h(EditOutlined)"
              block
              type="link"
              v-access:code="[NotificationDefinitionsPermissions.Update]"
              @click="onUpdate(definition)"
            >
              {{ $t('AbpUi.Edit') }}
            </Button>
            <Button
              v-if="!definition.isStatic"
              :icon="h(DeleteOutlined)"
              block
              danger
              type="link"
              v-access:code="[NotificationDefinitionsPermissions.Delete]"
              @click="onDelete(definition)"
            >
              {{ $t('AbpUi.Delete') }}
            </Button>
            <Dropdown v-if="hasAccessByCodes([NotificationPermissions.Create])">
              <template #overlay>
                <Menu @click="(info) => onMenuClick(definition, info)">
                  <MenuItem key="send" :icon="h(SendIcon)">
                    {{ $t('Notifications.Notifications:Send') }}
                  </MenuItem>
                </Menu>
              </template>
              <Button :icon="h(EllipsisOutlined)" type="link" />
            </Dropdown>
          </div>
        </template>
      </VxeGrid>
    </template>
  </GroupGrid>
  <NotificationDefinitionModal @change="() => onGet()" />
  <NotificationSendModal />
</template>

<style scoped></style>

// apps/react-admin/src/pages/management/notifications/definitions/notifications/notification-definition-table.tsx
import type React from "react";
import { useRef, useState } from "react";
import { Button, Tag, Space, Modal, Dropdown, Table, Card } from "antd";
import {
	EditOutlined,
	DeleteOutlined,
	PlusOutlined,
	CheckOutlined,
	CloseOutlined,
	EllipsisOutlined,
	SendOutlined,
} from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { ProTable, type ProColumns, type ActionType } from "@ant-design/pro-table";
import { useMutation } from "@tanstack/react-query";
import { deleteApi, getListApi as getDefinitionsApi } from "@/api/management/notifications/notification-definitions";
import { getListApi as getGroupsApi } from "@/api/management/notifications/notification-group-definitions";
import type { NotificationDefinitionDto } from "#/notifications/definitions";
import type { NotificationGroupDefinitionDto } from "#/notifications/groups";
import { NotificationDefinitionsPermissions, NotificationPermissions } from "@/constants/notifications/permissions";
import { hasAccessByCodes, withAccessChecker } from "@/utils/abp/access-checker";
import { localizationSerializer } from "@/utils/abp/localization-serializer";
import { useLocalizer } from "@/hooks/abp/use-localization";

import NotificationDefinitionModal from "./notification-definition-modal";
import { useEnumMaps } from "./use-enum-maps";
import NotificationSendModal from "./notification-send-modal";
import { listToTree } from "@/utils/tree";
// Extended interface for Table
interface ExtendedGroupDto extends NotificationGroupDefinitionDto {
	items: NotificationDefinitionDto[];
}

const NotificationDefinitionTable: React.FC = () => {
	const { t: $t } = useTranslation();
	const actionRef = useRef<ActionType>();
	// const queryClient = useQueryClient();
	const { deserialize } = localizationSerializer();
	const { Lr } = useLocalizer();
	const [modal, contextHolder] = Modal.useModal();
	const { notificationContentTypeMap, notificationLifetimeMap, notificationTypeMap } = useEnumMaps();

	// State
	const [definitionModalVisible, setDefinitionModalVisible] = useState(false);
	const [sendModalVisible, setSendModalVisible] = useState(false);
	const [selectedDefinitionName, setSelectedDefinitionName] = useState<string | undefined>();
	const [selectedDefinition, setSelectedDefinition] = useState<NotificationDefinitionDto | undefined>();

	const { mutateAsync: deleteDef } = useMutation({
		mutationFn: deleteApi,
		onSuccess: () => {
			toast.success($t("AbpUi.DeletedSuccessfully"));
			actionRef.current?.reload();
		},
	});

	const handleCreate = () => {
		setSelectedDefinitionName(undefined);
		setDefinitionModalVisible(true);
	};

	const handleUpdate = (row: NotificationDefinitionDto) => {
		setSelectedDefinitionName(row.name);
		setDefinitionModalVisible(true);
	};

	const handleDelete = (row: NotificationDefinitionDto) => {
		modal.confirm({
			title: $t("AbpUi.AreYouSure"),
			content: $t("AbpUi.ItemWillBeDeletedMessageWithFormat", { 0: row.name }),
			onOk: () => deleteDef(row.name),
		});
	};

	const handleSend = (row: NotificationDefinitionDto) => {
		setSelectedDefinition(row);
		setSendModalVisible(true);
	};

	// --- Sub-Table Columns (Definitions) ---
	const definitionColumns = [
		{
			title: $t("Notifications.DisplayName:Name"),
			dataIndex: "name",
			width: 250,
		},
		{
			title: $t("Notifications.DisplayName:DisplayName"),
			dataIndex: "displayName",
			width: 200,
		},
		{
			title: $t("Notifications.DisplayName:Description"),
			dataIndex: "description",
			ellipsis: true,
		},
		{
			title: $t("Notifications.DisplayName:AllowSubscriptionToClients"),
			dataIndex: "allowSubscriptionToClients",
			width: 100,
			align: "center" as const,
			render: (val: boolean) =>
				val ? <CheckOutlined className="text-green-500" /> : <CloseOutlined className="text-red-500" />,
		},
		{
			title: $t("Notifications.DisplayName:Template"),
			dataIndex: "template",
			width: 150,
		},
		{
			title: $t("Notifications.DisplayName:NotificationLifetime"),
			dataIndex: "notificationLifetime",
			width: 150,
			// Fix: Cast map to Record<number, string>
			render: (val: number) => (notificationLifetimeMap as Record<number, string>)[val] || val,
		},
		{
			title: $t("Notifications.DisplayName:NotificationType"),
			dataIndex: "notificationType",
			width: 150,
			// Fix: Cast map
			render: (val: number) => (notificationTypeMap as Record<number, string>)[val] || val,
		},
		{
			title: $t("Notifications.DisplayName:ContentType"),
			dataIndex: "contentType",
			width: 150,
			// Fix: Cast map
			render: (val: number) => (notificationContentTypeMap as Record<number, string>)[val] || val,
		},
		{
			title: $t("Notifications.DisplayName:Providers"),
			dataIndex: "providers",
			width: 200,
			render: (items: string[]) => (
				<Space wrap>
					{items?.map((p) => (
						<Tag key={p} color="blue">
							{p}
						</Tag>
					))}
				</Space>
			),
		},
		{
			title: $t("AbpUi.Actions"),
			key: "actions",
			fixed: "right" as const,
			width: 150,
			render: (_: any, record: NotificationDefinitionDto) => (
				<Space>
					{withAccessChecker(
						<Button type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
							{$t("AbpUi.Edit")}
						</Button>,
						[NotificationDefinitionsPermissions.Update],
					)}

					{!record.isStatic &&
						withAccessChecker(
							<Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(record)}>
								{$t("AbpUi.Delete")}
							</Button>,
							[NotificationDefinitionsPermissions.Delete],
						)}

					{hasAccessByCodes([NotificationPermissions.Create]) && (
						<Dropdown
							menu={{
								items: [
									{
										key: "send",
										label: $t("Notifications.Notifications:Send"),
										icon: <SendOutlined />,
										onClick: () => handleSend(record),
									},
								],
							}}
						>
							<Button type="link" icon={<EllipsisOutlined />} />
						</Dropdown>
					)}
				</Space>
			),
		},
	];

	// --- Main Table Columns (Groups) ---
	const columns: ProColumns<ExtendedGroupDto>[] = [
		{
			title: $t("AbpUi.Search"),
			dataIndex: "filter",
			valueType: "text",
			hideInTable: true,
		},
		{
			title: $t("Notifications.DisplayName:Name"),
			dataIndex: "name",
			width: 200,
			fixed: "left",
		},
		{
			title: $t("Notifications.DisplayName:DisplayName"),
			dataIndex: "displayName",
		},
	];

	return (
		<>
			{contextHolder}
			<Card>
				<ProTable<ExtendedGroupDto>
					headerTitle={$t("Notifications.NotificationDefinitions")}
					actionRef={actionRef}
					rowKey="name"
					columns={columns}
					search={{ labelWidth: "auto" }}
					toolBarRender={() => [
						withAccessChecker(
							<Button key="create" type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
								{$t("Notifications.NotificationDefinitions:AddNew")}
							</Button>,
							[NotificationDefinitionsPermissions.Create],
						),
					]}
					scroll={{ x: "max-content" }}
					// Nested Table for Definitions
					expandable={{
						expandedRowRender: (record) => (
							<Table
								columns={definitionColumns}
								dataSource={record.items}
								pagination={false}
								rowKey="name"
								size="small"
								scroll={{ x: "max-content" }}
								// Support tree structure if definitions have children (Vue code implies listToTree)
								expandable={{ defaultExpandAllRows: true, childrenColumnName: "children" }}
							/>
						),
						defaultExpandAllRows: true,
					}}
					request={async (params) => {
						const { filter } = params;
						const [groupRes, defRes] = await Promise.all([getGroupsApi({ filter }), getDefinitionsApi({ filter })]);

						const data: ExtendedGroupDto[] = groupRes.items.map((group) => {
							const groupLocal = deserialize(group.displayName);

							const groupDefinitions = defRes.items
								.filter((d) => d.groupName === group.name)
								.map((d) => {
									const dName = deserialize(d.displayName);
									const dDesc = deserialize(d.description);
									return {
										...d,
										displayName: Lr(dName.resourceName, dName.name),
										description: dDesc ? Lr(dDesc.resourceName, dDesc.name) : "",
									};
								});

							return {
								...group,
								displayName: Lr(groupLocal.resourceName, groupLocal.name),
								items: listToTree(groupDefinitions, { id: "name", pid: "parentName" }),
							};
						});

						return {
							data: data,
							success: true,
							total: groupRes.items.length,
						};
					}}
					pagination={false}
				/>
			</Card>
			<NotificationDefinitionModal
				visible={definitionModalVisible}
				definitionName={selectedDefinitionName}
				onClose={() => setDefinitionModalVisible(false)}
				onChange={() => actionRef.current?.reload()}
			/>

			<NotificationSendModal
				visible={sendModalVisible}
				notification={selectedDefinition}
				onClose={() => setSendModalVisible(false)}
			/>
		</>
	);
};

export default NotificationDefinitionTable;
